### PR TITLE
[DDW-855] Update React-Polymorph dependency

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces `react-polymorph` dependency update

## TODO:

- [x] Implement a new React Polymorph version with `<Options>` and  `<Dropdown>` updates.

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1584115963208600)

_Storybook testing_
- [ ] Check RP components at least in storybook

_In-App testing_
- [ ] Pay attention if React Polymorph components are correctly displayed especially: `Autocomplete`, `Select`, `Dropdown`
- [ ] New polymorph update has a fix for dropdown glitch described here : https://iohk.myjetbrains.com/youtrack/issue/DDW-1224 Please check if that is fixed now
---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
There is an issue with some of the dropdowns in Storybook containing no values. As shown in the video below 
BlankDrop09-03-2020-04-35-30

**Comment by ManusMcCole** [comment]
Issue with the dropsdowns has been fixed. Good work @tomothespian

**Comment by tomothespian** [comment]
@ManusMcCole PR is still in WIP

**Comment by gnpf** [comment]
@tomothespian I found a few issues with the dropdowns (None of these issues are reproducible on v2-integration)

1 - The _Settings_ dropdown looks longer and it is truncated when changing the size of the window:

image

image

2 - Also, the scrollbar is always displayed on these dropdowns, regarding the number of options:

image

**Comment by tomothespian** [comment]
@gnpf thanks. I investigated the issues you found. Problem is with React Polymorph <Options> component. React Polymorph has scrollable options with a new `ScrollBar` component which calculates options wrapper height based on fixed single option height. So we need to improve React Polymorph and disable fix hight declaration if some custom parameter is presented.

cc @nikolaglumac 
I have a solution for that! Should I create a new RP task for that?

**Comment by nikolaglumac** [comment]
Yes please @tomothespian

**Comment by tomothespian** [comment]
@gnpf all issues you found are fixed within React Polymorph. Can you test this PR locally and check if everything is ok now. Once guys @DominikGuzei or @MarcusHurney create new RP package we should check one more time because currently React Polymorph comes from GitHub repo

**Comment by tomothespian** [comment]
@gnpf @IuliaDolishniak  also this one should be fixed with React Polymorph update: https://iohk.myjetbrains.com/youtrack/issue/DDW-1224

The issue was originally reported here by @IuliaDolishniak :
https://github.com/input-output-hk/daedalus/pull/1877#issuecomment-596588591

**Comment by gnpf** [comment]
@tomothespian Fixes look good! But while running locally, I found that this option is visible
(not visible on v2-integration)


image

**Comment by tomothespian** [comment]
@gnpf you can ignore this

**Pull request merged**
