### PR TITLE
[DEVOPS-44]  An attempt at a proper update of Daedalus icons

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by deepfire** [comment]
https://github.com/input-output-hk/daedalus/pull/326, which is what this is, essentially, based upon, didn't pass CI.

**Comment by deepfire** [comment]
Alright.

Whoever experiences a stale Daedalus icon on OS X with this PR, the following should ease the pain:

`sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \;`

Yeah, cache invalidation and naming things..

**Comment by domenkozar** [comment]
@deepfire this one needs a rebase on top of `cardano-sl-0.5` branch

**Comment by deepfire** [comment]
@domenkozar, updated branch.  (it's already been rebased, but then the `Update MacInstaller.hs` was merged Friday evening)

**Comment by domenkozar** [comment]
cc @darko-mijic

**Comment by fersel** [comment]
Works fine for Win installer / application shortcut icons, works fine for macOS application shortcut / tray icons. .pkg file for macOS though has a default icon. Is that an expected behaviour?
image

**Comment by domenkozar** [comment]
Created DEVOPS-202 to track the macOS installer icon as it's not a fallout from this update but rahter was never implemented.

**Pull request merged**
