### PR TITLE
[DDW-567] Improve exporting public keys while signing witnesses

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces a public keys exporting improvement while signing transaction witnesses. The user is not prompted to export a public key for each witness returned from an already signed transaction.

**Dedicated QA:** @miorsufianiohk 

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616749426140200)

## Test Cases

```Gherkin
Scenario 1: Sending tx or delegating
Given I am (sending a tx|delegating) with Ledger
When I am signing the tx
Then on the device, ‘Confirm Transaction’ is the last step
And I am not asked to export multiple public keys anymore
```

_**NOTE:**_
_It is a regular signing and delegating process. Before you were prompted to export multiple public keys on the device after you confirmed the transaction. Now "Confirm Transaction" is the last step and you won't be prompted to export multiple public keys for every witness_

- [ ] Sign and Send Tx with Ledger
- [ ] Delegate with Ledger

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by ManusMcCole — APPROVED** [review]
Looks good @tomislavhoracek  👍 Tested with testnet on Ledger Nano S

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Tested on Ledger Nano X on build 17330. 👍  @tomislavhoracek

**Comment by darko-mijic** [comment]
I was still asked to export the public key at the end. Is this necessary? Adalite is not asking me to do the same. @tomislavhoracek

**Comment by tomislavhoracek** [comment]
> I was still asked to export the public key at the end. Is this necessary? Adalite is not asking me to do the same. @tomislavhoracek

@darko-mijic I'm even not sure how that is possible, because I removed that method from the whole signing process 😞

**Review by darko-mijic — APPROVED** [review]
Works great!

**Comment by darko-mijic** [comment]
It works better when I use the correct build. 😉

**Comment by tomislavhoracek** [comment]
> It works better when I use the correct build. 😉

@darko-mijic hehe 😄

**Pull request merged**
