### PR TITLE
Fix/daef 478 UI/UX fixes

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces UI/UX fixes.

## TODOs
- [x] Inject missing Japanese translation:
```
wallet.settings.exportWalletButtonLabel: Export wallet
```

## Reported issues
- [x] Ada symbol for redemption icon is too big

- [x] Dark theme: input field borders and separators should be #334152 (update also borders of images in themes screen)

- [x] Dark theme: scroll should be #E9F4FE not #C8CCCE

- [x] Dark theme: wallet settings dropdown arrow active/inactive states are mismatched

- [x] Dark theme: dropdown is white

- [x] Dark theme: all popups are white (shouldn’t we make them dark?)

- [x] About dialog MacOS: if expand window to full screen and then close -> it leaves black screen which can be closed only with closing whole app

- [x] Dark theme: disabled button issue - https://zpl.io/V1yJRlw

- [x] Green theme: dropdown list selection wrong color, should be #EDEEEF

- [x] Switch colors: correct https://zpl.io/V40ZGjQ
screen shot 2017-09-16 at 09 24 55
screen shot 2017-09-16 at 09 25 00
screen shot 2017-09-16 at 09 25 04
screen shot 2017-09-16 at 09 25 09
screen shot 2017-09-16 at 09 25 16
screen shot 2017-09-16 at 09 25 21

- [x] Terms or use: scroller should be as normal on right side, but menu should be fixed  (also should crop in the end of window (not with 20px padding)

- [x] Dialogs should be stylised for each theme (ex. “Cardano” should have gray icons in “add wallet” dialog), same for selections
screen shot 2017-09-16 at 09 26 03
screen shot 2017-09-16 at 09 26 11
screen shot 2017-09-16 at 09 26 17

- [x] Theme screen, dark theme chosen, selection in menu should be inverted (selection color = button color)

- [x] Receive screen -> “Copy address” should not underline when hovered

- [x] “export this wallet” underlined -> strange -> place next to the delete button

- [x] Summary page: scroll whole block (name, amount, tx number), because this info is duped in header
24a
24b

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@darko-mijic can you please obtain missing translation?
```
wallet.settings.exportWalletButtonLabel: Export wallet
```
Thanks! :)

**Comment by nikolaglumac** [comment]
@a-rukin all UI/UX issues are now fixed - please see the result screenshots in the PR's description.

@darko-mijic @DominikGuzei this PR is now ready for review...

**Comment by darko-mijic** [comment]
I have already requested translations for all open PRs @nikolaglumac. Waiting :)

**Comment by a-rukin** [comment]
"Dark theme: input field borders and separators should be #334152 (update also borders of images in themes screen)" : this screenshot shows that difference between active and inactive state is in borders and font weight Light/Regular. Inactive state also should have 50% transparency for text.

**Comment by a-rukin** [comment]
Other things are great!

**Comment by nikolaglumac** [comment]
Thanks for reporting! Will fix it ;)

**Comment by DominikGuzei** [comment]
Reviewing this now …

**Comment by DominikGuzei** [comment]
@nikolaglumac when i run `npm run dev` on this branch im getting this build error:
```
[0] ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]&importLoaders=1!./~/sass-loader?sourceMap!./app/themes/simple/SimpleSelect.scss
[0] Module build failed: 
[0]     border-color: rgba($bg-color, 0);
[0]                  ^
[0]       Argument `$color` of `rgba($color, $alpha)` must be a color
[0] 
[0] Backtrace:
[0] 	node_modules/react-polymorph/lib/themes/simple/mixins/arrow.scss:16, in function `rgba`
[0] 	node_modules/react-polymorph/lib/themes/simple/mixins/arrow.scss:16, in mixin `arrow`
[0] 	node_modules/react-polymorph/lib/themes/simple/SimpleSelect.scss:74
[0]       in /Users/dominik/work/clients/input-output/daedalus/daedalus/node_modules/react-polymorph/lib/themes/simple/mixins/arrow.scss (line 16, column 19)
[0]  @ ./app/themes/simple/SimpleSelect.scss 4:14-205 13:2-17:4 14:20-211
```

Do i have to cleanup something / install anything new?

**Comment by nikolaglumac** [comment]
@DominikGuzei please run `npm install` - new version of react-polymorph is needed in order to get pass those errors ;)

**Comment by nikolaglumac** [comment]
@DominikGuzei please wait with merging until @a-rukin approves the changes ;)

**Comment by a-rukin** [comment]
For now I don't have questions, we discussed mostly everything. So OK.

**Comment by nikolaglumac** [comment]
@a-rukin thanks!
@DominikGuzei we are ready for the merge ;)

**Comment by DominikGuzei** [comment]
@nikolaglumac translation is still missing isn't it?

**Comment by nikolaglumac** [comment]
Ah yeah! Sorry for the confusion :(
We need to wait for the translation first!

**Comment by DominikGuzei** [comment]
@nikolaglumac im adding the missing translation now …

**Comment by DominikGuzei** [comment]
This is ready to be merged as soon as CI is green 👍

**Pull request merged**
