### PR TITLE
[DDW-380] Unable to open Daedalus in safe mode in TestNet

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR fixes the problem where after Daedalus is restarted in safe mode the node and the launcher quit and Daedalus hangs on the connecting screen.
In the scope of this PR two improvements are added:
- better detection of the safe mode (by checking if Daedalus was started with `--safe-mode` argument)
- menu option to "Restart without safe mode" in case Daedalus is running in safe mode

### Menu item
44331587-2e97f780-a46a-11e8-848f-4d459c7a2c38
44331588-2e97f780-a46a-11e8-9030-0e2157dcc63c

### Titlebar label
44331606-3788c900-a46a-11e8-9308-36afe982d64a

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
I have updated the application menu:
screen shot 2018-08-20 at 11 03 11
screen shot 2018-08-20 at 11 03 40

...and also the titlebar label for the safe mode:
screen shot 2018-08-20 at 11 12 53

cc @darko-mijic @cleverca22 @daniloprates

**Comment by nikolaglumac** [comment]
@daniloprates please review this PR 🙏

**Comment by daniloprates** [comment]
I wasn't able to use the feature. When clicking "GPU safe mode" the app will just close and the terminal will show as follows:

image

**Comment by nikolaglumac** [comment]
@daniloprates that is expected in development mode. Please test using one of the installers produced by buildkite: https://buildkite.com/input-output-hk/daedalus/builds/2382

**Comment by nikolaglumac** [comment]
@daniloprates as you can see we now only exit Daedalus UI process with a special exit code so that the Launcher knows what to do (start it again in safe mode or without it): https://github.com/input-output-hk/daedalus/blob/fix/ddw-380-unable-to-open-daedalus-in-safe-mode-in-testnet/source/main/index.js#L39-L45

**Pull request merged**
