### PR TITLE
[DDW-301] Implement stake pool ID hover and copy

### PR DESCRIPTION
**Pull request by daniloprates**
This PR  implements stake pool ID hover and copy.

### Copy state

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates perhaps we should add some animation for the ID expanding?

**Comment by a-rukin** [comment]
Cursor: pointer should be not only for the icon, but for the whole ID

**Comment by a-rukin** [comment]
image
gradient goes under link icon 
p.s. other themes missing variables, right?

**Comment by daniloprates** [comment]
Jul-17-2020 10-54-27

I like it, now. What do you guys think?

@darko-mijic @nikolaglumac @a-rukin

**Comment by a-rukin** [comment]
> I like it, now. What do you guys think?
> 
> @darko-mijic @nikolaglumac @a-rukin

did you remove gradient?

**Comment by daniloprates** [comment]
> did you remove gradient?

@a-rukin I was using a css pseudo element with a gradient bg, but that was keeping the hovering in that bit, so I replaced it by a drop shadow.

**Comment by daniloprates** [comment]
Jul-17-2020 12-00-15

notice also there's a delay for the hover to be activated, now

@a-rukin

**Comment by daniloprates** [comment]
@darko-mijic @nikolaglumac @a-rukin

Adjustments:

* 3s checkmark notification
* Animation on mouse out
* By popular demand, a tooltip (I still think we should lose it, but 🤷🏻‍♂️ )

id

**Comment by a-rukin** [comment]
> @darko-mijic @nikolaglumac @a-rukin
> 
> Adjustments:
> 
> * 3s checkmark notification
> * Animation on mouse out
> * By popular demand, a tooltip (I still think we should lose it, but 🤷🏻‍♂️ )
> 
> id

Very nice! )
You can also change text to "Copied" while showing checkmark

**Comment by nikolaglumac** [comment]
> > @darko-mijic @nikolaglumac @a-rukin
> > Adjustments:
> > 
> > * 3s checkmark notification
> > * Animation on mouse out
> > * By popular demand, a tooltip (I still think we should lose it, but 🤷🏻‍♂️ )
> > 
> > id
> 
> Very nice! )
> You can also change text to "Copied" while showing checkmark

@a-rukin I would keep it as is. Checkmark icon is enough.

**Comment by a-rukin** [comment]
> > > @darko-mijic @nikolaglumac @a-rukin
> > > Adjustments:
> > > 
> > > * 3s checkmark notification
> > > * Animation on mouse out
> > > * By popular demand, a tooltip (I still think we should lose it, but 🤷🏻‍♂️ )
> > > 
> > > id
> > 
> > 
> > Very nice! )
> > You can also change text to "Copied" while showing checkmark
> 
> @a-rukin I would keep it as is. Checkmark icon is enough.

it's an optional step

**Pull request merged**
