### PR TITLE
[DDW-459] Replace in-app support request with links to support page

### PR DESCRIPTION
**Pull request by daniloprates**
This PR replaces in-app support request with links to the support and loading screens.

### Information sent:

The link will receive some information via query strings, as below:

```
{
  "frontendVersion": "0.11.1",
  "backendVersion": "1.3.2",
  "network": "staging",
  "build": "dev",
  "installerVersion": "...",
  "os": "macOS",
  "locale": "en-US",
  "product": "Daedalus wallet - staging",
  "supportLanguage": "English",
  "productVersion": "Daedalus 0.11.1+Cardano 1.3.2"
}
```

Link example:

`https://iohk.zendesk.com/hc/en-us/categories/360000877653-Daedalus-wallet-mainnet?frontendVersion=0.12.0&backendVersion=dev&network=staging&build=dev&installerVersion=dev&os=macOS&locale=en-US&product=Daedalus%20wallet%20-%20staging&supportLanguage=English&productVersion=Daedalus%200.12.0%2BCardano%20dev`

## Todo:

- [x] Support link URL - **Carl Shepard**

### Settings > Support page
- [x] Replace the current action with the link to the support page

### Connecting screen > Having trouble notification
- [x] Replace the action and also 
- [x] Add "download the logs locally" additional link

## Screenshots:

image

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by daniloprates** [comment]
Still missing the final URL and an answer from @a-rukin if the Loading screen should have a white background, but it can be reviewed already.

**Comment by nikolaglumac** [comment]
@daniloprates we show the same notification on connecting (blue) and syncing (grey) screen.
We should not change any colors in the scope of this PR. The task is only about removing in-app support request code and adding this new link "Download logs" on the notification itself.

> could you provide the Download Logs colors for normal and hover states?

There should be no color change on this link. The behavior should be the same as for the links on the Support screen:
screen shot 2018-11-30 at 09 29 32

**Comment by nikolaglumac** [comment]
@daniloprates aren't you missing an icon in the "Open support ticket" button?
screen shot 2018-11-30 at 09 31 14

Regarding the support link URL - we should discuss this with Carl. This will not be a simple link - we will need to pass a set of query params which will carry over important data to the support page. Please ping me once you start working today and I'll explain the details.

**Comment by a-rukin** [comment]
image

**Comment by daniloprates** [comment]
Hey @nikolaglumac!

> we show the same notification on connecting (blue) and syncing (grey) screen.
 
Sure, I didn't realise the "Having trouble syncing?" message could be shown in the syncing screen. I'll add this state for the Download Logs link.

> Regarding the support link URL - we should discuss this with Carl.

Cool, I remember the discussion. I'll ping you.

> aren't you missing an icon in the "Open support ticket" button?

The icon is there. Isn't it appearing for you? Maybe I missed something.

image

**Comment by daniloprates** [comment]
@a-rukin thanks, [fixed](https://github.com/input-output-hk/daedalus/pull/1199/commits/6156df4908f00f258029342a605584abb5812663).

**Comment by nikolaglumac** [comment]
Looks great now @daniloprates 👍

**Comment by DominikGuzei** [comment]
Also reviewing this now …

**Comment by nikolaglumac** [comment]
@DominikGuzei I don't think we can capture that event as it happens in 2 steps:
1. You need to select location for the file on disk and click "OK" (this event we can capture!)
2. Then the actual file gets saved to that location and this operation can take a while (this event I doubt we can capture)

**Comment by DominikGuzei** [comment]
@nikolaglumac i created DDW-509 and DDW-510 for this!

**Comment by nikolaglumac** [comment]
Perfect @DominikGuzei - thanks <3

**Comment by DominikGuzei** [comment]
@daniloprates there are a few merge conflicts here

**Comment by daniloprates** [comment]
@DominikGuzei 12 conflict files later: merged.

**Comment by daniloprates** [comment]
@DominikGuzei actually found some issues. Fixing them.

**Comment by nikolaglumac** [comment]
@daniloprates is this PR now ready for the final review?

**Comment by daniloprates** [comment]
@nikolaglumac I was waiting for some feedback or adjustments request, but I guess we can finish this one and treat any future requests as new cards.

**Comment by DominikGuzei** [comment]
@daniloprates when trying the latest version locally (dev) im getting this URL:
`https://iohk.zendesk.com/hc/en-us/categories/360000877653-Daedalus-wallet-mainnet?frontendVersion=0.12.0&backendVersion=undefined&network=undefined&build=dev&installerVersion=dev&os=macOS&locale=en-US&product=Daedalus%20wallet%20-%20undefined&supportLanguage=English&productVersion=Daedalus%200.12.0%2BCardano%20dev`

Seems like a couple of things are undefined

**Comment by daniloprates** [comment]
@DominikGuzei thanks, variable names updated.

**Comment by nikolaglumac** [comment]
@daniloprates can you please update the support page URLs?
- English: https://iohk.zendesk.com/hc/en-us/requests/new/
- Japanese: https://iohk.zendesk.com/hc/ja/requests/new/

**Pull request merged**
