### PR TITLE
[DDW-836] Fix design implementation issues

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR fixes multiple UI issues across different themes. Required list of fixes is located here:
https://docs.google.com/document/d/1z1EmdIjSsFz4gPch8CEK449fDle-xBvJp-bO9E_61ME/edit

## Todos

- [x] Fix few more remaining UI styling issues

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1566975592000300)
- [ ] Test if all the UI changes are implemented across different themes 

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by IuliaDolishniak** [comment]
screen
Hi @DeeJayElly issue with the arrow is still reproducible

**Comment by tomothespian** [comment]
@IuliaDolishniak This PR is still in WIP. We will ping you once is done

**Comment by a-rukin** [comment]
> Hi @DeeJayElly issue with the arrow is still reproducible

If I'm not mistaken @yakovkaravelov is applying new dropdown styles, so no arrow in future

**Comment by a-rukin** [comment]
image
when I told use light color as a base color, I didn't mean removing transparency ))

**Comment by a-rukin** [comment]
image

This words highlighting is a bit different from what I've suggested. My suggestion was to remove opacity, here just weight increase. With no opacity, it would be more visible (font-weight increase is a very good addition here).

**Comment by a-rukin** [comment]
image
is this only in Netlify?

**Comment by a-rukin** [comment]
image
Underline and link color is broken :((

**Comment by a-rukin** [comment]
image
yellow theme graphic is darker than here https://zpl.io/agQeOXM

**Comment by a-rukin** [comment]
image
headers still have opacity

**Comment by a-rukin** [comment]
image
nice idea, but i meant the whitish bg, it should be those red color + transparecy -> no white

**Comment by DeeJayElly** [comment]
> image
> 
> when I told use light color as a base color (for scroll bar), I didn't mean removing transparency ))
> noticed this in yellow, dark blue and dark cardano themes
> 
> image
> 
> another example

Fixed

**Comment by DeeJayElly** [comment]
> image
> 
> This words highlighting is a bit different from what I've suggested. My suggestion was to remove opacity, here just weight increase. With no opacity, it would be more visible (font-weight increase is a very good addition here).
> p.s. dark themes look good as it is right now 👍

Fixed

**Comment by DeeJayElly** [comment]
> image
> 
> yellow theme graphic is darker than here https://zpl.io/agQeOXM

Fixed

**Comment by DeeJayElly** [comment]
> image
> 
> is this only in Netlify?

Yes it's only rendered like that on Netifly, i don't know why, in the app it looks ok.

**Comment by DeeJayElly** [comment]
> image
> 
> nice idea, but i meant the whitish bg, it should be those red color + transparecy -> no white

Done

**Comment by DeeJayElly** [comment]
> image
> 
> headers still have opacity

Done

**Comment by IuliaDolishniak** [comment]
screen
@DeeJayElly will this one be fixed to be of "Copy path" color?

**Comment by IuliaDolishniak** [comment]
screen

have highlighted in red the color difference of Daedalus

**Comment by IuliaDolishniak** [comment]
Image 7

**Comment by IuliaDolishniak** [comment]
Image 11

**Comment by DeeJayElly** [comment]
> screen
> @DeeJayElly will this one be fixed to be of "Copy path" color?

Color of the Tooltip is the same like color of the notification in these screens.

**Comment by IuliaDolishniak** [comment]
> > screen
> > @DeeJayElly will this one be fixed to be of "Copy path" color?
> 
> Color of the Tooltip is the same like color of the notification in these screens.

Image 7
In the document attached it was requested to make it of the color of "Copy path" notification. Nikola said that it will be hard to do but try. I wanted to know what was the resolution?

**Comment by DeeJayElly** [comment]
> > > screen
> > > @DeeJayElly will this one be fixed to be of "Copy path" color?
> > 
> > 
> > Color of the Tooltip is the same like color of the notification in these screens.
> 
> Image 7
> In the document attached it was requested to make it of the color of "Copy path" notification. Nikola said that it will be hard to do but try. I wanted to know what was the resolution?

If you compare it now, they look the same, notifacations background and Copy path tooltip background

**Comment by DeeJayElly** [comment]
> screen
> 
> have highlighted in red the color difference of Daedalus

Fixed

**Comment by DeeJayElly** [comment]
https://github.com/input-output-hk/daedalus/pull/1547#issuecomment-526805231

Fixed

**Comment by a-rukin** [comment]
https://zpl.io/bzN3l07 - @DeeJayElly I also had a comment here about scrollbar hovering, can you apply it too?

**Comment by a-rukin** [comment]
image

Small misunderstanding: 
- we don't need to remove transparency for "Note that password needs to be at least", "long, and have at least" and "letter and"

**Comment by a-rukin** [comment]
image
dark cardano seems to be not fixed

**Comment by a-rukin** [comment]
image

Oh..
I meant this:

image

Dark Blue had it right: #EA4C5B for progress and #EA4C5B+20% opacity for bg

**Comment by IuliaDolishniak** [comment]
> > screen
> > @DeeJayElly will this one be fixed to be of "Copy path" color?
> 
> Color of the Tooltip is the same like color of the notification in these screens.

It was requested to make logs download and copy path notifications of the same color I was asking about this. 
Image 3

**Comment by a-rukin** [comment]
image

**Comment by a-rukin** [comment]
> > > > screen
> > > > @DeeJayElly will this one be fixed to be of "Copy path" color?
> > > 
> > > 
> > > Color of the Tooltip is the same like color of the notification in these screens.
> > 
> > 
> > Image 7
> > In the document attached it was requested to make it of the color of "Copy path" notification. Nikola said that it will be hard to do but try. I wanted to know what was the resolution?
> 
> If you compare it now, they look the same, notifacations background and Copy path tooltip background

so now they are all yellow?
and blue for blue?

**Comment by IuliaDolishniak** [comment]
> > > > > screen
> > > > > @DeeJayElly will this one be fixed to be of "Copy path" color?
> > > > 
> > > > 
> > > > Color of the Tooltip is the same like color of the notification in these screens.
> > > 
> > > 
> > > Image 7
> > > In the document attached it was requested to make it of the color of "Copy path" notification. Nikola said that it will be hard to do but try. I wanted to know what was the resolution?
> > 
> > 
> > If you compare it now, they look the same, notifacations background and Copy path tooltip background
> 
> so now they are all yellow?
> and blue for blue?

I see the absolutely the same as it was before. 
Image 2
Image 3

**Comment by a-rukin** [comment]
second is good ⬆️

**Comment by IuliaDolishniak** [comment]
> second is good ⬆️

Is this what you expected to be?

**Comment by IuliaDolishniak** [comment]
Image 2
Button color is still yellow

**Comment by IuliaDolishniak** [comment]
Image 2
dont' see transparancy on  the screen also for yellow and white themes.

**Comment by a-rukin** [comment]
> > second is good ⬆️
> 
> Is this what you expected to be?

first (log download) should be also like a second on this screen, on non-overlay screens it remains yellow

**Comment by IuliaDolishniak** [comment]
Solution looks like this
Image 2
In Storybook it looks like this
Image 5
Was it agreed not to make this change? @DeeJayElly @a-rukin

**Comment by a-rukin** [comment]
> Solution looks like this
> Image 2
> In Storybook it looks like this
> Image 5
> Was it agreed not to make this change? @DeeJayElly @a-rukin

this is a feature update, not a current bug, so probably other task

**Comment by DeeJayElly** [comment]
> https://zpl.io/bzN3l07 - @DeeJayElly I also had a comment here about scrollbar hovering, can you apply it too?

Added

**Comment by a-rukin** [comment]
> > https://zpl.io/bzN3l07 - @DeeJayElly I also had a comment here about scrollbar hovering, can you apply it too?
> 
> Added

Just checked and it seems like "like blue" and "cardano" themes have 20%  and 40% instead of 30% and 50% 🤔

**Comment by IuliaDolishniak** [comment]
> Image 2
> Button color is still yellow

On the doc attached it was required to change the button color to be like this:
screen

**Comment by DeeJayElly** [comment]
> > Image 2
> > Button color is still yellow
> 
> On the doc attached it was required to change the button color to be like this:
> screen

@a-rukin can you confirm this?

**Comment by IuliaDolishniak** [comment]
@DeeJayElly sorry for this, I have understood it wrong. Only font color was requested to be changed.

**Comment by a-rukin** [comment]
> > > Image 2
> > > Button color is still yellow
> > 
> > 
> > On the doc attached it was required to change the button color to be like this:
> > screen
> 
> @a-rukin can you confirm this?

Oh.. yes, apply proper button style for this one and that's it
Problem was that whole screen was broken (wrong BG and button style)

**Comment by DeeJayElly** [comment]
> > > > Image 2
> > > > Button color is still yellow
> > > 
> > > 
> > > On the doc attached it was required to change the button color to be like this:
> > > screen
> > 
> > 
> > @a-rukin can you confirm this?
> 
> Oh.. yes, apply proper button style for this one and that's it
> Problem was that whole screen was broken (wrong BG and button style)

Done

**Comment by IuliaDolishniak** [comment]
screen
Perfect. Thanks.

**Pull request merged**
