### PR TITLE
[DDW-618] Fix asset amount validation

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR fixes asset amount validation so that it is possible to send a maximum supported amount defined in cardano-wallet - which is `2^64 - 1`, or: `18,446,744,073,709,551,615`.

Slack-thread: https://input-output-rnd.slack.com/archives/GGKHNC5V4/p1617091466027300

## TODOs

- [x] Update cardano-wallet to a version which supports sending asset amounts in string format: https://github.com/input-output-hk/cardano-wallet/pull/2587 - This is not necessary because it is resolved with JSONbig parser!
- [x] Setup BigInt request/response parsing: https://www.npmjs.com/package/json-bigint
- [x] Check known Ledger TX send issue with big asset amount https://input-output-rnd.slack.com/archives/GGKHNC5V4/p1623066512026000 (**Followup task created https://jira.iohk.io/browse/DDW-701**)

## Screenshots

Screenshot 2021-03-22 at 14 28 47
Screenshot 2021-03-22 at 14 28 50
Screenshot 2021-03-22 at 14 29 32
Screenshot 2021-03-22 at 14 29 29

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test sending`18,446,744,073,709,551,615` (which should work) vs `18,446,744,073,709,551,616` amount (which should throw an error) 

---

## Test Cases

```Gherkin
Scenario 1: Send max allowed - 1
Given I have a wallet with at least 18,446,744,073,709,551,614 of the same native token
And I am on wallet send screen
When I send 18,446,744,073,709,551,614 of the same native token
Then the transaction is successful
And the transaction is correct on summary tab
And the transaction is correct on transaction tab

Scenario 2: Send max allowed 
Given I have a wallet with at least 18,446,744,073,709,551,615 of the same native token
And I am on wallet send screen
When I send 18,446,744,073,709,551,615 of the same native token
Then the transaction is successful
And the transaction is correct on summary tab
And the transaction is correct on transaction tab

Scenario 3: Send max allowed + 1
Given I have a wallet with at least 18,446,744,073,709,551,616 of the same native token
And I am on wallet send screen
When I send 18,446,744,073,709,551,616 of the same native token
Then an error message “Please enter a valid amount” is displayed

Scenario 4: Fees calculated when send max allowed -1 
iven I have a wallet with at least 18,446,744,073,709,551,614 of the same native token
And I am on wallet send screen
When I send 18,446,744,073,709,551,614 of the same native token
Then I could see the fees being calculated
And the displayed fees look reasonable

Scenario 5: Fees calculated when send max allowed
iven I have a wallet with at least 18,446,744,073,709,551,615 of the same native token
And I am on wallet send screen
When I send 18,446,744,073,709,551,615 of the same native token
Then I could see the fees being calculated
And the displayed fees look reasonable

Scenario 6: Fees not calculated when send max allowed + 1
iven I have a wallet with at least 18,446,744,073,709,551,616 of the same native token
And I am on wallet send screen
When I send 18,446,744,073,709,551,616 of the same native token
Then the fees are not calculated
And the displayed fees remain at 0.000000 ADA

```

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by piotr-iohk** [comment]
I've installed Daedalus testnet version from this PR and I think something is not quite right:

I'm seeing this error that is returned from cardano-wallet when trying to send 18446744073709551615 units of an asset:
```
  "msg": "AdaApi::calculateTransactionFee error",
  "data": {
    "error": {
      "code": "output_token_quantity_exceeds_limit",
      "message": "One of the token quantities you've specified is greater than the maximum quantity allowed in a single transaction output. Try splitting this quantity across two or more outputs. Destination address: 003c3a43...dfd8a398. Token policy identifier: 7a68ed78876dfab1044459684071331529fc030defea49f0f98bc98b. Asset name: 626967676572636f696e. 
Token quantity specified: 18446744073709552000. Maximum allowable token quantity: 18446744073709551615."
    }
  }
}
```
Note that despite specyfying `18446744073709551615` in UI the error says `...Token quantity specified: 18446744073709552000` (18446744073709552000 > 18446744073709551615). So it seems there is some sort of overflow...
Screenshot from 2021-03-22 15-21-37



Please note that It is possible for me to get fee estimation making request to cardano-wallet directly with the same parameters:

```
curl -X POST https://localhost:41029/v2/wallets/73d38c71e4b8b5d71769622ab4f5bfdedbb7c39d/payment-fees \
-d '{"payments":[{"address":"addr_test1qq7r5smuae9rnm9fj970srfzx4x7jfaquuad9zcmql2ckcz6zr7fqxtx886jcw4l2l5gt9exm4j73z6ut6hrth7c5wvqv3cyxr","amount":{"quantity":2000000,"unit":"lovelace"},"assets":[{"policy_id":"7a68ed78876dfab1044459684071331529fc030defea49f0f98bc98b","asset_name":"626967676572636f696e","quantity":18446744073709551615}]}]}' \
--cert /home/piotr/.local/share/Daedalus/testnet/tls/client/client.pem \
--cacert /home/piotr/.local/share/Daedalus/testnet/tls/client/ca.crt \
-H "Content-Type: application/json"

{
  "estimated_min": {
    "quantity": 192077,
    "unit": "lovelace"
  },
  "deposit": {
    "quantity": 0,
    "unit": "lovelace"
  },
  "minimum_coins": [
    {
      "quantity": 1481480,
      "unit": "lovelace"
    }
  ],
  "estimated_max": {
    "quantity": 192077,
    "unit": "lovelace"
  }
}

```

**Comment by nikolaglumac** [comment]
Will check it a bit later today.

**Comment by nikolaglumac** [comment]
> I've installed Daedalus testnet version from this PR and I think something is not quite right:
> 
> I'm seeing this error that is returned from cardano-wallet when trying to send 18446744073709551615 units of an asset:
> 
> ```
>   "msg": "AdaApi::calculateTransactionFee error",
>   "data": {
>     "error": {
>       "code": "output_token_quantity_exceeds_limit",
>       "message": "One of the token quantities you've specified is greater than the maximum quantity allowed in a single transaction output. Try splitting this quantity across two or more outputs. Destination address: 003c3a43...dfd8a398. Token policy identifier: 7a68ed78876dfab1044459684071331529fc030defea49f0f98bc98b. Asset name: 626967676572636f696e. 
> Token quantity specified: 18446744073709552000. Maximum allowable token quantity: 18446744073709551615."
>     }
>   }
> }
> ```
> 
> Note that despite specyfying `18446744073709551615` in UI the error says `...Token quantity specified: 18446744073709552000` (18446744073709552000 > 18446744073709551615). So it seems there is some sort of overflow...
> Screenshot from 2021-03-22 15-21-37
> 
> Please note that It is possible for me to get fee estimation making request to cardano-wallet directly with the same parameters:
> 
> ```
> curl -X POST https://localhost:41029/v2/wallets/73d38c71e4b8b5d71769622ab4f5bfdedbb7c39d/payment-fees \
> -d '{"payments":[{"address":"addr_test1qq7r5smuae9rnm9fj970srfzx4x7jfaquuad9zcmql2ckcz6zr7fqxtx886jcw4l2l5gt9exm4j73z6ut6hrth7c5wvqv3cyxr","amount":{"quantity":2000000,"unit":"lovelace"},"assets":[{"policy_id":"7a68ed78876dfab1044459684071331529fc030defea49f0f98bc98b","asset_name":"626967676572636f696e","quantity":18446744073709551615}]}]}' \
> --cert /home/piotr/.local/share/Daedalus/testnet/tls/client/client.pem \
> --cacert /home/piotr/.local/share/Daedalus/testnet/tls/client/ca.crt \
> -H "Content-Type: application/json"
> 
> {
>   "estimated_min": {
>     "quantity": 192077,
>     "unit": "lovelace"
>   },
>   "deposit": {
>     "quantity": 0,
>     "unit": "lovelace"
>   },
>   "minimum_coins": [
>     {
>       "quantity": 1481480,
>       "unit": "lovelace"
>     }
>   ],
>   "estimated_max": {
>     "quantity": 192077,
>     "unit": "lovelace"
>   }
> }
> ```

@piotr-iohk this is due to the maximum safe integer in JavaScript which is: 9007199254740991 (2^53 - 1) which is smaller than the maximum asset amount limit defined in CWB (2^64-1).
We need to modify the CWB API to accept token quantities as string in order for this to work.

**Comment by miorsufianiohk** [comment]
On build 18112:

When attempting to send allowed amount of tokens, GenericApiError displayed on console. Please [see screenshot](https://drive.google.com/file/d/10ucK7u_zi8kFmB6EJOPr7uRiJNzEQLyg/view?usp=sharing)

**Comment by tomislavhoracek** [comment]
@miorsufianiohk it should be fixed now. Can you test again 🙏

**Review by aleksandardjordjeviciohk — APPROVED** [review]
Looks ok, gj @tomislavhoracek

**Comment by miorsufianiohk** [comment]
Hi @tomislavhoracek on build 18115.

Thanks for fixing the previous issue. On this build I found:

- Validation error not displayed (both EN and JP) when amount of tokens = max amount + 1. Please [see screenshot](https://drive.google.com/file/d/14zaXzgpcIf8z4AamlWCnXLItv3xqQz_J/view?usp=sharing)

**Comment by miorsufianiohk** [comment]
Hi @tomislavhoracek . On build 18120.

Thanks for fixing the previous issues. I have found another issue which might be backend related. 

- When I entered the value: 1,844,674,407,370,955,161.6, validation error message "Please enter a valid amount" was displayed. However, there wasn't any error message when the value was 1,844,674,407,370,955,161.5. 

I could replicate the error message by using values that contains decimals eg. 1,844,674,407,370,955,161.7 ,1,844,674,407,370,955,161.8, 1,844,674,407,370,955,161.9 etc. But no error, when it was a whole number, ie 1,844,674,407,370,955,162

Also no error when the decimals were 1,844,674,407,370,955,161.5 or less, eg 1,844,674,407,370,955,161.4, 1,844,674,407,370,955,161.3, 1,844,674,407,370,955,161.2, etc

**Comment by miorsufianiohk** [comment]
Thank you for the explanation @tomislavhoracek . I agree the validation is working as expected 👍  
> Hi @tomislavhoracek . On build 18120.
> 
> Thanks for fixing the previous issues. I have found another issue which might be backend related.

**Review by miorsufianiohk — APPROVED** [review]
LGTM. :Great work @tomislavhoracek  👍 . Tested on 18150

**Review by gabriela-ponce — APPROVED** [review]

**Review by ManusMcCole — APPROVED** [review]

**Review by DominikGuzei — APPROVED** [review]
Code Looks great 🎉

**Comment by DominikGuzei** [comment]
@miorsufianiohk can you do a last re-test (i just merged `develop`, just to be safe)

**Review by miorsufianiohk — APPROVED** [review]
Looks good. Retested on 18510 👍

**Review by ManusMcCole — APPROVED** [review]

**Pull request merged**
