### PR TITLE
[DDW-1185] - Low disk space alert message not displayed for ITN

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR fixes low disk space alert message not being displayed for itn.

## Screenshots

Screenshot 2020-01-30 22 04 05

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1580418330081100)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by IuliaDolishniak** [comment]
@DeeJayElly hello, I have left 105 Mb free on disk C while Daedalus was running and was performing different actions on Daedalus but it was showing that I have 7Gb free for me. Only when I closed and reopened app I got this red error.

**Comment by DmitriiGaico** [comment]
> @DeeJayElly hello, I have left 105 Mb free on disk C while Daedalus was running and was performing different actions on Daedalus but it was showing that I have 7Gb free for me. Only when I closed and reopened app I got this red error.
> 
> 

That's expected behavior. Available disk space Value is saved/displayed once you start Daedalus (Not in RealTime.). As i remember this wasn't changed and works as i described. cc @nikolaglumac

**Comment by DmitriiGaico** [comment]
Here is the initial DDW tickets with the logic details. @ManusMcCole @IuliaDolishniak 
https://iohk.myjetbrains.com/youtrack/issue/DDW-256
cc @nikolaglumac

**Comment by IuliaDolishniak** [comment]
According to the YT ticket it should check every 10 seconds space availability, isn't it?

**Comment by DmitriiGaico** [comment]
> According to the YT ticket it should check every 10 seconds space availability, isn't it?

yes in case if you start Daedalus with >= 0 && < 2 GB OR You are Already see the Red Screen.

**Comment by IuliaDolishniak** [comment]
@DeeJayElly please ignore my issue in 10 minutes Red Alert is shown.

**Comment by DmitriiGaico** [comment]
@DeeJayElly 
Hello! I have noticed different statuses for the Node State so wanted to double check what to expect.
The scenario is : 
Fill up the Disk C <=1.5GB so once Daedalus is started the Red Screen is showed up. Start Daedalus.
The question is for this scenario what Node Status is expected? Currently for
Windows : Connecting to the Network is showed in the Background \ Running in Diagnostic Screen.
Linux : Starting Cardano Node is showed in the Background \ Starting in Diagnostics Screen.
Node States

**Comment by ManusMcCole** [comment]
On MacOs only when there is less than 1.5gb of space no red alert screen is showing. It just gives the Cardano node stopped error. It is recorded in the logs as in the video below
lessthan2gbdiskspaceMacOs

**Comment by DeeJayElly** [comment]
> @DeeJayElly
> Hello! I have noticed different statuses for the Node State so wanted to double check what to expect. As i recall we should Stop the node if Running or Not Even Start it if Space is Low.
> The scenario is :
> Fill up the Disk C <=1.5GB so once Daedalus is started the Red Screen is showed up. Start Daedalus.
> The question is for this scenario what Node Status is expected? Currently for
> Windows : Connecting to the Network is showed in the Background \ Running in Diagnostic Screen.
> Linux : Starting Cardano Node is showed in the Background \ Starting in Diagnostics Screen.
> Node States
> 
> Sometimes at Windows it shows the correct State but after 5 minutes Having Trouble Screen is showed. Do we expect it even node is not Running?
> image

Hmm yeah that's a strange behavior, it shouldn't be like that, we should unify the error messages and show the same messages in those situations. But i think that implementation is not part of this ticket. We should raise this and create a new ticket for it.

**Comment by DmitriiGaico** [comment]
@DeeJayElly Hey! I just tried PROD MainNet at Windows and Linux and if you Start Daedalus while Space is <1.5gb it shoots you Red Screen and in background you can Notice statuses "Stopping Cardano >Cardano Stopped" and always the last message is "Cardano Stopped" and same in Diagnostics Screen. However after waiting some time the Having Trouble message also showed up even Node is Stopped.

So for the ITN builds looks like even Red Screen is showed app still trying to Start or Run the Node. And sometimes it stuck and We cannot see Cardano Stopped Message.

I think we need Master @nikolaglumac here to clear the things up.

Thank you!

**Comment by DmitriiGaico** [comment]
The Actual Node is Stopped just fine so looks only the Statuses sometimes are wrong. Thank you.
cc @DeeJayElly @nikolaglumac

**Comment by ManusMcCole** [comment]
On the latest build 10451 the Red Screen with the message Daedalus requires more hard drive space is displayed correctly. It pops up immediately after accepting terms and conditions as expected

**Pull request merged**
