### PR TITLE
[DDW-821] Reorganize Test Setup

### PR DESCRIPTION
**Pull request by MarcusHurney**
- This PR **reorganizes all test files** comprising the Daedalus acceptance tests by dividing them into directories based on domain. A test belongs to a domain depending on the category of functionality it's meant to test. Within Daedalus the domains `wallets`, `paper-wallets`, `addresses`, `transactions`, `navigation`, `nodes`, `settings`, and `common`. These domains will now also constitute the top level directories of the Daedalus acceptance tests.

- Adds **flow support** and fixes all flow errors for all `.js` files (`steps` and `helpers`) within the `tests` directory.

- Also **expands the documentation** for the Daedalus acceptance `tests` suite.
---
### Basics

- [x] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn flow:test`)
- [x] There are no *lint* errors or warnings (`yarn lint`)
- [x] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [x] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [x] Japanese text changes are proofread and approved (Junko Oda)
- [x] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [x] Important parts of the code are properly commented and documented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-renderings
- [x] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@MarcusHurney all tests are passing now 🎉 

Screenshot 2019-09-25 at 12 45 46

@darko-mijic we need your approval for these changes as `features` folder was removed. Not sure if that is a good idea...

**Comment by nikolaglumac** [comment]
@MarcusHurney can you please merge latest develop into this branch?

**Comment by MarcusHurney** [comment]
@nikolaglumac I'm on it.

**Comment by nikolaglumac** [comment]
This PR will be merged as soon as we finish the 0.15.0 release...

**Pull request merged**
