### PR TITLE
Chore/daef 90 translation manager

### PR DESCRIPTION
**Pull request by darko-mijic**
This PR introduces [translation manager](https://github.com/GertjanReynaert/react-intl-translations-manager) which can be started using `npm run manage-translations`.
Translation manager removes unused translation keys and generates `app/i18n/locales/defaultMessages.json` file with all translations needed for importing into [Translation editor](https://bitbucket.org/bflower/react-intl-editor/wiki/Home) which will be used by translators.

In scope of this PR output location for generated translations messages was changed to `translations/messages`.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@darko-mijic i pulled, `npm install` and ran `npm run manage-translations`, now all translation files are empty … did i miss a step?

**Comment by darko-mijic** [comment]
Translations were moved to a different folder. I forgot to mention that you need to start the app once before running translation manager. Sorry about this. Please revert translations and start the app before running `npm run manage-translations`.

**Comment by DominikGuzei** [comment]
Yeah, i just figured that … since it's in the babel config 😉

**Comment by darko-mijic** [comment]
We can update German and Croatian translations in scope of the separate PRs before we launch with support for switching languages.

**Comment by DominikGuzei** [comment]
Should i update German here you mean?

**Comment by darko-mijic** [comment]
No, i would leave that for a separate PR. I haven't updated Croatian here. Let's keep this focused to introduction of translation managery only.

**Comment by DominikGuzei** [comment]
Ok great, it works perfectly and is really nice, will merge! 👍 👍 👍

**Pull request merged**
