### PR TITLE
[DDW-748] Implement upcoming LedgerJS breaking changes

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces a code that will cover upcoming LedgerJS breaking changes.
[JIRA Ticket](https://input-output.atlassian.net/browse/DDW-748)

## Todos

- [x] Update LedgerJS package to the official version once is published - **DO NOT MERGE**
- [x] Resolve the problem with TX signing rejection. Investigate what clause is wrong on our side or LedgerJS side

## Screenshots

_- No screenshots_

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1633953877430500)

**Ledger Devices (Test with old and new / unreleased Cardano App v3.0.0)**
- [ ] Sign and send regular TX
- [ ] Sign and send TX with native tokens
- [ ] Delegate or Redelegate
- [ ] Verify wallet address (receive screen)

**Trezor Devices**
- [ ] It would be nice if you can test the same actions as for Ledger devices just to ensure everything is working and that something is not corrupted with Ledger breaking changes.

**NOTES:**
- There is no need for testing breaking changes e.g. different connecting / pairing scenarios because those breaking changes introduced by LedgerJS package update are affecting only the data flow and not how the device will be connected!

- About _"Test with old and new Cardano App"_:
a) Old Cardano App is the current (official) app.
b) New Cardano App is an unreleased app and can be tested from experimental features. To update Ledger Cardano App to the unreleased RC version you need to do that with "Ledger Live". The app has been deployed on a test provider. In order to install the app, go to `Ledger Live settings` -> `experimental features`, activate `manage provider`, and set to **4**. After that, you will see **Cardano App v3.0.0** in the device manager applications list!

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by miorsufianiohk** [comment]
Hi @tomislavhoracek ,

This is my current report for build 19304.

**Comment by miorsufianiohk** [comment]
> @miorsufianiohk can you upload the correct screenshots. Both are same and one for delegating is not presented

@tomislavhoracek Sorry my friend. I have corrected the link now. Thanks for letting me know :)

**Comment by ManusMcCole** [comment]
Here is Ledger X testing report for build 19304 Cardano App 3.0.0 on Mac. Ledger Live has closed for all testing. Only ever 1 device persent in Daedalus or attatched to my machine at any one time.

Here is one scenario where I found an error. Install fresh Daedalus. Pair Ledger X device then restore shelley wallet. Wait for both to load. Close Daedalus. Disconnect Ledger X device. Open Daedalus .Share Shelley address. Create transaction from Ledger X to Shelley wallet. Click Send. Daedalus asks to connect device. I connect device and immediately see a "transaction confirmation failed" error. See [Screenshot](https://drive.google.com/file/d/144QI6hgCIb2kgTk0-Do67a-HzG_v266H/view?usp=sharing). Value for command 1 is 

"{\"inputs\":[{\"address\":\"addr_test1qzhn0xjjt4yy6cq702l0dka0cpgwcq7qyy6r9k35sqmyn3ps4ff3j7785e758sntc08thp46ruxwkfpxakyunck92eysfxgf9g\",\"amount\":{\"quantity\":5410963,\"unit\":\"lovelace\"},\"id\":\"fe725782ad94947421e2cdcd4cd6fdced0531797dcebc9e20698a519a33fdf5f\",\"index\":1,\"derivationPath\":[\"1852H\",\"1815H\",\"0H\",\"1\",\"40\"],\"assets\":[{\"policyId\":\"789ef8ae89617f34c07f7f6a12e4d65146f958c0bc15a97b4ff169f1\",\"assetName\":\"74727565636f696e\",\"quantity\":1},{\"policyId\":\"ee1d198fd1b4ef0f8aa0238d19c55c22562252e46abe195e79f68762\",\"assetName\":\"53696e67756c61726974794e4554\",\"quantity\":1}]}],\"outputs\":[{\"address\":\"addr_test1qrvuvj68g4z9dvcqmdwszzfm2c4mssltf5h36svc7f7a0rffq233y9t9vt5unrxgdxmv3ef4d4ae0np75uucswdyy0jshvk265\",\"amount\":{\"quantity\":2000000,\"unit\":\"lovelace\"},\"derivationPath\":null,\"assets\":[]},{\"address\":\"addr_test1qz8v7x0pq9elwagy0ueuqqrftuany0j7qse0u03r8vcrnv3s4ff3j7785e758sntc08thp46ruxwkfpxakyunck92eys7q7f8t\",\"amount\":{\"quantity\":3237190,\"unit\":\"lovelace\"},\"derivationPath\":[\"1852H\",\"1815H\",\"0H\",\"1\",\"47\"],\"assets\":[{\"policyId\":\"789ef8ae89617f34c07f7f6a12e4d65146f958c0bc15a97b4ff169f1\",\"assetName\":\"74727565636f696e\",\"quantity\":1},{\"policyId\":\"ee1d198fd1b4ef0f8aa0238d19c55c22562252e46abe195e79f68762\",\"assetName\":\"53696e67756c61726974794e4554\",\"quantity\":1}]}],\"certificates\":[],\"withdrawals\":[],\"fee\":\"0.173773\",\"deposits\":\"0\",\"depositsReclaimed\":\"0\",\"metadata\":null}" 

and value for command 2 is null. Here are the [Logs](https://drive.google.com/file/d/1hj0m-w6sse0tjS7KR985lTQygpCK26LD/view?usp=sharing)

**Review by ManusMcCole — APPROVED** [review]
Good work @tomislavhoracek 👍

**Pull request merged**
