### PR TITLE
[DDW-374] Submit network and software versions to reporting server

### PR DESCRIPTION
**Pull request by daniloprates**
This PR changes the information we are sending on support requests to the reporting server.

## Todo:

application field and submit these values based on the network:

- [x] Remove the `application` field
- [x] Submit these new values:
```
product: Cardano Wallet
frontendVersion: 0.11.0 (from the environment)
backendVersion: 1.3.0 (from the environment)
buildNumber: 211221 (from the environment)
network: testnet (from the environment)
```
**Note**: Currently the field `build` sends `${API_VERSION}.${BUILD_NUMBER}`. With this change, this information will be sent through a new field called `installerVersion`, whereas `build` will send, in fact, only the build number.

**Before**:
```
build: 1.2.1.211221,
```
**After**:
```
build: 211221,
installerVersion: 1.2.1.211221,
```

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by darko-mijic** [comment]
@daniloprates, I've made a mistake with target version. This needs to target `0.11.1` release.

**Comment by darko-mijic** [comment]
Retargeting did not really work. I think we will need to prepare a new PR.

**Comment by daniloprates** [comment]
@darko-mijic working on it.

**Comment by nikolaglumac** [comment]
@daniloprates @darko-mijic closing this one **unmerged** in favor of https://github.com/input-output-hk/daedalus/pull/1036

**Pull request closed without merging**
