### PR TITLE
[DDW-600] Implement button to open the local database directory

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR changes Daedalus Diagnostics Dialog and adds button to open local state directory next to state directory path. Clicking on the button local state directory is open.

## Screenshots

Screen Shot 2019-07-05 at 12 11 44

### On hovering and clicking the path

Screen Shot 2019-07-05 at 12 11 53

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1561569908137900)
- [ ] Test if clicking on the button, local state directory is open.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
What tab in netlify it is?

**Comment by a-rukin** [comment]
image
Judging the screenshot button seems to be too far away from the text

**Comment by DeeJayElly** [comment]
> @DeeJayElly Please fix the logic to have the exactly folder opened for Corresponding NET.

Done @DmitriiGaico

**Comment by DeeJayElly** [comment]
> @DeeJayElly Hello! Please fix the Resizing issue for Japanese. Thank you!
> image

Done

**Comment by nikolaglumac** [comment]
@daniloprates can you  please review this one? 🙏

**Comment by daniloprates** [comment]
Reviewing

**Comment by IuliaDolishniak** [comment]
I remember @a-rukin were saying on the distance between Open button and the path
screen

**Comment by a-rukin** [comment]
Open button can move (if text size changes) but it is sticked to the text with a 16px distance
https://zpl.io/2GyPKWm - 1 new addition is copy icon, as now there is no ability to copy path if text is cropped

**Comment by gnpf** [comment]
> > @DeeJayElly Hello! Please fix the Resizing issue for Japanese. Thank you!
> 
> Done

> > @DeeJayElly Please fix the logic to have the exactly folder opened for Corresponding NET.
> 
> Done @DmitriiGaico

@DeeJayElly I checked those fixes and they are approved.

**Pull request merged**
