### PR TITLE
[DDW-968] Introduce address validator

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces new address validation way using `cardano-js` npm package.

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1572006072228400)
- [ ] Enter wrong address into wallet send form and check if error occur

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by tomothespian** [comment]
> The requirements for this utility only specified the _network type_, however this was probably before node implementation variance was a concern. I propose this: [input-output-hk/cardano-js#10](https://github.com/input-output-hk/cardano-js/issues/10) as a better interface so you don't have to understand the values being passed back.
> 
> Currently there is a chance you could get a false-positive:
> 
> https://github.com/input-output-hk/cardano-js/blob/develop/src/Address/JormungandrAddress.ts#L7
> 
> https://github.com/input-output-hk/cardano-js/blob/develop/src/Address/ByronAddress.ts#L11

Thanks @rhyslbw we discussed that before you commented and `kind` check will be removed for now. Once your proposal will be implemented I can do code improvement which will check also `addressKind ` type and `nodeImplementation`. Can you ping me when that is done so we can discuss proper solution?

**Comment by rhyslbw** [comment]
@tomothespian I will do this tomorrow and release a new version along with https://github.com/input-output-hk/cardano-js/issues/9, which might be a nicer interface for validation per keystroke

**Comment by tomothespian** [comment]
@rhyslbw Thank you soo much

**Comment by nikolaglumac** [comment]
@tomothespian can we please get this one done today? 🙏

**Comment by tomothespian** [comment]
@rhyslbw I removed address KIND check from address validation method. Shall we wait for your new `cardano-js` release or we can merge this PR with current changes?
cc @nikolaglumac

**Comment by rhyslbw** [comment]
Sorry, guys. Yes, this LGTM. I'll let you know when the new version is out

**Pull request merged**
