### PR TITLE
[DDW-1145] Pending delegation preferences

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR implements pending delegation preferences and updates cardano-wallet revision.

## Todos

- [x] Integrate API
- [x] Extend `Wallet` domain to contain next delegation preference
- [x] Show next delegation preference in the UI

## Screenshots
Screenshot 2020-02-13 14 52 52

Screenshot 2020-02-13 15 03 47

Screenshot 2020-02-14 15 35 18
Screenshot 2020-02-14 15 34 59

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1581342150015000)
- [x] Test Delegation to stake pool to see the pending delegation icon and info
- [ ] Test multiple Delegations to stake pools to see the pending delegation icon and info
- [ ] Test Delegation to 2 different stake pools and trying to delegate again to the last delegated stake pool to see the pending delegation label in Delegation Wizard step 3
- [ ] Test Delegation to 2 different stake pools and trying to delegate again to the last delegated stake pool to see the disabled Continue button in Delegation Wizard step 3

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by daniloprates** [comment]
@a-rukin @darko-mijic 
image

Maybe we could display an ⌛️ icon in the next pool, like the ✔️ in the current one, and make it not-selectable.

**Comment by DeeJayElly** [comment]
> image
> 
> When trying to delegate to a Stake Pool already pending to be delegated, we show a generic error. We should either disable this pool or display a better error message.

Fixed

**Comment by DeeJayElly** [comment]
> @a-rukin @darko-mijic
> image
> 
> Maybe we could display an ⌛️ icon in the next pool, like the ✔️ in the current one, and make it not-selectable.

Should we add something here because this was already stated on the delegation center screen where you have the sand clock icon if it's pending and you clearly see which one is currently staking, which one is pending?

@a-rukin @daniloprates @darko-mijic

**Comment by DeeJayElly** [comment]
> > @a-rukin @darko-mijic
> > image
> > Maybe we could display an ⌛️ icon in the next pool, like the ✔️ in the current one, and make it not-selectable.
> 
> Should we add something here because this was already stated on the delegation center screen where you have the sand clock icon if it's pending and you clearly see which one is currently staking, which one is pending?
> 
> @a-rukin @daniloprates @darko-mijic

Fixed

**Comment by a-rukin** [comment]
> > @a-rukin @darko-mijic
> > image
> > Maybe we could display an ⌛️ icon in the next pool, like the ✔️ in the current one, and make it not-selectable.
> 
> Should we add something here because this was already stated on the delegation center screen where you have the sand clock icon if it's pending and you clearly see which one is currently staking, which one is pending?
> 
> @a-rukin @daniloprates @darko-mijic

we had a call with @darko-mijic and @daniloprates and realized that only last choice should block you from continuing, so there is no need in extra icon there, as we already have text and logic for this

**Comment by a-rukin** [comment]
image
here #1 is where we delegate now #2 pending delegation #3 is another pool
so we need to have here only #2 faded (like #1 on the screenshot) and that's it. No need in non-transparent checkmarks
cc @darko-mijic

**Comment by a-rukin** [comment]
image
think it would be better to get rid of extra text here 
cc @darko-mijic

**Comment by DeeJayElly** [comment]
> image
> 
> here №1 is where we delegate now №2 pending delegation №3 is another pool
> so we need to have here only №2 faded (like №1 on the screenshot) and that's it. No need in non-transparent checkmarks
> p.s. maybe also №2 should be included in the "recent" list 🤷‍♂
> cc @darko-mijic

I dont think it should be in the recent list as the delegation didn't started. It will be when the delegation starts.

I will just add transparency to pending stake pool and that's it.

**Comment by a-rukin** [comment]
> I will just add transparency to pending stake pool and that's it.

note that current pool should be available for delegating again, so only one is disabled

**Comment by tomothespian** [comment]
@DeeJayElly please add testing checklist!

**Comment by DeeJayElly** [comment]
> > I will just add transparency to pending stake pool and that's it.
> 
> note that current pool should be available for delegating again, so only one is disabled

Fixed

**Comment by DeeJayElly** [comment]
> @DeeJayElly please add testing checklist!

Added

**Comment by gnpf** [comment]
@DeeJayElly Sometimes the alignment of the text inside the bubble is off

image

**Pull request merged**
