### PR TITLE
[DDW-457] Update Webpack to version 4

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR updates the following main dependencies (and related ones) to latest versions and introduces all necessary changes to make it work:

webpack, babel (+loaders), eslint, storybook, react-intl

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei seems like we have CI build issues :(

**Comment by DominikGuzei** [comment]
@nikolaglumac yeah some issue were expected since this was the first push to PR 😉 but looks easy … im on it 👍

**Comment by DominikGuzei** [comment]
@nikolaglumac of course this also must be tested on all OSes before merging 😉 (i only tested on OSx so far)

**Comment by DominikGuzei** [comment]
@nikolaglumac opening external links is fixed! 👍

**Comment by nikolaglumac** [comment]
Works great @DominikGuzei 🎉 
Once CI is done with the builds I will ask the QA to help us test different platforms and then we are ready to merge this beauty of a PR :)

**Comment by nikolaglumac** [comment]
The BK build is failing due to a known issue: https://iohk.myjetbrains.com/youtrack/issue/devops-1180
...DEVOPS team is working on a fix.
cc @disassembler

**Comment by DmitriiGaico** [comment]
@DominikGuzei @nikolaglumac Hello! I have found that "Clear" button is not working when you are in the process of creating a Paper Wallet. You enter words no matter it is 1 or 27 Clear button is pressed but nothing happens.

**Comment by DominikGuzei** [comment]
@DmitriiGaico @nikolaglumac the clear button is fixed! 👍

**Comment by DominikGuzei** [comment]
@DmitriiGaico @nikolaglumac yeah this doesn't look correct (although this has nothing todo with this PR): 

I don't think it should be "Submit Request" here (the request just failed, obviously) … and nothing happens when you click the button … also i find it a bit weird that the dialog explains UI elements that are hidden behind it.

screenshot 2018-12-13 um 14 40 44

**Comment by nikolaglumac** [comment]
@DominikGuzei this looks wrong. There should not be "Submit request" button there but 2 buttons "Download logs " and "Submit manually" buttons instead 😱

**Comment by DmitriiGaico** [comment]
@DominikGuzei @nikolaglumac That't what i have at Windows. 
image

**Comment by DominikGuzei** [comment]
@nikolaglumac sorry that was my fault … i just changed a variable locally and of course this didn't fully change the UI 😉

**Comment by DmitriiGaico** [comment]
@DominikGuzei @nikolaglumac Build 10692. Wallet name field is broken. when you focus on this field system counts it as a Link instead of field to type in. When you press on it Daedalus goes Blank.

**Comment by nikolaglumac** [comment]
I have reproduced @DmitriiGaico's report with the wallet name input field - here's the error we are getting:
screen shot 2018-12-13 at 15 42 09

**Comment by DominikGuzei** [comment]
@nikolaglumac yeah we need to go through all `getRef` cases because they are all failing …

**Comment by DominikGuzei** [comment]
@nikolaglumac getRef stuff should be fixed now

**Comment by DominikGuzei** [comment]
@DmitriiGaico @nikolaglumac the mentioned issues should be fixed now!

**Pull request merged**
