### PR TITLE
Feature/daef 456 add acceptance tests for General Settings screens

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces acceptance tests for General Settings screens.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@nikolaglumac can i merge this?

**Comment by nikolaglumac** [comment]
@DominikGuzei please drop an eye on the changes before merging ;)

**Comment by DominikGuzei** [comment]
Reviewing this now …

**Comment by DominikGuzei** [comment]
Merging now since one travis build succeeded.

**Pull request merged**
