### PR TITLE
[DDW-757] Implement new themes

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces new 3 themes (Dark Cardano, White, Yellow).

## Todos

- [x] White  theme fine tuning
- [x] Dark Cardano  theme fine tuning

## Screenshots

_0. Settings page_

Settings page - En

Settings page - Ja

_1. Yellow theme preview_

Yellow theme preview

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@a-rukin @IuliaDolishniak please test the yellow theme 🙏

**Comment by IuliaDolishniak** [comment]
Have 2 questions that cause confusion:
1. Does the About Dialog need to be so pale in comparison with other screens?
screen
2. Does the copy notification on Daedalus Diagnostic screen color should differ from other notifications color of that kind?
screen2

**Comment by IuliaDolishniak** [comment]
The Cardano theme was translated into Japanese but on Dark Cardano theme only the work 'Dark' was translated
screen

**Comment by IuliaDolishniak** [comment]
Different color of hovered closing button on Block Consolidation and Daedalus Diagnostic screens
screen
screen2

**Comment by IuliaDolishniak** [comment]
> Different color of hovered closing button on Block Consolidation and Daedalus Diagnostic screens
> screen
> screen2

This one is not fixed

**Comment by gnpf** [comment]
@tomothespian The color of the text in the button is too light and different from the "External link" icon.

image

**Comment by gnpf** [comment]
@tomothespian The color for the selected item and the color of the dropdown itself are very similar and it's hard to determine which one is selected

image

**Comment by tomothespian** [comment]
@a-rukin @IuliaDolishniak 
All requested changes are done. 
Can you please test again?

**Comment by IuliaDolishniak** [comment]
@tomothespian please advise if this one is not going to be also yellow?
screen (7)

**Comment by nikolaglumac** [comment]
@IuliaDolishniak that’s how it should be.

**Comment by IuliaDolishniak** [comment]
screen
No change of color on hovering for both yellow and white themes

**Comment by darko-mijic** [comment]
❤️

**Pull request merged**
