### PR TITLE
[DDW-694] Improve UTXO screen

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR improves UTXO screen with styling changes such as: shrinking down the width of BarChart elements. Adding more space/padding around BarChart.

## Screenshots

- Screenshot
Screenshot 2019-06-26 15 49 11
Screenshot 2019-06-26 15 49 01

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1561557189134100)
- [ ] Test size of BarChart items
- [ ] Test padding/margin around BarChart container
- [ ] Test responsiveness and how BarChart behaves on different screen sizes

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
сan we force netlify build? @DeeJayElly

**Comment by IuliaDolishniak** [comment]
screen
Cardano theme

**Comment by DeeJayElly** [comment]
> screen
> Cardano theme
> 
> @IuliaDolishniak
> Hmm this is a good point, not part of my changes, but its another bug - color styling issue which i will fix

Fixed

**Comment by nikolaglumac** [comment]
@a-rukin please review this one 🙏

**Comment by nikolaglumac** [comment]
Reviewing this one now...

**Comment by a-rukin** [comment]
image
font of these labels should be medium instead of regular

**Comment by nikolaglumac** [comment]
@DeeJayElly unrelated to the code changes - please make sure to always use **only** lowercase letters in the branch name 🙏

**Comment by a-rukin** [comment]
image
strange bug with positioning of hover overlay

**Comment by nikolaglumac** [comment]
> strange bug with positioning of hover overlay

I couldn't reproduce this bug. @a-rukin did you test this on Netlify or in Daedalus?

**Comment by a-rukin** [comment]
> I couldn't reproduce this bug. @a-rukin did you test this on Netlify or in Daedalus?

Netlify

**Comment by nikolaglumac** [comment]
In that case I would ignore this issue as it is probably Netlify specific.
@DeeJayElly please focus only on this one: https://github.com/input-output-hk/daedalus/pull/1437#issuecomment-506287246

**Comment by DeeJayElly** [comment]
> @DeeJayElly I know this was not caused by your changes but could you please make sure the hover styles of the settings menu match the design spec?
> 
> How it is:
> screenshot_2019-06-27_at_12 54 14
> 
> How it should be:
> image
> 
> Please contact @a-rukin for support if needed.

Added

**Comment by a-rukin** [comment]
image

Still [here](https://deploy-preview-1437--daedalus-storybook.netlify.com/?selectedKind=WalletScreens&selectedStory=Wallet%20UTXO%20distribution&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by DeeJayElly** [comment]
> image
> 
> font of these labels should be medium instead of regular

done

**Comment by DeeJayElly** [comment]
> image
> 
> Still [here](https://deploy-preview-1437--daedalus-storybook.netlify.com/?selectedKind=WalletScreens&selectedStory=Wallet%20UTXO%20distribution&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

Fixed @a-rukin

**Comment by a-rukin** [comment]
image

hover color is wrong :(
it's #CECFD1 – rgb(206, 207, 209), but it should be #202225 with 7% opacity – rgba(32, 34, 37, 0.07)

**Comment by DeeJayElly** [comment]
> image
> 
> hover color is wrong :(
> it's #CECFD1 – rgb(206, 207, 209), but it should be #202225 with 7% opacity – rgba(32, 34, 37, 0.07)

@a-rukin color or background-color?

**Comment by a-rukin** [comment]
image
@DeeJayElly would this be fixed here?

**Pull request merged**
