### PR TITLE
Chore/DAEF-423 Removal of the Client API

### PR DESCRIPTION
**Pull request by darko-mijic**
**NOTE: This PR is based on #448 so please review and merge that before!**

This PR is the first step to the removal of the purescript `daedalus-client-api` and replacement with a flow-typed JS version. The `notify` websocket logic has been replaced by simple polling of `/api/settings/sync/progress` in the network store and the `makePayment` endpoint has been replaced by a POST request to `/api/txs/payments/{from}/{to}/{amount}`.

These are two important examples that highlight any interaction we need with the backend api (polling a GET endpoint and POSTing query/path params).

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@darko-mijic @nikolaglumac @tomothespian the PR is ready for review! Please take a careful look at the new way to implement the api!

**Comment by DominikGuzei** [comment]
@darko-mijic @nikolaglumac PR is ready for review again.

**Comment by darko-mijic** [comment]
This PR also fixes:
https://issues.serokell.io/issue/DAEF-460

**Comment by darko-mijic** [comment]
Something is wrong with the reviewer list. I can not add myself there. 
This is a beautiful simplification of the cumbersome logic we had with the Notify API. 
Love the new Request API! Brilliant work as always @DominikGuzei :)

**Comment by nikolaglumac** [comment]
@darko-mijic you and @DominikGuzei can not be added as reviewers since you were assigned to this task ;)

**Pull request merged**
