### PR TITLE
[DDW-504] Number format for syncing percentage and stake pools

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR fixed number format issue on syncing percentage and stake pools panels
[Jira Ticket](https://jira.iohk.io/browse/DDW-504)

## Todos
- [x] Fix number format issue on syncing percentage and stake pools panels

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611221462003100)

### App
- [x] Select wallet and watch syncing percentage notification to make sure percentage value is formatted using selected configuration settings.
- [x] Select wallet and watch blocks syncing tooltip to make sure percentage value is formatted using selected configuration settings.
- [x] Go to stake pools screen and make sure number of stake pools label is formatted using selected configuration settings.

### Test Cases 

**Scenario 1 - Validate format of Syncing blocks**
```Gherkin
Given that Daedalus is syncing
When I change the number format in settings
Then the syncing percentage of the blocks is displayed on that format
```

**Scenario 2 - Validate format of Syncing wallet**
```Gherkin
Given that a wallet is syncing 
When I change the number format in settings
Then the syncing percentage of the wallet is displayed on that format
```

**Scenario 3 - Validate format of Stake pools**
```Gherkin
Given that more than 999 stake pools are displayed on "Staking Center" 
When I change the number format in settings
Then the number of stake pools is displayed on that format
```

**Scenario 4 - Validate format of "CPU" on "Daedalus diagnostics"**
```Gherkin
Given that Daedalus is running
When I change the number format in settings
Then the value of CPU in "Daedalus diagnostics" is displayed on that format
```

**Scenario 5 - Validate format of "RAM" on "Daedalus diagnostics"**
```Gherkin
Given that Daedalus is running
When I change the number format in settings
Then the value of "RAM" in "Daedalus diagnostics" is displayed on that format
```

**Scenario 6 - Validate format of "Available disk space" on "Daedalus diagnostics"**
```Gherkin
Given that Daedalus is running
When I change the number format in settings
Then the value of "Available disk space" in "Daedalus diagnostics" is displayed on that format
```

**Scenario 7 - Validate format of "Local time difference" on "Daedalus diagnostics"**
```Gherkin
Given that Daedalus is running
When I change the number format in settings
Then the value of "Local time difference" in "Daedalus diagnostics" is displayed on that format
```

## Testing Summary

Fixed  issues:

Test case | Status | Comments
-- | -- | --
Scenario 6 | Failed | The value on "Available disk space" always displays a dot as the decimal separator. Check [this screenshot](https://drive.google.com/file/d/17h1ps0veGfBjH8g6_qk99bCDXZHVj_-5/view?usp=sharing) (Observe the rest of the values show comma, as the second format option is selected)

## Screenshots

English
image
image
image
image

Japanese
image
image
image
image

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@yakovkaravelov Cases 1 to 3 passed.

I added more cases to validate the changes suggested in [this thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611221462003100) (values on Daedalus Diagnostics).

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov Cases 1 to 3 passed.
> 
> I added more cases to validate the changes suggested in [this thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611221462003100) (values on Daedalus Diagnostics).

@gnpf @nikolaglumac This is done and ready for review/test.
Thanks.

**Comment by ManusMcCole** [comment]
Hi @yakovkaravelov. There seems to be an issue with scenario 1 and 2. The values are reversed, when I select comma a dot used, and when i select dot a comma is used. Also when a space is selected a comma is used. See <a href="https://drive.google.com/file/d/11LH3JEh0LDBqxP6FszBWr7DAtN0OPe6V/view?usp=sharing">video</a>

The same is also true for Daedalus diagnostics screen for scenario 4, 5 and 6 for Ram, CPU and Disk Space. See <a href="https://drive.google.com/file/d/1wo94mZw9IH476KgTTxMm2MX5VB0_uHKN/view?usp=sharing">video</a>

**Comment by yakovkaravelov** [comment]
> Hi @yakovkaravelov. There seems to be an issue with scenario 1 and 2. The values are reversed, when I select comma a dot used, and when i select dot a comma is used. Also when a space is selected a comma is used. See [video](https://drive.google.com/file/d/11LH3JEh0LDBqxP6FszBWr7DAtN0OPe6V/view?usp=sharing)
> 
> The same is also true for Daedalus diagnostics screen for scenario 4, 5 and 6 for Ram, CPU and Disk Space. See [video](https://drive.google.com/file/d/1wo94mZw9IH476KgTTxMm2MX5VB0_uHKN/view?usp=sharing)

@ManusMcCole No, it's totally not right. 
RAM size is 16.0GB.
So if you select first option, it should be 16.0GB
If you select second option, it should be 16,0GB
So they are working fine.

**Comment by ManusMcCole** [comment]
Sorrry @yakovkaravelov my mistake I was looking at the symbol one place to the side and was mistaken

**Comment by gnpf** [comment]
@yakovkaravelov There is an issue for one of the scenarios:

Test case | Status | Comments
-- | -- | --
Scenario 6 | Failed | The value on "Available disk space" always displays a dot as the decimal separator. Check [this screenshot](https://drive.google.com/file/d/17h1ps0veGfBjH8g6_qk99bCDXZHVj_-5/view?usp=sharing) (Observe the rest of the values show comma, as the second format option is selected)

The rest look good 👍

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov There is an issue for one of the scenarios:
> 
> Test case	Status	Comments
> Scenario 6	Failed	The value on "Available disk space" always displays a dot as the decimal separator. Check [this screenshot](https://drive.google.com/file/d/17h1ps0veGfBjH8g6_qk99bCDXZHVj_-5/view?usp=sharing) (Observe the rest of the values show comma, as the second format option is selected)
> The rest look good 👍

@gnpf Fixed now. Please test again, thanks.
@nikolaglumac This is finished, please review, thanks.

**Review by gnpf — APPROVED** [review]

**Review by nikolaglumac — APPROVED** [review]
Nice work @yakovkaravelov 🎉

**Pull request merged**
