### PR TITLE
[DEVOPS-981] Vary application icon by network

### PR DESCRIPTION
**Pull request by rvl**
This changes the Daedalus icon based on the network that the installer was built for.

@a-rukin Can you push the final artwork onto this branch? Use the established file naming scheme. See `README.md` for the command to generate the Windows icon.

## Screenshots

See _Files changed_ tab, and view icon images.

## Windows icon

Before and after for mainnet icon:

before-after

### CODE REVIEW

**Comment by a-rukin** [comment]
@rvl check pls

**Comment by rvl** [comment]
Looks good. Are you also able to generate `{mainnet,staging,testnet}/64x64.ico` for windows?

**Comment by darko-mijic** [comment]
@rvl, what is left to do here?

**Comment by rvl** [comment]
@darko-mijic It should be ready to go. I'm unable to "approve" the PR because I opened it.

**Comment by rvl** [comment]
:+1:  @cleverca22 Does the installers side look OK to you?

**Pull request merged**
