### PR TITLE
[DDW-679] Enable theme and language change in Storybook

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR makes it possible to select theme and locale in Storybook.

## Screenshots

SB-menu

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Open any storybook screen and use "Theme" and "Language" knobs to change theme/language

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by daniloprates** [comment]
I found the problem. There's a conflict when you get and set the current themes and locales from the localStorage. This is because the knobs don't have callback fn.

If you get the info from the localStorage outside `addDecorator` the flickering stops, but the state doesn't persist when you change the story.

I have tried an alternative solution, using a React component and React state:

sb

It's in another branch, `chore/ddw-679-enable-time-and-language-change-in-storybook-state`

**Comment by nikolaglumac** [comment]
@daniloprates feel free to update this PR.
Local storage usage was just a hack...

**Comment by nikolaglumac** [comment]
@daniloprates your solution is much better than mine 🎉 

However, there is one small problem - now the Daedalus screen is cut off and we get a scrollbar :(
Perhaps we can somehow fine-tune this?

issue

**Comment by daniloprates** [comment]
@nikolaglumac I've made it collapsible, so it won't push the content down.

**Pull request merged**
