### PR TITLE
[DDW-403] Log GPU-crash events

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements logging GPU-crash events.

## Todo:

- [x] Listen to the `gpu-process-crashed` main event and log it

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates wouldn’t it be better to add this gpu event handler in 
https://github.com/input-output-hk/daedalus/blob/d2a423de2908e66f88eabddb83130e43b3e91f42/source/main/utils/rendererErrorHandler.js

**Comment by daniloprates** [comment]
@nikolaglumac yes, I was wondering that. Moving it.

**Comment by daniloprates** [comment]
@nikolaglumac done. I wasn't able to reproduce this error, so not sure the best way to log it. Please, let me know if you think it should be done in a different way.

**Comment by nikolaglumac** [comment]
@daniloprates you can test it by opening developer-tools and then entering the following command in JS console: `window.location = "chrome://gpucrash"`

**Comment by nikolaglumac** [comment]
@daniloprates there are multiple debug calls we can use:
```
For Debug
The following pages are for debugging purposes only. Because they crash or hang the renderer, they're not linked directly; you can type them into the address bar if you need them.

chrome://badcastcrash/
chrome://inducebrowsercrashforrealz/
chrome://crash/
chrome://crashdump/
chrome://kill/
chrome://hang/
chrome://shorthang/
chrome://gpuclean/
chrome://gpucrash/
chrome://gpuhang/
chrome://memory-exhaust/
chrome://ppapiflashcrash/
chrome://ppapiflashhang/
chrome://quit/
chrome://restart/
```

**Pull request merged**
