### PR TITLE
[DDW-337] Handle wallet migration leftovers

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements the wallet migration leftovers handling.

## Todos

- [x] Update API
- [x] Update container/component
- [x] Create article

## Screenshots

EN

JP 

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by gnpf — APPROVED** [review]

**Review by ManusMcCole — APPROVED** [review]

**Review by mioriohk — APPROVED** [review]
Looks good to me. Tested on Shelley-QA build 14586. Great job @daniloprates 👍

**Review by nikolaglumac — APPROVED** [review]
@daniloprates great work! Please remove test/dummy data - we are ready to merge this 👍

**Comment by nikolaglumac** [comment]
@a-rukin please test this one too and make sure UI changes look good in all the themes 🙏

**Comment by nikolaglumac** [comment]
@daniloprates please run translation manager 🙏

**Comment by a-rukin** [comment]
image

Pretty sure we don't need "dot" here

**Comment by a-rukin** [comment]
image

disabled input state is broken for all themes. Referense - [here](https://zpl.io/VOA37B8)

**Comment by a-rukin** [comment]
image
for this tiny button link icon should be another (right one)

**Comment by a-rukin** [comment]
image
this is not working 🤷 it should be bold, but it's not 🤔

**Comment by daniloprates** [comment]
> image
> 
> this is not working 🤷 it should be bold, but it's not 🤔

Where is it?

**Comment by daniloprates** [comment]
> image
> 
> for this tiny button link icon should be another (right one)

This was done on React Polymorph. Pls approve this PR and will fix this in the component.

**Comment by daniloprates** [comment]
@a-rukin 

> image
> 
> disabled input state is broken for all themes. Reference - [here](https://zpl.io/VOA37B8)

✅

> image
> 
> Pretty sure we don't need "dot" here

✅

**Comment by a-rukin** [comment]
> > image
> > this is not working 🤷 it should be bold, but it's not 🤔
> 
> Where is it?

This is styles for text inside this button

**Comment by a-rukin** [comment]
@daniloprates 
image
can you pls recheck colors for dark-blue theme?

**Review by a-rukin — APPROVED** [review]
LGTM

**Pull request merged**
