### PR TITLE
[DDW-603] Enable pasting of wallet recovery phrase

### PR DESCRIPTION
**Pull request by aleksandardjordjeviciohk**
This PR enables pasting of wallet recovery phase.

This PR will utilized changes from React Polymorph Autocomplete component from here:
https://github.com/input-output-hk/react-polymorph/pull/163

## Todos

- [x] Improve logic to parse pasted strings (words)
- [x] Handle wrong words from the passphrase and break parsing of strings 
- [x] Fix js console error
- [x] Prevent dropdown opening on deletion of the word
- [x] Disable button on dialog opening with empty recovery phase
- [x] Fix opening/closing of dropdown on words copy/paste

## Screenshots

Screen Shot 2021-03-18 at 7 48 55 AM

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616074971012200)

## Test Cases

```Gherkin
Scenario 1: Copy and paste wallet passphrase
Given I am restoring a wallet
And I am at Recovery Phrase Step in (Restore wallet|Verify wallet phrase)
And I have the correct wallet passphrase
And I have copied the entire wallet passphrase
When I paste the wallet passphrase into the text area
And I select ‘Check Recovery Phrase’
Then it is successful
```

## Test Report

For build 17700

**Fixed issues**

Issues 1 to 4 were reported [here](https://github.com/input-output-hk/daedalus/pull/2459/#pullrequestreview-636374706).

1 - When deleting an already entered words by using "Backspace" key we should always hide the options dropdown in case it is shown (this is reproducible in develop too)

2 - When you enter the 2nd step of the "Wallet restoration" dialog, the button "Check recovery phrase" should be disabled by default (this is reproducible in develop too):

3 - When deleting already entered words by clicking on the "x" button we should prevent the options dropdown to show (this is reproducible in develop too)

4 - When pasting recovery phrase on the "Verification of the recovery phrase" dialog, there is a JS error thrown (this does not happen in the "Wallet restoration" dialog)

5 -  I was able to paste more than maximum words. [See screenshot](https://drive.google.com/file/d/1jYkm9D4yplqvQAX1DJq0Hh-kO4uHqU9A/view?usp=sharing)

6 -  After pasting words, dropdown didn't close automatically
[See video](https://drive.google.com/file/d/1-UrgAd6bv5iTe6C-ST6uzscCxiUaAMJZ/view?usp=sharing)

7 -  When there're extra white spaces, it seemed the remaining words were not able to be pasted
[See video](https://drive.google.com/file/d/1mvNe_Qi4ypOrZxoMQdrJJJikOV30phfU/view?usp=sharing)

8 -  Sometimes it is needed to click twice in the field to successfully paste values

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@aleksandardjordjeviciohk this is not ready yet. Please see the video of the bugs I have found:

https://user-images.githubusercontent.com/376611/112901914-ab40e700-90e5-11eb-8fa8-17cd7143b27d.mp4

These are mainly:
- Dropdown not closing after you select an option from it by clicking on it (compare to earlier version)
- When pasting values the dropdown remains open and then covers the field (should close)
- Sometimes it is needed to click twice in the field to successfully paste values

**Comment by miorsufianiohk** [comment]
Hi @aleksandardjordjeviciohk . The followings is report for build 17477

**New issues**

1. I was able to paste more than maximum words. [See screenshot](https://drive.google.com/file/d/1jYkm9D4yplqvQAX1DJq0Hh-kO4uHqU9A/view?usp=sharing)

2. When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons
[See video](https://drive.google.com/file/d/1f6AxjbPUYpfWtk8VuZ7zN2q6RuXGjqnr/view?usp=sharing)

3. After pasting words, dropdown didn't close automatically
[See video](https://drive.google.com/file/d/1-UrgAd6bv5iTe6C-ST6uzscCxiUaAMJZ/view?usp=sharing)

4. When there're extra white spaces, it seemed the remaining words were not able to be pasted
[See video](https://drive.google.com/file/d/1mvNe_Qi4ypOrZxoMQdrJJJikOV30phfU/view?usp=sharing)

**Pending issues**

1. Could replicate the issue found by @nikolaglumac :Sometimes it is needed to click twice in the field to successfully paste values

**Comment by aleksandardjordjeviciohk** [comment]
> Hi @aleksandardjordjeviciohk . The followings is report for build 17477
> 
> **New issues**
> 
> 1. I was able to paste more than maximum words. [See screenshot](https://drive.google.com/file/d/1jYkm9D4yplqvQAX1DJq0Hh-kO4uHqU9A/view?usp=sharing)
> 2. When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons
>    [See video](https://drive.google.com/file/d/1f6AxjbPUYpfWtk8VuZ7zN2q6RuXGjqnr/view?usp=sharing)
> 3. After pasting words, dropdown didn't close automatically
>    [See video](https://drive.google.com/file/d/1-UrgAd6bv5iTe6C-ST6uzscCxiUaAMJZ/view?usp=sharing)
> 4. When there're extra white spaces, it seemed the remaining words were not able to be pasted
>    [See video](https://drive.google.com/file/d/1mvNe_Qi4ypOrZxoMQdrJJJikOV30phfU/view?usp=sharing)
> 
> **Pending issues**
> 
> 1. Could replicate the issue found by @nikolaglumac :Sometimes it is needed to click twice in the field to successfully paste values

@miorsufianiohk pls retest

**Comment by gabriela-ponce** [comment]
@aleksandardjordjeviciohk I just checked the issues @nikolaglumac and @miorsufianiohk reported on build 17488.

These are **fixed**:

> - Dropdown not closing after you select an option from it by clicking on it (compare to earlier version)
> 
> - When pasting values the dropdown remains open and then covers the field (should close)
> 
> - Sometimes it is needed to click twice in the field to successfully paste values
> 
> - I was able to paste more than maximum words.
> 
> - After pasting words, dropdown didn't close automatically
> 
> - When there're extra white spaces, it seemed the remaining words were not able to be pasted

This one still reproduces. Check [video](https://drive.google.com/file/d/1Kl_bFMkgTxYaX0rE-o9ScgTHC34lu-ck/view?usp=sharing). 

> - When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons

It doesn't reproduce if you paste the word with a space after it. Could this be improved?

Also, this is a **new** potential issue.

- After pasting some phrase, the list flashes for a moment. Check [this video.](https://drive.google.com/file/d/1XK_lPzWZnd4WJsY047goW0vA_StspBpm/view?usp=sharing) Could this be improved?

**Comment by aleksandardjordjeviciohk** [comment]
> @aleksandardjordjeviciohk I just checked the issues @nikolaglumac and @miorsufianiohk reported on build 17488.
> 
> These are **fixed**:
> 
> > * Dropdown not closing after you select an option from it by clicking on it (compare to earlier version)
> > * When pasting values the dropdown remains open and then covers the field (should close)
> > * Sometimes it is needed to click twice in the field to successfully paste values
> > * I was able to paste more than maximum words.
> > * After pasting words, dropdown didn't close automatically
> > * When there're extra white spaces, it seemed the remaining words were not able to be pasted
> 
> This one still reproduces. Check [video](https://drive.google.com/file/d/1Kl_bFMkgTxYaX0rE-o9ScgTHC34lu-ck/view?usp=sharing).
> 
> > * When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons
> 
> It doesn't reproduce if you paste the word with a space after it. Could this be improved?
> 
> Also, this is a **new** potential issue.
> 
> * After pasting some phrase, the list flashes for a moment. Check [this video.](https://drive.google.com/file/d/1XK_lPzWZnd4WJsY047goW0vA_StspBpm/view?usp=sharing) Could this be improved?

@gabriela-ponce i have managed to resolve:

- When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons

**Comment by aleksandardjordjeviciohk** [comment]
> > @aleksandardjordjeviciohk I just checked the issues @nikolaglumac and @miorsufianiohk reported on build 17488.
> > These are **fixed**:
> > > * Dropdown not closing after you select an option from it by clicking on it (compare to earlier version)
> > > * When pasting values the dropdown remains open and then covers the field (should close)
> > > * Sometimes it is needed to click twice in the field to successfully paste values
> > > * I was able to paste more than maximum words.
> > > * After pasting words, dropdown didn't close automatically
> > > * When there're extra white spaces, it seemed the remaining words were not able to be pasted
> > 
> > 
> > This one still reproduces. Check [video](https://drive.google.com/file/d/1Kl_bFMkgTxYaX0rE-o9ScgTHC34lu-ck/view?usp=sharing).
> > > * When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons
> > 
> > 
> > It doesn't reproduce if you paste the word with a space after it. Could this be improved?
> > Also, this is a **new** potential issue.
> > 
> > * After pasting some phrase, the list flashes for a moment. Check [this video.](https://drive.google.com/file/d/1XK_lPzWZnd4WJsY047goW0vA_StspBpm/view?usp=sharing) Could this be improved?
> 
> @gabriela-ponce i have managed to resolve:
> 
> * When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons

@gabriela-ponce i am not sure if we could eliminate this fully, anyone has any suggestions. @DominikGuzei @daniloprates ?

"After pasting some phrase, the list flashes for a moment. Check this video. Could this be improved?"

This happens now if you are copy/pasting words very fast and sometimes there is a slight delay while showing/hiding the suggestion dropdown.

**Comment by gabriela-ponce** [comment]
@aleksandardjordjeviciohk This issue is fixed in the [React Polymorph PR](input-output-hk/react-polymorph#168), but not yet in the build 17500:
> When I pasted a single word, the word wasn’t recognised until I pressed “tab” or “space” buttons

**Review by miorsufianiohk — APPROVED** [review]
LGTM 👍 . Tested on 17523. Great work @aleksandardjordjeviciohk

**Comment by nikolaglumac** [comment]
@gabriela-ponce @DominikGuzei @aleksandardjordjeviciohk is this ready to be merged?

**Comment by gabriela-ponce** [comment]
@nikolaglumac Waiting for some fixes on the [react polymorph PR](https://github.com/input-output-hk/react-polymorph/pull/168#pullrequestreview-629254928).
However, I couldn't reproduce the issue @DominikGuzei mentioned in the latest build of this PR.

**Comment by nikolaglumac** [comment]
@gabriela-ponce @aleksandardjordjeviciohk is it ready now?

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@aleksandardjordjeviciohk great work! Your changes work great - still, I need you to focus on the following list of remaining issues (not all of them are caused by your changes - most of them are present in develop but I would like to have them fixed in this PR):

1. When deleting an already entered words by using "Backspace" key we should always hide the options dropdown in case it is shown (this is reproducible in develop too):

https://user-images.githubusercontent.com/376611/114833185-98a9fb80-9dcf-11eb-8edc-f0112a58cd24.mp4

2. When you enter the 2nd step of the "Wallet restoration" dialog, the button "Check recovery phrase" should be disabled by default (this is reproducible in develop too):



3. When deleting already entered words by clicking on the "x" button we should prevent the options dropdown to show (this is reproducible in develop too)

https://user-images.githubusercontent.com/376611/114833907-58974880-9dd0-11eb-9c9f-3c86f1bca386.mp4

4. When pasting recovery phrase on the "Verification of the recovery phrase" dialog, there is a JS error thrown (this does not happen in the "Wallet restoration" dialog):

https://user-images.githubusercontent.com/376611/114833857-4cab8680-9dd0-11eb-8609-368c32faf389.mp4



Thanks for fixing those 🙏 

cc @gabriela-ponce

**Comment by aleksandardjordjeviciohk** [comment]
> @aleksandardjordjeviciohk great work! Your changes work great - still, I need you to focus on the following list of remaining issues (not all of them are caused by your changes - most of them are present in develop but I would like to have them fixed in this PR):
> 
> 1. When deleting an already entered words by using "Backspace" key we should always hide the options dropdown in case it is shown (this is reproducible in develop too):
> 
>  1.mp4 
> 1. When you enter the 2nd step of the "Wallet restoration" dialog, the button "Check recovery phrase" should be disabled by default (this is reproducible in develop too):
> 
> 
> 
> 1. When deleting already entered words by clicking on the "x" button we should prevent the options dropdown to show (this is reproducible in develop too)
> 
>  3.mp4 
> 1. When pasting recovery phrase on the "Verification of the recovery phrase" dialog, there is a JS error thrown (this does not happen in the "Wallet restoration" dialog):
> 
>  4.mp4 
> 
> 
> Thanks for fixing those 🙏
> 
> cc @gabriela-ponce

All of the listed issues are fixed.

**Comment by gabriela-ponce** [comment]
I tested this on build 17687 and on Netlify from [this PR.](https://github.com/input-output-hk/react-polymorph/pull/168)
Regarding [this list ](https://github.com/input-output-hk/daedalus/pull/2459/#pullrequestreview-636374706)of issues:

> 1 - When deleting an already entered words by using "Backspace" key we should always hide the options dropdown in case it is shown (this is reproducible in develop too):

1 - Fixed on Netlify


> 2 - When you enter the 2nd step of the "Wallet restoration" dialog, the button "Check recovery phrase" should be disabled by default (this is reproducible in develop too):

2 - Can't test on Netlify, doesn't reproduce on build 17687


> 3 - When deleting already entered words by clicking on the "x" button we should prevent the options dropdown to show (this is reproducible in develop too)

3 - Still reproduces on Netlify and build 17687. Check Video.

>4 -  When pasting recovery phrase on the "Verification of the recovery phrase" dialog, there is a JS error thrown (this does not happen in the "Wallet restoration" dialog):

4 - Can't test on netlify, doesn't reproduce on build 17687

**Review by gabriela-ponce — APPROVED** [review]
Looks good, great job

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
Great fixes @aleksandardjordjeviciohk 🎉 
There is just one more bug left - it is specific to the "Wallet recovery phrase verification" dialog. When you type in first character in the autocomplete a JS error is thrown.
You can get it each time you delete and enter first character in the search as shown in the following video:

https://user-images.githubusercontent.com/376611/115672326-bcc78880-a34b-11eb-88f9-74799bb882cd.mp4

**Comment by aleksandardjordjeviciohk** [comment]
> Great fixes @aleksandardjordjeviciohk 🎉
> There is just one more bug left - it is specific to the "Wallet recovery phrase verification" dialog. When you type in first character in the autocomplete a JS error is thrown.
> You can get it each time you delete and enter first character in the search as shown in the following video:
> 
>  bug.mp4

There was an event error onChange() method, its fixed now with these updates -> https://github.com/input-output-hk/react-polymorph/pull/168/commits/26e5704c07b11f0603efa2b9895e5346bcd31ca2

**Review by nikolaglumac — APPROVED** [review]
Works great now! 💯

**Pull request merged**
