### PR TITLE
[DEVOPS-779] remove nix-shell.sh in favor of buildkite hooks

### PR DESCRIPTION
**Pull request by disassembler**
This PR CHANGES buildkite to no longer use nix-shell.sh.

This is accomplished by having nix-shell pre-existing in the PATH by the buildkite agent.

## Todo:

- [ ] Todo
- [ ] Todo
- [ ] Todo

## Screenshots:

- Screenshot

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by deepfire** [comment]
It's interesting, a lot has changed since the old times where `${NIX_SHELL} -p nix bash binutils coreutils curl` was a necessity..

**Comment by rvl** [comment]
@deepfire Look at [`iohk-ops/nix-darwin`](https://github.com/input-output-hk/iohk-ops/blob/master/nix-darwin/modules/buildkite-agent.nix). This defines the buildkite-agent environment in code.

**Comment by nikolaglumac** [comment]
@disassembler @deepfire @clemenshelm what is the story behind this PR? It's opened and approved but not merged?

**Comment by nikolaglumac** [comment]
@disassembler @deepfire @rvl @cleverca22 do we still need this PR? I would like to close it unmerged and delete the branch...

**Comment by disassembler** [comment]
This needs a fix to buildkite mac to fix the path which requires me to get some fixes in for nix-darwin so I can deploy the change. I'll try to get this wrapped up tomorrow.

**Comment by nikolaglumac** [comment]
@disassembler does this change have any impact on our development process now that we are using the nix-shell to run Daedalus?

**Pull request merged**
