### PR TITLE
[DEVOPS-414] Sign cardano-launcher.exe after setting manifest

### PR DESCRIPTION
**Pull request by jmitchell**
We still need to test this has the desired effect.

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @fersel

**Comment by fersel** [comment]
I tried https://ci.appveyor.com/api/buildjobs/xij3y4166bx7da0w/artifacts/installers%2Fdaedalus-win64-1.0.3447.0-installer.exe, neither installer itself nor launcher were signed.

**Comment by deepfire** [comment]
@fersel, they weren't signed, because we don't sign the PR builds.

Please, try https://ci.appveyor.com/project/jagajaga/daedalus/build/1.0.3446 instead -- it's a  branch build, which should be signed.

**Comment by fersel** [comment]
OK, both installer and launcher are signed for the provided build. Sorry for the initial mess.

**Pull request merged**
