### PR TITLE
[DDW-844] Update small 3rd party dependencies

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces 3rd party dependencies update.

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1583754751161800)
- [ ] App regresssion testing

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@yakovkaravelov @DeeJayElly @daniloprates please review this one today 🙏

**Comment by IuliaDolishniak** [comment]
screen2
dropdown sometimes is not showing when click on Receive or Transactions tab

**Comment by nikolaglumac** [comment]
@IuliaDolishniak is this present on `v2-integration` builds?

**Comment by IuliaDolishniak** [comment]
screen3
Unable to delete wallet

**Comment by nikolaglumac** [comment]
@IuliaDolishniak please check the Javascript Console and check if this issue is present in v2-integration builds.

**Comment by tomothespian** [comment]
@IuliaDolishniak compare with `v2-integration` builds and check if issues are presented only in this PR or not

**Comment by IuliaDolishniak** [comment]
> @IuliaDolishniak please check the Javascript Console and check if this issue is present in v2-integration builds.

C:\Program Files\Dae…ain\preload.js:1233 [2020-03-09T13:26:10.503Z] [daedalus.*itn_rewards_v1*:error:ipcRenderer] {
  "msg": "AdaApi::deleteWallet error",
  "data": {
    "error": {
      "code": "no_such_wallet",
      "message": "I couldn't find a wallet with the given id: abc89e851f7d7f080ce1cd8dca7589a5cbdacc73"
    }
  }
}

**Comment by nikolaglumac** [comment]
@IuliaDolishniak please try to reproduce this on a clean-state machine 🙏

**Comment by IuliaDolishniak** [comment]
Both issues cannot be reproduced in v2-integration build.

**Comment by tomothespian** [comment]
@IuliaDolishniak oke then I will check here

**Comment by tomothespian** [comment]
@IuliaDolishniak I can't reproduce issues you found. Issues are not presented here and I even can't reproduce on the latest `v2-integration` build. Can you please clean your state and try again. 
@DmitriiGaico @ManusMcCole can you also check issues Iulia reported?

**Comment by IuliaDolishniak** [comment]
> @IuliaDolishniak I can't reproduce issues you found. Issues are not presented here and I even can't reproduce on the latest `v2-integration` build. Can you please clean your state and try again.
> @DmitriiGaico @ManusMcCole can you also check issues Iulia reported?

@tomothespian I always test on a clean state. I said it doesnt exist in v2-integration. I tried on a different machine and still can reproduce the first issue with More dropdown. Trying to reproduce the second now.
proof2

**Comment by IuliaDolishniak** [comment]
> @IuliaDolishniak I want to say that behaviour is the same here as in `v2-integration` build. @ManusMcCole @DmitriiGaico please let us know if you can reproduce that.

I reproduced this issue on a clean state and different machine. Can you try same steps as on a video attached?

**Comment by tomothespian** [comment]
@IuliaDolishniak already tried and can't reproduce :(

**Comment by IuliaDolishniak** [comment]
@tomothespian please try to reproduce with Daedalus Rewards wallet

**Comment by nikolaglumac** [comment]
@IuliaDolishniak @tomothespian please get on a call and try to reproduce it together.

**Pull request merged**
