### PR TITLE
[DDW-354]: Dependency update

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR updated npm packages and eliminated security vulnerabilities.
[Jira Ticket](https://jira.iohk.io/browse/DDW-354)

## Todos
- [x] Update npm packages
- [x] Eliminate security vulnerabilities

## Description
- `babel` and `loader` packages were not updated because they are much related each other and make build errors which can't be fixed easily. They will be updated later.
- `react-intl` package was not updated because it is using the latest React features such as hooks. Because our app is not using hooks yet, this will be updated later.
- All the electron related packages were not updated because updating them requires huge refactor on build scripts. They will be updated later.
- Security vulnerabilities of packages were eliminated by resolving dependent package versions as following:
```
    "**/**/elliptic": "^6.5.3",
    "**/**/bl": "^4.0.3",
    "**/**/lodash": "^4.17.20",
    "**/**/yargs-parser": "^20.2.0",
    "**/**/braces": "^2.3.1",
    "**/**/node-fetch": "^2.6.1"
```
    This can be checked by using `yarn audit` command.

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1601283863028500)

### App
- [x] Make sure app is working properly

### Storybook
- [x] Make sure all the stories are working properly

### Test suite
The test suite executed for this PR can be found on [this link](https://docs.google.com/spreadsheets/d/1tc2XvC0naspHw7UPbuw4pOZdwclaE4l-Fz-sQLcGL9Q/edit?usp=sharing).

### Fixed
1 - Blank screen is displayed. Reported [here](https://github.com/input-output-hk/daedalus/pull/2190#issuecomment-701950733).

2 -  Wallets can't be restored or created. Reported [here](https://github.com/input-output-hk/daedalus/pull/2190#issuecomment-703544034)

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by yakovkaravelov** [comment]
@nikolaglumac @gnpf @mioriohk This is done. You can review/test.

**Comment by ManusMcCole** [comment]
Hi @yakovkaravelov. I am seeing an error where the whole screen of Daedalus is completley white. The error in the console is attatched. 
image

**Comment by nikolaglumac** [comment]
@yakovkaravelov can we do something about this warning?

```
$ yarn audit
warning Resolution field "unicode-properties@1.1.0" is incompatible with requested version "unicode-properties@^1.2.2"
```

**Comment by yakovkaravelov** [comment]
@nikolaglumac  @gnpf @ManusMcCole @mioriohk This is finished. You can review/test.

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov can we do something about this warning?
> 
> ```
> $ yarn audit
> warning Resolution field "unicode-properties@1.1.0" is incompatible with requested version "unicode-properties@^1.2.2"
> ```

@nikolaglumac This can't be eliminated for now.
If I fix that warning, app doesn't start.

**Comment by ManusMcCole** [comment]
Hi @yakovkaravelov. I am having an error trying to verify mnemonics. No valid mnemonics will be accepted for any wallet. Here is the <a href="https://drive.google.com/file/d/1nyXmd8TM-J6ZGrKjbH7WQbyMIKVHnhHi/view?usp=sharing"> console error</a>

**Comment by gnpf** [comment]
@yakovkaravelov On the stake pools view, the saturation is not displayed. This was modified on #2187.  Is it expected to display the same information here?

I updated the summary and the testing sheet for this PR.

**Comment by yakovkaravelov** [comment]
@ManusMcCole @gnpf Fixed them, please test again. Thanks.

**Comment by gnpf** [comment]
@yakovkaravelov A quick summary for 14630:

**Fixed:**
 - Can't restore or create any type of wallet. Reported [here](https://github.com/input-output-hk/daedalus/pull/2190#issuecomment-703544034).

**Reincident:**
- I still can't see the saturation on the stake pools. [Here's a new screenshot.](https://drive.google.com/file/d/1HkSkWUFLm-2HXX9mpSCZAas5pvXapb6I/view?usp=sharing)

**Comment by nikolaglumac** [comment]
@gnpf saturation has been disabled and is not supposed to be displayed. Please compare to develop builds...

**Comment by ManusMcCole** [comment]
Hi @Yakov. 

Fixed:
Can't restore or create any type of wallet. Reported here.
 
New:
I have found an issue on Linux where when I go to support and click on download logs Daedalus closes never to reopen and logs are not downloaded. See <a href="https://drive.google.com/file/d/1Fydzf_h7x3JcLmE4cwdeBmqW6SX8okLj/view?usp=sharing">Video</a>

**Comment by nikolaglumac** [comment]
> Hi @yakovkaravelov
> 
> Fixed:
> Can't restore or create any type of wallet. Reported here.
> 
> New:
> I have found an issue on Linux where when I go to support and click on download logs Daedalus closes never to reopen and logs are not downloaded. See [Video](https://drive.google.com/file/d/1Fydzf_h7x3JcLmE4cwdeBmqW6SX8okLj/view?usp=sharing). See Logs Attatched
> 
> [Logs (1).zip](https://github.com/input-output-hk/daedalus/files/5339672/Logs.1.zip)

@ManusMcCole this is a known issue if I am not mistaking - @alan-mcnicholas can confirm.

**Comment by alan-mcnicholas** [comment]
> > Hi @yakovkaravelov
> > Fixed:
> > Can't restore or create any type of wallet. Reported here.
> > New:
> > I have found an issue on Linux where when I go to support and click on download logs Daedalus closes never to reopen and logs are not downloaded. See [Video](https://drive.google.com/file/d/1Fydzf_h7x3JcLmE4cwdeBmqW6SX8okLj/view?usp=sharing). See Logs Attatched
> > [Logs (1).zip](https://github.com/input-output-hk/daedalus/files/5339672/Logs.1.zip)
> 
> @ManusMcCole this is a known issue if I am not mistaking - @alan-mcnicholas can confirm.

Yes that is correct, this is seen on Ubuntu 18.04 and older distros and is a known issue.

**Comment by nikolaglumac** [comment]
@ManusMcCole @gnpf @mioriohk can we please get this one done today?

**Review by gnpf — APPROVED** [review]
Good job 🎉 

Test suite can be found [here](https://docs.google.com/spreadsheets/d/1tc2XvC0naspHw7UPbuw4pOZdwclaE4l-Fz-sQLcGL9Q/edit#gid=0).

**Review by mioriohk — APPROVED** [review]
Tested on build 14630. Looks good to me. Well done @yakovkaravelov 👍

**Review by ManusMcCole — APPROVED** [review]

**Pull request merged**
