### PR TITLE
Fix/ddw 109 fix minor styling issues for release 0.9.0

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes all remaining styling issues and updates to latest react-polymorph version.
The theming configurations is now used as intended and there should be no problems with double-inclusion of css styles anymore.

screenshot 2018-02-16 um 12 46 12

screenshot 2018-02-16 um 12 46 19

# Updates to `react-polymorph@0.6.4`

### Fixes

- Add `border-radius` CSS property to Autocomplete component [PR 45](https://github.com/input-output-hk/react-polymorph/pull/45)

### Fixes

- Fix Options component window resize event handling, Add `border-radius` CSS property to Textarea component [PR 44](https://github.com/input-output-hk/react-polymorph/pull/44)

### Fixes

- Fixes dependencies to be React 16 compatible [PR 41](https://github.com/input-output-hk/react-polymorph/pull/41)
- Fixes broken options positioning logic that was accidentially removed when bubble was introduced 
  [PR 42](https://github.com/input-output-hk/react-polymorph/pull/42)

### Features

- Add Radio component [PR 34](https://github.com/input-output-hk/react-polymorph/pull/34)

### Fixes

- Fix broken theming setup for `InputSkin`, `BubbleSkin` and `SelectSkin` [PR 36](https://github.com/input-output-hk/react-polymorph/pull/36)

### Features

- Add Bubble component [PR 31](https://github.com/input-output-hk/react-polymorph/pull/31)
- Use Bubble component in Options component [PR 31](https://github.com/input-output-hk/react-polymorph/pull/31)
- Add Tooltip component [PR 32](https://github.com/input-output-hk/react-polymorph/pull/32)

### Fixes

- Fix bug causing crash when hitting backspace in an Autocomplete component [PR 31](https://github.com/input-output-hk/react-polymorph/pull/31)

### CODE REVIEW

**Comment by darko-mijic** [comment]
Changelog entry is missing @DominikGuzei. 😱

**Comment by DominikGuzei** [comment]
@darko-mijic changelog entry added!

**Comment by nikolaglumac** [comment]
@DominikGuzei there is just one more defect - on the dark theme active input border color is to bright.
This is how it should look like: https://zpl.io/VO0W9gP

**Comment by nikolaglumac** [comment]
We also forgot to run `npm run build-dll` :(
Will fix that today!

**Comment by nikolaglumac** [comment]
Input border issues fixed.
DLL package freshly built.
I only need to fix one ReactPolymorph JS error and then we are done 🎉

**Pull request merged**
