### PR TITLE
Release/0.9.1

### PR DESCRIPTION
**Pull request by darko-mijic**
### Bug fixes and improvements

- A presentation bug has been fixed that caused only five recent transactions to be shown on the transaction list, even though there were more than five transactions in the wallet. ([PR 778](https://github.com/input-output-hk/daedalus/pull/778))

- An issue has been fixed that stopped copy and paste operations from working when initiated using the right-click context menu. ([PR 817](https://github.com/input-output-hk/daedalus/pull/817))

- A "Couldn't pack log files” error that masked the real reason for the Cardano node crashing has been fixed.

- On Windows, the desktop icon was not showing the Daedalus image; this has now been fixed. ([PR 837](https://github.com/input-output-hk/daedalus/pull/837))

- An error has been fixed that in some cases prevented users creating a wallet with a name containing non-latin characters, like Japanese Kanji or Chinese. ([PR 840](https://github.com/input-output-hk/daedalus/pull/840))

### Features

- New Edit section in system menu with copy & paste and related actions ([PR 817](https://github.com/input-output-hk/daedalus/pull/817))

### CODE REVIEW

**Comment by Cyfirr** [comment]
@nikolaglumac @darko-mijic my question regarding the unit testing the change is still unanswered and therefore this PR is hanging in the air...
Can you please respond / take action if it is possible to unit test?

**Comment by nikolaglumac** [comment]
@Cyfirr we don't have a unit nor acceptance test for this change. We will add it in the future for sure.
Still, we have manually tested the fix and confirmed that it works as expected...
This PR is tagged with `DO NOT MERGE` tag and it should stay that way until next release is out.

**Comment by jmitchell** [comment]
Provisional mainnet installers have been built using the CI output of the previous rev (cd19ef984bce3ff27fd08e792d09c1ecd262716e).

*Any additional changes that need to be added to this PR must be raised internally!*

**Comment by nikolaglumac** [comment]
@jmitchell we will not be anything more to this PR. It will be merged once release is out. I expect this will happen tomorrow during the day...

**Pull request merged**
