### PR TITLE
[DDW-642] Update to latest react-polymorph

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR updates to latest `react-polymorph@0.8.6` version.

---

## Testing Checklist

- Potentially any feature with react-polymorph components could be broken (theoretically), so i guess the whole app must be tested to be sure that everything really works.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by DmitriiGaico** [comment]
Staring review.

**Comment by IuliaDolishniak** [comment]
@MarcusHurney after discussion with @nikolaglumac it was agreed to reset the scroll position of the select dropdown on open.
screen

**Comment by MarcusHurney** [comment]
@nikolaglumac @IuliaDolishniak 
I still haven't added the the reset scroll position for the `Options` component, but that would involve another patch in `react-polymorph`. Do we want to include that patch in this PR, or do it separately?

**Comment by IuliaDolishniak** [comment]
Hi @MarcusHurney can you please make dropdown scrolls up after selection, e.g. if we selected option in the middle, like here
screen
it scrolls up so it shows the selection option down, It was agreed with @nikolaglumac 
screen2

**Comment by nikolaglumac** [comment]
@MarcusHurney please add a patch for that in the current PR - I feel like it belongs here.

**Comment by IuliaDolishniak** [comment]
@MarcusHurney on Ada Redemption >>> Paper vended tab dropdown is not fully shown
screen

**Comment by IuliaDolishniak** [comment]
@MarcusHurney still can reproduce the dropdown issue
screen (7)

**Comment by nikolaglumac** [comment]
The issue @IuliaDolishniak discovered is to be resolved within: https://iohk.myjetbrains.com/youtrack/issue/DDW-690

**Pull request merged**
