### PR TITLE
[DDW-1184] Implement stake pool saturation and desirability attributes

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR adds stake pool saturation info on the "Stake pools" screen and within the stake pool tooltip.

## Todos

- [x] Add saturation info to stake pool tiles on the "Stake pools" screen
- [x] Add saturation info to stake pool tooltip
- [x] Bump cardano-wallet version

## Screenshots

Screenshot 2020-01-21 at 15 18 32
Screenshot 2020-01-21 at 15 18 38

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Check the display of stake pools saturation on "Staking pools" screen (both on stake pool cards/tiles and within the tooltip)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by daniloprates** [comment]
> Got NaN when running with the generated wallets.

After rebuilding it, the error's gone

**Comment by nikolaglumac** [comment]
@daniloprates I added a fallback to zero: https://github.com/input-output-hk/daedalus/pull/1826/commits/451633c4d40c1a032073250c1d988e64492fef41

**Comment by tomothespian** [comment]
@nikolaglumac I don't see that stake pools are ranked / ordered by their desirability. Did I miss something?

**Comment by nikolaglumac** [comment]
> @nikolaglumac "Saturation" is visible in the delegation wizard while the stake pool is selected. Can you please take a look
> Screen Shot 2020-01-21 at 15 46 32

Will check @tomothespian

**Comment by nikolaglumac** [comment]
> @nikolaglumac I don't see that stake pools are ranked / ordered by their desirability. Did I miss something?

Sorting is applied on the Api level @tomothespian

**Comment by tomothespian** [comment]
> > @nikolaglumac I don't see that stake pools are ranked / ordered by their desirability. Did I miss something?
> 
> Sorting is applied on the Api level @tomothespian

Aha aha ok @nikolaglumac 
Then just "Saturation" while stake pool is selected. Rest is amazing 🚀

**Comment by nikolaglumac** [comment]
> @nikolaglumac "Saturation" is visible in the delegation wizard while the stake pool is selected. Can you please take a look
> Screen Shot 2020-01-21 at 15 46 32

@tomothespian fixed:

Screenshot 2020-01-21 at 17 26 36

**Pull request merged**
