### PR TITLE
[DDW-927] Implement Custom Scrollbars for Each Daedalus Theme

### PR DESCRIPTION
**Pull request by MarcusHurney**
This PR integrates the new react-polymorph `ScrollBar` component into Daedalus and also adds the corresponding CSS variables for every theme. Bumps the version of react-polymorph to the latest version to include new `ScrollBar` component.

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585778417257000)
---

### Basics

- [x] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn flow:test`)
- [x] There are no *lint* errors or warnings (`yarn lint`)
- [x] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [x] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [x] Japanese text changes are proofread and approved (Junko Oda)
- [x] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by MarcusHurney** [comment]
@DominikGuzei Hey man I'm integrating react-polymorph `v0.9.2-rc.2` into Daedalus for the purpose of themeing the scrollbars. Unfortunately, none of the `Options` are rendering. Can you give me your take on this? I can't figure it out at the moment.

Screen Shot 2020-02-11 at 3 44 52 PM

Screen Shot 2020-02-11 at 3 45 16 PM

**Comment by DominikGuzei** [comment]
@MarcusHurney you just forgot to include the scrollbar component styles in Daedalus, issue is fixed 👍

**Comment by gnpf** [comment]
@MarcusHurney The hovered scrollbar on "Dark blue" is not visible:

A9awZTii9K

**Comment by gnpf** [comment]
@MarcusHurney The opacity of the scrollbar is too low for most themes (Not reproducible on _Yellow_ and _White_)

image

**Comment by a-rukin** [comment]
> @MarcusHurney The opacity of the scrollbar is too low for most themes (Not reproducible on _Yellow_ and _White_)
> 
> image

it seems for me that there is a wrong color applied. The one we use for normal (dark on light) parts. For inverted overlays, we use another color. It's quite simple -> color of the scrollbar is the color of a text.

**Comment by MarcusHurney** [comment]
@nikolaglumac @a-rukin @daniloprates 
This is ready to be reviewed again.

**Comment by nikolaglumac** [comment]
@gnpf @DmitriiGaico please test this one again 🙏

**Comment by nikolaglumac** [comment]
@a-rukin please check this one again too 🙏

**Comment by a-rukin** [comment]
for the dark blue theme hover state is strange (in netlify) 

image

here one of the scrollbars is hovered

**Comment by nikolaglumac** [comment]
@a-rukin I can also see that the Share icon is cut-off on the bottom edge on your screenshot?

**Comment by a-rukin** [comment]
> @a-rukin I can also see that the Share icon is cut-off on the bottom edge on your screenshot?

eye of an eagle 👀

**Comment by a-rukin** [comment]
image
this is true for non-used

**Comment by a-rukin** [comment]
also I remember that we have issue in netlify only with right padding (where scroll bar lives) 
p.s. trying to build and test in app

**Comment by a-rukin** [comment]
Oh.. I see that scroll is 6px width with 7px paddings left and right
It should be 4px with 8px paddings :(

**Comment by a-rukin** [comment]
image
we have some extra right padding here

**Comment by a-rukin** [comment]
image
was it here before? never noticed that we are cropping it with some padding 🤔

**Comment by a-rukin** [comment]
image
something went wrong 😮

**Comment by a-rukin** [comment]
image
with minimum height (at least smaller than scrollable content here) we are missing bottom padding

**Comment by a-rukin** [comment]
image
PR with switches is not merged here right?

**Comment by nikolaglumac** [comment]
@MarcusHurney please merge latest v2-integration 🙏

**Comment by nikolaglumac** [comment]
I sorted the merge https://github.com/input-output-hk/daedalus/pull/1827/commits/d46df3d3e087d746d3dc08fb22c00944b16c2fe0

**Comment by nikolaglumac** [comment]
@MarcusHurney any update on this one?

**Comment by nikolaglumac** [comment]
@MarcusHurney do you have an ETA of when this one could be done?

**Comment by MarcusHurney** [comment]
@nikolaglumac 
I went through and resolved all merge conflicts so that this is up to date with the latest `v2-integration` branch. I think I do need help on finishing off the remaining fixes that are still lingering here. There is a lot for me to get done on the `MnemonicEntry` component in react-polymorph. Do we have the bandwidth for someone to step in and see if they can finish off the remaining stylistic issues Sasha found here?

**Comment by nikolaglumac** [comment]
OK @MarcusHurney - I will reassign this task so you can focus on mnemonic entry one. Thanks!

**Comment by a-rukin** [comment]
image
width is still 6px

in design it's 4px

**Comment by a-rukin** [comment]
image

for the yellow theme it’s light not #2D2D2D

image

for the wallet list it’s still 6px

**Comment by DeeJayElly** [comment]
> image
> 
> for the yellow theme it’s light not #2D2D2D
> 
> image
> 
> for the wallet list it’s still 6px

Fixed

**Comment by a-rukin** [comment]
image

for cardano theme you also changed white to gray for wallet list, pls return white back)
opacities change is good

**Comment by DmitriiGaico** [comment]
Hardly visible Scroll Bar + Wallet renaming issues looks to be fixed at Windows. QA Continue General Testing.

**Comment by DmitriiGaico** [comment]
Can we fix this in framework of current PR ? @DeeJayElly @nikolaglumac 
image

**Comment by nikolaglumac** [comment]
Yes please @DeeJayElly 🙏

**Comment by DeeJayElly** [comment]
> image
> 
> for cardano theme you also changed white to gray for wallet list, pls return white back)
> opacities change is good
> for the splash screen it should be white too (now it's not)

Fixed

**Comment by DeeJayElly** [comment]
> Can we fix this in framework of current PR ? @DeeJayElly @nikolaglumac
> image
> 
> image

Can you try it now @DmitriiGaico

**Comment by DmitriiGaico** [comment]
@DeeJayElly Hey! Unfortunately still reproducible.
OverLap

**Comment by a-rukin** [comment]
> @DeeJayElly Hey! Unfortunately still reproducible.
> OverLap

I'm more confused that these rows are not in one line -_-

**Comment by gnpf** [comment]
@DeeJayElly @nikolaglumac This little issue with the _external icon_ on a different line was fixed before, but it is reproducible now.

CC: @DmitriiGaico 

image

**Comment by a-rukin** [comment]
> @DeeJayElly @nikolaglumac This little issue with the _external icon_ on a different line was fixed before, but it is reproducible now.
> 
> CC: @DmitriiGaico
> 
> image

@gnpf was it bigger before? NMow it's aligned to the base line, so I don't see issue here. It would be the same in eng locale too if it will go after CAPS

**Comment by DmitriiGaico** [comment]
@a-rukin The question is about icon positioning. In FC the icon is moved to the next row in Minimal Window Size.

**Comment by a-rukin** [comment]
> @a-rukin The question is about icon positioning. In FC the icon is moved to the next row in Minimum Window Size.

ye ye, i'm blind noticed this after comment

**Pull request merged**
