### PR TITLE
[DDW-1039] Add the `marlowe_pioneers` installers

### PR DESCRIPTION
**Pull request by michalrus**
This PR adds installers for the `marlowe_pioneers` network.

Related: https://github.com/input-output-hk/iohk-nix/pull/508

Related: https://github.com/input-output-hk/marlowe-cardano/pull/137

Implements: DDW-1039, DDW-1085

## Todos

- [ ] Windows build of `marlowe-cli` + `“Open a Marlowe terminal”` on Windows
- [ ] Japanese translation of `“Open a Marlowe terminal”` in the main Daedalus menu

## New QA scenario

As in the screenshots below, you need to:
1. Open Daedalus (the Marlowe Pioneers variant).
2. Click on the main “Daedalus” menu.
3. Click on “Open a Marlowe terminal”.
4. A *new* terminal window is opened in the foreground — in both cases:
    a. either if there already was a terminal app running
    b. or with no previous terminal process
5. In the terminal, run `marlowe-cli util slotting`.
6. Verify if you get a sensible JSON back (instead of an error):
    ```json
    {
        "scSlotLength": 1000,
        "scSlotZeroTime": 1649949631000
    }
    ```
7. You should be able to also run (without errors):
    * `jq --version`
    * `cardano-cli --version`
    * `cardano-wallet version`
    * `cardano-address --version`
    * `basenc --version`
    * `sed --version` — it should say **GNU** sed

## Screenshots

Screenshot_macos11_2022-05-11_16:38:59

Screenshot_ubuntu20 04_2022-05-11_16:43:00

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1649245987466519)
- [ ] Test

---

### Basics

- [x] PR assigned to the PR author(s)
- [x] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [x] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [x] PR link is added to a Jira ticket, ticket moved to In Review
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes
- [x] PR contains screenshots (in case of UI changes)
- [x] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by michalrus** [comment]
@bwbush confirms it’s working fine → https://input-output-rnd.slack.com/archives/C038C07ADTL/p1649362372715239?thread_ts=1649328622.195919&cid=C038C07ADTL

**Comment by miorsufianiohk** [comment]
Hi @michalrus 

For build 21733, on both Linux and Mac, the option to "Open a Marlowe terminal" existed, however it was missing on Windows. I am aware that this is currently being discussed on Slack but I am filing this report as a formality so that we could keep track of issues on here. Thanks.

**Comment by miorsufianiohk** [comment]
Hi @michalrus ,

Just for reference. On build 21738, on Mac, after running this command:
```
jq --version
cardano-cli --version
cardano-wallet version
cardano-address --version
basenc --version
```

The response was:
```
zsh: command not found: jq
cardano-cli 1.34.1 - darwin-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23
v2022-04-27 (git revision: 3ee8ca721f3704b34e29194ae25c6cbcb50ff506)
3.9.0 @ 8bf98905b903455196495e231b23613ad2264cb0
zsh: command not found: basenc
```

As discussed on Slack, I am aware that you will be working on Mac to rectify this issue. 
No problem with Linux.

**Comment by michalrus** [comment]
@miorsufianiohk yes, thank you! I will work on macOS `jq` etc. tomorrow =)

**Comment by michalrus** [comment]
@miorsufianiohk it should be good now. =)

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Tested on build 21765 across all 3 platforms. Great job @michalrus 👍

**Comment by michalrus** [comment]
Closing as no longer needed, we can reopen on new updates of Marlowe

**Pull request closed without merging**
