### PR TITLE
[DEVOPS-1086] fault injection acceptance tests

### PR DESCRIPTION
**Pull request by deepfire**
This adds extends the acceptance test suite with scenarios covering cardano misbehaviors based on fault injection:
1. `cardano-node` failing to exit when receiving an EOF on the IPC fd.
2. ... failing to exit when an update was requested.
3. ... exiting with a wrong exit code when an update was requested.
4. ... ignoring API endpoints.

TODO:

- [ ] fix the fact that sometimes (50/50) `When I inject fault named "FInjApplyUpdateWrongExitCode"` doesn't result in the IPC message being sent -- this can be observed in the cardano logs, through absence of `[cardano-sl.*production*:Warning:ThreadId 84] [2018-10-25 15:54:56.89 UTC] *** EXPECT MISCHIEF -- ENABLING INJECTION OF FAULT FInjApplyUpdateWrongExitCode`.  Note that this PR also bumps CSL so the messages are actually emitted.
- [ ] come up with a better test scenario for the entire-API-being-ignored situation
- [ ] the `Closing the main window, while cardano ignores exit request` scenario appears to expose a bug(?):
```
1) Scenario: Closing the main window, while cardano ignores exit request # features/quit-app.feature:15
   ✔ Before # features/support/electron.js:47
   ✔ Before # features/support/i18n.js:4
   ✔ Before # features/support/webdriver.js:4
   ✔ Given Daedalus is running # features/step_definitions/app-steps.js:9
   ✔ And cardano-node is running # features/step_definitions/cardano-steps.js:7
   ✔ When I inject fault named "FInjIgnoreShutdown" # features/step_definitions/helper-steps.js:19
   ✔ When I close the main window # features/step_definitions/app-steps.js:17
   ✖ Then cardano-node process is not running # features/step_definitions/cardano-steps.js:13
       Error: function timed out after 61000 milliseconds
           at Timeout._onTimeout (/home/deepfire/daedalus/node_modules/cucumber/src/user_code_runner.js:61:18)
           at ontimeout (timers.js:475:11)
           at tryOnTimeout (timers.js:310:5)
           at Timer.listOnTimeout (timers.js:270:5)
```
..and the node is happily running indeed, while at the same time Daedalus appears to be confused, thinking that it has exited (`process really exited with...`):
```
[2018-10-25T16:47:32.0877Z] [info] [main] CardanoNode: says it exited with [1, null]
[2018-10-25T16:47:32.0944Z] [debug] [main] CardanoNode: No previous cardano-node process is running anymore.
[2018-10-25T16:47:32.0944Z] [info] [main] CardanoNode: process really exited with [1, null]}
[2018-10-25T16:47:32.0944Z] [info] [main] CardanoNode: transitions to <crashed>
[2018-10-25T16:47:32.0945Z] [info] [main] CardanoNode crashed with code 1. Restarting in 30000ms …
[2018-10-25T16:47:34.0455Z] [info] [renderer] NetworkStatusStore: requesting node state.
[2018-10-25T16:47:34.0455Z] [info] [main] ipcMain: Received request from renderer for node state.
[2018-10-25T16:47:34.0520Z] [info] [renderer] NetworkStatusStore: handling cardano-node state <crashed>
[2018-10-25T16:47:34.0903Z] [info] [main] Daedalus:before-quit: stopping cardano-node with PID 16000
[2018-10-25T16:47:34.0990Z] [debug] [main] CardanoNode: No previous cardano-node process is running anymore.
[2018-10-25T16:47:34.0990Z] [info] [main] CardanoNode#stop: process is not running anymore.
[2018-10-25T16:47:34.0990Z] [info] [main] Daedalus:before-quit: exiting Daedalus with code 0.
```

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Im reviewing your changes now! Will also refactor your code a bit and try to fix some of the todos

**Comment by DominikGuzei** [comment]
@deepfire for me injecting the faults doesn't work … only `FInjIgnoreShutdown` "works" (at least it doesn't give an error) but it's not included in the returned array of "injected faults" by cardano … which our logic is based on. So basically none of the fault injections works atm :(

**Comment by nikolaglumac** [comment]
@deepfire what is the relation between this PR and the following one: https://github.com/input-output-hk/daedalus/pull/1125

**Comment by deepfire** [comment]
@nikolaglumac, closed #1125, it was using an old branch.

**Comment by DominikGuzei** [comment]
Closing this in favor of the rebase to develop in #1154

**Pull request closed without merging**
