### PR TITLE
[DDW-313] Cleanup IPC API

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR refactors the old ipc channels setup (untyped, using constants and electron ipc directly) to the better flow-typed, promise based version that abstracts the underlying electron ipc implementation and covers all required scenarios.

## How to Test
Since this is a code refactoring nothing should have changed in functionality.

**The following features could be affected by the changes and should be tested:**

- Any interaction with cardano-node (correct behavior, states etc.)
- Downloading logs
- Generating Paper wallets
- Parsing redemption code from PDF (Ada redemption page)
- Toggling dialogs & special screens (anything triggered form the system menu)
- Opening external URLs (links)

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@daniloprates can you take a look and resolve them if it's not too much? im off today … so it would be faster 😉 if not i can fix that tomorrow.

**Comment by daniloprates** [comment]
> @daniloprates can you take a look and resolve them if it's not too much? im off today … so it would be faster 😉 if not i can fix that tomorrow.

@DominikGuzei bit of guessing, when you have time, [please check](https://github.com/input-output-hk/daedalus/pull/1332/commits/3160088b8da922b2a5aa07d112aaa4757de439e5) if it's all correct.

**Comment by DominikGuzei** [comment]
Looks good @daniloprates

**Comment by nikolaglumac** [comment]
@daniloprates perhaps you can start reviewing this one. I will send the installers to @DmitriiGaico and @IuliaDolishniak once they are ready.

**Comment by nikolaglumac** [comment]
@IuliaDolishniak @DmitriiGaico please approve this PR once you are done with testing. That's the last thing we need to merge this PR 🙏

**Pull request merged**
