### PR TITLE
[DDW-581] Replace ada symbol images with unicode character

### PR DESCRIPTION
**Pull request by daniloprates**
This PR replaces ada symbol images with unicode character.

### SVG
svg

### UTF
image

### SVG
loading svg

### UTF - Light
loading utf

### UTF - Thin
image

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates we need @a-rukin to approve this! Please align with him and perhaps do a live demo call 🙏

**Comment by a-rukin** [comment]
I'd suggest using ADA as a unicode symbol only in the smallest pending/outgoing transactions with a space (' ') before. Rest look too different from an original ADA symbol. Sorry 😢

**Comment by daniloprates** [comment]
svg
loading svg
@a-rukin ?

**Comment by nikolaglumac** [comment]
What about transactions and the send screen (including transaction confirmation dialog)? There we use ‘ada’ word - wouldn’t it be better to use ada symbol instead?

cc @darko-mijic

**Comment by a-rukin** [comment]
Examples would help understanding if it works

**Comment by a-rukin** [comment]
image
woah @daniloprates looks the same as svg one, think it work for the small ones

**Comment by daniloprates** [comment]
@a-rukin @nikolaglumac @darko-mijic  I like it

image
image

**Comment by a-rukin** [comment]
Looks good 👍

**Comment by nikolaglumac** [comment]
What about transactions tab?

**Comment by daniloprates** [comment]
This is the only one @a-rukin had agreed in changing. The big symbol in the Summary tab and the one in the Loading screens remain SVG.
image

**Comment by daniloprates** [comment]
@nikolaglumac 
image

**Comment by daniloprates** [comment]
To summarize... ⌛️

**Comment by daniloprates** [comment]
@a-rukin which one?

which

**Comment by nikolaglumac** [comment]
@darko-mijic what do you say: https://github.com/input-output-hk/daedalus/pull/1317#issuecomment-467525725

**Comment by DominikGuzei** [comment]
Looks great, except for the unicode symbol after the transaction amount … i think that's too thick and probably would be better as `--font-light` (but the amount itself should stay `--font-medium`)

**Comment by nikolaglumac** [comment]
@daniloprates @DominikGuzei @a-rukin I have replaced "ADA" text with this new UTF symbol in few places:
ada

**Comment by a-rukin** [comment]
Left menu is ok, but those in a middle looks awkward

**Comment by nikolaglumac** [comment]
@a-rukin fixed: 
screen shot 2019-02-27 at 12 44 42

**Comment by nikolaglumac** [comment]
@DominikGuzei fixed:
screen shot 2019-02-27 at 12 56 05

**Pull request merged**
