### PR TITLE
[DDW-523] Ada Redemption page reloading issues

### PR DESCRIPTION
**Pull request by daniloprates**
This PR fixes issues when reloading the app in the Ada Redemption page.

- [x] Remove the "Ada redemption is not available because you don't have any wallets." message
- [x] Hide the wallets menu

## Screenshots:

image

image

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates there are some lint and flow issues:
screen shot 2018-12-12 at 12 41 45
screen shot 2018-12-12 at 12 41 53

...and the logic is broken now - when you try to navigate to Ada redemption page (given that you don't have any wallets at that time) it will fail to open the Ada redemption page :(
error

I think you took the wrong approach here.
Ada redemption page should be re-added to the `isPageThatDoesntNeedWallets` list and you should add the isLoadingWallets to this page so that when you refresh it we first wait for the wallets to load and only once this is done we either:
A) show "you have no wallets" content or
B) show the Ada redemption form if user has wallets

What do you think?

**Comment by daniloprates** [comment]
@nikolaglumac makes sense!

**Comment by nikolaglumac** [comment]
@daniloprates I added some more changes: https://github.com/input-output-hk/daedalus/pull/1217/commits/235bab47ada32ab54b27980f62a8cc58b327d327
Please re-test to confirm that it works as you would expect...

**Comment by daniloprates** [comment]
@nikolaglumac works great.

**Comment by nikolaglumac** [comment]
The BK build is failing due to a known issue: https://iohk.myjetbrains.com/youtrack/issue/devops-1180
...DEVOPS team is working on a fix.

**Pull request merged**
