### PR TITLE
[DDW-83] Update about screen

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR updated about screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-83)

## Todos
- [x] Update build info section of about screen

### Mainnet
image

### ITN
image

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585563043076300)
- [x] Start app using `yarn nix:mainnet` and `yarn dev`, and then make sure that about screen is showing proper build info text on header section
- [x] Start app using `yarn nix:itn_selfnode` and `yarn dev`, and then make sure that about screen is showing proper build info text on header section
- [x] Go to `About` component of storybook and make sure that about screen is showing proper build info text on header section

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by DmitriiGaico** [comment]
@yakovkaravelov Hey, do we Keep "Node \ Wallet" not translated?

image

**Comment by nikolaglumac** [comment]
Yes @DmitriiGaico

**Comment by ManusMcCole** [comment]
Storybook is failing to render properly. I cannot navigate through pages and this error below is shown 
image

**Comment by DmitriiGaico** [comment]
@nikolaglumac We might have a general issue with StoryBook as it just not working. Do you want us to test About screen In-App only and Create a separate task to Check/Fix Netlify?

**Comment by nikolaglumac** [comment]
@ManusMcCole @DmitriiGaico @yakovkaravelov storybook is now fixed in this PR - it will be fixed in develop as soon as this PR is merged...

**Pull request merged**
