### PR TITLE
appveyor: use CARDANO_SL_BRANCH to set backend branch

### PR DESCRIPTION
**Pull request by domenkozar**
Let's wait for CI to confirm it works.

### CODE REVIEW

**Comment by georgeee** [comment]
Where this `CARDANO_SL_BRANCH` would be taken from?

**Comment by georgeee** [comment]
Ah, ok, I see. Sorry for stupid question

**Comment by domenkozar** [comment]
Well it still fails to concatenate strings correctly.. I'll use the old way for now.

**Comment by domenkozar** [comment]
@darko-mijic windows installer should be ready soon :)

**Pull request merged**
