### PR TITLE
[LW-10808] Update HW dependencies

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces:
- Updated `@cardano-foundation/ledgerjs-hw-app-cardano` to version `7.1.3`
- Updated `@trezor/connect` to version `9.3.0`
- Fix delegation / staking while using Ledger HW device

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1722592851686219)
- [ ] HW Ledger and Trezor regression testing

QA Note: If you want to test it on preview, please use https://github.com/input-output-hk/daedalus/tree/todelete/lw-10808-cardano-node-9-with-hw-updates. It is a temp branch until we have the Michals update merged https://github.com/input-output-hk/daedalus/pull/3212

---

### Basics

- [ ] PR assigned to the PR author(s)
- [ ] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [ ] PR link is added to a Jira ticket, ticket moved to In Review
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR contains screenshots (in case of UI changes)
- [ ] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by michalrus — APPROVED** [review]
Awesome! :tada: 

The "tests" check [is failing](https://github.com/input-output-hk/daedalus/actions/runs/10213700096/job/28259634925?pr=3215), though:

```
error @ethereumjs/tx@5.3.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.21.3"
```

Are we really using Node.js 14? I don’t think so :confused: Especially since Buildkite passed?

**Comment by tomislavhoracek** [comment]
> Awesome! 🎉
> 
> The "tests" check [is failing](https://github.com/input-output-hk/daedalus/actions/runs/10213700096/job/28259634925?pr=3215), though:
> 
> ```
> error @ethereumjs/tx@5.3.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.21.3"
> ```
> 
> Are we really using Node.js 14? I don’t think so 😕 Especially since Buildkite passed?

Thanks @michalrus that is something I wanted to ask as well.
I see node`v18.12.1`. To be honest, I think we are good

**Review by michalrus — COMMENTED** [review]
No, wait, Buildkite also fails for `aarch64-darwin`, I’m taking a look :hourglass_flowing_sand: 

I think Node.js 14.× might be used only by this (outdated) GitHub workflow?

**Review by michalrus — CHANGES_REQUESTED** [review]
@tomislavhoracek you can see in [this run](https://github.com/input-output-hk/daedalus/actions/runs/10214293516/job/28261393472?pr=3215), that currently `yarn check:all` is failing:

```
Error: node_modules/@sinclair/typebox/typebox.d.ts(134,121): error TS1005: '?' expected.
```

**Comment by michalrus** [comment]
Re: Netlify – given that:
1. Netlify **forces** running `yarn install` as the very first step,
2. Which fails because their machine doesn’t include `libudev.h` (`sudo apt-get install libudev-dev`),
3. And you cannot run anything before their call to `yarn install`,
4. And they don’t allow to run commands with `sudo`,
5. And in our `preinstall`, the `node_modules` aren’t populated, so it's too early to unpack `libudev-dev` manually,
6. And in our `postinstall`, it’s too late because `yarn install` already failed with missing `libudev.h`

… I really don’t know how to fix this.

Maybe a separate `package.json` which only builds `storybook`? Though they force `yarn install` from the root anyways, so it won’t work.

It feels like a really bad design decision on Netlify’s part, or I'm not seeing something.

**Review by danielmain — APPROVED** [review]
Wizzard Tomo!

**Comment by michalrus** [comment]
Netlify fixed in 4ce5d1f6628842a5f1af156a84dccc8985b8faa6 – had to use Homebrew :)

**Review by michalrus — APPROVED** [review]
Brilliant, thanks! :)

**Pull request merged**
