### PR TITLE
[DDW-531] Update minor dependencies

### PR DESCRIPTION
**Pull request by DominikGuzei**
**Please NOTE: this depends on #1219 so please merge that first**

This PR updates minor dependencies and fixes eslint issues.

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by daniloprates** [comment]
image

I got this error when running the tests. I'm having the same issue in [this card](https://github.com/input-output-hk/daedalus/pull/1157), so it's probably something prior to them.

**Comment by nikolaglumac** [comment]
For this one we need extensive testing by @DmitriiGaico and his approval that everything is working right.

**Comment by nikolaglumac** [comment]
@daniloprates may I ask you to merge `chore/ddw-457-update-electron` branch into this one?
There are some merge conflicts connected to your PR where you have removed in-app bug-reporting feature 🙏

**Comment by daniloprates** [comment]
@nikolaglumac done. I've chosen the HEAD version, here, although I'm not sure it was the correct one.

```
<<<<<<< HEAD
    "es6-error": "4.1.1",
    "fbjs-scripts": "0.8.3",
=======
    "es6-error": "4.0.2",
>>>>>>> chore/ddw-457-update-electron
```

**Comment by nikolaglumac** [comment]
@daniloprates I don't think that was right. I would rather remove "fbjs-scripts" as we don't use it any more and bump es6-error to 4.1.1.

**Comment by daniloprates** [comment]
> @daniloprates I don't think that was right. I would rather remove "fbjs-scripts" as we don't use it any more and bump es6-error to 4.1.1.

✅

**Comment by DominikGuzei** [comment]
@nikolaglumac cucumber deprecations are fixed! 👍

**Comment by nikolaglumac** [comment]
Great news @DominikGuzei!
Are the tests working for you now?

**Comment by DominikGuzei** [comment]
@nikolaglumac yes 😉

**Comment by nikolaglumac** [comment]
Thanks @DominikGuzei 🎉 
I still have issues running tests BUT I guess this is related to my local setup.
Will merge your PR now...

screen shot 2018-12-30 at 16 54 58

**Pull request merged**
