### PR TITLE
[DDW-553] Hardware Wallets - Force Public Key export

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces an additional security step on every device interaction. Before pairing wallets, sending transactions, or delegating a wallet, exporting a public key is a mandatory step!

## Todos

- [x] Remove logs and code cleanup
- [x] Add comment to all crucial places in code for better flow understanding
- [x] CHANGELOG update

## Screenshots

**_English - ( Pair / Send Tx / Delegate)_**

_a) Pair_

Screen Shot 2021-02-08 at 12 46 46

_b) Send Tx_

Screen Shot 2021-02-08 at 12 45 19

_c) Delegate_

Screen Shot 2021-02-08 at 12 47 12

**_Japanese - ( Pair / Send Tx / Delegate)_**

_a) Pair_

Screen Shot 2021-02-08 at 12 48 33

_b) Send Tx_

Screen Shot 2021-02-08 at 12 48 55

_c) Delegate_

Screen Shot 2021-02-08 at 12 49 13

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1612785707164800)
- [ ] Test all Hardware Wallets cases

**NOTE:**
- The main change in this PR is that on each interaction you will be asked to export the public key with your hardware wallet device. On the Ledger devices, this action will occur once you open Cardano App on the device and on Trezor immediately when you want to do something with a device. Cases, where you will be prompted to export public key, are:
1. Add Wallet ( Pair ) - Even if you already have a wallet restored with device you will be prompted to export a public key every time you want to "Pair" again your software and a hardware wallet
2. When you want to send a transaction - Before confirming (signing) transaction
3. When you want to delegate wallet - Before confirming (signing) transaction

- It is crucial to test all possible cases as you did for the first hardware wallets integration because this logic can potentially affect some edge cases.

---

## Test Cases 

**Trezor Test Cases**
```Gherkin
Scenario 1 : Add Wallet
Given that I have Daedalus running
When I try to add a Trezor Wallet
Then I will be prompted to export the public key
And the wallet will be successfully imported

Scenario 2 : Reconnecting device
Given that I have a Trezor wallet already paired and loaded
And my device is physically disconnected from my machine
When I physically reconnect my device
And click pair
Then I will be asked to export my public key 
And exporting public key will be a success
And I will be redirected to the corresponding wallet summary screen

Scenario 3 : Redelegation
Given that I have a Trezor wallet already paired and loaded
And I wish to redelegate my wallet
When I select redelegate from the Stake Pools Wallet Menu
And I follow the Delegate Wallet wizard instructions
Then I am prompted to export my public key
And I am asked to confirm the transaction

Scenario 4 : Sending a transaction
Given that I have a Trezor wallet already paired and loaded
When I select to send a transaction
Then I am prompted to export my public key
And I am asked to confirm the transaction

```
**Ledger Test Cases**

```Gherkin

Scenario 1 : Add Wallet
Given that I have Daedalus running
When I try to add a Ledger Wallet
Then I will be prompted to export the public key
And exporting public key will be succesfull
And the wallet will be succesfully imported

Scenario 2 Unlocking and launching Cardano App before opening Daedalus
Given that I have Daedalus installed and currently closed
And my Ledger device is not connected
When I unlock my device
And Launch Cardano App
And launch Daedalus
And click on "Pair"
Then I am asked to export the public key
And I am brought to the landing page for the correct wallet

Scenario 3: Unlock device before opening Daedalus.But dont launch Cardano App until after clicking Pair
Given that Ledger Device is plugged in and unlocked
And I Open Daedalus
And I Click on "Pair"
When I Launch Cardano App
Then I am asked to confirm export the key
And I am brought to the landing page for the correct wallet

Scenario 4: Open Daedalus first.Plug in device and unlock.Select Cardano app after clicking pair
Given that I have Daedalus installed and open
And I Click on "Pair"
And I Plug in the Ledger Device
And Unlock it
When I Launch the Cardano App
Then I am asked to export the public key
And I am brought to the landing page for the correct wallet

Scenario 5 : Reconnecting device
Given that I have a Ledger wallet already paired and loaded
And I disconnect my device
When I reconnect my device
And I click Pair
And I unlock my device
Then I will be asked to export my public key 
And exporting public key will be a success
And I will be redirected to the corresponding wallet summary screen

Scenario 6 : Redelegation
Given that I have a Ledger wallet already paired and loaded
And I wish to redelegate my wallet
When I select redelegate from the Stake Pools Wallet Menu
And I follow the Delegate Wallet wizard instructions
Then I am prompted to export my public key
And I am asked to confirm the transaction

Scenario 7 : Sending a transaction
Given that I have a Ledger wallet already paired and loaded
When I select to send a transaction
Then I am prompted to export my public key
And I am asked to confirm the transaction
```

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by darko-mijic** [comment]
I will also review this PR.

**Comment by ManusMcCole** [comment]
Hi Tomislav. On Ledger Nano S and Ledger X all tests have passed. 

For Trezor Scenario 2 is failing. On Windows When I try to pair a device that is already synced in Daedalus it asks the user to "Connect your device and enter your pin to unlock it". I enter password and unlock device then it briefly says "Launch Cardano Application on your device" before reverting back to the "Connect your device and enter your pin to unlock it" message. It remains on this message with the spinner circling. No errors on the console. The message asking the user to export public key is never shown 

On Mac scenario 2 goes as follows. When I try to pair a device that is already synced in Daedalus it asks the user to "Connect your device and enter your pin to unlock it". I enter password and unlock device. It remains stuck on the "Connect your device and enter your pin to unlock it" message. It remains on this message with the spinner circling. No errors on the console. The message asking the user to export public key is never shown

**Comment by tomothespian** [comment]
@ManusMcCole are you sure that message "Launch Cardano Application on your device" is shown for Trezor device. 
Did you maybe have Ledger plugged in the machine when you were trying to connect Trezor and you are interacting with the wrong device?
Also "When I try to pair a device that is already synced in Daedalus", what means synced? You paired Trezor device and you immediately tried to sync again? Did you unplugged and plugged again your device? Can you please describe your steps more briefly or even better if you can show me that

**Comment by tomothespian** [comment]
@ManusMcCole If I understand from your cases you paired the device and you tried to pair again without reconnecting (physically) your device which means that your device is PAIRED with software wallet and already CONNECTED so all further connection actions are skipped. Reconnect your device physically and you will see standard flow

**Comment by ManusMcCole** [comment]
Hi Tomislav. I definitely did reconnect physically the device. Yes it is strange that I saw the ledger message in Daedalus "Launch Cardano Application on your device".When I say synced I mean that the wallet is 100% synced with the blockchain. I guess its best I show you on a call. I am available now if you are too

**Comment by darko-mijic** [comment]
```Gherkin
Given I have Daedalus running
And I click the Pair button
And I successfully pair my Ledger Nano X device
And I leave it connected and unlocked
When I try to sign a transaction
Then I get the "Connect the "Ledger Nano X" device and enter your PIN to unlock it" message 
And the DEVICE_NOT_CONNECTED error message in the console
```

@tomothespian, I have this issue. Also, Adalite does not require two clicks on the device to export the key. It just asks to export 6 public keys and one click is enough. We can discuss this separately since we will need the same for multi-account support.

image

**Comment by tomothespian** [comment]
@darko-mijic Thanks for the review. I will check the issue you found.
Nikola and I discussed a case with multiple key exports when you are signing witnesses ( I think that you and I also talked about that before few months ) and maybe would be better to improve that in the scope of the new task. 

@ManusMcCole A fix for an issue with Trezor ( re-connecting ) we were investigated yesterday will be included in this PR.

I will let you know when is ready for another review round!

**Comment by tomothespian** [comment]
@ManusMcCole Trezor reconnect issue should be fixed now. Can you please test again?

**Comment by ManusMcCole** [comment]
Sure thing Tomislav :). On it now 👍

**Comment by tomothespian** [comment]
@ManusMcCole can you also check a case Darko mentioned 🙏 https://github.com/input-output-hk/daedalus/pull/2342#issuecomment-776499063
I can't reproduce this issue anymore!

cc @darko-mijic

**Comment by ManusMcCole** [comment]
Hi @tomothespian. Good work on fixing the Trezor reconnect issue. I added some extra test cases testing to do with keeping the devices connected
Scenario 6 for Ledger fails intermittently. Sometimes it works and others it doesnt.No errors on the console. Daedalus gets stuck on the message "Connect your device and enter your pin to unlock it" I believe this is related to @darko-mijic issue #2342 (comment) as in his scenario also Cardano App is still running on the device.
Trezor Scenario 4 also fails intermittently. It seems to work many times in a row and then once it fails it fails many times in a row.No errors on the console.

I am working now on figuring out if there are more clear reproduction steps and to see can I track down why it works sometimes and not on other occasions

**Comment by tomothespian** [comment]
@ManusMcCole Related to Scenarios 4. and 6
But if your device is paired and you didn't physically reconnect the device then we are treating the device already as paired device and it is normal that you can't pair that device again until is physically reconnected. So, this means that you can have only one active session between the software wallet and a device at a time.
cc @nikolaglumac

**Review by ManusMcCole — APPROVED** [review]
Good work @tomothespian 👍

**Review by nikolaglumac — APPROVED** [review]
Great work @tomothespian 🎉

**Pull request merged**
