### PR TITLE
[DDW-797]: Fix external and copy icons inconsistencies

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR fixed external and copy icons inconsistencies
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-797)

## Todos
- [x] Fix external and copy icons to let them on same line with text labels

## Screenshots
image

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1565105548108400)
- [x] Create sidebar button to open `Create paper wallet certification` modal and then walk through step by step to finally open above view on modal

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
on the screenshot, only 102 characters in address... is it just a random line?

**Comment by daniloprates** [comment]
We need to account [this possibility](https://github.com/input-output-hk/daedalus/blob/feature/ddw-797-fix-external-and-copy-icons-inconsistencies/source/renderer/app/components/staking/stake-pools/StakePoolTooltip.scss#L199) of a large link:

image

Please, check if it's possible to implement the [middle ellipsis](https://github.com/input-output-hk/daedalus/blob/feature/ddw-797-fix-external-and-copy-icons-inconsistencies/source/renderer/app/utils/strings.js) in this case.

**Comment by daniloprates** [comment]
This is how it's going to look on Windows. Please, try reducing the `letter-spacing` to `-.5px`

image

**Comment by yakovkaravelov** [comment]
@daniloprates Fixed the issues you reported.
Please review again, thanks.

**Comment by daniloprates** [comment]
@yakovkaravelov please, update your branch to the latest `develop`, so we can get the Windows/Linux installers

**Comment by nikolaglumac** [comment]
@daniloprates PR updated with latest develop...

**Comment by a-rukin** [comment]
image
text split is a bit strange, don't you think?

**Comment by a-rukin** [comment]
image

is it possible to prolong fade time (twice) in terms of this task? or should I mark it as a fix for later changes?

**Comment by nikolaglumac** [comment]
@daniloprates are the issues you raised fixed now?

**Comment by nikolaglumac** [comment]
@gnpf please make sure to check all external icon and copy links in both English and Japanese.
Please try to change Daedalus windows size to see if the icon breaks into a new line. Thanks!

**Pull request merged**
