### PR TITLE
[DDW-617] Move all tests into same folder

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR refactors and simplifies our test setup:

- All acceptance tests (unit & end-to-end) are in the `features` folder
- The support folder was renamed to `features/tests` and contains two sub-folders `e2e/unit` for the respective test implementations … (no steps are shared atm)
- End-to-end tests have the tag `@e2e` and unit tests `@unit`
- They are run separately to keep unit tests blazing fast (0.006 seconds atm)
- Test commands reduced to:
  - `yarn test` (build + run all unit and ui tests)
  - `yarn test:unit` run all unit tests (those tagged with `@unit`)
  - `yarn test:unit:watch` only run unit tests with `@unit` and `@watch` tags and rerun on file changes
  - `yarn test:e2e` run all UI tests (app is not built before!)
  - `yarn test:e2e:watch` only run tests with `@e2e` and `@watch` tags (app is built and in watch mode) reruns tests when files change

## What to test
No QA necessary: Nothing has changed in functionality of the app - only the test setup was refactored.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance  and unit tests are passing (`yarn run test` and `yarn run test:unit`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] There are no *prettier* errors or warnings (`yarn run prettier:check`)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by daniloprates** [comment]
I am reviewing this PR

**Comment by daniloprates** [comment]
@DominikGuzei:

```shell
$ yarn test:unit:unbound --tags @mnemonics
yarn run v1.9.4
error Command "test:unit:unbound" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nikolaglumac** [comment]
@daniloprates that test is added in a different PR: https://github.com/input-output-hk/daedalus/pull/1379

**Comment by DominikGuzei** [comment]
@daniloprates that description was a mistake 😉 i updated the wrong PR description

**Pull request merged**
