### PR TITLE
[DDW-717] Update Trezor logic to cover upcoming breaking changes

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces a logic update to cover upcoming breaking changes.

[**Test document #1 - Build 18930**
](https://docs.google.com/spreadsheets/d/1BTrNKbNcUj2HqqE7ijMJC-rUPo_BN32Ftz8rkIst47A/edit?usp=sharing)

**_Notes:_**
- Logic is now designed to cover the current Trezor response and "potential" response after firmware update. New Trezor firmware response will return data like Ledger and that is handled by trezor-connect package. This logic is improved following  current documentation https://github.com/trezor/connect/pull/841/commits/25b66381b3438b68cf4786f6d51d8bf1db9b6783#diff-95d2cba6d3ec639fa89710a8e43e188282fa57da8eae165242e5d20392417f93R752

- Trezor Firmware update Slack thread: https://input-output-rnd.slack.com/archives/G010N9UFDNH/p1625213306062200
- Good news: _the transaction streaming update for Trezor (to remove the 8kB limitation on transaction size) will be released in September, not in August._  https://input-output-rnd.slack.com/archives/G010N9UFDNH/p1626872687078200

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test regular transaction with Trezor device on current firmware
- [ ] Test transaction with native tokens with Trezor device on current firmware
- [ ] Delegate with Trezor device on current firmware
- [ ] Test regular transaction with Trezor device on NEW firmware (once is releases)
- [ ] Test transaction with native tokens with Trezor device on NEW firmware (once is releases)
- [ ] Delegate with Trezor device on current NEW firmware (once is releases)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@ManusMcCole @dmitrii-gaico I would appreciate if you could test this one 🙏 
Thanks!

**Comment by ManusMcCole** [comment]
Hi @nikolaglumac. Functionality works as expected for the current Trezor firmware of 2.4.1 on newest builds 18689

**Comment by nikolaglumac** [comment]
@ManusMcCole on all 3 platforms?

**Comment by ManusMcCole** [comment]
Yes on all 3 platforms @nikolaglumac 👍

**Comment by nikolaglumac** [comment]
Great news! Can you please approve the PR if you think it is all working? Thanks!

**Comment by ManusMcCole** [comment]
> Great news! Can you please approve the PR if you think it is all working? Thanks!

Dont I need to wait for the new Trezor firmware in order to complete testing ? @tomislavhoracek mentioned it will be released in September @nikolaglumac

**Comment by nikolaglumac** [comment]
Alright, let's wait for Tomislav!

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek. On all 3 OS there is an error when trying to run Daedalus "Error: Cannot find module 'ieee754'".See [screenshot](https://drive.google.com/file/d/10CH2OuPiWp0xyZe61yJ1EXUgRkLnBzeb/view?usp=sharing). Going to run it locally now

**Comment by tomislavhoracek** [comment]
@ManusMcCole it is probably because of the unofficial `trezor-connect` version installed directly from the pre-release GH tar.gz

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek. While running the builds locally all transactions are initially getting the green transaction confirmed success message, but once the user clicks on send "an error occured" message pops up. A malformed tx payload error is displayed in the console. See [screenshot](https://drive.google.com/file/d/1NBpqJEgX5LyJ5aOa9id9Ln7oNMuA2lX7/view?usp=sharing)

**Comment by tomislavhoracek** [comment]
@ManusMcCole we discussed that issue yesterday. It is related to the Alonzo hard fork (Testnet)!

**Review by nikolaglumac — APPROVED** [review]
Great work 💯

**Review by ManusMcCole — APPROVED** [review]
Great work @tomislavhoracek 🚀

**Review by dmitrii-gaico — APPROVED** [review]

**Review by gabriela-ponce — APPROVED** [review]

**Review by miorsufianiohk — APPROVED** [review]
LGTM 👍

**Pull request merged**
