### PR TITLE
[DDW-1095] Integrate stake pool join V2 API endpoint and update "Delegation" wizard

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces stake pool "join" V2 API endpoint and update for "Delegation" wizard.

## Screenshots

Delegation Center

Delegation Wizard - Intro

Delegation Wizard - Step 1

Delegation Wizard - Step 2

Delegation Wizard - Step 3

Delegation Wizard - TA-DA

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1575632285272400)
- [ ] Open "Delegation center" screen and click on "delegate". Walkthrough wizard. On step 1 wallet is preselected depending on your choice. On step 2, the stake pool is not preselected. When you are done, in "Delegation center" should be visible what is delegated

- [ ] Open "Stake Pool" screen, select stake pool and click on "delegate". Walkthrough wizard. On step 1 wallet is not preselected. On step 2, the stake pool you selected should be also preselected in wizard. When you are done, in "Delegation center" should be visible what is delegated

- [ ] Open "Delegation center" screen, select stake pool and click on "delegate". Select already delegated wallet and choose "Change delegation" from the dropdown.  Walkthrough wizard. On step 1 wallet is preselected depending on your choice. On step 2, the stake pool you selected should be also preselected in the wizard. When you are done, in "Delegation center" will show what was changed.

**NOTE:** _Pay attention on wizard copy and Japanese translations as well as on design changes_
1. Copy: https://docs.google.com/document/d/1avBpmynpeyqwQXez_aoDZLgsslnIF3VjLbfuQK8NfY0/edit

2. Design: https://app.zeplin.io/project/57acfaa7436a750316161a8b/screen/5cb05e0cecae12a09a715861

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by DmitriiGaico** [comment]
Can we update the error message when trying to Re-Delegate to the same Stake Pool?
Thank you!

image

**Comment by DmitriiGaico** [comment]
@tomothespian The Drop Down is truncated a little bit but mb it is easy to fix. Please see below.
Drop_D

**Comment by tomothespian** [comment]
> Can we update the error message when trying to Re-Delegate to the same Stake Pool?
> Thank you!
> 
> image

@DmitriiGaico I will create new task for this one after we get suggestions from Darko!

**Comment by tomothespian** [comment]
> @tomothespian The Drop Down is truncated a little bit but mb it is easy to fix. Please see below.
> Drop_D

@DmitriiGaico this one is related to React-Polymorph "Select".
@nikolaglumac Should we create a new task for that?

**Comment by a-rukin** [comment]
image
it seems for me that lines which don't have ticker is vertically unaligned (may be it's beeing fixed in other task)

**Comment by nikolaglumac** [comment]
@DmitriiGaico @a-rukin @tomothespian we only need to fix this: https://github.com/input-output-hk/daedalus/pull/1744#issuecomment-562609842 - @tomothespian please create a new task for this!
The other issue with dropdown being cut off we can leave as is.

**Comment by a-rukin** [comment]
@nikolaglumac shouldn't we open dialog right on step 2 when clicking "delegate" or "change delegation" (with ability to go back ofc). Thought we've already discussed this.
Zero step is shown when we click "Delegate to this pool" from the "Stake pools" tab.

**Comment by darko-mijic** [comment]
@a-rukin, @tomothespian, can we disable the stake pool user is already delegating to? If not it is better to disable to submit button instead of displaying the error.

**Comment by a-rukin** [comment]
image
distance is bigger than it is here https://zpl.io/a8p7ePJ

**Comment by a-rukin** [comment]
> @a-rukin, @tomothespian, can we disable the stake pool user is already delegating to? If not it is better to disable to submit button instead of displaying the error.

I'd disable button, because removing those pool would look strange

**Comment by darko-mijic** [comment]
Not removing @a-rukin, disabling. It can be grayed-out or something. If that is too much work we should disable the submit button.

**Comment by a-rukin** [comment]
> Not removing @a-rukin, disabling. It can be grayed-out or something. If that is too much work we should disable the submit button.

actually this is even better, as while browsing you still keep track of which pool it's currently delegated to

**Comment by a-rukin** [comment]
30% of opacity for disabled one (as always) + disabling button
NOTE: this opacity doesn't affect top selection

**Comment by tomothespian** [comment]
> Not removing @a-rukin, disabling. It can be grayed-out or something. If that is too much work we should disable the submit button.

@darko-mijic I will disable the already delegated stake pool. That shouldn't be too much work..

**Comment by tomothespian** [comment]
> @nikolaglumac shouldn't we open dialog right on step 2 when clicking "delegate" or "change delegation" (with ability to go back ofc). Thought we've already discussed this.
> Zero step is shown when we click "Delegate to this pool" from the "Stake pools" tab.

@darko-mijic what you think that is best?

**Comment by tomothespian** [comment]
> @DmitriiGaico @a-rukin @tomothespian we only need to fix this: [#1744 (comment)](https://github.com/input-output-hk/daedalus/pull/1744#issuecomment-562609842) - @tomothespian please create a new task for this!
> The other issue with dropdown being cut off we can leave as is.

https://iohk.myjetbrains.com/youtrack/issue/DDW-1113

**Comment by darko-mijic** [comment]
Yes, It would be best to start from the stake pool step (2) if the wallet is already known.

**Comment by tomothespian** [comment]
@darko-mijic part with blocking already delegated stake pool to be delegated again is done. Please let me know if everything is correct. 🙏  Thanks

**Comment by gnpf** [comment]
@tomothespian As the first step is skipped, when trying to delegate a wallet with no ADA, a generic error is displayed:

**Comment by DmitriiGaico** [comment]
> @tomothespian As the first step is skipped, when trying to delegate a wallet with no ADA, a generic error is displayed:
> 
> 

That's expected. Error message would be improved in future.

**Comment by tomothespian** [comment]
@DmitriiGaico actually I'm not sure in that. I think that we didn't understand each other. In case @gnpf found we should not skip wallet selection but we also should not show "Delegation not available". 
Maybe, in that case, we should start with a wizard from beginning "Intro" step? @darko-mijic

**Comment by a-rukin** [comment]
We should not skip a step if it's returning an error
So in case of low amount of ada we will be on step 1 with red field and error message
p.s. I see step skip not like a jump to a direct point, but like a click-through

**Comment by tomothespian** [comment]
> We should not skip a step if it's returning an error
> So in case of low amount of ada we will be on step 1 with red field and error message
> p.s. I see step skip not like a jump to a direct point, but like a click-through

@a-rukin @DmitriiGaico @daniloprates @gnpf This one is improved !

**Comment by tomothespian** [comment]
> > We should not skip a step if it's returning an error
> > So in case of low amount of ada we will be on step 1 with red field and error message
> > p.s. I see step skip not like a jump to a direct point, but like a click-through
> 
> @a-rukin @DmitriiGaico @daniloprates @gnpf This one is improved !

**Pull request merged**
