### PR TITLE
[DDW-767] Remove ADA Redemption Feature

### PR DESCRIPTION
**Pull request by MarcusHurney**
This PR removes all Ada Redemption components, containers, stores, api methods, actions, utility functions, tests, CSS variables, constants, types, and terms of use.

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [x] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn flow:test`)
- [x] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by daniloprates** [comment]
@darko-mijic @nikolaglumac shouldn't we review the [T&C's](https://github.com/input-output-hk/daedalus/blame/chore/ddw-767-remove-ada-redemption-feature/source/renderer/app/i18n/locales/terms-of-use/mainnet/en-US.md#L61) if we're removing the Ada Redemption feature?

**Comment by MarcusHurney** [comment]
@daniloprates 
I updated the terms and conditions to not include Ada Redemption, but it's still worth reviewing.

**Comment by daniloprates** [comment]
We need @darko-mijic to approve this [change](https://github.com/input-output-hk/daedalus/pull/1510/files#diff-a335efe2c58ee94992b4f5064c28f327L61). Also probably remove it from the [Japanese version](https://github.com/input-output-hk/daedalus/blob/chore/ddw-767-remove-ada-redemption-feature/source/renderer/app/i18n/locales/terms-of-use/mainnet/ja-JP.md#user-content-%E7%AC%AC11%E6%9D%A1-ada%E3%81%AE%E6%8F%9B%E9%87%91) and [Testnet T&C's](https://github.com/input-output-hk/daedalus/tree/chore/ddw-767-remove-ada-redemption-feature/source/renderer/app/i18n/locales/terms-of-use/other).

**Comment by nikolaglumac** [comment]
@darko-mijic and I will pair review this one tomorrow.

**Comment by MarcusHurney** [comment]
@nikolaglumac Does QA need to test this PR?

**Comment by nikolaglumac** [comment]
@MarcusHurney we need @DmitriiGaico / @gnpf to run basic smoke tests on this build.

**Comment by DmitriiGaico** [comment]
I Start Testing.

**Pull request merged**
