### PR TITLE
[DDW-529] Verify HW wallet receiving address - Trezor

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces Hardware Wallet receiving address verification for Trezor devices.

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)

**_In-App testing_**

- [ ] Go to wallet receive screen for some Hardware Wallet and check the address verification process. You can test the same steps / cases as is for signing transactions. Instead of "Sign transaction" you will see an Address Verification message.
- [ ] Spending and Staking paths are added to the "Share wallet address" for ALL types of wallets under QR code.

**_NOTES:_**
1.  I added screenshots with titles / descriptions in the exact order on how the process is going so please check before you start with testing

2. There are multiple cases presented:
- On the first attempt you will be asked to export the address (with device) and after that address will also show on the device. When you confirm all the actions you will see that the first checkbox is checked in UI. After that, you will be asked to answer a question ( is the address true or not). If you select "No, reverify", you will pass through the same process but with one additional option to select (inside answers section), "No, I am sure that address displayed in Daedalus is different from the address displayed on my Trezor device" one. If you select that option new section will appear. This section will ask you to confirm that address is not valid. If you check that the "Submit request" button becomes enabled, it is disabled otherwise. 
- If you select an option that address is valid you should see "Save QR" and "Save PDF" buttons ass well as the possibility to enter a PDF note.
- Important thing is also that both checkboxes on the top "Daedalus verified the address" and "You have verified the address" are disabled and will be checked automatically as you are walking through the process. The first one is checked after you confirm everything in the device and the second one when you choose an option from "Is the address you have verified correctly".

---

## Test Cases
- TBD
---

## Testing Summary
---

## Screenshots

**_ENGLISH_**

_1. Start Veifying_

1  Verify (start) - EN

_2. Answer to the question_

2  Answer to question

_2.1. Answer - YES_

2 1  YES - answer

_2.2. Answer - NO, reverify ( State after reverifying)_

2 2 NO - reverify

_2.2.1 Answer NO after reverifying_

2 2 1 - Wrong address confirmed by the user

_2.2.2 Confirm wrong address_

2 2 2 - Confirm manual check

_3. Rejected Verification_

3  Verification failed - cancel address export

_4. Spending and Staking addresses on "regular" wallet receive screen_

4  Default Regular wallets

**_JAPANESE_**

_1. Start Veifying_

1  Verify (start) - JP

_2. Answer to the question_

2  Answer to question - JP

_2.1. Answer - YES_

2 1  YES - answer - JP

_2.2. Answer - NO, reverify ( State after reverifying)_

2 2 NO - reverify - JP

_2.2.1 Answer NO after reverifying_

2 2 1 - Wrong address confirmed by the user - JP

_2.2.2 Confirm wrong address_

2 2 2 - Confirm manual check - JP

_3. Rejected Verification_

3  Verification failed - cancel address export - JP

_4. Spending and Staking addresses on "regular" wallet receive screen_

4  Default Regular wallets - JP

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek. Here is the testing report.Tested on 17924

I found an issue.Prerequisites =  Pair and fully load 2 Trezor hardware wallets. Wallet 1 = no passphrase Wallet 2 = passphrase.No other wallets are in Daedalus.This error happens across all OS

1.Open Daedalus
2.Go to receive screen for wallet 1
3.Connect and unlock Ledger Trezor device
4.Unlock and export public key
5.Enter passphrase
6. Answer question with Daedalus to confirm address 
7.Leave Device plugged in
8.Go to receive screen for wallet 2
9.Exporting public key failed (As it should as device was not disconnected)
10.Daedalus asks to reconnect device
11.Device is reconnected and unlocked
12.Daedalus does not recognise device and it continues to show the text ”Connect the myTrezor device and enter pin to unlock it”
13.No matter how many times I reconnect and unlock device it remains stuck on the above screen
14.Exit the screen.
15.Try to verify receive address again for wallet 2


Then wallet number 2 gets stuck in some state where exporting of public key fails everytime before asking the user to input the passphrase. State persists even after restart. No messages on the console apart from the disconnection error that pops up everytime Trezor is removed. Error happens everytime

**Comment by tomislavhoracek** [comment]
@ManusMcCole Issue should be fixed now. Can you please check again? 🙏

**Review by ManusMcCole — APPROVED** [review]
Great work @tomislavhoracek. Fix works great 👍

**Review by nikolaglumac — APPROVED** [review]
Graet work @tomislavhoracek 💯

**Pull request merged**
