### PR TITLE
[DDW-590] Improve spending password validation

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes our password validation logic to correctly enforce the following rules for any language:

 - should contain at least one digit
 - should contain at least one lower case
 - should contain at least one upper case
 - should contain at least 7 characters long
 - should allow passwords in caseless languages like Kanji
   - must contain at least one unicase letter
   - all characters must either be unicase, digit or punctuation letters
 - should enforce the case rules in mixed language passwords

**note:** for languages that do not use the concept of *case* the uppercase/lowercase rules are ignored if all letters of the password are in that language (e.g: Kanji)

This PR also introduces a new unit test setup which runs tests without the UI … here is the first spec for the spending password validation:

```gherkin
Feature: Spending password validation

  - should contain at least one digit
  - should contain at least one lower case
  - should contain at least one upper case
  - should contain at least 7 characters long
  - should allow passwords in caseless languages like Kanji
  - should enforce the case rules in mixed language passwords

  Scenario Outline: Valid spending passwords
    Given I use the spending password "<PASSWORD>"
    Then the spending password validation should succeed

    Examples:
      | PASSWORD           |
      | Correct1           |
      | 学年別漢字配当表1     |
      | 正确的马电池钉1      |
      | 正确的马电池钉1!     |
      | Mix学年別漢字配1     |
      | Привет1            |
      | mixПривет1         |
      | !№;%:?()_+1Mm      |
      | Mysuperpassword1!  |

  Scenario Outline: Invalid spending passwords
    Given I use the spending password "<PASSWORD>"
    Then the spending password validation should fail

    Examples:
      | PASSWORD       |
      | 2Short         |
      | S p a c 3 s    |
      | ONLY8UPPERCASE |
      | only8lowercase |
      | 学年別漢字配当表  |
      | mix学年別漢字配  |
      | Привет!        |
      | привет1        |
      | mixпривет1     |
      | 1234567        |
      | 123456!        |
      | !№;%:?*()_+1   |

```

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@daniloprates @nikolaglumac i did some further cleanup and improvements 😉 it's now ready from my side!

**Comment by nikolaglumac** [comment]
@DominikGuzei have you removed password validation from the "Current password" field in the "Change password" dialog? That is a very important thing to do since we are changing the validation rules!

**Comment by DominikGuzei** [comment]
@nikolaglumac i removed the validation from the "current password" field and tested it with an old (now invalid password) and changed it to a new one 👍

**Comment by nikolaglumac** [comment]
@DominikGuzei @daniloprates let's wait with merging this one until QA approves it 🙏

**Comment by nikolaglumac** [comment]
@DominikGuzei I have added this extra fix: https://github.com/input-output-hk/daedalus/commit/a834bbf7e3f4e2fca6551a346b0cd94ae24cd7fe
It is not connected to your changes BUT I had a lot of random test failures due to the problems with forced NTP checks. This fix resolves the issues.

**Comment by DominikGuzei** [comment]
@DmitriiGaico @nikolaglumac please specify the exact rules … should special chars like `!` be allowed at all in passwords?

**Comment by nikolaglumac** [comment]
@DominikGuzei @DmitriiGaico yes special chars are allowed.
Still, the password:
- should contain at least one digit
- should contain at least one lower case
- should contain at least one upper case
- should contain at least 7 characters long
- should allow passwords in caseless languages like Kanji
- should enforce the case rules in mixed language passwords

Password `123456!` should be invalid as it doesn't contain one lowercase and one upper case letter!

**Comment by DmitriiGaico** [comment]
> @DmitriiGaico @nikolaglumac please specify the exact rules … should special chars like `!` be allowed at all in passwords?

@DominikGuzei From my point of view basing on the rules 
  - should contain at least one lower case
  - should contain at least one upper case
The passwords 
!"№;%:?*()_+1 - Rejected
!"№;%:?*()_+1Mm - Accepted.

I do agree the special characters can be used as a password but they should also fall under the rules.

**Comment by nikolaglumac** [comment]
@DominikGuzei @DmitriiGaico `: !"№;%:?*()_+1` should be invalid as it is missing one lower case letter!

**Comment by DominikGuzei** [comment]
@nikolaglumac @DmitriiGaico i fixed the validation logic to only allow `Other_Letter` (= unicase letters) and numbers to be regarded as caseless https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)

I added your examples to the unit tests 👍

**Comment by nikolaglumac** [comment]
@DominikGuzei I have updated my original review comment with more details: https://github.com/input-output-hk/daedalus/pull/1354#pullrequestreview-219886636

**Comment by DominikGuzei** [comment]
@nikolaglumac @DmitriiGaico all issues addressed and fixed - ready for the final round of testing 💪

**Comment by DominikGuzei** [comment]
@IuliaDolishniak @DmitriiGaico @nikolaglumac ready for final review!

**Pull request merged**
