### PR TITLE
[DDW-629] Fix external currencies not appearing when not connected

### PR DESCRIPTION
**Pull request by daniloprates**
This PR fixes external currencies not appearing when not connected.

- [x] Keep the last fetched value in case of error and the rate was previously fetched
- [x] Keep "-" in case of error and no rate was fetched

## Screenshots

Screen Shot 2021-05-11 at 12 44 33
Screen Shot 2021-05-11 at 12 44 45

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1620748055062100)
- [Jira card](https://jira.iohk.io/browse/DDW-629)
- [ ] Test

---
## Test scenarios

**Scenario 1 - Validate rate and balance when no rate was fetched**
```gherkin
Given that Daedalus has connection issues
And displaying balance in other currencies is enabled
And no currency rate was fetched before
When I check the balance of the wallet
Then I can see the total balance for that currency is displayed as "-"
And "-" is displayed instead of the rate
And the message "fetching rates" would be displayed below those
```

**Scenario 2 - Validate rate and balance when a rate was fetched**
```gherkin
Given that Daedalus has connection issues
And displaying balance in other currencies is enabled
And the currency rate was fetched before
When I check the balance of the wallet
Then I can see the previous rate is displayed
And a message that informs how long ago the rate was fetched is displayed below
```
**Scenario 3 - Validate rate and balance are updated after the connection is restored**
```gherkin
Given that Daedalus has connection issues
And displaying balance in other currencies is enabled
When the connection with the network is restored
Then I can see on the wallet balance that within a minute the rate is fetched 
And after the fetching is completed, the rate is updated
And the balance is updated accordingly
```

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates is this ready for QA?

**Comment by daniloprates** [comment]
> @daniloprates is this ready for QA?

I need to do a general checking before handing over to QA

**Comment by gabriela-ponce** [comment]
@daniloprates, here are a few issues and suggestions for the latest build (17936)

- When Daedalus is started with no Internet, the list of currencies is displayed empty. Check [this](https://drive.google.com/file/d/10t71OyPZkUnUB6lxYSbBImeZWdXVJfzi/view?usp=sharing) screenshot. Could this be improved? Maybe a spinner or a disclaimer that informs the list would be updated once the network is restored?

- If you switch off the option of show ADA in other currencies, and then check the balance of the wallet, you can still see the conversion. Check [this](https://drive.google.com/file/d/1CQRzVYvQSzNRyUjWfQgnRfNMUjtd5luh/view?usp=sharing) video.

- @dmitrii-gaico suggested that the user should also be informed if the old rates are displayed while Daedalus is still fetching. Maybe an icon and a tooltip as on native tokens? I think we could discuss this at the design meeting.

**Comment by daniloprates** [comment]
Thanks for the inputs, @gabriela-ponce and @dmitrii-gaico. As we talked in the UX meeting, let's leave the other details, for now. I've just pushed a fix for the currency visible when disabled.

**Review by alexander-rukin — APPROVED** [review]
looks ok

**Review by gabriela-ponce — APPROVED** [review]

**Review by dmitrii-gaico — APPROVED** [review]

**Review by ManusMcCole — APPROVED** [review]

**Review by nikolaglumac — APPROVED** [review]
💯

**Pull request merged**
