### PR TITLE
[DDW-728] Stake pool ranking improvements

### LINKED ISSUE #2637: Retiring pool indicator missing in Delegation Center
When a pool is marked for retirement, a red square in top right corner of its entry in Stake Pools section (list of ~2800 pools) is added. However, in Delegation Centre section where the user's current delegated pools for each wallet are shown, this indicator is currently missing and user will only discover that the pool they're staking with is due to retire if they hover their mouse over it.

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements Stake Pools ranking improvements

* [Dependency](https://github.com/input-output-hk/cardano-wallet/pull/2781)

## Todos

- [x] Rank all pools which have met their pledge, keep current ranking for pools that have estimated rewards > 0, rank other pools based on the desirability
- [x] Give no ranking  for pools that have not met their pledge
- [x] Change the gradient from green/red to green/gray for the pools which have ranking
- [x] Implement a X icon for Pools that have not met their pledge and display the delegate button in red
- [x] Set rewards to 0 for Pools that have not met their pledge
- [x] Set potential rewards to ? for pools which have a rank but have rewards estimated at 0
- [x] Fix #2637 

## Screenshots

Screen Shot 2021-08-31 at 17 08 35
Screen Shot 2021-08-31 at 17 08 46
Screen Shot 2021-08-31 at 17 09 19
Screen Shot 2021-08-31 at 17 09 33
Screen Shot 2021-08-31 at 17 09 42
Screen Shot 2021-08-31 at 17 10 05

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1630440402061700)
- [ ] Test

---
## Test Scenarios

**Scenario 1 - Validate ranking criteria**
```gherkin
Given that I am on any of the stake pool views (Grid | List | Delegation wizard)
And the pools are sorted by ranking
When I validate the ranking criteria
Then I can see the pools that met their pledge have different ranking numbers 
And these are ranked by potential rewards
And the pools that didn’t met their pledge show a “-” instead of a ranking number
And these are at the bottom of the ranking, sorted by desirability
```

**Scenario 2 -  Validate gradient**
```gherkin
Given that I am on any of the stake pool views (Grid | List | Delegation wizard)
And the pools are sorted by ranking
Then I can see that the gradient for the ranking goes from green to gray
And green applies to higher-ranked pools
And gray applies to lower-ranked pools
And the pools that haven’t met their pledge are displayed in red
```

**Scenario 3 - Validate pools that didn’t met their pledge on grid view**
```gherkin
Given that I am on stake pools grid view (Grid | Delegation wizard)
When I check the box of any of the pools that didn’t met their pledge
Then I can see that they show a “-” instead of a ranking number
And no “*” is displayed next for the ranking
And a red “Ø” is displayed on the right corner of the box
And upon hovering the “Ø” a tooltip is displayed reading the following:

ENGLISH: This pool has not met its pledge requirements. This means that the pool will not produce blocks or generate rewards until the pledge is met.

JAPANESE: このプールは出資要件を満たしていません。出資額が満たされるまで、このプールがブロックを生成したり報酬を生み出すことはありません。
```

**Scenario 4 - Validate pools that didn’t met their pledge on list view**
```gherkin
Given that I am on stake pools list view
When I check the row of any of the pools that didn’t met their pledge
Then I can see that they show a “-” instead of a ranking number
And the potential rewards show “?”
```

**Scenario 5 - Validate popover for pools that didn’t met their pledge**
```gherkin
Given that I am on any of the stake pool views (Grid | List | Delegation wizard)
When I click on a stake pool that hasn’t met their pledge
Then I can see on the popover that the button “Delegate to this pool” is displayed in red
And the rank shows “-” instead of a number
And the potential rewards show “?”
And a red tag is displayed next to the ticker, reading the following:

ENGLISH: Pledge not met
JAPANESE: 出資額不足
```

**Scenario 6 - Validate pools that didn’t met their pledge on Delegation Center**
```gherkin
Given that I am on delegation center
And I have a wallet that is delegated to a stake pool that hasn’t met their pledge
When I check the box for this stake pool
Then I can see that they show a “-” instead of a ranking number
And no “*” is displayed next for the ranking
And the ranking color is the same as on grid view for this stake pool
And a red “Ø” is displayed on the upper right corner of the box
And upon hovering the “Ø” a tooltip is displayed reading the following:

ENGLISH: This pool has not met its pledge requirements. This means that the pool will not produce blocks or generate rewards until the pledge is met.

JAPANESE: このプールは出資要件を満たしていません。出資額が満たされるまで、このプールがブロックを生成したり報酬を生み出すことはありません。
```

**Scenario 7 - Validate the “Retirement” indicator and popover on delegation center**
```gherkin
Given that I am on delegation center
And I have a wallet that is delegated to a Stake Pool that is retiring soon
And the Stake pool has met their pledge
When I check the last epoch box for this wallet 
Then I can see the retiring icon is displayed on the upper right corner
And on the popover I can see a red tag that indicates how much time is remaining until the stake pool retires
```

**Scenario 8 - Validate the “Ø” indicator and popover on delegation center**
```gherkin
Given that I am on delegation center
And I have a wallet that is delegated to a Stake Pool that is retiring soon
And the Stake pool has not met their pledge
When I check the last epoch box for this wallet 
Then I can the rank shows “-” instead of a number
And I can see the “Ø” icon is displayed on the upper right corner
And the potential rewards show “?”
And on the popover I can see a red tag that indicates how much time is remaining until the stake pool retires
And a red tag is displayed next to the ticker, reading the following:

ENGLISH: Pledge not met
JAPANESE: 出資額不足
```

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by alexander-rukin** [comment]
image

"x" is too small 
"–" is off centered

design - left; implementation - right

**Comment by alexander-rukin** [comment]
image
in this state "–" should be moved even more to the top, to be centered

**Comment by alexander-rukin** [comment]
https://user-images.githubusercontent.com/2539345/131652414-f27f7d62-8a91-4bae-a393-0bbd54d8a513.mp4

I also noticed this strange behaviour of clicks (not related to this PR  i suppose)

**Comment by alexander-rukin** [comment]
image

can we swap percentage like here https://zpl.io/2jyD0Zq

**Comment by gabriela-ponce** [comment]
@daniloprates a few issues on the build 18933:

- The "X" indicator on the tiles, overlaps the text for long tickers. Check [this](https://drive.google.com/file/d/10pqDRIgEEZAfzGs2xqH8ky_CDW7505Lv/view?usp=sharing) screenshot.
- The popover on delegation center for stake pools that didn't met the pledge, doesn't show the ranking color (red), as on the "green/gray" stake pools. Check [this](https://drive.google.com/file/d/1ntUdU9rL6Cb5o2ZB9hoAy5QxqR2paKRP/view?usp=sharing) video.
- There is no way to know if a stake pool is retiring unless you check the list view. Check screenshots [1](https://drive.google.com/file/d/1Wx2YObKvQu3KFHUrNBDcWhe3E8uyQoSp/view?usp=sharing) and [2](https://drive.google.com/file/d/1OmsfEpvQjIX6HRMPIp3vVO10LEHzzR56/view?usp=sharing). This applies for stake pools that didn't met their pledger and are retiring as well.

**Comment by alexander-rukin** [comment]
image
"x" is offcentered (but when size would be normal I think it would be fixed too)

**Comment by alexander-rukin** [comment]
> * The "X" indicator on the tiles, overlaps the text for long tickers. Check [this](https://drive.google.com/file/d/10pqDRIgEEZAfzGs2xqH8ky_CDW7505Lv/view?usp=sharing) screenshot.

This one is OK 

> * There is no way to know if a stake pool is retiring unless you check the list view. Check screenshots [1](https://drive.google.com/file/d/1Wx2YObKvQu3KFHUrNBDcWhe3E8uyQoSp/view?usp=sharing) and [2](https://drive.google.com/file/d/1OmsfEpvQjIX6HRMPIp3vVO10LEHzzR56/view?usp=sharing). This applies for stake pools that didn't met their pledger and are retiring as well.

"didn't meet pledge" has a bigger priority in terms of icons -> as for the popup - we should stack those badges there (it also could be an "ITN pioneer" (if it was released)) -> https://zpl.io/VQy1ZjP

**Comment by daniloprates** [comment]
@gabriela-ponce @alexander-rukin all fixed, with the exception to those I didn't 👀 

> I also noticed this strange behaviour of clicks

☝️ I've noticed too. Need to investigate what's causing it

> The "X" indicator on the tiles, overlaps the text for long tickers

> There is no way to know if a stake pool is retiring unless you check the list view

☝️ As Sasha [explained](https://github.com/input-output-hk/daedalus/pull/2649#issuecomment-910441951)

**Comment by daniloprates** [comment]
>  screencast.2021-09-01.12-55-48.mp4 
> I also noticed this strange behaviour of clicks (not related to this PR i suppose)

@alexander-rukin @gabriela-ponce https://jira.iohk.io/browse/DDW-736

**Comment by alexander-rukin** [comment]
image
Was this "x"  always so small? https://zpl.io/VQy1ZjP - here it's bigger

**Comment by alexander-rukin** [comment]
image
retiring icon looks too small (circle sizes for retirement and pledge not met are the same)

**Comment by alexander-rukin** [comment]
image
top-right border radius should be same as bottom-left (and tile)

**Comment by alexander-rukin** [comment]
image

triangle is bigger and closer to the number than in designs 

image

**Comment by alexander-rukin** [comment]
image
@daniloprates let's make hover area for this whole cell, since hovering small objects not an easy task :D

**Comment by alexander-rukin** [comment]
image
tiles in "delegation center" (left) and "stake pools" (right) look bit different

**Comment by alexander-rukin** [comment]
image
image
sizes are different (also border radiuses)

**Comment by alexander-rukin** [comment]
image
in stakepools it look almost corrent (just a tiny fix for border radiuses and all good)

**Comment by dmitrii-gaico** [comment]
@daniloprates Hey Danilo. Could you please advise if you completed all the changes and we can proceed with testing? Thank you in advance.

**Comment by daniloprates** [comment]
> @daniloprates Hey Danilo. Could you please advise if you completed all the changes and we can proceed with testing? Thank you in advance.

Hi @dmitrii-gaico, I'm waiting for Sasha to make some final touches in the thumbnail, but everything else could be tested, already. Also, I haven't been able to sync with the blockchain in this branch, because the CWB is not using the latest cardano node, so you might only be able to test it on Storybook.

**Comment by dmitrii-gaico** [comment]
> > @daniloprates Hey Danilo. Could you please advise if you completed all the changes and we can proceed with testing? Thank you in advance.
> 
> Hi @dmitrii-gaico, I'm waiting for Sasha to make some final touches in the thumbnail, but everything else could be tested, already. Also, I haven't been able to sync with the blockchain in this branch, because the CWB is not using the latest cardano node, so you might only be able to test it on Storybook.

Thank you for updates.
From my side i installed the latest build and it synced just fine. I transplanted the chain. I'll try to sync 0-100% and see if it works.
image

**Comment by daniloprates** [comment]
> @daniloprates Hello! Delegation Center [pop-up position](https://drive.google.com/file/d/1CVQD-EBrH_Zf3lMZSvFPBGW8DPHfNMWw/view?usp=sharing) seems to be wrong if pool is retiring + pledge not met.
> cc @alexander-rukin

Hey @dmitrii-gaico, we don't have control over the popover positioning. It's done automatically. When the pool is both retiring and has the pledge not met, its height is higher (it's now even higher). Also, on Storybook these things can be a bit wrong because the screen height is smaller. Let's wait until we can run it in the actual app to test this.

**Comment by alexander-rukin** [comment]
image
all pools lost coloring for me

**Comment by daniloprates** [comment]
> image
> 
> all pools lost coloring for me and font weight (for rank number)

Is it on Storybook or the actual app? We can't run it in the app ATM.

**Comment by alexander-rukin** [comment]
> Is it on Storybook or the actual app? We can't run it in the app ATM.

It was app, but in storybook we have this "font" issue too

**Comment by daniloprates** [comment]
Blocked due to [ADP-996](https://input-output.atlassian.net/browse/ADP-996) and [CAD-3479](https://input-output.atlassian.net/browse/CAD-3479):

https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1632818218305700?thread_ts=1630440402.061700&cid=GGKFXSKC6

**Comment by nikolaglumac** [comment]
This PR is to be unblocked by https://github.com/input-output-hk/cardano-wallet/pull/3071

**Pull request closed without merging**
