### PR TITLE
[DDW-541] Fix blank window rendering issue

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR reverts Electron to version `3.0.13` and keeps the `electron-chromedriver: 4.0.0-beta.1` as this combination fixes all blank window rendering issues and keeps the acceptance tests working too.

## Todos:

- [x] Find a way to re-establish `enableRemoteModule: isTest` and in the same time avoid the blank screen issues...

### Installer:
screen shot 2019-01-03 at 11 30 46

### Development: 
screen shot 2019-01-03 at 13 29 46

### The problem is caused by `electron-storage` package which requires `remote` in order to run (which we prevent by setting `enableRemoteModule: false` for non-test environments) :
screen shot 2019-01-03 at 14 18 54

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei I will need your help regarding this one 🙏

**Comment by nikolaglumac** [comment]
> @nikolaglumac does this only happen on electron 4?

@DominikGuzei interestingly, it is not happening on Electron 3 😱

**Comment by DominikGuzei** [comment]
@nikolaglumac yeah i think they improved the security in electron 4 and now `enableRemoteModule: false` really, really disables it (also in preload.js) … i read somewhere about incidents about the `remote` module leaking into the global scope when it was exposed in the wrong way inside `preload.js` … and to be honest i think it's a good thing anyway to completely remove the direct / indirect access to `remote` and move all that logic to the main process.

**Comment by nikolaglumac** [comment]
@DominikGuzei I have now downgraded Electron to `3.0.13` and the issue is gone which means you are right - Electron 4 improved security is the culprit.

A preferred solution for this problem would be as you said - removal of access to `remote` from the rendering process. Unfortunately, it looks like Electron 4 build fails both on Windows and Linux (even with my fix from this PR). Thus, I will push an update with the downgrade to Electron 3.0.13 and revert of the `enableRemoteModule` change.
The original reason why we have upgraded to Electron 4 was because of acceptance test issues.
These issues are fixed by upgrading `electron-chromedriver` to v4 which enables us to use Electron 3 🎉

**Pull request merged**
