### PR TITLE
[DO NOT MERGE] Csl 1071/addr conversion

### PR DESCRIPTION
**Pull request by gromakovsky**
It's only needed to produce an installer.

### CODE REVIEW

**Comment by domenkozar** [comment]
How is cardano-addr-convert invoked?

**Comment by gromakovsky** [comment]
`cardano-addr-convert VENDING_ADDRESS` or just `cardano-addr-convert` and then it will be interactive mode.

**Comment by domenkozar** [comment]
oh so through CLI?

**Comment by gromakovsky** [comment]
Yes, it's a simple command line utility and the whole point is that we don't want Jeremy to build it locally. Well, now I am thinking about it and probably it is not proper approach, I could just build it locally and send it to him… 🤦‍♂️

**Pull request closed without merging**
