### PR TITLE
[DAEF-255] add amount input skin with fees labels

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR adds the `AmountInputSkin` which is used to display transaction fees on the wallet send form. Fees are currently hardcoded into the wallet send form and need to be fetched from an endpoint when it's ready.

## TODOs:
- [x] fix BigNumber show-stopping error during total-amount/fees calculation
- [x] Add client side API endpoint with dummy return
- [x] Integrate with API endpoint for fees
```
"wallet.amountInput.feesLabel": "+ {amount} of fees" 
```

screenshot 2017-06-29 um 15 04 36

screenshot 2017-06-29 um 15 00 12

screenshot 2017-06-29 um 15 00 24

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@nikolaglumac that sounds very boring … but ok since you asked so kindly 😉

**Comment by darko-mijic** [comment]
We need that checklist ;)

**Comment by nikolaglumac** [comment]
@DominikGuzei sorry for nitpicking :(

**Comment by DominikGuzei** [comment]
@nikolaglumac i just figured that i didn't add translations for the `AmountInputSkin` … can you add them before merging? Im working on another project atm 😉

**Comment by nikolaglumac** [comment]
@DominikGuzei I will do it in the evening - I'm not near my computer at the moment ;)

**Comment by nikolaglumac** [comment]
@DominikGuzei I have added missing translation key:  https://github.com/input-output-hk/daedalus/pull/356/commits/06684b86b04e52d8a7a97c90fe32d0f896221df6

Unfortunately I have stumbled upon a major issue - on Send Form screen when you enter sending amount with more than 3 digits before the dot (e.g. 1,000.000000) a "big-red-screen" is presented:
error
Can you please take a look at this @DominikGuzei?
I have narrowed down the search to this line: https://github.com/input-output-hk/daedalus/blob/feature/daef-255-ui-for-transaction-fees/app/components/wallet/WalletSendForm.js#L187

@darko-mijic we will need one more Japanese translation. Please see TODO section in the PR's description. Thanks!

**Comment by DominikGuzei** [comment]
@nikolaglumac the bignumber bug is fixed now!
@darko-mijic should we merge this already or wait for Japanese translation?

**Comment by DominikGuzei** [comment]
@nikolaglumac this PR is ready for final review!
The real endpoint should be implemented this week and then we can add the integration with one-line PR as soon as this has happened!

**Comment by nikolaglumac** [comment]
@DominikGuzei looks great!
I've added just one small fix: https://github.com/input-output-hk/daedalus/pull/356/commits/59a95f7e30d89e420f12486730c642730782d494 (there were some BigNumber related errors if you enter an amount with 4+ digits before the dot)

We are only missing one Japanese translation:
```
"wallet.amountInput.feesLabel": "+ {amount} of fees" 
```
@darko-mijic can you please provide this ☝️  - thanks! :)

**Comment by darko-mijic** [comment]
Here is Japanese translation @nikolaglumac: 
`“wallet.amountInput.feesLabel”: “+ {amount}の手数料”`

**Comment by nikolaglumac** [comment]
Thanks @darko-mijic! I have injected it into translation file. All checks for this PR were green prior to that - can you merge it or do we need to wait for the CI?
@DominikGuzei cc

**Pull request merged**
