### PR TITLE
[DDW-508] Design implementation fixes

### PR DESCRIPTION
**Pull request by daniloprates**
This PR fixes the [following accepted](https://docs.google.com/document/d/1YU5R0rLIiacTREnCPOcsUlx_iqVmU2AUaJbnVHGgobg/edit) design issues.

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by daniloprates** [comment]
@a-rukin regarding:

image

They have actually the same padding. How should I change it?

padding

**Comment by a-rukin** [comment]
@daniloprates what are the sizes of these two paddings?

**Comment by a-rukin** [comment]
30px is only before the button, rest should be 20px 
reference: zpl.io/bl9zDG2

**Comment by a-rukin** [comment]
@daniloprates Pls check that distance between other "blocks" are 20px
Seems like it 30px before "Enter password" (on your screenshot)

**Comment by daniloprates** [comment]
@a-rukin yes, it's 30px. Changing to 20px, then.

**Comment by daniloprates** [comment]
image
@a-rukin not sure what to change.

**Comment by daniloprates** [comment]
@a-rukin regarding:

image

It looks fine on my screen. I've tried 2px but it's strange:

image

Maybe a bit more whity? This is how it looks with `border-color: #f8f8f9`:

image

**Comment by daniloprates** [comment]
@a-rukin @nikolaglumac I couldn't spot the bug. What is the issue?

image

**Comment by a-rukin** [comment]
> Maybe a bit more whity? This is how it looks with `border-color: #f8f8f9`:
> 
> image

I like this one! 👍

**Comment by a-rukin** [comment]
@daniloprates you requested review, what and where should I look?

**Comment by nikolaglumac** [comment]
@a-rukin OSX build is not ready yet.
@daniloprates please send the link to the installer once it the build is green.

**Comment by a-rukin** [comment]
I should check:
- paddings in dialogs (header and error)
- time screen link underline 
- dropdown arrow position
right?

**Comment by daniloprates** [comment]
Hey @a-rukin, do you have a Mac?

**Comment by nikolaglumac** [comment]
@daniloprates yes - @a-rukin has a Mac. Please send him the link to Daedalus Testnet installer for Mac 🙏

**Comment by nikolaglumac** [comment]
@a-rukin you should check everything from the Google Doc you provided originally...

**Comment by a-rukin** [comment]
Okay, that's good!

**Comment by daniloprates** [comment]
@a-rukin: https://buildkite.com/organizations/input-output-hk/pipelines/daedalus/builds/3721/jobs/45b08023-cd5a-431c-9d85-41a4afd41b7f/artifacts/b3ec3ed9-e226-4972-8b56-182daded4d62

**Comment by a-rukin** [comment]
image
seems like here was used semi-bold font, instead of regular (https://zpl.io/2vW3AKP)

**Comment by daniloprates** [comment]
image
It's already using the regular one. 

About the bg color, it's using `#fafbfc`. I'll change it to `#243E62`

**Comment by a-rukin** [comment]
wow, that's strange, looks too bold, may be worth trying thin then? What do you think?

**Comment by daniloprates** [comment]
I like it. Font light.

image

**Comment by a-rukin** [comment]
yeah, much better! 👍

**Comment by daniloprates** [comment]
@a-rukin should I keep the title regular?

**Comment by a-rukin** [comment]
> @a-rukin should I keep the title regular?

last screenshot is fine! Keep it

**Comment by nikolaglumac** [comment]
@a-rukin please let us know once you check all the fixes 🙏

**Pull request merged**
