### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by KimUJeon**
Maybe Now it's clear to see.
Can I translate terms of use?

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
Hey again.
It may be helpful for you to read this blog: http://nvie.com/posts/a-successful-git-branching-model/
This repository (loosely) follows this model for development therefore you shouldn't try and merge directly to Master
You may also be interested in issue #714 where @darko-mijic talks about the translation process. You may want to talk with him about the best way to integrate this into the project.
Thank you for all your work 👍

**Comment by KimUJeon** [comment]
@SebastienGllmt Then should I edit my pull?
That's a little bit hard to me :(

**Comment by SebastienGllmt** [comment]
@KimUJeon You can probably just press the "Edit" button on this page and change the base from "Master" to "Develop". Although as I mentioned, I'm not sure if this will be accepted until the translation guidelines are released.

**Comment by nikolaglumac** [comment]
Thank you for your contribution! Unfortunately, at this moment in time, we can not accept this translation as it would be hard to maintain it without internal translation/audit process.

**Pull request closed without merging**
