### PR TITLE
[DDW-580] Improve transactions history CSV export

### PR DESCRIPTION
**Pull request by daniloprates**
This PR improves the transactions history CSV content, by separating the Amount currency in a different column and adding Fee and Native tokens columns.

## Todos

**Transactions**

- [x] Remove the amount currency and add it to the table header
- [x] Add the Fee column
- [x] Add the Native tokens column
- [x] Add the Deposit column
- [x] New columns translation
- [x] ISO Extended timestamp format

**Rewards**
- [x] Remove the reward currency and add it to the table header
   - [x] In the CSV content
   - [x] In the Rewards screen table (still to be confirmed by @darko-mijic @nikolaglumac @alexander-rukin)
- [x] Change the button from `primary` to `flat` (secondary)
- [x] ISO Extended timestamp format

---
- Related issues:  #2394 & #2170
- [JIRA](https://jira.iohk.io/browse/DDW-580)
- [QA thread](https://github.com/input-output-hk/daedalus/pull/2451)

### Transactions

**EN**

T EN

**JP**

T JP
### Rewards

**EN**

R EN

**JP**

R JP

## Testing Checklist

- [ ] Test

---
## Test Scenarios

**Scenario 1 - Validate that fees are included in outgoing transactions on CSV file**
```Gherkin
Given that I have a wallet with outgoing transactions
When I access to the “Transactions” tab 
And export the CSV file with the transaction history
And I validate the information on the file
Then I can see on the outgoing transactions the fees are displayed on a separate column
And the data matches the corresponding transactions in Daedalus
```
**Scenario 2 - Validate currency is displayed separately from the amount**
```Gherkin
Given that I have a wallet with transaction history
When I access to the “Transactions” tab 
And export the CSV file with the transaction history
And I validate the information on the file
Then I can see the currency is displayed only on the header
And the data matches the corresponding transactions in Daedalus
```
**Scenario 3 - Validate Native Tokens are displayed** 
```Gherkin
Given that I have a wallet with transaction history
And these transactions include Native Tokens
When I access to the “Transactions” tab 
And export the CSV file with the transaction history
And I validate the information on the file
Then I can see the Tokens are displayed on a independent column
And the data matches the corresponding transactions in Daedalus
```

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by ManusMcCole — APPROVED** [review]
Looks good @daniloprates 👍

**Review by gabriela-ponce — APPROVED** [review]
Great job, looks good to me on build 17131 👍

**Review by nikolaglumac — COMMENTED** [review]
@daniloprates would like to keep the "ADA" in the Rewards column (only on the screen).
Also, I think we should consider using positive numbers even for outgoing transactions in the CSV file? Or perhaps make the fees negative value? @darko-mijic help us out here 🙏 

111164212-9c522480-857c-11eb-8ef0-d421519ea7f7

**Comment by darko-mijic** [comment]
We need consistency and logic here. @daniloprates, can you check formats used by https://www.cointracker.io/ and similar services?

**Comment by daniloprates** [comment]
@darko-mijic @nikolaglumac [Coinbase](https://user-images.githubusercontent.com/1504716/111489330-ca6c6b80-8718-11eb-8b1c-93577cecec00.jpg) shows + and -, while [Binance](https://user-images.githubusercontent.com/1504716/111489323-c8a2a800-8718-11eb-8158-2ec1762812b9.png) doesn't. I don't have a Cointracker account and couldn't find a screen for that.

I don't see a problem in having fees in positive and sent tx in negative. It'd the best setup for me in a spreadsheet. Or at least fees in negative, but all tx amounts in negative would make things harder to manipulate.

**Comment by daniloprates** [comment]
> @daniloprates would like to keep the "ADA" in the Rewards column (only on the screen).

@nikolaglumac do you mean keep in the values (1.000000 ADA), as it is now?

**Comment by nikolaglumac** [comment]
> > @daniloprates would like to keep the "ADA" in the Rewards column (only on the screen).
> 
> @nikolaglumac do you mean keep in the values (1.000000 ADA), as it is now?

Yes please 🙏 
I think that is what @darko-mijic wanted too.

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Great work @daniloprates . 👍  Tested on 17161

**Review by gabriela-ponce — APPROVED** [review]
Looks good

**Comment by nikolaglumac** [comment]
@tomislavhoracek please review this PR 🙏

**Review by tomislavhoracek — COMMENTED** [review]
@daniloprates Great 🎉 
Please add CHANGELOG entry

**Comment by daniloprates** [comment]
> @daniloprates Great 🎉
> Please add CHANGELOG entry

@tomislavhoracek thanks for the heads up. Done ✅

**Review by tomislavhoracek — APPROVED** [review]
@daniloprates 💯

**Comment by nikolaglumac** [comment]
@daniloprates what about the dates? Did you take the suggestions from this comment https://github.com/input-output-hk/daedalus/issues/2394#issuecomment-783723047 into account?

I can still see we display the date/time as: 
Screenshot 2021-03-22 at 18 13 00

cc @darko-mijic

**Comment by daniloprates** [comment]
> @daniloprates what about the dates? Did you take the suggestions from this comment [#2394 (comment)](https://github.com/input-output-hk/daedalus/issues/2394#issuecomment-783723047) into account?
> 
> I can still see we display the date/time as:
> Screenshot 2021-03-22 at 18 13 00
> 
> cc @darko-mijic

Missed it! Now [done](https://github.com/input-output-hk/daedalus/pull/2451/commits/33ff9140a42ab48e018616ce61015b45bd1a16b4)

**Review by nikolaglumac — APPROVED** [review]
Nice work @daniloprates! I like how you improved the assets filtering 👌

**Pull request merged**
