### PR TITLE
[DEVOPS-398] installers: Add config for public testnet

### PR DESCRIPTION
**Pull request by rvl**
Configures the testnet installer so that the wallet can connect to the public testnet.

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@rvl this one should not be merged right?

**Comment by rvl** [comment]
It should be merged, but I just realised that this will be dependent on first merging input-output-hk/cardano-sl#3090.

**Comment by rvl** [comment]
Cardano is fixed now. This is ready to go.

**Comment by nikolaglumac** [comment]
Thanks @rvl! Before we merge it I would like to get one approval from your team members ;)

**Comment by rvl** [comment]
Yes thanks, quite right, I forgot to add the devops team onto reviewers.

**Comment by rvl** [comment]
OK fixed that, and rebased on latest develop.

**Comment by nikolaglumac** [comment]
@rvl we will need to port over this to ([release/0.11.1](https://github.com/input-output-hk/daedalus/tree/release/0.11.1)) branch...

**Comment by rvl** [comment]
OK here is the PR for release/0.11.1: #991

**Pull request merged**
