### PR TITLE
Chore/DAEF-496 Ada redemption tests in mainnnet mode

### PR DESCRIPTION
**Pull request by darko-mijic**
This PR modifies Ada redemption tests to run in `mainnet` mode, where Ada redemption warning is not shown.

All tests are now green when ran with `NETWORK=mainnet npm run test`

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@darko-mijic this PR is ready to be merged. I did not do it myself as I was not sure if we are allowed to do so ;)

**Comment by darko-mijic** [comment]
Thanks @nikolaglumac. We will merge this on Monday since it is not urgent and we are publishing a release over the weekend.

**Comment by DominikGuzei** [comment]
@darko-mijic what's the status on this PR? can be merged?

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei I'm closing this PR in favour of: https://github.com/input-output-hk/daedalus/pull/681

**Pull request closed without merging**
