### PR TITLE
[AR release] Update state directories and add new icon

### PR DESCRIPTION
**Pull request by disassembler**
This PR updates state dir on all OS's for all clusters and adds a AR icon for all 3 networks (Mainnet, Staging and Testnet).

## Screenshots

icon

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by alan-mcnicholas** [comment]
Windows and MacOS are working correctly with separate state directories and associated processes. Linux in installing the artifacts into the MainNet directory however and no additional icon is seen, see attached installation output.
[Installer output.txt](https://github.com/input-output-hk/daedalus/files/3878854/Installer.output.txt)

**Comment by nikolaglumac** [comment]
@disassembler can you please check comment @alan-mcnicholas posted? https://github.com/input-output-hk/daedalus/pull/1711#issuecomment-557462905

**Comment by nikolaglumac** [comment]
> @disassembler can you please check comment @alan-mcnicholas posted? #1711 (comment)

@disassembler @cleverca22 ping ☝️ 

cc @alan-mcnicholas @darko-mijic

**Comment by nikolaglumac** [comment]
@alan-mcnicholas @DmitriiGaico this one is ready for testing!

**Comment by alan-mcnicholas** [comment]
This is still an issue on Linux using the same builds; the installer is still using the standard MainNet paths. See attached 
log for more details.

[AR_Install.log](https://github.com/input-output-hk/daedalus/files/4116514/AR_Install.log)

**Comment by alan-mcnicholas** [comment]
This is still broken on daedalus-0.14.AR-cardano-sl-3.0.3-mainnet-x86_64-linux-10458.bin; the AR icon is indeed installed however it seems to replace the icon for MainNet Deadalus. 
[AR_10458_installer.log](https://github.com/input-output-hk/daedalus/files/4147986/AR_10458_installer.log)

**Comment by nikolaglumac** [comment]
@alan-mcnicholas can you please re-test the latest build from this PR? I belive the issues were fixed 🙏

**Comment by alan-mcnicholas** [comment]
I can launch both MainNet and AR individually and their corresponding icons are correct in the sidebar however there is a known issue that the Daedalus AR application is not marked as active in the launcher. Considering this is not something that recommended for continuous use this is a very minor cosmetic issue.

**Pull request merged**
