### PR TITLE
Feature/daef 300 exporting wallet to file

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR adds the "export to file" feature on wallet settings, which currently doesn't work correctly on the backend (it exports all wallets) but is mostly done on the frontend. I think we should wait with implementing acceptance tests for the feature until we have a working backend. If the wallet has a spending password it is also asked for but currently not passed to the backend since that's not supported yet.

wallet-export-to-file-feature

Apart from the feature, the following smaller fixes and improvements have been made:
- Made storybook work with happypack (performance improvements)
- Added global translations for spending password (but not yet fully refactored all other usages!)
- Moved the export dialogs etc. into dedicated folders and simplified their structure.
- Improved flow typing within the component / api / action, which can be used as a guideline for refactorings and future features.

**TODO:**
- [x] Checkout / fix storybook problem that nikola had
- [ ] Add missing Japanese translations
```
global.spendingPasswordLabel: !!!Spending Password
global.spendingPasswordPlaceholder: !!!Password
wallet.exportToFile.dialog.headline: !!!Export Wallet
wallet.exportToFile.dialog.introduction: !!!You are exporting <strong>{walletName}</strong> to a file.
wallet.exportToFile.dialog.submit.label: !!!Export
```

### CODE REVIEW

**Comment by darko-mijic** [comment]
> Why have you removed paper-wallet-export-dialog? Is this export-to-file a replacement for the paper one?
No. We need paper wallets but we are still waiting for the endpoint.

**Comment by DominikGuzei** [comment]
@nikolaglumac thanks for reviewing, im re-installing my npm deps to see if i can reproduce your storybook problem!

**Comment by DominikGuzei** [comment]
@nikolaglumac  @darko-mijic i think we don't need to bring back the `WalletExportDialog` in my PR because this dialog was just the "main entry point" for exports in general … since we don't expose paper wallet exports yet we don't need to show that option in the ui. All the specific paper wallet dialogs are still available in the sub-folder `paper-wallet-export-dialogs`

**Comment by DominikGuzei** [comment]
@nikolaglumac i found the issue with broken storybook (im referencing `electron` in the export dialog container to open the dialog via `remote`, but that import fails in storybook because it's not a electron-renderer environment), trying to fix this now …

**Comment by DominikGuzei** [comment]
@nikolaglumac all issues apart from translations are fixed now!

**Comment by nikolaglumac** [comment]
Great @DominikGuzei - will review again in the evening ;)

**Comment by nikolaglumac** [comment]
@DominikGuzei I have checked your update and fixed some minor theming/styling issues on Settings screen as well as loading inline-svgs in storybook.
I still have issues running storybook :(
Staking components that we don't use in the app are to blame:
screen shot 2017-08-22 at 19 03 15
BUT even if I comment them out from storybook config storybook looks broken - I think it is related to our theming setup - looks like css-variables are not loaded at all.
If you want we can check it out together tomorrow?

**Comment by DominikGuzei** [comment]
@nikolaglumac i have fixed the remaining issues with storybook!

**Pull request merged**
