### PR TITLE
[DDW-534] Fix Ledger TXs to Byron addresses

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces a fix for Ledger TXs to the Byron address.

[JIRA](https://jira.iohk.io/browse/DDW-534)

---

### TODO
- [ ] Remove debugging logs

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1610453612143400)
- [ ] Try to send ADA from Shelley wallet (Hardware Wallet - Ledger ) to Byron address on MAINNET
- [ ] Try to send ADA from Shelley wallet (Hardware Wallet - Ledger ) to Byron address on TESTNET

---

## Test cases

**Scenario 1: Send ADA from Ledger Nano S to Byron wallet**
_(Regression template: row 32)_

```Gherkin
Given a Ledger Nano S wallet is added to Daedalus
And a Byron wallet is added to Daedalus
And both wallets are synced
And the Ledger Nano S wallet balance is >=2
When I access the "Send" screen for the Shelley wallet
And I paste an address from the Byron wallet on the "Receiver" input
And I insert a valid amount on the "Amount" input
And I click on "Next"
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the transaction is performed
And the transaction can be visible on both wallets
```

**Scenario 2: Send ADA from Ledger Nano X to Byron wallet**
_(Regression template: row 33)_

```Gherkin
Given a Ledger Nano x wallet is added to Daedalus
And a Byron wallet is added to Daedalus
And both wallets are synced
And the Ledger Nano X wallet balance is >=2
When I access the "Send" screen for the Shelley wallet
And I paste an address from the Byron wallet on the "Receiver" input
And I insert a valid amount on the "Amount" input
And I click on "Next"
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the transaction is performed
```
---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@tomothespian please add CHANGELOG entry 🙏

**Comment by tomothespian** [comment]
> @tomothespian please add CHANGELOG entry 🙏

@nikolaglumac  Aah, sorry.
Done

**Comment by gnpf** [comment]
@tomothespian I tested this on **Ledger Nano S**, on Linux and macOS (Windows is still pending). These are the results so far for that device:

Test case | Status | Comments
-- | -- | --
Scenario 1 | Failed | In most of the iterations, the transaction is performed successfully. However, in some ocassions, **[this error](https://drive.google.com/file/d/1x3GPmObbMdTbS74p4DSPv2x6qBXFMJsC/view?usp=sharing)** is displayed after clicking on "Send". Usually happens if the device was plugged and unlocked before trying to submit the transaction, but it doesn't reproduce all the time. I tried to reproduce this on **3.1.0** (with Shelley addresses) and it doesn't happen.

Check the evidence for all the iterations on [Mainnet](https://drive.google.com/drive/folders/1DnqyLt-s9ywOrGJxfxFGUjZ45B84_dNT?usp=sharing) and [Testnet](https://drive.google.com/drive/folders/1ajhUTtH4L6iCYRXb-WknIkiB27CmfJbP?usp=sharing) (on Linux).

**Comment by nikolaglumac** [comment]
> @tomothespian I tested this on **Ledger Nano S**, on Linux and macOS (Windows is still pending). These are the results so far for that device:
> 
> Test case	Status	Comments
> Scenario 1	Failed	In most of the iterations, the transaction is performed successfully. However, in some ocassions, **[this error](https://drive.google.com/file/d/1x3GPmObbMdTbS74p4DSPv2x6qBXFMJsC/view?usp=sharing)** is displayed after clicking on "Send". Usually happens if the device was plugged and unlocked before trying to submit the transaction, but it doesn't reproduce all the time. I tried to reproduce this on **3.1.0** (with Shelley addresses) and it doesn't happen.
> Check the evidence for all the iterations on [Mainnet](https://drive.google.com/drive/folders/1DnqyLt-s9ywOrGJxfxFGUjZ45B84_dNT?usp=sharing) and [Testnet](https://drive.google.com/drive/folders/1ajhUTtH4L6iCYRXb-WknIkiB27CmfJbP?usp=sharing) (on Linux).

@tomothespian looks like an issue with witnesses?

**Comment by tomothespian** [comment]
@gnpf thanks.
@nikolaglumac I tried multiple times and didn't get that error :( 
Also what I can see is that there is a UTXO failure - `OutputTooSmallUTxO`
I will prepare a few logs so we can see all inputs and outputs from coins selection as well as serialized body to better understand what caused those failures . Maybe also Matthias can help us.

**Comment by tomothespian** [comment]
@gnpf Logs added to code
Please follow instructions and provide results to us. Thx
https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1610482267146900?thread_ts=1610453612.143400&cid=GGKFXSKC6

**Comment by mioriohk** [comment]
@tomothespian  Tested on Ledger Nano X for build 15847. Working as expected on Mac/Linux/Windows on both Mainnet and Testnet. 👍

**Comment by nikolaglumac** [comment]
@tomothespian I have added "DO NOT MERGE" label so that we don't forget to remove logging!

**Review by gnpf — APPROVED** [review]
Works great 🎉

**Review by nikolaglumac — APPROVED** [review]
Great fix @tomothespian 💯

**Pull request merged**
