### PR TITLE
[DDW-369] Implement copy CSS variables

### PR DESCRIPTION
**Pull request by daniloprates**
This PR introduces a tool that allows for developers to quickly copy properties from an element into another in all theme files.

## Screenshots

Screen Shot 2020-11-11 at 18 23 32
Screen Shot 2020-11-11 at 18 25 36

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- No QA needed

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates I would like you to have a discussion about this one with @DominikGuzei 🙏

**Comment by daniloprates** [comment]
> @daniloprates I would like you to have a discussion about this one with @DominikGuzei 🙏

Let's do it :)

**Comment by DominikGuzei** [comment]
@nikolaglumac Danilo and I discussed this task and both think it's useful 👍 I haven't tested the PR yet but did you want us to discuss anything else?

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
Great work @daniloprates 🎉 

There are some flow and lint errors I hope you can fix 🙏 
Also, can you please add CHANGELOG entry and update the Theming Readme: https://github.com/input-output-hk/daedalus/blob/develop/source/renderer/app/themes/README.md with info about your script? Also, it would be awesome if you can review existing content of that file... 

Thanks!

**Comment by daniloprates** [comment]
> Great work @daniloprates 🎉
> 
> There are some flow and lint errors I hope you can fix 🙏
> Also, can you please add CHANGELOG entry and update the Theming Readme: https://github.com/input-output-hk/daedalus/blob/develop/source/renderer/app/themes/README.md with info about your script? Also, it would be awesome if you can review existing content of that file...
> 
> Thanks!

@nikolaglumac done. I didn't change the rest of the README content because it's just linking to the YT tutorials.

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@daniloprates thanks for fixing the issues! 
Please fix these remaining 2 lint issues and then we are ready to merge this PR!
Screenshot 2020-11-12 at 22 26 03

**Comment by daniloprates** [comment]
> @daniloprates thanks for fixing the issues!
> Please fix these remaining 2 lint issues and then we are ready to merge this PR!

image
It won't push itself 🤦🏻‍♂️

**Review by nikolaglumac — APPROVED** [review]
Great work @daniloprates 💯

**Pull request merged**
