### PR TITLE
Forward port 0.3 changes

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@domenkozar can you add a bit of explanation what i can/should test to verify your PR?

**Comment by domenkozar** [comment]
We should test that windows installer works correctly. These bugfixes were in 0.2/0.3 but are not in master yet.

**Comment by DominikGuzei** [comment]
Ok I will boot up my windows VM and try it … btw. where can i get the latest builds?

**Comment by domenkozar** [comment]
Show all checks -> pick `appveyor/branch` then `Artifacts` tab

**Comment by domenkozar** [comment]
Without this change, Windows installer just can't work :)

**Comment by DominikGuzei** [comment]
Ok sorry for the delay … i just figured i cannot test windows because my Vm ware does not work anymore since i upgraded to el capitan …

**Comment by darko-mijic** [comment]
@domenkozar: I can not find a build in AppVeyor. I don't have Show all checks option. I have clicked show more until I loaded all of available history and I could not find the build that I need to verify this.

**Comment by domenkozar** [comment]
2017-03-27-170918_862x321_scrot

There should be "Show all checks" and then you can click on appveyor build:

2017-03-27-171012_877x434_scrot
Once appveyor opens (it takes a while to load), go to artifacts tab.

**Comment by darko-mijic** [comment]
Thanks @domenkozar. I have installed it but desktop icon installer created did not work. Here is the target from the icon: `"C:\Program Files\Daedalus\cardano-launcher.exe" --node "%PROGRAMFILES%\Daedalus\cardano-node.exe" --node-log-path "%APPDATA%\Daedalus\Logs\cardano-node.log" --wallet "%PROGRAMFILES%\Daedalus\Daedalus.exe" --updater  "%APPDATA%\Daedalus\Installer.exe" --node-`

screen shot 2017-03-27 at 18 28 02

**Comment by domenkozar** [comment]
@neongreen does launcher now require the updater to exist unconditionally?

**Comment by neongreen** [comment]
```
    unlessM (testfile path) $ do
        echo "Running the updater"
        let args' = args ++ maybe [] (one . toText) updateArchive
        exitCode <- proc (toText path) args' mempty
        printf ("The updater has exited with "%s%"\n") (show exitCode)
        when (exitCode == ExitSuccess) $ do
            -- this will throw an exception if the file doesn't exist but
            -- hopefully if the updater has succeeded it *does* exist
            whenJust updateArchive rm
```

Seems to be a bug. Unfortunately, git blame didn't tell me who introduced it.

**Comment by neongreen** [comment]
(And thus I'm not sure it's actually a bug.)

**Comment by neongreen** [comment]
Okay, looks like it was introduced as a part of the HLint pull-request: https://github.com/input-output-hk/cardano-sl/pull/128/files#diff-9bc0ce73245ad9dfcba632fe7450ad0cR215

What would be the best way to fix it? Change `unlessM` to `whenM` in master and cherry-pick to this branch? Or to the 0.3 branch as well?

**Comment by domenkozar** [comment]
Best to cherry-pick to all branches that have this bug including this PR so we can test it again.

**Comment by domenkozar** [comment]
@neongreen was it fixed?

**Comment by domenkozar** [comment]
FYI @darko-mijic @DominikGuzei this is also why macOS installer doesn't work:

```
DE339:~ admin$ DISPLAY=:0.0 /Applications/Daedalus.app/Contents/MacOS/Daedalus
Running in the client scenario
Running the updater
cardano-launcher: /Users/admin/Library/Application Support/Daedalus/installer.pkg: createProcess: runInteractiveProcess: exec: invalid argument (Bad file descriptor)
```

**Comment by neongreen** [comment]
@domenkozar I'm sorry, I haven't noticed your “Best to cherry-pick to all branches that have this bug including this PR so we can test it again.” message. I will fix it today and ping you.

**Comment by domenkozar** [comment]
Waiting on https://ci.appveyor.com/project/jagajaga/cardano-sl/build/0.2.3512 and then I can rebase

**Comment by domenkozar** [comment]
Blocked on a failing cardano-sl test.

**Comment by domenkozar** [comment]
@darko-mijic can you test again?

**Comment by domenkozar** [comment]
Now I get following, is this fixed in master? @DominikGuzei @darko-mijic 
2017-04-02-141748_582x442_scrot

**Comment by domenkozar** [comment]
@DominikGuzei will fix that, I'll just merge this PR as without it the packaging for Windows isn't complete anyway.

**Pull request merged**
