### PR TITLE
Fix/daef 439 QR code changes for dark themes

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR introduces improvements for QR code colors on Wallet Receive screen.

### Default theme
screen shot 2017-08-29 at 09 24 30

### Dark theme
screen shot 2017-08-29 at 09 24 19

### CODE REVIEW

**Comment by darko-mijic** [comment]
@a-rukin: Is this looking OK?

**Comment by a-rukin** [comment]
@darko-mijic yes, but there is one important note in QRs. There should be white border around it, because some of the readers won't be able to scan it

**Comment by nikolaglumac** [comment]
@darko-mijic @a-rukin here you go ;)

**Comment by a-rukin** [comment]
OK

**Comment by a-rukin** [comment]
Actually, we don't need this icon screen shot 2017-08-29 at 14 04 47

**Comment by nikolaglumac** [comment]
@a-rukin icon removed!

screen shot 2017-08-29 at 13 11 23

**Comment by a-rukin** [comment]
cool 👍

**Comment by darko-mijic** [comment]
Great. The last one is picked up by QR scanners instantly.

**Pull request merged**
