### PR TITLE
[DDW-161] Fix theming issues on the wallet import overlays

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR fixes UI issues on wallet import overlays

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1587452387461800)
- [ ] Test importing of wallets and compare with the design on all themes

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
image
inputs shouldn't have BG

**Comment by a-rukin** [comment]
image

4 in 1:
• icon should be dark 
• checkbox should be dark 
• "i" icon should be dark 
• triangle and tooltip body are in different color

**Comment by a-rukin** [comment]
image
Input field color is wrong + text should be disabled too

**Comment by a-rukin** [comment]
image
checkbox here should be #fafbfc

**Comment by a-rukin** [comment]
image
for the disabled state border color and bg color should be exactly the same, so you can see it as one object

**Comment by a-rukin** [comment]
image
for the yellow theme we use other red to use on top of yellow color #be0b0b

**Comment by a-rukin** [comment]
image
when name is entered (field not empty and valid atm) we don't need this tooltip anymore I think

**Comment by a-rukin** [comment]
image
and
image

for dark blue theme are white (#ffffff), but proper color is #e9f4fe

**Comment by a-rukin** [comment]
screencast 2020-04-21 13-01-54
checkbox is jumping 🤔

**Comment by DeeJayElly** [comment]
> screencast 2020-04-21 13-01-54
> checkbox is jumping 🤔

Fixed

**Comment by DeeJayElly** [comment]
> e9f4fe

fixed

**Comment by DeeJayElly** [comment]
imageand
image

for dark blue theme are white (#ffffff), but proper color is #e9f4fe



> image
> 
> and
> image
> 
> for dark blue theme are white (#ffffff), but proper color is #e9f4fe

Fixed

**Comment by DeeJayElly** [comment]
> image
> 
> inputs shouldn't have BG

fixed

**Comment by DeeJayElly** [comment]
> image
> 
> 4 in 1:
> • icon should be dark
> • checkbox should be dark
> • "i" icon should be dark
> • triangle and tooltip body are in different color

Fixed

**Comment by DeeJayElly** [comment]
> image
> 
> when name is entered (field not empty and valid atm) we don't need this tooltip anymore I think

Fixed

**Comment by DeeJayElly** [comment]
> image
> 
> 4 in 1:
> • icon should be dark
> • checkbox should be dark
> • "i" icon should be dark
> • triangle and tooltip body are in different color

Done

**Comment by DeeJayElly** [comment]
> image
> 
> for the disabled state border color and bg color should be exactly the same, so you can see it as one object

Fixed

**Comment by a-rukin** [comment]
image
seems like triangle doesn't have opacity

**Comment by a-rukin** [comment]
Fix colors introduced by @nikolaglumac for block of text (1st step)

**Comment by a-rukin** [comment]
image
A few months ago we've updated all checkboxes, radio buttons and switches to be a bit smaller and borders to be thicker. Here borders are still thin,

**Comment by gnpf** [comment]
@DeeJayElly This message is split on two lines in Japanese:

image

**Comment by a-rukin** [comment]
> @DeeJayElly This message is split on two lines in Japanese:
> 
> image

@DeeJayElly we agreed to reduce those padding to 20px (instead of 70+)

**Comment by DeeJayElly** [comment]
> image
> 
> seems like triangle doesn't have opacity

Fixed

**Comment by DeeJayElly** [comment]
> > @DeeJayElly This message is split on two lines in Japanese:
> > image
> 
> @DeeJayElly we agreed to reduce those padding to 20px (instead of 70+)

Fixed

**Pull request merged**
