### PR TITLE
[DDW-683] Refactor the Loading screen

### PR DESCRIPTION
**Pull request by daniloprates**
This PR refactors the Loading screen, adding containers for each overlay and splitting it into smaller components.

## Todos

- [x] Reorganize the files, so the Loading container loads the overlays containers
- [x] Break the Loading component into smaller components
- [x] Update storybook stories

### SyncingConnecting

image

image

image

### NoDiskSpaceError

image

### SystemTimeError

image

image

### ManualUpdate

image

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1562251075237900)
- [ ] [SyncingConnecting](https://deploy-preview-1446--daedalus-storybook.netlify.com/?selectedKind=Loading&selectedStory=SyncingConnecting&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs). This screen has a lot of props combinations, so it's better to test in the actual app.
- [ ] [NoDiskSpaceError](https://deploy-preview-1446--daedalus-storybook.netlify.com/?selectedKind=Loading&selectedStory=NoDiskSpaceError&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
- [ ] [SystemTimeError](https://deploy-preview-1446--daedalus-storybook.netlify.com/?selectedKind=Loading&selectedStory=SystemTimeError&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
- [ ] [ManualUpdate](https://deploy-preview-1446--daedalus-storybook.netlify.com/?selectedKind=Loading&selectedStory=ManualUpdate&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@daniloprates Looks good.

**Comment by nikolaglumac** [comment]
@a-rukin please ping me once you start today so that I can show you what I mean...

**Comment by nikolaglumac** [comment]
@tomothespian please review the code too 🙏

**Comment by a-rukin** [comment]
The main point of the transparent bg for all these overlays is to show that something you have been working with is still there and waiting for you. 
We (will) have only one overlay with no transparency - locking screen where we want to hide all sensitive data, so it's not an overlay actually, but a completely separate screen without anything underneath.

**Pull request merged**
