### PR TITLE
[DEVOPS-1219] Bump cardano-sl to latest release/2.0.1

### PR DESCRIPTION
**Pull request by rvl**
This is just an `applicationVersion` increment for testnet. This version will only be proposed on testnet. It contains a change for the linux platform so that it checks for updates correctly.

### CODE REVIEW

**Comment by deepfire** [comment]
cc @nikolaglumac

**Comment by nikolaglumac** [comment]
@rvl @deepfire we need to merge `release/0.12.1` into master after this PR has been merged right?

**Comment by disassembler** [comment]
yes @nikolaglumac

**Comment by nikolaglumac** [comment]
@disassembler please approve the following PR: https://github.com/input-output-hk/daedalus/pull/1290

**Comment by nikolaglumac** [comment]
@disassembler actually this will be the one we will be merging: https://github.com/input-output-hk/daedalus/pull/1291

**Pull request merged**
