### PR TITLE
[DDW-560] Red outlining in "Wallet Name" input 

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR fixed InlineEditingInput common component so that wallet name input works well
[Jira Ticket](https://jira.iohk.io/browse/DDW-560)

## Todos
- [x] Fix InlineEditingInput common component so that wallet name input works well

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1614339262035800)

### App
- [x] Go to `Wallet` => `Settings`, try to edit wallet name by using various characters and make sure it works well in any case

### English
image

### Japanese
image

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gabriela-ponce** [comment]
@yakovkaravelov I'm still able to reproduce this. It happens less often, but it usually appears when the whole name is updated.
No errors on the console. Check [this link](https://drive.google.com/drive/folders/1uS_vtwZdeapJnsQIH-sQj5B_ZS7-vLqT?usp=sharing) to see screenshots and a video for Windows and macOS.

**Comment by yakovkaravelov** [comment]
@tomislavhoracek @gabriela-ponce @miorsufianiohk @ManusMcCole Please review/test this, thanks.

**Review by gabriela-ponce — APPROVED** [review]
Works as expected, nice job 🚀

**Review by tomislavhoracek — APPROVED** [review]

**Review by miorsufianiohk — APPROVED** [review]
LGTM 👍 . Tested on 16837. Good work @yakovkaravelov

**Review by nikolaglumac — APPROVED** [review]

**Pull request merged**
