### PR TITLE
[DDW-1002] Implement Incentivized Testnet Daedalus Theme

### PR DESCRIPTION
**Pull request by MarcusHurney**
This PR implements the `incentivized-testnet` theme as well as:
- Disables theme selection in "Incentivized Testnet" Daedalus version
- Defaults to "Incentivized Testnet" theme
- Removes "Display Settings" item in the "Settings" screen menu

## Screenshots

Screenshot 2019-10-30 at 15 32 16

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1572383441264400)

---

### Basics

- [x] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn flow:test`)
- [x] There are no *lint* errors or warnings (`yarn lint`)
- [x] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [x] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [x] Important parts of the code are properly commented and documented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-renderings
- [x] Any code that only works in main process is neatly separated from components

### Testing
- [x] New feature/change is covered by acceptance tests
- [x] New feature/change is manually tested and approved by QA team
- [x] All existing acceptance tests are still up-to-date
- [x] New feature/change is covered by Daedalus Testing scenario
- [x] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
No plans to add this theme to storybook?

**Comment by nikolaglumac** [comment]
@SebastienGllmt it will be added. No worries!

cc @MarcusHurney

**Comment by a-rukin** [comment]
image

for "dark-cardano" and "ITN" themes let's switch this spinner color on button to a text color

**Comment by a-rukin** [comment]
https://zpl.io/b6B0oYN checkboxes and radio buttons should have dark instead of white 

image

**Comment by a-rukin** [comment]
May be it's an old branch fork, but this issue with paddings again here: 

image

**Comment by DmitriiGaico** [comment]
@MarcusHurney Hello Marcus. Could you please update PR description with details about which screens were already implemented. Comparing to Zeplin info in Story Book we are missing a lot of screen so it might be the case all of those missing screens are just not Ready yet.
Thank you in advance.

**Comment by nikolaglumac** [comment]
@DmitriiGaico only **existing** screens are styled. No new screens need to be added in the scope of this PR. Please list what are your concerns.

**Comment by DmitriiGaico** [comment]
@MarcusHurney @nikolaglumac 
Please see below :
Having Trouble Connecting to Network screen in Zeplin
image

Same screen in StoryBook
image

It's not the same at all.

**Comment by nikolaglumac** [comment]
@DmitriiGaico only background should be fixed. Other changes will be implemented in a separate task.

**Comment by a-rukin** [comment]
https://zpl.io/b6B0oYN

image

Here are styles for the warning button to avoid confusion with original red buttons (with white text) and theme-specific buttons (dark text)

**Comment by MarcusHurney** [comment]
@DmitriiGaico I've corrected the background color of the syncing and connecting screens to match the Zeplin mockup as you pointed out.

@nikolaglumac  @a-rukin The export wallet screen doesn't actually exist in the app so there is no need to worry about the colors there. The spinner on all the other buttons is the same color as the button text. I've also changed the warning buttons to the orange color, along with the warning check boxes. Unfortunately we do not use the terminology "warning" in the code itself, so I don't actually know which buttons are considered warning buttons. I've just made my best guess here.

There is however an issue with changing the checkmark color. We do not have a CSS variable implemented in react-polymorph for the checkmark color, therefore it can't be overwritten in our theme files. In order to change the checkmark color from white (as it currently is) to the dark blue text color in the mockups, I would need to implement the variable in react-polymorph, then install it in this PR, and overwrite the new color variable. This will change the checkmark color. Yes or no?

**Comment by nikolaglumac** [comment]
@a-rukin can you assist us here? Please check if @MarcusHurney updated the correct warning buttons and didn't leave out some of them.
@MarcusHurney in general "warning" buttons are the ones displayed in red background color in other themes - e.g. the light-blue one.

I believe we can go without having the right checkmark color BUT I believe we can probably modify those even without updating the React polymorph. I will check if this is doable today.

**Comment by a-rukin** [comment]
Button for the "delete wallet" dialog is updated 👍 
Checkbox background updated also, but check-marks √ are white. If it's a tough issue to fix, we probably can live with this. This decision is up to @nikolaglumac then. 

> in general "warning" buttons are the ones displayed in red background color in other themes - e.g. the light-blue one.

And how do we call these "delete wallet" buttons or when we try to cancel something?

**Comment by nikolaglumac** [comment]
@MarcusHurney @a-rukin the checkbox icon color has been fixed: https://github.com/input-output-hk/daedalus/pull/1620/commits/74420428b45f61625e4114b4cd4cbced889b2bd3
Currently, I have overridden the color but we will fix this properly in within React-Polymorph in the scope of this task: https://iohk.myjetbrains.com/youtrack/issue/DDW-1031
cc @DominikGuzei

**Pull request merged**
