### PR TITLE
[DDW-557] Update cardano-wallet

### PR DESCRIPTION
**Pull request by disassembler**
This PR updates the `cardano-wallet` to `2021-01-28` pre-release that supports Mary hard fork and node `1.25.1`.

## Todos

- [x] Disable Byron wallet migration feature as the Api for that feature has temporarily been disabled:
Screenshot 2021-01-29 at 09 48 24
- [x] Update the Api integration to match the Api breaking changes: https://gist.github.com/KtorZ/58833c0214e1896bd90f554730cd6808#api-changes (including: https://github.com/input-output-hk/cardano-wallet/pull/2468)
- [x] Update cardano-node version display value: https://github.com/input-output-hk/daedalus/blob/develop/source/main/environment.js#L63
- [x] Update cardano-wallet tag value: https://github.com/input-output-hk/daedalus/blob/wallet-mary/nix/sources.json#L37

## Known issues on the 2021-01-28 pre-release (so far):

- https://jira.iohk.io/browse/ADP-678 (Delegation fee response's estimated_max/min includes deposit but shouldn't)
- https://jira.iohk.io/browse/ADP-679 ("Something went wrong" on delegation fee request while wallet and node are syncing through Byron era)

## Screenshots

Screenshot 2021-01-29 at 16 04 52
Screenshot 2021-01-29 at 16 05 01

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Full regression test: [Regression document](https://docs.google.com/spreadsheets/d/1UONhBYhYKCRnIW27QTVrEmEmfpmmt2RJ7eGBRQ4Uh9w/edit?usp=sharing)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
- The "Name" input in "Wallets settings" now has the x, > and pencil buttons that were used on the "Custom server" input for the SMASH server PR. It's not too critic, but they functionality is inconsistent. [Slack thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611944676102000?thread_ts=1611933171.089400&cid=GGKFXSKC6).
- The SMASH server by default in Staging should be `https://smash.staging.cardano.org/`. Instead it displays  `https://smash.awstest.iohkdev.io/`. [Slack thread.](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611945831102600?thread_ts=1611933171.089400&cid=GGKFXSKC6)
- Redeem ITN rewards is not working on both platforms. [Slack thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611947037102900?thread_ts=1611933171.089400&cid=GGKFXSKC6).
- Fee calculation seems off, sometimes the error "No enough ADA for fees" is displayed on the confirmation dialog after trying to submit a transaction (even when there is enough ADA). [Slack thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611956728105000?thread_ts=1611933171.089400&cid=GGKFXSKC6).

**Comment by nikolaglumac** [comment]
> Issues on 16148
> 
> * The "Name" input in "Wallets settings" now has the x, > and pencil buttons that were used on the "Custom server" input for the SMASH server PR. It's not too critic, but they functionality is inconsistent. [Slack thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611944676102000?thread_ts=1611933171.089400&cid=GGKFXSKC6).

@gnpf this is not an issue. It was implemented this way. The "x" button is not a "Clear input" but a "Revert to previously saved value" action. The behavior  is the same on SMASH URL configuration and the wallet settings name input field.
If you save a custom SMASH URL and then try to use that button you will see the value being reset to the last saved one.
If you feel this to be wrong, please raise this issue for discussion on our next **Daedalus UI/UX Design** call with the rest of the team.
cc @darko-mijic @daniloprates @a-rukin 

> * The SMASH server by default in Staging should be `https://smash.staging.cardano.org/`. Instead it displays  `https://smash.awstest.iohkdev.io/`. [Slack thread.](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611945831102600?thread_ts=1611933171.089400&cid=GGKFXSKC6)

I have inspected both the Daedalus code and the launcher config in the iohk-nix repository. There is no mention of `https://smash.awstest.iohkdev.io/` so I assume you entered this URL as a custom SMASH URL and saved it that way.
This is the only way it could remain saved and showed again on next Daedalus start.
I would like to see a live demo of this bug on your machine on Monday. Please ping me once you start and we will check this together 🙏 

> * Redeem ITN rewards is not working on both platforms. [Slack thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611947037102900?thread_ts=1611933171.089400&cid=GGKFXSKC6).

I have fixed this in: https://github.com/input-output-hk/daedalus/pull/2325/commits/ce1d4e1f4cbd398ae5e66d09e19823e16888754f
@KtorZ it seems that now we get the `withdrawal_not_worth` error thrown instantly during fee calculation and this was not the case in the earlier versions of CWB. Can you please confirm if this is expected behavior? Did you do some improvements on the ITN wallet balance detection?

> * Fee calculation seems off, sometimes the error "No enough ADA for fees" is displayed on the confirmation dialog after trying to submit a transaction (even when there is enough ADA). [Slack thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611956728105000?thread_ts=1611933171.089400&cid=GGKFXSKC6).

This is definitely not a Daedalus bug.
We need to see if this is related to a [known issue](https://jira.iohk.io/browse/ADP-679) of cardano-wallet.
Please prepare logs of a clean reproduction and share it with @KtorZ on Monday.

**Comment by gnpf** [comment]
@nikolaglumac @disassembler We finished the regression for Staging/Testnet (build 16148/16168). There is only one issue pending:

- The confirmation screen is missing for ITN rewards redemption. Check [this video](https://drive.google.com/file/d/1LT3BzzF2eJ4ts0xuIAR3Uhdd2awO0jV5/view).

More details on the [regression document](https://docs.google.com/spreadsheets/d/1UONhBYhYKCRnIW27QTVrEmEmfpmmt2RJ7eGBRQ4Uh9w/edit#gid=613057473).

**Comment by nikolaglumac** [comment]
> @nikolaglumac @disassembler We finished the regression for Staging/Testnet (build 16148/16168). There is only one issue pending:
> 
> * The confirmation screen is missing for ITN rewards redemption. Check [this video](https://drive.google.com/file/d/1LT3BzzF2eJ4ts0xuIAR3Uhdd2awO0jV5/view).
> 
> More details on the [regression document](https://docs.google.com/spreadsheets/d/1UONhBYhYKCRnIW27QTVrEmEmfpmmt2RJ7eGBRQ4Uh9w/edit#gid=613057473).

@gnpf if that rewards wallet is empty then this is expected.

**Review by gnpf — APPROVED** [review]

**Review by nikolaglumac — APPROVED** [review]

**Pull request merged**
