### PR TITLE
[DDW-941] / [DDW-938] Fix reward CSV export issues

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes two issues:

[DDW-941](https://input-output.atlassian.net/browse/DDW-941): remove the "date" column from rewards CSV export because it's not the date when the reward was received but when the CSV was exported (hence useless for tax declarations)

[DDW-938](https://input-output.atlassian.net/browse/DDW-938): Export CSV amounts in raw/not prettified format that is readable by other import tools.

## Screenshots

grafik

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test that the "date" column is removed from CSV exports
- [ ] Test that the reward amounts are formatted in machine-readable format

---

### Basics

- [ ] PR assigned to the PR author(s)
- [ ] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [ ] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [ ] PR link is added to a Jira ticket, ticket moved to In Review
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR contains screenshots (in case of UI changes)
- [ ] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### Test Scenarios

```Gherkin
Scenario1: Date column not on CSV
Given I export rewards into CSV
When I observe the CSV document
Then the date column is absence

Scenario2: Data exported match data on app
Given I export rewards into CSV
When I observe the CSV document
Then the exported data match the one displayed on app
```

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by renanvalentin** [comment]
Great job @DominikGuzei 🚀! The overall code looks good! I only left a few suggestions

**Comment by szymonmaslowski** [comment]
Hey @DominikGuzei I can see a lot of changes that suppose to be already in the develop as they were merged in this PR: https://github.com/input-output-hk/daedalus/pull/2803/files

I guess there is some problem with the commits history. Could you please clean the changes so only new ones are visible in the diff?

**Comment by DominikGuzei** [comment]
@szymonmaslowski I don't see any unrelated changes in the Github diff? Or do you mean the changes in the "defaultMessages" ?

**Comment by DominikGuzei** [comment]
> Great job @DominikGuzei 🚀! The overall code looks good! I only left a few suggestions

Thanks :) where did you leave your suggestions? I can't see any here on Github

**Comment by szymonmaslowski** [comment]
> @szymonmaslowski I don't see any unrelated changes in the Github diff? Or do you mean the changes in the "defaultMessages" ?

@DominikGuzei I can see you merged the develop branch and probably that fixed the diff. Before the merge, diff contained literally all changes from this PR: https://github.com/input-output-hk/daedalus/pull/2803/files so 26 files changed 😄 Anyway, it is correct right now 👍

**Review by szymonmaslowski — APPROVED** [review]

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Great work @DominikGuzei . Tested on 21049 👍

**Review by renanvalentin — CHANGES_REQUESTED** [review]

**Comment by DominikGuzei** [comment]
@renanvalentin please re-review, there seems to have been some hiccup on Github's side because the suggestions you gave are concerning an already merged PR https://github.com/input-output-hk/daedalus/pull/2803

**Review by renanvalentin — APPROVED** [review]

**Pull request merged**
