### PR TITLE
[DDW-651]: UI - Delegation Center

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR implements delegation center screen on staking module.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-651)

## Todos
- [x] Header section with DonutRing component
- [x] Body section with wallets data with dropdown menu 
- [x] Inject Japanese translations

## Screenshots
image

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1561600059139500)
- [x] Test delegation center screen on storybook by visiting `Staking` => `Delegation Center` story
- [x] Test all other UI components if they are not broken.
---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by yakovkaravelov** [comment]
@nikolaglumac @daniloprates @MarcusHurney Please review this.
Thanks.

**Comment by a-rukin** [comment]
image
icon color is from other theme

**Comment by a-rukin** [comment]
image
@nikolaglumac @darko-mijic mb  we should hide this circle when 100%?

**Comment by nikolaglumac** [comment]
I like this circle. Let's discuss this on our next design call on Tuesday together with @daniloprates.

**Comment by a-rukin** [comment]
image
my initial thought was to show this options only on "cog" click (not on hover)

**Comment by nikolaglumac** [comment]
> my initial thought was to show this options only on "cog" click (not on hover)

I prefer click as well 👍

**Comment by a-rukin** [comment]
image
same bug as @DeeJayElly is fixing

**Comment by nikolaglumac** [comment]
> same bug as @DeeJayElly is fixing

@yakovkaravelov please ignore this one. It will be fixed by @DeeJayElly in the scope of this PR: https://github.com/input-output-hk/daedalus/pull/1437

**Comment by a-rukin** [comment]
image
in the design there are colored indicators of current pool rank. Do we ignore this feature? @nikolaglumac

**Comment by a-rukin** [comment]
All green text should have "cursor: pointer". 
It can be implemented later when we cave all endpoints. 
p.s. just mentioning to bring some attention

**Comment by nikolaglumac** [comment]
> in the design there are colored indicators of current pool rank. Do we ignore this feature? 

@yakovkaravelov did you implement it as such?

> All green(link_color) text should have "cursor: pointer".
It can be implemented later when we cave all endpoints.

@yakovkaravelov please make it like that.

**Comment by a-rukin** [comment]
>>All green(link_color) text should have "cursor: pointer".
>>It can be implemented later when we cave all endpoints.

>@yakovkaravelov please make it like that.

@nikolaglumac not sure it should be done right now, as other screens (e.g. "rewards" and "epochs") use these "in-app actions" but not using proper cursor.

**Comment by nikolaglumac** [comment]
OK then let's skip it for now but to it in the end at once.

**Comment by IuliaDolishniak** [comment]
Drop-down is not fully shown for the last wallet in the list when minimized mode is selected
Screenshot_20190627-152659

**Comment by IuliaDolishniak** [comment]
Also not sure if it is important that when we click on Learn More link we are redirected to the first page of Storybook

**Comment by a-rukin** [comment]
Dark theme bugs: 

cog color 
image


separator color 
image


bg circle doesn't use opacity 
image

**Comment by a-rukin** [comment]
I've revisited dark theme again to make an example of this screen...
https://zpl.io/aX50nGM

Changed small drop menu a big to have a better definition

**Comment by yakovkaravelov** [comment]
@a-rukin Please review again. Thanks.

**Comment by yakovkaravelov** [comment]
> Drop-down is not fully shown for the last wallet in the list when minimized mode is selected
> I have added video on the thread
> screen

@IuliaDolishniak 
This is due to `Select` component of `react-polymorph`.
All pages work same way if you try them in small view port.
Need to update that global component to fix this issue.
I think it should be rather separate ticket, not this PR.

**Comment by yakovkaravelov** [comment]
> Also not sure if it is important that when we click on Read article link we are redirected to the first page of Storybook

@nikolaglumac Please give me decision about this.

**Comment by a-rukin** [comment]
image
don't know if it's an issue, but if the pools is the same color should be same too

**Comment by a-rukin** [comment]
image
cog should be opaque when dropdown is opened 
and dropdown should be aligned to right (like in designs)

**Comment by a-rukin** [comment]
image
this line should have 30% opacity

**Comment by a-rukin** [comment]
image
@nikolaglumac what elements should be under this cog? 🤔

**Comment by nikolaglumac** [comment]
> Also not sure if it is important that when we click on Read article link we are redirected to the first page of Storybook

> @nikolaglumac Please give me decision about this.

This is fine @yakovkaravelov ...

**Comment by nikolaglumac** [comment]
> image don't know if it's an issue, but if the pools is the same color should be same too

@a-rukin you are right but I am not sure what kind of dummy stake pool data @yakovkaravelov is using. Anyways, @yakovkaravelov if the pool is the same please use the same color 🙏

**Comment by nikolaglumac** [comment]
> @nikolaglumac what elements should be under this cog? 🤔
> I mean that we can't delete delegation here and change could be done via link below

@yakovkaravelov @a-rukin in this case the menu should have only one item "Delegate"

**Comment by nikolaglumac** [comment]
> @IuliaDolishniak
This is due to Select component of react-polymorph.
All pages work same way if you try them in small view port.
Need to update that global component to fix this issue.
I think it should be rather separate ticket, not this PR.

@yakovkaravelov @IuliaDolishniak we definitely need to see how to fix this

**Comment by a-rukin** [comment]
> @yakovkaravelov @a-rukin in this case the menu should have only one item "Delegate"

as an option we can remove this icon as it makes not to much sense

**Comment by IuliaDolishniak** [comment]
> > @IuliaDolishniak
> > This is due to Select component of react-polymorph.
> > All pages work same way if you try them in small view port.
> > Need to update that global component to fix this issue.
> > I think it should be rather separate ticket, not this PR.
> 
> @yakovkaravelov @IuliaDolishniak we definitely need to see how to fix this

@nikolaglumac in this PR or another?

**Comment by nikolaglumac** [comment]
Another PR @IuliaDolishniak - please create a card for this on YT 🙏

**Comment by yakovkaravelov** [comment]
@nikolaglumac @IuliaDolishniak @a-rukin Please review again.
Thanks.

**Comment by a-rukin** [comment]
image
If I remember correctly it should be "ADA" here

**Comment by a-rukin** [comment]
image
bug with colored line here

**Comment by a-rukin** [comment]
image
on hover it should change opacity too

**Comment by a-rukin** [comment]
> as an option we can remove this icon as it makes not to much sense

@nikolaglumac should we?

**Comment by nikolaglumac** [comment]
> as an option we can remove this icon as it makes not to much sense

@a-rukin I would not do that but OK... Let's discuss this on the design call today.

**Comment by nikolaglumac** [comment]
@yakovkaravelov I have moved this PR into the WIP stage (together with the card on YT) until the issues @a-rukin reported are resolved.

**Comment by nikolaglumac** [comment]
@IuliaDolishniak - @DominikGuzei has fixed the issue which you reported (https://iohk.myjetbrains.com/youtrack/issue/DDW-723) in the scope of this PR. Can you please re-test?

**Comment by IuliaDolishniak** [comment]
The issue with the dropdown appears to be fixed. But now I cannot see the icon that we need to click for the dropown to be shown @yakovkaravelov can you please have a look?
dropdown_icon

**Comment by yakovkaravelov** [comment]
@IuliaDolishniak @nikolaglumac @a-rukin Would you please review again? Thanks.

**Pull request merged**
