### PR TITLE
[DDW-370] add antivirus restoration slowdown notification component t…

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR adds a notification during wallet restoration that tells Windows users that their usage of anti-virus software might slow down the process.

The logic is written like this:

- Show notification for any wallet restoration
- If user discards the notification -> save that information as "last discarded notification for wallet id"
- Don't show the notification for the last discarded restoration wallet id (since we can only restore a single wallet
- If the wallet (for which the notification was last discarded) is deleted -> reset the saved value, so that the notification appears again for the same wallet restoration

This assumes that we can only restore one wallet at the same time.

## Todo:

- [x] Add notification component + render it in storybook
- [x] Add logic to display it during restoration & only on windows

## Screenshots:

- The component in storybook:

screenshot 2018-07-26 um 13 27 53

- In the Daedalus UI:

screenshot 2018-07-26 um 18 00 28

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by a-rukin** [comment]
Note: the shadow type depends on the position.
When prompt is on top of the screen: Y=5px, bottom: Y=-5px

**Comment by DominikGuzei** [comment]
@a-rukin how should the normal state of this button look like?

**Comment by a-rukin** [comment]
transparent (bg is visible)

**Comment by DominikGuzei** [comment]
@a-rukin Here with syncing state and fixed button:

screenshot 2018-07-26 um 18 00 28

**Comment by DominikGuzei** [comment]
@a-rukin @darko-mijic this PR is now ready for review on Windows - you can test it as soon as the CI build is ready!

**Comment by daniloprates** [comment]
@DominikGuzei great work! 🎉

I've left just a minor observation. And there are some Flow & Lint errors.

**Comment by DominikGuzei** [comment]
@daniloprates thanks for the feedback! Flow and linting issues should be fixed now!
@darko-mijic i updated the notification copy!

**Comment by DominikGuzei** [comment]
@daniloprates regarding the className … there is no real reason but it doesn't hurt - especially later on for testing ;) but you're right, i shouldn't have added it if not necessary. Now i will leave it since it's more work / we lose CI build time if push another change 😆

**Pull request merged**
