### PR TITLE
[DEVOPS-239] Run build-dll on all supported platforms

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Looks good, let's wait for the build and see if it fixed the problem 👍

**Comment by domenkozar** [comment]
@fersel will you test or someone else? It's ready for testing.

**Comment by DominikGuzei** [comment]
@domenkozar i will check it out

**Comment by DominikGuzei** [comment]
@domenkozar that didn't work … i will try another approach where you don't need to change anything about the build process.

**Pull request closed without merging**
