### PR TITLE
[DDW-565] Improve performance of rendering huge lists

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR improves the performance of rendering huge lists (e.g: transactions or addresses) by using a virtual list rendering technique where only the visible part of the complete list items is rendered on-screen which makes it possible to performantly scroll through the whole list without the need to resort to paging.

## TODOs:

- [x] Use "normal" (old) list on wallet summary screen, where only 5 tx are rendered
- [x] Try to improve the tx row height calculation (currently there can be gaps when window resizes)
- [x] Fix double scroll-bar during wallet restoration
- [x] Refactor the addresses list on "receive" screen to a virtual list too.
- [x] Fix transaction collapse arrow positioning when scrolling transactions on "Transactions" screen
- [x] Fix issue with delayed updates of confirmations / assurance level on "Transactions" screen when 500+ tx are loaded
- [x] Refresh full transaction history after wallet restoration is done

### Improved logging

- Addresses logging (we log only total numer of addresses):
```
[2019-02-04T09:08:14.0932Z] [info] [renderer] AdaApi::getAddresses success: [
  {
    "index": 2147483648,
    "addresses": 6152,
    "amount": 104582,
    "name": "Account: HdAccountIx 2147483648",
    "walletId": "Ae2tdPwUPEZ53tgL67DsviQ1nk1zdBuEtfjPRcHau4kVR16R3Sde2DJwH9t"
  }
]
```

- Transactions logging (we log only request and response stats):
```
[2019-02-04T09:08:13.0814Z] [info] [renderer] AdaApi::searchHistory called: {
  "walletId": "Ae2tdPwUPEZ53tgL67DsviQ1nk1zdBuEtfjPRcHau4kVR16R3Sde2DJwH9t",
  "limit": null,
  "skip": 0,
  "searchTerm": "",
  "isFirstLoad": false,
  "isRestoreActive": false,
  "isRestoreCompleted": false,
  "cachedTransactions": 6171
}
[2019-02-04T09:08:15.0513Z] [info] [renderer] AdaApi::searchHistory success: 6171 transactions loaded {
  "apiRequested": "all",
  "apiFiltered": "fresh",
  "apiReturned": 0,
  "apiPagesTotal": 1,
  "apiPagesRequested": 1,
  "daedalusCached": 6171,
  "daedalusLoaded": 0,
  "daedalusTotal": 6171,
  "requestDurationInMs": 1699
}
```

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
Great work @DominikGuzei!

Here is my feedback regarding the "Todos" you added in the PRs description:

> Discuss if the current solution of rendering the "show more tx" button on the wallet summary screen is good enough … i haven't found a way to render it "right below the transactions list". You can see that effect on large screens … the button will always stick to the bottom of the screen.

I think the simplest option would be not to render the transaction list on the "Summary" screen using the virtual list. We could create another transactions list component which will not use virtual list OR we could pass the prop to the existing list which will enable/disable virtual list usage?

> Discuss if the current solution of calculating transaction row heights (virtual lists need to know an explicit row height in pixels and aren't very flexible) is sufficient … the calculation takes into account that transaction addresses can wrap around to the next line on small window sizes. So basically for each address the maximum amount of height it can take on screen is added to the tx row height. This results in whitespace "gaps" when the window is wide enough so that addresses are just rendered on a single line.

We need to discuss this. Perhaps, there's a way to recalculate the height once the text breaks - we could do it on window-resize event?

> Refactor the addresses list on "receive" screen to a virtual list too.

I would definitely add this to this PR 🙏

**Comment by nikolaglumac** [comment]
@DominikGuzei I have noticed one more issue:
scroller

**Comment by DominikGuzei** [comment]
@nikolaglumac i updated the todo section

**Comment by nikolaglumac** [comment]
Great work @DominikGuzei 🎉 
I have added one more todo!

**Pull request merged**
