### PR TITLE
[DDW-376] Fix address validation on the Shelley QA and Staging networks

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR fixes Address validation on Shelley QA and Staging networks and adds Shelley QA network SMASH server URL.

## Todos

- [x] Fix Shelley QA network address validation
- [x] Check Staging network address validation (@DeeJayElly)
- [x]  Add Shelley QA SMASH server URL

## Screenshots

Screen Shot 2020-10-27 at 6 16 28 PM
Screen Shot 2020-10-27 at 6 16 00 PM

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1603819038247400)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by mioriohk — APPROVED** [review]
Looks good. Good work @DeeJayElly 👍

**Comment by gnpf** [comment]
@DeeJayElly this is working well. I was wondering if the same issue with Staging is going to be addressed on this PR too.
@alan-mcnicholas [mentioned it happens there as well.](https://jira.iohk.io/browse/DDW-376?focusedCommentId=26027&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26027)

**Comment by nikolaglumac** [comment]
> @DeeJayElly this is working well. I was wondering if the same issue with Staging is going to be addressed on this PR too.
> @alan-mcnicholas [mentioned it happens there as well.](https://jira.iohk.io/browse/DDW-376?focusedCommentId=26027&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26027)

@DeeJayElly please check this 🙏

**Comment by nikolaglumac** [comment]
@DeeJayElly I have added one more TODO for you:
Screenshot 2020-10-29 at 10 46 34

cc @alan-mcnicholas

**Comment by DeeJayElly** [comment]
> @DeeJayElly I have added one more TODO for you:
> Screenshot 2020-10-29 at 10 46 34
> 
> cc @alan-mcnicholas

Fix is added for network tag

**Comment by alan-mcnicholas** [comment]
Address validation is now working on staging, great work @DeeJayElly ! :)

**Comment by nikolaglumac** [comment]
> Address validation is now working on staging, great work @DeeJayElly ! :)

Thanks @alan-mcnicholas! Did you also make sure non-staging addresses are rejected? E.g. the mainnet ones?

cc @gnpf @ManusMcCole @mioriohk

**Comment by alan-mcnicholas** [comment]
@nikolaglumac I checked that address discrimination is working between staging\mainnet and testnet.
Valid addresses for both are accepted and invalid ones are rejected as expected due to incompatible networkMagic.

**Comment by nikolaglumac** [comment]
> @nikolaglumac I checked that address discrimination is working between staging\mainnet and testnet.
> Valid addresses for both are accepted and invalid ones are rejected as expected due to incompatible networkMagic.

Great! Thanks for checking that @alan-mcnicholas ❤️ 
Can you please approve the PR?

**Review by alan-mcnicholas — APPROVED** [review]
Looks good to me, great work!

**Review by nikolaglumac — APPROVED** [review]
Works great @DeeJayElly 👍

**Pull request merged**
