### PR TITLE
[DDW-115] Implement smart error handler

### PR DESCRIPTION
**Pull request by tomothespian**
This PR Introduces smart error handler implementation.

---

### Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1586932832385500)
- [ ] Walk through the app and check if all errors are presented as is expected e.g. `Address is not valid` on wallet send screen... My suggestion is regression testing!

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by DmitriiGaico** [comment]
@tomothespian Hello!
Duplicating errors here for tracking purposes.
1. Wrong Fee calculations. Sometimes a generic error is showed instead of corresponding Not Enough Fee.
2. After entering Wrong Password wrong Error message is displayed.

cc @gnpf @IuliaDolishniak

**Comment by DmitriiGaico** [comment]
@tomothespian Hey!
Expected Message : Message => "Not enough ada . Try sending a smaller amount."
image

**Comment by DmitriiGaico** [comment]
@tomothespian hey, adding a screen shot for current error message when Not Enough Funds.
image

**Comment by tomothespian** [comment]
@DmitriiGaico @IuliaDolishniak @gnpf @ManusMcCole 
All issues are fixed.
1. After entering Wrong Password wrong Error message is displayed. - **DONE**
2. Error message when _Not Enough Funds_. - **DONE**

NOTE for `Wrong Fee calculations. Sometimes a generic error is showed instead of corresponding Not Enough Fee.` -> _An error occured_

**case:** I have a wallet with **1M ADA** and if I want to send `999,999.8` everything is ok with an error handler. Error message `Not enough ada for fees. Try sending a smaller amount.` occur. If I want to send `999,999.7` then we have a problem. Error message `An error occurred` is shown. This is not related to error handlers and Daedalus code. After deep investigation, I saw that backend returns `code: 500, Internal server error` and even more interesting that is returned directly through the response body. So we can not handle error like this if we don't know what is real error so `An error occurred` message is OK to me. We need to report that to the backend team for sure. **QA, nice catch** 🚀 
cc. @nikolaglumac

**Comment by nikolaglumac** [comment]
@KtorZ can you look into this error? @tomothespian will prepare logs.

**Comment by DmitriiGaico** [comment]
@tomothespian hey! Could you please also remove the Learn more link? Thank you in advance.
image

**Comment by tomothespian** [comment]
@DmitriiGaico This one is done `Could you please also remove the Learn more link? Thank you in advance.`

**Pull request merged**
