### PR TITLE
[DDW-505] Overlapping Data on Transactions

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixed the row height estimation of the `VirtualTransactionList` to include expanded transactions.

## Screenshots

CleanShot 2020-12-02 at 22 53 24

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1606946436489300)
- [ ] Test:
   - Go to "transactions" on a wallet
   - Filter transactions by "received"
   - Expand any transaction
   - Filter transactions by "sent"
   - Filter transactions by "received"

**Expected result:** expanded transactions should always have the correct height

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei please fix flow issues 🙏

**Comment by nikolaglumac** [comment]
@gnpf please review/test this one today 🙏

**Comment by nikolaglumac** [comment]
@DominikGuzei no work for you here in the end - I have fixed the lint issues here: https://github.com/input-output-hk/daedalus/commit/4d0cc707afeb5fa02358b370208ee540ec60544c 🎉

**Comment by gnpf** [comment]
@DominikGuzei This still reproduces on some scenarios. Try expanding various transactions of different lengths with the wallet on [DDW-505](https://jira.iohk.io/browse/DDW-505). Check transaction splitting on [video 1](https://drive.google.com/file/d/1SpJ7QCxm_hJCVTVZbFKWBBodbI6ny9K1/view?usp=sharing), check overlapping on [video 2](https://drive.google.com/file/d/1HwFWJbQcrhBSBNYMIpDO5mgBVcFppOgF/view?usp=sharing).

**Comment by DominikGuzei** [comment]
@gnpf thanks, this looks like a different issue - I will investigate 👍

**Comment by DominikGuzei** [comment]
@gnpf please try again. I could reproduce the issue you recorded and after the latest changes I pushed, it seems to be fixed 🙏

**Review by ManusMcCole — APPROVED** [review]
Looks good to me 👍

**Review by mioriohk — APPROVED** [review]
LGTM 👍

**Pull request merged**
