### PR TITLE
Fix/daef 468 Frontend AtoA transaction handling

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR introduces improved error messages for transaction-fees-calculation endpoint.

## TODO
- [x] Inject missing Japanese translation
```
"api.errors.AllFundsAlreadyAtReceiverAddressError": "All your funds are already at the address you are trying send money to.",
```

screen shot 2017-09-18 at 11 25 03
screen shot 2017-09-18 at 11 24 50

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Reviewing this now …

**Comment by DominikGuzei** [comment]
@nikolaglumac how can i reproduce this? I sent two transactions from "Genesis wallet" to addresses of itself and it worked without any errors..

**Comment by DominikGuzei** [comment]
I ran backend on `cardano-sl-0.6--0.6.2-candidate` (commit: `9f5b591e7365c9723cca02ee8fbb284957b0fb42`) and started it with `./scripts/launch/connect-to-cluster/testnet-staging-0.6.sh`

**Comment by nikolaglumac** [comment]
@DominikGuzei here are the steps to reproduce both errors:

1. A -> A error aka. `All your funds are already at the address you are trying send money to.`
- import **new** Genesis wallet which has never been used before (aka. transaction history is empty and wallet has only single address)
- try to send any amount to the single address of imported wallet

2. A -> B error for sending too much money aka. `Not enough Ada for fees.`
- use the same imported wallet from first step and try to send amount larger than the wallet's balance to some other wallet (eg. create/import/restore another wallet and use it's address as receiver)

I also used `cardano-sl-0.6--0.6.2-candidate` branch BUT I use `./scripts/launch/connect-to-cluster/testnet-0.6.sh` script to launch it - but I don't think it should matter...

**Comment by DominikGuzei** [comment]
@nikolaglumac i will push the missing translation now

**Comment by DominikGuzei** [comment]
Closing this PR in favor of new target against `release/0.8.2`

**Pull request merged**
