### PR TITLE
Merge release/0.8.3 into master branch

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR merges latest release into our stable master branch.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@nikolaglumac the merge conflicts have to be resolved before i can merge it!

**Comment by nikolaglumac** [comment]
@DominikGuzei I am not sure what to do with those conflicts. Perhaps @domenkozar can help us out here?

PS. we need to update the CHANGELOG too @DominikGuzei - but that is smth @darko-mijic said he will do before merging this PR...

**Comment by darko-mijic** [comment]
@domenkozar: This is prerequisite for preparing the new release branch.

**Comment by domenkozar** [comment]
We've used `release/0.8.2` and all of the changes in 0.8.3 can be left out.

**Comment by DominikGuzei** [comment]
Ok then we need to open a different PR from `0.8.2` to `master` instead!

**Pull request closed without merging**
