### PR TITLE
[DDW-33] Reduce layout re-renderings

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR removes any unnecessary layout re-renderings which caused the whole app to re-render anytime we fetched wallets.

The reasons for the re-renderings have been two-fold and this is an important performance knowledge when working with mobx & react:

1. Always use `@computed` properties inside stores for calculating stuff (we had a few calculations done in the layout render code, which triggered re-renderings if any dependency changed). **Better:** don't calculate stuff in `render` functions, only in stores.

2. I saw that we were not using [@computed.struct](https://alexhisen.gitbooks.io/mobx-recipes/content/use-computedstruct-for-computed-objects.html) anywhere which is sad because that was actually the biggest cause of unnecessary re-renderings since using only `@computed` doesn't work with objects or arrays (it always invalidates if you return a new object / array).
**Better:** I refactored all computed props that return objects or arrays to `@computed.struct` which only invalidates dependencies if the objects actually/structurally changed.

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571159403100500)

**QA**
- [ ] Wallet notifications
- [ ] Wallet restoration
- [ ] Wallet sidebar etc. double check if data / amounts are correctly updating!

**Developers**
- [ ] run the app with `MOBX_DEV_TOOLS=1 yarn dev` and click the first icon (show component re-renderings) … then you will see the difference between `develop` and this PR.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by IuliaDolishniak** [comment]
Same for me, just wanted to report @daniloprates

**Comment by DominikGuzei** [comment]
Thanks @daniloprates, good catch - the interesting part is that from what i see in the code this should never have worked the way it does (before this PR) 😆 If you debug / analyze the wallet store code you will see that importing a wallet only sets it as active (via `refreshWalletsData`) if there already is an active wallet … so i wonder how this even worked before?

The second interesting part is that my changes should not affect that logic in any way … so i guess i stumbled upon an existing bug that was covered by inefficient mobx usage 😄

**Comment by DominikGuzei** [comment]
Ok forget it, i found the issue 😉

**Comment by DominikGuzei** [comment]
@daniloprates @nikolaglumac all issues should be fixed now 👍 i reverted most of the `computed.struct` changes because i didn't fully understand how it's intended to be used: we should only use it in cases where we create new objects based on other observables (i left one example in the sidebar store where it really makes sense).

The wins in this PR still apply, it was mostly the refactoring of the layout components that reduced the re-renderings 🎉

**Pull request merged**
