### PR TITLE
[DDW-929] Implement date, time and number format user options

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements date, time and number format user options.

## Todos

* [x] General Settings screen
* [x] App First Launch screen
* [x] Profile Store actions
* [x] LocalStorage actions
* [x] Apply formats to all screens using date, time and number
* [x] Update Storybook stories
* [x] Translation
* [x] Update tests ('Select Language' tests were disabled and will be fixed on DDW-1017)

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1572027649234600)
- [Slack Translation thread](https://input-output-rnd.slack.com/archives/CBECZ2K47/p1571673444049700)

### EN
image

### JP
image

---

## Testing Checklist
- **Initial Screen**
  - [ ] Test if the initial screen correctly sets all the values
    - [ ] This screen has a new behavior: when changing the language, the page already changes its content language
- **General Settings screen**
  - [ ] Test if the General Settings screen correctly sets all the values
- **Both screens**
    - [ ] Changing the language should change the Date format select options
    - [ ] Returning to the previous language should keep the previous Date format choice
- **Whole app**
   - [ ] The whole app should respond to the new settings. The only exception is the Wallet Send Screen input, as it's not possible to change the Numeric Input format. This will be addressed on a [different task](https://iohk.myjetbrains.com/youtrack/issue/DDW-1018). 
- [ ] Check the Japanese translation

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@daniloprates There is some inconsistency with the dates formats is Japanese, is this expected?

image

**Comment by gnpf** [comment]
@daniloprates I submitted these options on the initial setup screen

image

But then the formats are not persisted on the application:

image

image

image

**Comment by daniloprates** [comment]
> There is some inconsistency with the dates formats is Japanese, is this expected?

@gnpf this is expected. The Japanese language has different date formats.

**Comment by daniloprates** [comment]
> I submitted these options on the initial setup screen

@gnpf thanks, I'll fix it

**Comment by gnpf** [comment]
@daniloprates I changed the format from the settings screens and the number format was not affected in the _Amount_ field.
For reference, the selected format is **1.234,56** (the wallet balance shows the correct format)

image

**Comment by daniloprates** [comment]
> I changed the format from the settings screens and the number format was not affected in the _Amount_ field.

@gnpf yeap, I left a not in the QA checklist. It's not possible to change the NumericInput, yet. [DDW-1018](https://iohk.myjetbrains.com/youtrack/issue/DDW-1018) will fix it.

image

**Comment by MarcusHurney** [comment]
@daniloprates 
When I change the number formatting, my formatting selection isn't reflected in the Delegation stepper within steps 3 and 4 (photos below):

Screen Shot 2019-10-25 at 7 47 53 PM

Screen Shot 2019-10-25 at 7 48 30 PM

Also in the rewards screen, my number formatting selection isn't reflected in the 'Amount' column's values (photo below):

Screen Shot 2019-10-25 at 7 49 41 PM

**Comment by daniloprates** [comment]
> @daniloprates I submitted these options on the initial setup screen
> But then the formats are not persisted on the application:

@gnpf fixed. It was a bug in the initial screen, that was not actually getting the chosen settings.

Could you please test again?

**Comment by daniloprates** [comment]
> On the general settings screen, I am seeing the Language label on every field.

> When I change preferences for number formatting from the general settings screen, my formatting selection isn't reflected in the Delegation stepper within steps 3 and 4 (photos below)

> Also in the rewards screen, my number formatting selection isn't reflected in the 'Amount' column's values (photo below)

@MarcusHurney great catches! Could you please test again?

**Comment by gnpf** [comment]
@daniloprates 
The initial balance of a wallet is always displayed on the default format:


image
_The selected format on this screenshot was 1.234,56_

**Comment by MarcusHurney** [comment]
@daniloprates 
Yes I will test it again today.

**Comment by gnpf** [comment]
@daniloprates The changes on diagnostics screen do not affect the fields _Latest local block age_, _Latest network block age_ and _Local time difference:

image

Also I'm not sure if the thousands or decimal separators should apply to the IDs on _Core info_ section. Let me know what you think.

**Comment by gnpf** [comment]
@daniloprates In this screenshot the format is _1.234,56_ (as displayed on _Network Block Height_) but the percentage is displayed as _100.00 %_

image

**Pull request merged**
