### PR TITLE
[DDW-350] Fix Japanese translation for Byron wallets

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR fixes Japanese translation of "Byron" wallet label and enables "Send" screen for Byron wallets.
The "Learn more" button shown on the "Byron wallet migration" notification has been removed.

#### Before
Screenshot 2020-08-11 at 13 48 23

#### After
Screenshot 2020-08-11 at 13 48 34

### Send screen for "Byron" wallets

Screenshot 2020-08-11 at 13 48 08
Screenshot 2020-08-11 at 13 48 39

### Removed "Learn more" button on "Byron wallet migration" notification

Screenshot 2020-08-11 at 16 14 11
Screenshot 2020-08-11 at 16 14 18

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
Hi @nikolaglumac. Probly out of the scope for this PR but the Learn More link associated with the Byron wallets is broken 
Screenshot 2020-08-11 at 14 35 04

**Comment by nikolaglumac** [comment]
@ManusMcCole please check production build...

**Comment by nikolaglumac** [comment]
> Hi @nikolaglumac. Probly out of the scope for this PR but the Learn More link associated with the Byron wallets is broken
> Screenshot 2020-08-11 at 14 35 04

@ManusMcCole broken link has been removed...

**Comment by gnpf** [comment]
@nikolaglumac The label looks good and the "send" tab is enabled. Not sure if this is on the scope of this task, but this error is visible when trying to calculate fees for a transaction:

Screenshot at Aug 11 12-01-17

**Comment by nikolaglumac** [comment]
> @nikolaglumac The label looks good and the "send" tab is enabled. Not sure if this is on the scope of this task, but this error is visible when trying to calculate fees for a transaction:
> 
> Screenshot at Aug 11 12-01-17

@gnpf fixed in: https://github.com/input-output-hk/daedalus/commit/02648ada95a774795584adb13be738d60e88d17a

**Pull request merged**
