### PR TITLE
[DDW-304]: Implement logarithmic stake slider

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR implemented logarithmic stake slider.
[Jira Ticket](https://jira.iohk.io/browse/DDW-304)

## Todos
- [x] Make stake pools ranking slider logarithmic

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1597881023112700)

### App
- [x] Go to `Staking` => `Stake Pools` and make sure stake pools ranking slider is logarithmic

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
On Mac Shellley Testnet from hovering over the number 7 it makes it seem as though 7ada is now the minimum amount required to stake. Is this as expected ? 
Screenshot 2020-08-20 at 09 36 06

**Comment by ManusMcCole** [comment]
The numbers on the slider are  7, 20, 55, 148 , 403, 1097, 2981..ect. Is there a reason it starts at 7 and not 10 ? If started at 10 the increments can be even numbers which would look a lot tidier. Also it would make more sense as minimum amount to delegate is 10ADA

**Comment by ManusMcCole** [comment]
The circulating supply of ada is 25Billion according to coinmarketcap. it is listed as 33Billion on the hover tool tip. Was this figure based on future projections ? 
Screenshot 2020-08-20 at 10 11 26
Screenshot 2020-08-20 at 10 12 47

**Comment by mioriohk** [comment]
@yakovkaravelov I intend to delegate 40,000 ADA but I could only choose either 22,026 or 59,874. My concern is the message  "Use the slider to rank the stake pools based on the amount you intend to delegate" is not 100% correct because I am not able to choose 40,000 using the slider.  

From user point of either the slider needs to be fixed so user is able to choose the specific amount that he wants or the message needs to be altered to explain to the user that he could select an approximation which not necessarily be closed to his intended amount.

Annotation 2020-08-20 102137

**Comment by yakovkaravelov** [comment]
This needs some quotes from @nikolaglumac and @darko-mijic 
Let's solve this once they return.

**Comment by yakovkaravelov** [comment]
@gnpf @mioriohk @ManusMcCole 
This was updated.
Please review.
Thanks.

**Comment by nikolaglumac** [comment]
@ManusMcCole @gnpf please test this one again 🙏 

@darko-mijic I would like to hear your opinion too!

**Comment by ManusMcCole** [comment]
Hi @yakovkaravelov. Is the the total circulating supply listed not getting changed to 26Billion ? Was there a discussion on this ? Coinmarketcap says almost 26billion is current circulating supply.
Screenshot 2020-09-02 at 16 38 36
Screenshot 2020-09-02 at 16 39 34

**Comment by yakovkaravelov** [comment]
> Hi @yakovkaravelov. Is the the total circulating supply listed not getting changed to 26Billion ? Was there a discussion on this ? Coinmarketcap says almost 26billion is current circulating supply.
> Screenshot 2020-09-02 at 16 38 36
> Screenshot 2020-09-02 at 16 39 34

@ManusMcCole Those values were what I got from @nikolaglumac and @darko-mijic

**Comment by gnpf** [comment]
@yakovkaravelov Is there a way to round up some of the small numbers of the sequence? **55, 148, 403** look out of place to me.

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov Is there a way to round up some of the small numbers of the sequence? **55, 148, 403** look out of place to me.

I was asked to implement small numbers as they are while big numbers are rounded up.

**Comment by ManusMcCole** [comment]
Hi @nikolaglumac. How do you feel about the numbers 55, 148, 403 that @gnpf Gabriela mentioned above ?

**Comment by ManusMcCole** [comment]
I see Coingecko says circulating supply is 31billion.If this is the correct figure should somebody email coinmarketcap and tell them to change it ?

**Comment by nikolaglumac** [comment]
> Hi @nikolaglumac. How do you feel about the numbers 55, 148, 403 that @gnpf Gabriela mentioned above ?

@ManusMcCole that one should be signed off by @darko-mijic

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@yakovkaravelov can we please make the slider more fluid?
We should also show the values from the "Select a wallet" dropdown "as-is" and not rounded...

**Comment by yakovkaravelov** [comment]
@nikolaglumac Fixed things. Please review again. Thanks.

**Comment by nikolaglumac** [comment]
@yakovkaravelov the slider now works great!
There is just one issue - when you use the dropdown to select one of your wallets (or all wallets option) the Api breaks as it looks this sends the amount of stake in a wrong format:

Screenshot 2020-09-08 at 10 25 53

**Comment by ManusMcCole** [comment]
Hi @yakovkaravelov. The numbers are now 10 - 254,345 - 504,707 - 759,042....... This doesn't seem very user friendly to users with small wallet balances. Is there plans to add an input box in the future ? @nikolaglumac

**Comment by ManusMcCole** [comment]
Hi @yakovkaravelov. Sorry ignore my previous comment I was on the wrong build

**Comment by nikolaglumac** [comment]
@ManusMcCole slider works great now!

slider

**Comment by ManusMcCole** [comment]
Yeah looks really good now @nikolaglumac . Good work @yakovkaravelov 👍

**Review by gnpf — APPROVED** [review]
Good job 🎉

**Comment by nikolaglumac** [comment]
@yakovkaravelov all issues fixed in https://github.com/input-output-hk/daedalus/pull/2162/commits/6f72ee4a122094e5abbfb3bcffbee03413127433

**Comment by nikolaglumac** [comment]
@gnpf @ManusMcCole @yakovkaravelov shouldn't the default slider value be set to "all wallets"?
Can you please compare to the production version?

**Comment by yakovkaravelov** [comment]
> @gnpf @ManusMcCole @yakovkaravelov shouldn't the default slider value be set to "all wallets"?
> Can you please compare to the production version?

@nikolaglumac Default value was set by Darko.

**Review by nikolaglumac — APPROVED** [review]
Excellent work @yakovkaravelov 🎉

**Pull request merged**
