### PR TITLE
Fix/ddw 91 fix broken options component styles (FORK)

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR uses the new 0.6.4 release of `react-polymorph` to clean-up and fix many styling issues we had because of incorrect configuration (and some bugs in `react-polymorph`). The original goal was to fix the select component in the Daedalus `Dark blue` theme, then i discovered several underlying issues and problems which are all fixed now:

- Some components in `react-polymorph` did not include the raw components, and thus the whole default theme was also included, even though we are only using raw components (with custom theme) in Daedalus -> this resulted in the weird overrides and issues. This was fixed in the 0.6.1 release
- Due to the issues with react-polymorph we have used ugly hacks in our component styles setup in Daedalus to override styles in weird ways … i fixed all of these issues now and only use the proper theming variables (like it was intended)
- Some other issues like options/bubble positioning have been fixed in later versions of react-polymorph!

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei to review this we need you to release new react-polymorph version on npm ;)

**Comment by DominikGuzei** [comment]
Not really, you can checkout the react-polymorph PR (which also needs review & merge first) and build + copy it over to test 😉

**Comment by DominikGuzei** [comment]
@nikolaglumac i release `react-polymorph@0.6.1` now and updated this PR to include it! So you can just `npm install` and test away 😉

**Comment by DominikGuzei** [comment]
Thanks @tomothespian, i will look into the font issue!

**Comment by DominikGuzei** [comment]
@tomothespian for me the Options font works well (`var(--font-light)`), to what do you want to change it?

**Comment by darko-mijic** [comment]
😱

**Comment by DominikGuzei** [comment]
@nikolaglumac we need to check your setup (please try to delete complete `node_modules` folder and use node 8.2.1 to install) - i don't see any of these issues here!

**Comment by nikolaglumac** [comment]
@DominikGuzei I have already tried that twice :(
Once with node `8.5.0` and second time with `8.2.1` that you suggested. Both of those tests resulted in the same issues as shown in the screenshots I have posted earlier.
Will try tomorrow on @tomothespian's machine and get back to you with the results.
I surely hope these issues are the result of my broken local setup :-/

**Comment by DominikGuzei** [comment]
@nikolaglumac yeah please do so, your machine already had some issues a while ago! 😉 so i re-installed on node `8.2.1` here and still haven't seen any of these issues … but i found a real issue i have to fix on the restore wallet screen (the dialog content is cut-off)

screenshot 2018-02-12 um 10 08 44

**Comment by DominikGuzei** [comment]
@nikolaglumac interestingly now the extra space in the dialog also is there … but i don't have the fonts issues for example 🤔

**Comment by DominikGuzei** [comment]
@nikolaglumac and me found all the issues, so this is what's missing for this PR:
- [ ] Properly generate / copy the `index.html` into `dist/renderer` folder on build
- [ ] Fix broken input styles when they are in error state (red border is missing)
- [ ] Fix broken Options/bubble positioning in `react-polymorph` (our custom JS positioning solution got lost because we didn't have a proper example in the repo that showcased it and thus it seemed like everything is ok to 3rd party contributor and me)

**Comment by DominikGuzei** [comment]
@nikolaglumac this PR is now ready for review again. I ported over our latest fixes and changes for all the styling issues in the 0.9.0 release!

**Comment by DominikGuzei** [comment]
@nikolaglumac this is now ready to be reviewed and merged! 👍

**Pull request merged**
