### PR TITLE
[DDW-291] Fix PopOver Themes

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes the pop over themes after a detailed double-check from @a-rukin:

- Update to react-polymorph@0.9.6-rc3 (which sets the default pop over font to `regular`)
- Fix wrong background colors for some themes
- Handle the potentially (atm only in cardano theme) different bg color for the status icon tooltip

### Cardano Theme:
The cardano theme is "special" because it requires a different tooltip bg color for the status icons:

CleanShot 2020-10-29 at 13 12 56

But the default tooltips should all look like this:

CleanShot 2020-10-29 at 13 13 11

---

## Testing Checklist

This PR is really mostly fixing tooltips styles for the work done in [[DDW-291] Smart Tooltip MVP integration](https://github.com/input-output-hk/daedalus/pull/2210), so i don't think a whole QA session is needed here but @a-rukin should take a final look and give approval (because the other PR was merged before he could do that) .…

- [ ] Double-check that all the new tooltips (syncing/connecting, paper wallet info, staking slider) are good 🙏 

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by a-rukin — APPROVED** [review]
tenor

**Review by nikolaglumac — APPROVED** [review]
Great work @DominikGuzei 💯

**Comment by nikolaglumac** [comment]
@gnpf @mioriohk can you please re-check status-icon tooltips? As well as the ones for the paper wallets on the wallet settings page (you need to restore Byron wallet for that one to appear)?

Thanks!

**Review by mioriohk — APPROVED** [review]
Looks good to me. Tested on build 14988. Great work @DominikGuzei 👍

**Review by gnpf — APPROVED** [review]

**Pull request merged**
