### PR TITLE
[DDW-814] White theme styling adjustments

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces "White" theme styling adjustments.

## Screenshots

_Secondary button_
Secondary button

_Dropdown arrow colour_
Dropdown arrow color

Dropdown arrow color 2

_Syncing Daedalus colour_
Syncing Daedalus colour

_Layout shadows_
Layout shadows

_UTXO graph colors_
UTXO graph colors

_Settings - active menu item bg colour_
Settings - active menu item bg color

_Wallet navigation item hove bg color_
Wallet navigation item hove bg color

_Wallet list scroll bar color_
Wallet list scroll bar color

_Connecting screen bg color_
Connecting screen bg color

_Syncing screen bg color_
Syncing screen bg color

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1565629893194100)

**TESTING NOTES:**

- Testing required for white theme
- Take a look on requested changes: https://docs.google.com/document/d/1PASumA56UY7DAW5RR39KH7Se15MZg1LcCiDfhe1hFsI/edit

**TESTING STEPS:**

1. _Secondary button colour_
- [x] Test Storybook story under: `Widgets -> NodeUpdateNotification`

2. _Dropdown arrow colour (all themes)_
- [x] Test Storybook story under: `Staking -> Epochs`
- [x] Test Storybook story under: `Staking -> DelegationStepsChooseWalletDialog`
- [x] Test Storybook story under: `WalletScreens -> Settings`
- [x] Test Storybook story under: `Add Wallet -> Wallet Restore`
- [x] Test Storybook story under: `Paper Wallet -> Shielded recovery phrase and password verification`
- [x] Test Storybook story under: `LanguageSelectionForm -> Form - initial`

3. Syncing Daedalus colour 
- [x] Test Storybook story under: `Loading -> SyncingConnecting - Sync Issues`
**NOTE: Test screen for all themes since new variables are presented**

4. Layout shadows (Top Bar & Main Content shadow)
- [x] Test Storybook story under: `WalletScreens -> Summary`

5. UTXO graph colors
- [x] Test Storybook story under: `WalletScreens -> Wallet UTXO distribution`

6. _Settings - active menu item bg color_
- [x] Test Storybook story under: `Settings -> SettingsMenu`

7. _Wallet navigation item hove bg color_
- [x] Test Storybook story under: `WalletScreens -> WalletNavigation`

8. _Wallet list scroll bar color (decrease window height)_
- [x] Test Storybook story under: `WalletScreens -> WalletNavigation`

9. _Connecting screen bg color_
- [x] Test Storybook story under: `Loading -> SyncingConnecting - Default`

10. _Syncing screen bg color_
- [x] Test Storybook story under: `Loading -> SyncingConnecting - Sync Issues`

11. _"Add Wallet" button initial / hover colour_
- [x] Test Storybook story under: `WalletScreens -> WalletNavigation`
---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@a-rukin can you please review this one?

**Comment by a-rukin** [comment]
@tomothespian I've added few more comments here https://docs.google.com/document/d/1PASumA56UY7DAW5RR39KH7Se15MZg1LcCiDfhe1hFsI/edit

**Comment by a-rukin** [comment]
image

“Add wallet” background… Initially, it didn’t have any BG, so no bug here. But I’ve started thinking that it may worth unify everything with other themes and add some. https://zpl.io/2ZzmDll Thought? 
@nikolaglumac we can jump a quick call to not wait for our design call

**Comment by a-rukin** [comment]
@tomothespian pls check that BG of 
https://zpl.io/aw4EyB7 - connecting 
https://zpl.io/VqL6Zk7 - syncing 
are properly applied. Now they seem to me like swapped.

**Comment by gnpf** [comment]
@tomothespian The fixes look great. Waiting on the changes @a-rukin asked to approve.

**Comment by tomothespian** [comment]
@gnpf @a-rukin All requested changes are done and listed in Testing section (6 - 10). Please review.

**Comment by a-rukin** [comment]
image

@tomothespian you changed BG, but forgot to change this small overlays (when "troubles syncing/connecting)

**Comment by tomothespian** [comment]
> image
> 
> @tomothespian you changed BG, but forgot to change this small overlays (when "troubles syncing/connecting)

@a-rukin For syncing, color is how is defined by design. 
Can you send me proper colors so I can change?

**Comment by nikolaglumac** [comment]
This PR must NOT be merged until we get an approval from @gnpf.

**Pull request merged**
