### PR TITLE
[DEVOPS-533] mantis support in daedalus installer

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by domenkozar** [comment]
@cleverca22 make sure to prepend DEVOPS-533 to commits and cleanup history.

**Comment by nikolaglumac** [comment]
Hi @cleverca22 do you still need this PR?
If not I would like to ask you to close it and delete the branch.
OR if you need it please add DO-NOT-MERGE tag...
#springCleanup :)
Thanks!

**Comment by cleverca22** [comment]
i think we need to remove the conflicting make-installer changes, and get the pure javascript/mantis stuff merged into develop, then i can redo the make-installer stuff against the most recent develop

**Comment by cleverca22** [comment]
ah, the bulk of the commits i'm seeing here are likely due to the target being master not develop, i'll see about redoing things when i get a chance

**Comment by nikolaglumac** [comment]
Sounds like a plan @cleverca22!
I have assigned this PR to you and added DO-NOT-MERGE tag...

**Comment by nikolaglumac** [comment]
@cleverca22 is this PR still needed? Can we close it and delete the branch?

**Pull request closed without merging**
