### PR TITLE
[DDW-262] Tooltip promoting password managers

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR adds tooltip promoting password managers on all password input fields.

## Todos

- [x] Fix info icon color and hover color on all themes
- [x] Align input fields with info icon
- [x] Fix tooltip position

## Screenshots

Screen Shot 2020-08-20 at 4 45 13 PM

Screen Shot 2020-08-20 at 4 45 00 PM

Screen Shot 2020-08-20 at 4 44 42 PM

Screen Shot 2020-08-20 at 4 44 29 PM

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1597067257028100)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
Hi @DeeJayElly. On mac part of the message gets cut off in the edit wallet passphrase screen as in the screenshot below 
Screenshot 2020-08-10 at 15 25 22

**Comment by ManusMcCole** [comment]
Hi @DeeJayElly. The comment above applys  to all Operating systems

**Comment by gnpf** [comment]
@DeeJayElly The text is overlapping this tooltip on Japanese:

Screenshot at Aug 10 12-00-35

**Comment by gnpf** [comment]
@DeeJayElly The icon is not aligned with the text on the last step of wallet restoring:

Screenshot at Aug 10 13-30-07

**Comment by DeeJayElly** [comment]
> @DeeJayElly The icon is not aligned with the text on the last step of wallet restoring:
> 
> Screenshot at Aug 10 13-30-07

fixed

**Comment by DeeJayElly** [comment]
> @DeeJayElly The text is overlapping this icon on Japanese:
> 
> Screenshot at Aug 10 12-00-35

fixed

**Comment by gnpf** [comment]
@DeeJayElly Nice work, all the issues reported above seems to be fixed. I'll still have pending to check on Win and Lin, but I'd like to highlight a minor inconsistency I found:

The space between the text and the **" i "** icons seems to be different on each screen. Here are the screenshots:

- Create new wallet: [JAP](https://drive.google.com/file/d/153QnUdoNs1B0m9Jl9vBcVTdStBTGEnK1/view?usp=sharing), [ENG](https://drive.google.com/file/d/1Kf68fWQANZ0dwfGEhE4hMpChmIqu7sjg/view?usp=sharing)
- Restore a wallet: [JAP](https://drive.google.com/file/d/1k35WB_bJGIX-ooSa-aWhAZ7_I4nVsZu4/view?usp=sharing), [ENG](https://drive.google.com/file/d/1k35WB_bJGIX-ooSa-aWhAZ7_I4nVsZu4/view?usp=sharing)
- Change password: [JAP](https://drive.google.com/file/d/1s2koGEi6AR4AxMtYnD9x3Tjn7iPrCKln/view?usp=sharing), [ENG](https://drive.google.com/file/d/1ZRXAm8soAJczmhNmwH9CKCKNkoKAQKw6/view?usp=sharing)

**Comment by DeeJayElly** [comment]
> @DeeJayElly Nice work, all the issues reported above seems to be fixed. I'll still have pending to check on Win and Lin, but I'd like to highlight a minor inconsistency I found:
> 
> The space between the text and the **" i "** icons seems to be different on each screen. Here are the screenshots:
> 
> * Create new wallet: [JAP](https://drive.google.com/file/d/153QnUdoNs1B0m9Jl9vBcVTdStBTGEnK1/view?usp=sharing), [ENG](https://drive.google.com/file/d/1Kf68fWQANZ0dwfGEhE4hMpChmIqu7sjg/view?usp=sharing)
> * Restore a wallet: [JAP](https://drive.google.com/file/d/1k35WB_bJGIX-ooSa-aWhAZ7_I4nVsZu4/view?usp=sharing), [ENG](https://drive.google.com/file/d/1k35WB_bJGIX-ooSa-aWhAZ7_I4nVsZu4/view?usp=sharing)
> * Change password: [JAP](https://drive.google.com/file/d/1s2koGEi6AR4AxMtYnD9x3Tjn7iPrCKln/view?usp=sharing), [ENG](https://drive.google.com/file/d/1ZRXAm8soAJczmhNmwH9CKCKNkoKAQKw6/view?usp=sharing)

All stated issues are fixed, pls recheck it now @gnpf

**Review by mioriohk — APPROVED** [review]
Looks good 👍

**Review by ManusMcCole — APPROVED** [review]

**Pull request merged**
