### PR TITLE
[DDW-486] Close Newsfeed on Blur

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR implements the small UX feature of closing the Newsfeed when clicking anywhere else in the UI:

## Screenshots

ddw-486 close newsfeed on blur

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1606402935471400)
- [ ] Please test anything related to the Newsfeed (opening, closing, interacting with news items, etc.)

## Testing Summary

For build 15390

**Fixed**
1 - When the user clicks on Language, Number Format, Date Format or time format the Newsfeed does not automatically close. See  <a href="https://drive.google.com/file/d/13LfYunXxP9h2p_NufscI_8wuYIFfhKrF/view?usp=sharing">video</a>
2 - When I clicked on the grey out area of "Join" and "Import", the Newsfeed didn't close. Please see recording [here](https://drive.google.com/file/d/1AJGtdookhq87ip6j7jFfq_tdQ-JoCGb4/view?usp=sharing). Addition: I have taken a screenshot and highlighted the problematic areas in red rectangles [See here](https://drive.google.com/file/d/1aP9cKO-HeS78uQQtJcN12q2ILU32LW11/view?usp=sharing)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by mioriohk** [comment]
Hi @DominikGuzei . For build 15340:

All looks good to me except when I clicked on the grey out area of "Join" and "Import", the Newsfeed didn't close. Please see recording [here](https://drive.google.com/file/d/1AJGtdookhq87ip6j7jFfq_tdQ-JoCGb4/view?usp=sharing)

**Comment by ManusMcCole** [comment]
Hi @DominikGuzei. Very minor or perhaps not an issue at all. Similar to Miors findings when the user clicks on Language, Number Format, Date Format or time format the Newsfeed does not automatically close. See  <a href="https://drive.google.com/file/d/13LfYunXxP9h2p_NufscI_8wuYIFfhKrF/view?usp=sharing">video</a>

**Comment by DominikGuzei** [comment]
Thanks, @mioriohk, and @ManusMcCole - I will look into these issues 👍

**Comment by DominikGuzei** [comment]
@mioriohk @ManusMcCole please re-check, I generalized the logic so it should work in any scenario now!

**Comment by mioriohk** [comment]
@DominikGuzei , this is the current findings for build 15388. Only pending issue listed. I have moved fixed issue into testing summary above.

**Pending**
1 - When I clicked on the grey out area of "Join" and "Import", the Newsfeed didn't close. Please see recording [here](https://drive.google.com/file/d/1AJGtdookhq87ip6j7jFfq_tdQ-JoCGb4/view?usp=sharing). Addition: I have taken a screenshot and highlighted the problematic areas in red rectangles [See here](https://drive.google.com/file/d/1aP9cKO-HeS78uQQtJcN12q2ILU32LW11/view?usp=sharing)

**Comment by DominikGuzei** [comment]
@mioriohk I also tested this and it worked for me 🤔

**Comment by DominikGuzei** [comment]
@mioriohk oh I just double-checked and indeed it doesn't work 👍 will debug

**Comment by nikolaglumac** [comment]
@DominikGuzei is this ready for testing again?

**Comment by DominikGuzei** [comment]
@nikolaglumac @mioriohk yes, ready for final testing 👍

**Comment by mioriohk** [comment]
Hi @DominikGuzei . Looks good to me on build 15390

**Fixed**
1 - When I clicked on the grey out area of "Join" and "Import", the Newsfeed didn't close. Please see recording [here](https://drive.google.com/file/d/1AJGtdookhq87ip6j7jFfq_tdQ-JoCGb4/view?usp=sharing). Addition: I have taken a screenshot and highlighted the problematic areas in red rectangles [See here](https://drive.google.com/file/d/1aP9cKO-HeS78uQQtJcN12q2ILU32LW11/view?usp=sharing)

**Review by mioriohk — APPROVED** [review]
Great job @DominikGuzei . Approved. 👍

**Review by ManusMcCole — APPROVED** [review]
Looks good 👍

**Review by nikolaglumac — APPROVED** [review]
Great work @DominikGuzei 💯

**Pull request merged**
