### PR TITLE
[DDW-856] Update storybook dependencies

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR updated storybook dependencies.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-856)

## Todos
- [x]  Update storybook dependencies such as `@storybook/react`, and etc.
- [x]  Check `yarn.lock` to see if bad entires were added
- [x]  Check terminal to see if everything was installed properly
- [x]  Make sure that all `yarn ...` scripts work well

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1583313516103900)

- [ ] Test storybook stories

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by tomothespian** [comment]
@yakovkaravelov I can fix CI failures If you want?

**Comment by tomothespian** [comment]
@yakovkaravelov please check this WARNINGS, probably that caused CI to fail:
Screen Shot 2020-03-04 at 11 55 53

**Comment by ManusMcCole** [comment]
There seems to be an issue in Storybook with rendering the experimental features page. Decentralization -> Staking-> Delegation Centre -Experimental Feature. The user cannot scroll down and half of the one visible line is cut off 
image

**Comment by tomothespian** [comment]
@ManusMcCole PR is in WIP state!

**Comment by tomothespian** [comment]
@yakovkaravelov CI is ok now. Please investigate the console warning I posted above!

**Comment by tomothespian** [comment]
@yakovkaravelov please don't use `force-push` . We had huge problem last time we did that

Screen Shot 2020-03-05 at 12 04 45

**Comment by tomothespian** [comment]
@yakovkaravelov also, please fix resolution issue. I fixed that and after your commit is here again!

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov please don't use `force-push` . We had huge problem last time we did that
> 
> Screen Shot 2020-03-05 at 12 04 45

Sometimes, we need to remove chore commits, or refactor, that's why I used that.
And also, huge problem comes when force-push removes important commits.
I just wanted to clear above commits and fix warnings, and build issues in new commit. That's why I did it.
But anyway, if force-push is not preferable in the project, I will not use it.
Thanks, Tomislav.

**Comment by tomothespian** [comment]
@yakovkaravelov CI pass. Please ensure that PR is provided to QA team!

**Comment by ManusMcCole** [comment]
The issue I had previously posted above still persists in the page  Decentralization -> Staking-> Delegation Centre -Experimental Feature

**Comment by ManusMcCole** [comment]
There appears to be some sort of issue rendering Wallets-> Transfer Funds-> Step2 . The image below appears. It generally appears after clicking between themes a few times 
image

**Comment by yakovkaravelov** [comment]
@ManusMcCole These bugs were not generated from this task implementation, but anyway, will fix it in next commit.
Thanks.

**Comment by yakovkaravelov** [comment]
@ManusMcCole It was fixed. Thanks.

**Comment by ManusMcCole** [comment]
Good job @yakovkaravelov

**Comment by nikolaglumac** [comment]
@tomothespian please review this one today 🙏

**Comment by yakovkaravelov** [comment]
@nikolaglumac @tomothespian Oh, you guys merged before I push final commit. :(

**Comment by nikolaglumac** [comment]
@yakovkaravelov hope it was nothing big - please add it to your next PR (DDW-854)
cc @tomothespian

**Comment by yakovkaravelov** [comment]
@nikolaglumac @tomothespian Ok, thanks guys.

**Pull request merged**
