### PR TITLE
[DEVOPS-13]  webpack:  provide a developer-oriented launcher-config.yaml

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@deepfire this issue is already fixed in this PR: https://github.com/input-output-hk/daedalus/pull/867
Commit: https://github.com/input-output-hk/daedalus/pull/867/commits/1722f39e2c06dabaaca1d278b8269c7a60e88a71
...but that PR targets the `release/0.10.0` branch. Do you think we should still keep your PR?

**Comment by deepfire** [comment]
Superceded by https://github.com/input-output-hk/daedalus/pull/867

**Comment by deepfire** [comment]
Reopening, as per Nikola's suggestion that it's unclear on when his version will hit `develop`..

**Comment by nikolaglumac** [comment]
@deepfire approved! Please merge as soon as CI is done...

**Pull request merged**
