### PR TITLE
WIP - [CSLA-62] Use $INSTDIR for Windows shortcut.

### PR DESCRIPTION
**Pull request by jmitchell**
Should fix installations to non-default paths.

This doesn't yet make the shortcut target a batch file instead. Manual testing of that approach raised some other issues. Investigating that while this minimal fix builds.

### CODE REVIEW

**Comment by jmitchell** [comment]
This initial approach didn't work. `$INSTDIR` appears verbatim in the shortcut link itself.

**Comment by jmitchell** [comment]
The generated nsi script escapes `$INSTDIR`, e.g. `$\"$\"$$INSTDIR\cardano-node.exe$\"$\"`

**Comment by domenkozar** [comment]
Yeah I remember that's why I hardcoded it :)

**Comment by domenkozar** [comment]
@jmitchell can we write `.bat` file using nsis variables?

**Comment by jmitchell** [comment]
@domenkozar: Perhaps, although at the moment I'm not focused on using `.bat`. Running `cardano-launcher.exe` directly from cmd or batch files tend to result in an `hPutChar: invalid argument (Bad file descriptor)`. I need to diagnose/fix that first.

**Pull request closed without merging**
