### PR TITLE
[DDW-1118] Use next epoch info from the Api

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR changes Delegation Center Epoch info to use it from the API.

## Screenshots

Screenshot 2019-12-12 at 10 09 04
Screenshot 2019-12-12 at 10 09 10

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1575985457331200)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
https://zpl.io/agBvE5Q - here is an example of how it should look like with 5 seconds left

**Comment by DmitriiGaico** [comment]
CountDown
When the countdown is done the timer becomes narrowed!

**Comment by nikolaglumac** [comment]
@DmitriiGaico that was already reported https://github.com/input-output-hk/daedalus/pull/1751#issuecomment-564064908

**Comment by DeeJayElly** [comment]
> https://zpl.io/agBvE5Q - here is an example of how it should look like with 5 seconds left

Fixed

**Comment by DeeJayElly** [comment]
> @DmitriiGaico that was already reported [#1751 (comment)](https://github.com/input-output-hk/daedalus/pull/1751#issuecomment-564064908)

Fixed

**Comment by a-rukin** [comment]
image
@DeeJayElly can we apply transparent styles to leading zeroes as here - https://zpl.io/agBvE5Q

**Comment by nikolaglumac** [comment]
@DeeJayElly if that is not easy to do I would suggest we merge it as is.
cc @a-rukin

**Comment by DeeJayElly** [comment]
> preapproving
> if hard to do transparent zeroes now, pls create a card for this

Done

**Pull request merged**
