### PR TITLE
[DDW-162, DDW-163] Fix 'Wallet import' UI/UX issues

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR fixes:

- Restores "learn more" link on the first "Wallet import" dialog
- Updates open/save dialogs to use "Desktop" as default path for opening/saving files
- Resets "Wallet import" dialog values on open
- Fixes wallet rename success message flashing on "Wallet settings" screen
- Fixes wallet screens scrollbar issue when active restoration notification is shown
- Fixes "Wallet import" exception dialog locale

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test fixes listed above.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
On MacOS only there is an issue where the loading box flickers when a selected wallet import is loading. The box intermittently dissapears and reappears
LoadingBoxFlickering

**Comment by nikolaglumac** [comment]
@ManusMcCole I don't see this issue on my mac. I believe this is due to the fact you were testing on a macOS VM.
@DeeJayElly @daniloprates @tomothespian please test this on your Mac's and let us know the results.

@DmitriiGaico @IuliaDolishniak @gnpf please check if you can reproduce this on Linux/Windows and please make sure to use real machines and not VMs.

**Comment by nikolaglumac** [comment]
@DmitriiGaico I have added a fix for https://jira.iohk.io/browse/DDW-163 into this PR. Please test that as too 🙏

**Comment by DmitriiGaico** [comment]
@nikolaglumac Disappearing button is showed for MacOS vms only. At Linux/Windows button works as expected.

**Comment by nikolaglumac** [comment]
@gnpf @alan-mcnicholas can you confirm this bug on your macOS VM?

I would like to hear if any of the developers face the same issue on their real macs @tomothespian @DeeJayElly @yakovkaravelov @daniloprates 🙏

**Comment by darko-mijic** [comment]
I can't reproduce this on a real Mac with the installer from this PR.

image

**Comment by ManusMcCole** [comment]
Gabriela also experienced this issue on her Mac VM on Friday

**Comment by nikolaglumac** [comment]
OK. If this can only be produced on VMs then I am fine with ignoring this issue...

**Comment by darko-mijic** [comment]
Completely agree @nikolaglumac. Merge away.

**Pull request merged**
