### PR TITLE
[DDW-280] Update copy for Shelley Testnet

### PR DESCRIPTION
**Pull request by daniloprates**
This PR updates the following copy:

https://docs.google.com/document/d/1mf6P1yCCMN9vHl95XIuQMeM_wERDCJpERN4L-RlZibo/edit

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1592575105074300)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
I am seeing an error where Daedalus turns in to a blank white screen. Once I refresh it goes back to normal but happens again after a short interval. This happens on Flight and Shelley Testnet builds
ezgif com-video-to-gif (2)

**Comment by ManusMcCole** [comment]
Here is the error message as it not clear from the video.This is on the windows builds. Checking Mac now.
 Uncaught Invariant Violation: [React Intl] An `id` must be provided to format a message at invariant (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/index.js:38522:15)
    at formatMessage (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/index.js:63908:51)
    at formatHTMLMessage (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/index.js:63968:10)
    at FormattedHTMLMessage.render (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/index.js:64800:34)
    at Ro (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/vendor.dll.js:59:69876)
    at Io (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/vendor.dll.js:59:69671)
    at yu (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/vendor.dll.js:59:105470)
    at ls (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/vendor.dll.js:59:96717)
    at us (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/vendor.dll.js:59:96642)
    at Qu (file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/vendor.dll.js:59:93672)
DevTools failed to parse SourceMap: file:///C:/Program%20Files/Daedalus%20Flight/resources/app/dist/renderer/preload.js.map

**Comment by gnpf** [comment]
@daniloprates The same issue @ManusMcCole mentioned is also reproducible in Linux. In this case, I was trying to restore a wallet, so when I selected the type, the blank screen was displayed:

image

**Comment by ManusMcCole** [comment]
Reproducible across all Platforms

**Comment by daniloprates** [comment]
@ManusMcCole @gnpf ⏳ checking...

**Comment by daniloprates** [comment]
@ManusMcCole @gnpf fixed the issue.

**Comment by ManusMcCole** [comment]
Hi @daniloprates. Byron Wallets are not showing correctly in the sidebar. When I click in to another wallet there is no way to navigate back to the Byron Wallet
ByronError

**Comment by ManusMcCole** [comment]
Byron Wallet issue happens across all Operating Systems

**Comment by daniloprates** [comment]
> Byron Wallet issue happens across all Operating Systems

@ManusMcCole could you send me this mnemonics set?

**Comment by ManusMcCole** [comment]
> > Byron Wallet issue happens across all Operating Systems
> 
> @ManusMcCole could you send me this mnemonics set?

Hi Danilo. Sure here it is ....loyal,hurry,wall,fame,police,mushroom,delay,hint,board,assist,forum,exit

**Comment by daniloprates** [comment]
> Byron Wallet issue happens across all Operating Systems

Thanks, Manus. I ended up removing a check to disable Byron wallets restoration:

Screen Shot 2020-06-22 at 14 09 45

**Pull request merged**
