### PR TITLE
[DDW-173] Submit forms on Enter key

### PR DESCRIPTION
**Pull request by daniloprates**
This PR enables submitting forms on Enter key press.

## Todo:

- [x] Submit forms on Enter key
- [x] Enable it in the Confirm Transaction dialog
- [x] Add the `:focus` state style to all buttons
- [x] Replace `onMouseUp` to `onClick` on buttons, so it can be triggered by pressing Enter
- [x] Define the buttons `:focus` state style and colors for the 3 Daedalus themes (@a-rukin)

## Screenshots

image
image
image
image
image

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`npm run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`npm run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`npm run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`npm run flow:test`)
- [ ] There are no *lint* errors or warnings (`npm run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `npm run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`npm run storybook`)
- [ ] In case of npm dependency changes both `package-lock.json` and `yarn.lock` files are updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by daniloprates** [comment]
@nikolaglumac probably not the best [way](https://github.com/input-output-hk/daedalus/pull/981/commits/51ef1d3a48bbdb0b3579e6758eb746aa1c23659f) to handle the "submit on enter" in the Send dialog.

**Comment by nikolaglumac** [comment]
@daniloprates there are some flow/lint issues detected by the CI check.
Also, I don't think we need "Enter" key submission for this dialog.
Let's narrow down this feature just to the form input elements. E.g. only if some input is focused - only then it should be possible to submit by the enter key. Before we do it like that I would like to hear what @DominikGuzei thinks about it.

**Comment by daniloprates** [comment]
@nikolaglumac it makes sense, although, from a user perspective, it feels right to have it, when submitting the previous form with Enter. Waiting for @DominikGuzei's opinion.

**Comment by nikolaglumac** [comment]
@daniloprates if that is what you want to have then we must have some kind of a active button state outline/glow on the active element - in this case the blue submit button.

**Comment by DominikGuzei** [comment]
Yeah i agree with both of you - UX wise it would be nice to be able to submit all dialogs too with ENTER but then the submit button needs a glow / active state

**Comment by daniloprates** [comment]
Cool, I'll give it a try

**Comment by nikolaglumac** [comment]
The question is where to put an end to this feature - e.g. should the user also be able to use TAB key to switch between the fields and also change the focus of the buttons?

**Comment by daniloprates** [comment]
@nikolaglumac yes, I was thinking of changing my approach to a simple focus in the confirm button.

**Comment by nikolaglumac** [comment]
@daniloprates OK let's see how it will look and feel ;)

**Comment by daniloprates** [comment]
I like the solution. It feels good to use Enter when you've just used in the previous form. 

image

The code is also much cleaner:
image

Looking forward to hear from you @nikolaglumac @DominikGuzei

**Comment by nikolaglumac** [comment]
@a-rukin what do you think about the active button state? Do you like what @daniloprates is proposing or you have some better idea?

**Comment by a-rukin** [comment]
Is this dotted line shown only when hovered by tab?

**Comment by daniloprates** [comment]
@a-rukin nope, only in the `:focus` state.

**Comment by a-rukin** [comment]
@daniloprates how this focus state can be achieved?

**Comment by a-rukin** [comment]
Also what happens on focus with grey bbutton?

**Comment by daniloprates** [comment]
@a-rukin this is the state where you can press Space or Enter to click the button. It can be achieve via javascript (`<button autofocus ...` and `button.focus()`) or when you mousedown a button and move the mouse arrow away from it.

I've chosen the light themes color based in the default Chrome outline color: #3b99fc. For the dark theme I've just chosen a lighter version of its background color. It's just a suggestion, feel free to choose more appropriate colors.

Bellow is how it looks in the dark theme:

image

**Comment by a-rukin** [comment]
So if we press "Tab" button it should be the same, right?
Colors are fine

**Comment by Syeikhleiman** [comment]
How to get the Daedalus wallet address plz

**Comment by daniloprates** [comment]
@DominikGuzei ✓

**Comment by a-rukin** [comment]
41667241-d9b45f18-7482-11e8-88ca-623050a04c6f
Seems border lacks opacity

**Comment by daniloprates** [comment]
@a-rukin that's right, I hadn't realized the opacity. 

image

**Comment by a-rukin** [comment]
Looks good!

**Comment by nikolaglumac** [comment]
Great work @daniloprates! We can merge this PR as soon as CI is done...

**Comment by ShimShamSam** [comment]
Why not just bind to the ["submit" event](https://developer.mozilla.org/en-US/docs/Web/Events/submit) of the form instead of listening for a keypress or mouse click individually?

**Comment by daniloprates** [comment]
@ShimShamSam all forms had been done this way, so it was easier and safer to implement the "Enter" this way.

**Pull request merged**
