### PR TITLE
Fix/daef 375 Change node-update UI text messages

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR implements node-update wording change, default update title & message and fixes layout issues.

## TODOs
- [x] Inject missing Japanese translations:
```
"cardano.node.update.notification.titleWithVersion": "Cardano-Core update v{version} is available",
"cardano.node.update.notification.titleWithoutVersion": "Cardano-Core update is available",
"cardano.node.update.notification.accept.button.label": "Update and restart",
"cardano.node.update.notification.postpone.button.label": "Postpone until restart",
"cardano.node.update.notification.message": "Daedalus and Cardano node update is available. Would you like to install the update?"
```

screen shot 2017-07-19 at 11 18 16
screen shot 2017-07-19 at 13 40 16

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei @darko-mijic before this PR is merged we must inject missing Japanese translations (you can find the details in PR's description).

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei Japanese translations are now up to date. This PR can now be reviewed and merged after that ;)

screen shot 2017-07-20 at 12 07 40

**Comment by a-rukin** [comment]
@nikolaglumac let's expand paddings a bit:
1) inside buttons (at least by half, ideally to 30px)
2) left and right side of notification (text should start from same line as "menu icon")
https://zpl.io/1IEH6N

**Comment by nikolaglumac** [comment]
@a-rukin is it better now? :)
...I had to set max width in order to make the buttons the same width since the text length varies...

screen shot 2017-07-20 at 13 39 19
screen shot 2017-07-20 at 13 39 24

**Comment by a-rukin** [comment]
@nikolaglumac are paddings 50px?

**Comment by nikolaglumac** [comment]
@a-rukin I have not moved the menu icon. Now both the icon and left/right paddings are set to 50px as it is in the design. Do you want me to set both the icon and the paddings to 40px?

**Comment by nikolaglumac** [comment]
@a-rukin I have reduced the left/right paddings to 40px. Also the menu icon is moved to the left to keep it in line with the text... Is it OK now?

screen shot 2017-07-20 at 19 07 47

**Comment by darko-mijic** [comment]
@a-rukin is this OK now? This PR contains an important fix and we need to merge it ASAP.

**Comment by a-rukin** [comment]
It is good

**Pull request merged**
