### PR TITLE
[DDW-1151] Implement acceptance tests for "Rewards" screen

### PR DESCRIPTION
**Pull request by tomothespian**
This PR implemented acceptance tests for staking rewards screen.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-1151)

## Todos
- [x] "No rewards" message is shown if user has no Rewards wallets in the UI
- [x]  Correct display of rewards
- [x]  Export to CSV feature is working

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1582579763016400)

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by tomothespian** [comment]
@yakovkaravelov I made some changes. Please take a look. The most important thing while preparing E2E tests is to not modify code to force tests to pass especially Stores. Always prepare tests to cover current logic and test if works.
Also now you can prepare one more scenario `Export to CSV feature is working`. Added to TODO list

**Comment by nikolaglumac** [comment]
@daniloprates can you please review this one? 🙏

**Comment by yakovkaravelov** [comment]
@nikolaglumac This was fixed. Please review again. Thanks.

**Comment by tomothespian** [comment]
@yakovkaravelov I already fixed that. Please revert back this: https://github.com/input-output-hk/daedalus/pull/1861/commits/c387bc6fd6a462a24f0f2574faed276cacc3445d#diff-a1eb7c890a9c0d1dd0db71a89645ee06L209

That is not a valid fix because you can't just remove the error handler because it causes error. It causes error because that was true!

**Comment by nikolaglumac** [comment]
@yakovkaravelov this doesn't work :(

Screenshot 2020-02-27 at 10 54 10

**Comment by nikolaglumac** [comment]
@yakovkaravelov perhaps the unlink should be within try/catch block?

**Comment by tomothespian** [comment]
@yakovkaravelov I reverted back error handler.
@nikolaglumac you can test now

**Pull request merged**
