### PR TITLE
Fix/daef 370 Replace all CSS hardcoded values by variables

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces replacement of hardcoded CSS values with variables.

## TODOs
- [x] Inject missing Japanese translations (screenshot will be posted in comments)
```
"settings.display.themeLabel": "!!!Theme",
"settings.menu.display.link.label": "!!!Themes",
```
### FOR ALL THEMES
- [x] Add real themes thumbnails for the settings page
- [x] Add real themes names for the settings page
- [x] Switch all* icons to SVG (* wallet menu icons, transactions icons: https://app.zeplin.io/project/57acfaa7436a750316161a8b/screen/58e36fc7ae2d423d44bc0703)
- [x] Inspect all button colors
- [x] Inspect input fields error message opacity/color
- [x] Inspect node-update notification styling
- [x] Connecting screen background color (initial fade)

### DARK THEME
- [x] Update active state border color for all input elements
- [x] [Receive screen] QR code color
- [x] [Receive screen] Copy address link color, Hide used link color opacity increase opacity by 0.15
- [x] [Transactions] Incoming/Outgoing transaction icon colors
- [x] [Transactions] Low/Med/High tag color
- [x] [Transactions] Ada symbol color
- [x] [Wallet Settings] Delete wallet link color (like standard red button)
- [x] [Settings] Right menu active item background color: #0b1926

## Themes:
screen shot 2017-07-28 at 15 49 28
screen shot 2017-07-28 at 15 49 24
screen shot 2017-07-28 at 15 49 19

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@darko-mijic please request and inject missing Japanese translations:
```
"settings.display.themeLabel": "!!!Theme",
"settings.menu.display.link.label": "!!!Themes",
```

translations

**Comment by darko-mijic** [comment]
We need to update icon colors for the dark theme. Here are the design specs:

263345-summary
263345-send

**Comment by darko-mijic** [comment]
Here are the translations @tomothespian and @nikolaglumac:
```
“settings.display.themeLabel”: “テーマ“,
“settings.menu.display.link.label”: “テーマ“,
```

**Comment by nikolaglumac** [comment]
@darko-mijic thanks for the translations! I have just injected them in the code ;)

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei all icons are now replaced by SVG files and adjusted for each of the themes.
Also all other items from the checklist in the PR's description are solved and tested.
We are ready for review and merge of this `gigantic` PR :)

screen shot 2017-08-19 at 11 11 25

screen shot 2017-08-19 at 11 12 32

screen shot 2017-08-19 at 11 12 38

**Comment by darko-mijic** [comment]
Reviewing this now.

**Comment by nikolaglumac** [comment]
Thanks @darko-mijic!
Full credit goes to @tomothespian :)

**Pull request merged**
