### PR TITLE
[DDW-606] Reveal / hide action improvements

### PR DESCRIPTION
**Pull request by aleksandardjordjeviciohk**
This PR improves reveal / hide action by adding an eye icon to show/hide public key value.

## Screenshots

Screen Shot 2021-03-23 at 12 28 20 PM

Screen Shot 2021-03-23 at 12 28 40 PM

Screen Shot 2021-03-23 at 12 28 53 PM

Screen Shot 2021-03-23 at 12 32 53 PM

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616525747089200)

## Test Cases

```Gherkin
Scenario 1: Reveal tooltip
Given I am on Reveal public key section
When I hover on the reveal icon
Then ‘Reveal’ tooltip is displayed

Scenario 2: Select reveal icon
Given I am on Reveal public key section
When I select reveal icon
Then it will change to hide icon
And ‘Hide’ tooltip is displayed
And the public key will be displayed in the textfield

Scenario 3: Select hide icon
Given I am on Reveal public key section
And hide icon is displayed
When I select hide icon
Then it will change to reveal icon
And ‘Reveal’ tooltip is displayed
And the public key will be hidden from the textfield
```
---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@aleksandardjordjeviciohk @nikolaglumac the text copy says "click the 'reveal' button" - but I'm not sure if it's totally clear that the eye icon is the "reveal" button

**Review by DominikGuzei — APPROVED** [review]
The code looks good 👍 I think the text copy within the public key input field could be improved to say something like "click the reveal icon to the right" or "the eye icon" … but its also a minor issue

**Comment by nikolaglumac** [comment]
> The code looks good 👍 I think the text copy within the public key input field could be improved to say something like "click the reveal icon to the right" or "the eye icon" … but its also a minor issue

We need @darko-mijic's, @daniloprates' and @alexander-rukin's support with this 🙏

**Comment by nikolaglumac** [comment]
@miorsufianiohk please test this one and please ignore this text part https://github.com/input-output-hk/daedalus/pull/2473#pullrequestreview-619549315 - we will update it!

**Comment by miorsufianiohk** [comment]
@nikolaglumac , I have tested 17258 and left comments on slack [here](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616580553106100?thread_ts=1616525747.089200&cid=GGKFXSKC6). According to @alexander-rukin the button focus state shouldn't be [there](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616583203107700?thread_ts=1616525747.089200&cid=GGKFXSKC6) cc: @aleksandardjordjeviciohk

**Comment by aleksandardjordjeviciohk** [comment]
@miorsufianiohk @alexander-rukin can you pls recheck once again. I have removed focus on buttons.

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Tested on 17278. Great work @aleksandardjordjeviciohk 👍

**Comment by aleksandardjordjeviciohk** [comment]
@darko-mijic @nikolaglumac Copy was updated

**Pull request merged**
