### PR TITLE
[DDW-284] Merge release 0.10.0 branch into develop - FORK

### PR DESCRIPTION
**Pull request by nikolaglumac**
**This is a FORK of PR: https://github.com/input-output-hk/daedalus/pull/940**

This PR merges `release/0.10.0` into develop branch.

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`npm run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`npm run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`npm run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`npm run flow-test`)
- [ ] There are no *lint* errors or warnings (`npm run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `npm run manage-translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`npm run storybook`)
- [ ] In case of npm dependency changes both `package-lock.json` and `yarn.lock` files are updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei @darko-mijic this is a PR which merges `release/0.10.0` into `develop`.
I had to create a fork of `release/0.10.0` branch in order to fix the conflicts.
This is done within the commit: https://github.com/input-output-hk/daedalus/pull/941/commits/69df85bafb166262fa8dfb08d7cde5496da0cd65
Please inspect this with great detail as I had to replace the "magical strings" within the new Ada redemption code and fix some other issues.

Once we merge this PR the original one (https://github.com/input-output-hk/daedalus/pull/940) should show no conflicts too - perhaps that one will become obsolete after that moment...

**Comment by nikolaglumac** [comment]
@cleverca22 @deepfire could one of you guys please review the devops changes in this PR?
We had 4 conflicts that @rvl helped me to resolve. Still I would like to have at least one more approval from your team. Thanks!

**Comment by DominikGuzei** [comment]
@nikolaglumac so from what i see this is basically your ada redemption PR (without magic constants) + some devops changes, right? All tests pass, green light from my side 👍

**Comment by DominikGuzei** [comment]
@nikolaglumac is this ready to be merged?

**Comment by nikolaglumac** [comment]
@DominikGuzei it was but then something new was added to develop and now we have a failing CI: https://hydra.iohk.io/build/133841/nixlog/1
...I guess we need to fix it before merging.

**Comment by nikolaglumac** [comment]
@DominikGuzei we had few lint issues and a broken `purge-translations` script which was only partially renamed to `purge:translations`. All fixed now in: https://github.com/input-output-hk/daedalus/pull/941/commits/4ee6b5bb6e51c15ebf8867f39462c3ffb6e11e74
...once CI passes we can merge this one 👍

**Comment by nikolaglumac** [comment]
@DominikGuzei please approve this one 🙏 
We need to get it merged before Monday...

**Comment by nikolaglumac** [comment]
@cleverca22 can you please check why appveyor build is failing? :( Thanks!

**Pull request merged**
