### PR TITLE
DAEF-432 Update the changelog for the 0.8.0 as a next release

### PR DESCRIPTION
**Pull request by darko-mijic**
This PR prepares the changelog and application version for the 0.8.0 release.
There is no need to go over the complete review checklist when reviewing this PR since there were no changes to the application code.

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@darko-mijic what about this version? https://github.com/input-output-hk/daedalus/blob/master/app/containers/TopBarContainer.js#L20
This one stays the same or?

**Comment by darko-mijic** [comment]
@nikolaglumac: Cardano SL and Daedalus have different versions. Versions are not tied together.

**Comment by nikolaglumac** [comment]
@darko-mijic I know that :)
I just thought that we need to bump the Cardano SL version too...

**Comment by darko-mijic** [comment]
I will merge this one before the CI completes since no code was modified and having this not merged creates merge conflicts in new PRs and we have to resolve them and wait for the CI again.

**Pull request merged**
