### PR TITLE
Fix/daef 541 Fix all post ETC integration translation issues

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR introduces translation issues fixed introduced with ETC integration and several other important improvements:
- Api specific CSS file names must contain Api suffix (e.g. for ETC `Example.css` file should be named `ExampleEtc.css` in order to avoid CSS class names conflicts)
- Resolver update (in case resolved file contains default export it is automatically returned)
- Ensure transaction groups ordering by descending group date on Transactions and Summary screens
- Added specific Japanese translations for ETC transaction details (`From/To Address` instead of `From/To Addresses` / singular in place of plural form)
- Prevent validation on blur of Send Form fields (which caused text flicker on Transaction Confirmation Dialog)
- Update Electron version in `webpack/package.js`
- Various flow and lint issues fixes
- ETC dummy wallet data has been updated to match default local Mantis instance wallet keys
- All unused parts of the application such as Staking and Export-Paper-Wallet have been commented out

### TODO:
- [x] Inject missing Japanese translations:
```
"wallet.transaction.address.from": "!!!From address",
"wallet.transaction.address.to": "!!!To address",
```

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei we are still waiting for missing translations but otherwise this PR is ready for review.

**Comment by DominikGuzei** [comment]
Reviewing this now …

**Comment by DominikGuzei** [comment]
@nikolaglumac great work! Can be merged as soon as Japanese translations are ready 👍

**Comment by nikolaglumac** [comment]
@DominikGuzei we are now ready for the merge - I have just injected missing Japanese translations.
Please approve and merge at will :)

**Pull request merged**
