### PR TITLE
[DDW-924] Create link component

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces React-Polymorph "Link" component integration.

## Todos

- [x] Update react-polymorph to the latest version which includes `Link` component once is ready
- [x] Check components one more time and add RP `Link` component or `ButtonLink` widget if miss on some places
- [x] Add CHANGELOG once PR is ready

## Screenshots

_1  Nodes -  Syncing and Connecting -  System Time Error (NTP reachable)"_
1  Nodes -  Syncing and Connecting -  System Time Error (NTP reachable)

_1.1  Nodes -  Syncing and Connecting -  System Time Error"_
1.1  Nodes -  Syncing and Connecting -  System Time Error

_2  General -  Support"_
2  General -  Support

_3  Nodes -  Splash -  Network Info"_
3  Nodes -  Splash -  Network Info

_4  Decentralization -  Staking -  Rewards"_
4  Decentralization -  Staking -  Rewards

_5  Decentralization -  Staking -  Pool Index"_
Screen Shot 2020-01-13 at 12 41 20

_6  Nodes -  About -  About Dialog"_
6  Nodes -  About -  About Dialog

_7  Nodes -  Status -  Daedalus Diagnostics"_
7  Nodes -  Status -  Daedalus Diagnostics

_8  Wallets -  Paper Wallets -  Completion"_
8  Wallets -  Paper Wallets -  Completion

_9  Wallets -  Paper Wallets -  Instructions"_
9  Wallets -  Paper Wallets -  Instructions

_10  Wallets -  Transactions"_
10  Wallets -  Transactions

_11  Wallets -  Transactions -  UTXO Distribution"_
11  Wallets -  Transactions -  UTXO Distribution

_13 1 Nodes -  Syncing and Connecting -  Trouble Syncing"_
13 1 Nodes -  Syncing and Connecting -  Trouble Syncing

_13 2 Nodes -  Syncing and Connecting -  Trouble Connecting"_
13 2 Nodes -  Syncing and Connecting -  Trouble Connecting

_14 1  Nodes -  Updates -  Manual Update (Icon and label are inside button)"_
14 1  Nodes -  Updates -  Manual Update (Icon and label are inside button)

_14 2 Common -  Widgets -  ButtonLink"_
14 2 Common -  Widgets -  ButtonLink

_15  News -  Alerts -  Alerts Overlay (Icon and label are inside button)"_
15  News -  Alerts -  Alerts Overlay (Icon and label are inside button)

_16  News -  Incident -  Incident Overlay (Icon and label are inside button)"_
16  News -  Incident -  Incident Overlay (Icon and label are inside button)

_17  News -  NewsFeed -  Fetched (Icon and label are inside button)"_
17  News -  NewsFeed -  Fetched (Icon and label are inside button)

_18  Wallets -  Summary -  Wallet Summary + Legacy Wallet (Icon and label are inside button)"_
18  Wallets -  Summary -  Wallet Summary + Legacy Wallet (Icon and label are inside button)

_19  Decentralization -  Countdown -  Decentralization Countdown"_
19  Decentralization -  Countdown -  Decentralization Countdown

_20  Decentralization -  Staking -  Info"_
20  Decentralization -  Staking -  Info

---

## Testing Checklist

- [Slack QA thread]()

_**Storybook Testing:**_

_1. LINKS WITH / WITHOUT ICON_

- [ ] Test Storybook stories under `Nodes -> Errors -> System Time Error`
- [ ] Test Storybook stories under `Settings -> General -> Support`
- [ ] Test Storybook stories under `Nodes -> Splash -> Network Info`
- [ ] Test Storybook stories under `Decentralization -> Staking -> Rewards`
- [ ] Test Storybook stories under `Decentralization -> Staking -> Pool Index`
- [ ] Test Storybook stories under `Nodes -> About -> About Dialog`
- [ ] Test Storybook stories under `Nodes -> Status -> Daedalus Diagnostics (Available disk space: unknown)`
- [ ] Test Storybook stories under `Wallets -> Paper Wallets -> Completion`
- [ ] Test Storybook stories under `Wallets -> Paper Wallets -> Instructions`
- [ ] Test Storybook stories under `Wallets -> Transactions`
- [ ] Test Storybook stories under `Wallets -> Transactions -> UTXO Distribution`
- [ ] Test Storybook stories under `Wallet Settings -> Wallet Recovery Phrase (Verification Failure Step Dialog)`
- [ ] Test Storybook stories under `Nodes -> Syncing and Connecting -> Trouble Syncing`
- [ ] Test Storybook stories under `Nodes -> Syncing and Connecting -> Trouble Connecting`

_2. BUTTON LINKS_

- [ ] Test Storybook stories under `Nodes -> Updates -> Manual Update (Icon and label are inside button)`
- [ ] Test Storybook stories under `Common -> Widgets -> ButtonLink`
- [ ] Test Storybook stories under `News -> Alerts -> Alerts Overlay (Icon and label are inside button)`
- [ ] Test Storybook stories under `News -> Incident -> Incident Overlay (Icon and label are inside button)`
- [ ] Test Storybook stories under `News -> NewsFeed -> Fetched (Icon and label are inside button)`
- [ ] Test Storybook stories under `Wallets -> Summary -> Wallet Summary + Legacy Wallet (Icon and label are inside button)`
- [ ] Test Storybook stories under `Decentralization -> Countdown -> Decentralization Countdown`
- [ ] Test Storybook stories under `Decentralization -> Staking -> Info`

_**In-App Testing:**_
- [ ] Follow storybook steps and test all in-app related screens. Pay attention that `Link` and `ButtonLink` clicks (open external / internal links) works properly

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@MarcusHurney @tomothespian what's holding us up with this one?

**Comment by tomothespian** [comment]
@nikolaglumac now we have a new RP version with Link component. I will add a new package version and we are ready for review.

**Comment by ManusMcCole** [comment]
For 8 Wallets - Paper Wallets - Completion the text "WalletCertificateAddress" does not get translated as in the screenshot below 
image

**Comment by nikolaglumac** [comment]
@ManusMcCole that's expected... Please ignore this part.

**Comment by IuliaDolishniak** [comment]
there is no 'Learn More' hyperlink on Rewards screen

**Comment by nikolaglumac** [comment]
@IuliaDolishniak it has been removed on purpose. I did this part before I left for my vacation.

**Comment by IuliaDolishniak** [comment]
It is shown on screen and in Storybook @nikolaglumac

**Comment by nikolaglumac** [comment]
@IuliaDolishniak screenshots are old. This link should not be visible neither in Daedalus nor Storybook.

**Comment by tomothespian** [comment]
@IuliaDolishniak there is no "Learn more" link for incentivized testnet. 
You can see in storybook that we have `Rewards` and `Rewards - ITN` stories

**Comment by IuliaDolishniak** [comment]
This is the screenshot from Storybook

**Comment by nikolaglumac** [comment]
@tomothespian please merge latest v2-integration into this PR please!

**Comment by nikolaglumac** [comment]
@DeeJayElly @MarcusHurney @yakovkaravelov please review this one!

**Comment by MarcusHurney** [comment]
**Before we merge**, let's get this question answered by Sasha.
@a-rukin Should the icon have a `margin-right` of 10px or 12px? It is currently set at 12px. I'm going to post some screenshots below showing the difference. I think 12px looks like too much!
(This is is on the decentralization countdown screen's button at the bottom)

**12px**
12px

**10px**
10px

**Comment by tomothespian** [comment]
> I pushed a commit to fix both 😃

@MarcusHurney thanks a lot ❤️

**Comment by a-rukin** [comment]
@MarcusHurney instead of tweaking 10px or 12px I'd unified all these buttons to be **"text+icon"** instead of both (_"icon+text"_ or _"text+icon"_).

**Pull request merged**
