### PR TITLE
[DDW-755] Refactor wallet nav to use new Dropdown

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR refactors the existing dropdown in the wallet navigation ("more") to the new react-polymorph [Dropdown component](https://github.com/input-output-hk/react-polymorph/pull/122).

_Note_: Originally the idea was also to refactor the click-to-open delegation "popup" on the delegation center (click on the cog in storybook) but when i looked into refactoring it i figured that it's already quite customized and would take big effort to refactor to the general purpose RP dropdown component (so there wouldn't be many gains compared to the current way it's based on select component).

## Screenshots

- Before
screenshot 2019-10-15 um 11 48 09

- After
screenshot 2019-10-15 um 15 43 16

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571147157097500)
- [ ] Test the "more" dropdown in the wallet navigation

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@DominikGuzei On the default and smaller resolutions, the second item is split in two rows. Also, the alignment is different from the screenshots. Can this be improved?

image

**Comment by nikolaglumac** [comment]
@a-rukin can you please make sure the font size and the colors are fine? 🙏

**Comment by a-rukin** [comment]
image

for me it shows strange:
- sticked to the right 
- strange width (should be just text width + 24px (12 left and right)
- and has strange fixed position (screenshot below) 

image

**Comment by DominikGuzei** [comment]
@a-rukin @gnpf that's really weird, in local Daedalus for me everything looks correct but i can see the issues you mentoined in the storybook build 🤔 something is off here, need to investigate!

**Comment by DominikGuzei** [comment]
@nikolaglumac no, as mentioned in the PR description the staking delegation dropdown was not refactored since it is customized to a degree where refactoring to the new dropdown component would not bring many benefits apart from a lot of extra work.

**Comment by nikolaglumac** [comment]
Great work @DominikGuzei 💯

**Comment by nikolaglumac** [comment]
Goot catch @DmitriiGaico!

@DominikGuzei it actually looks like the content in Japanese is cut off 😱 

Screenshot 2019-10-17 at 13 03 02

**Comment by nikolaglumac** [comment]
Hope it is a quick fix @DominikGuzei 🙏

**Comment by nikolaglumac** [comment]
@DominikGuzei this commit https://github.com/input-output-hk/daedalus/pull/1593/commits/84933f1fa6c47f500fd5dd4bc1b62cb7aeef9d14 fixes a bug which was introduced in the scope of DDW-33 task: https://github.com/input-output-hk/daedalus/blame/develop/source/renderer/app/stores/WalletsStore.js#L399

I've checked the bug @DmitriiGaico reported and it looks like it is a React-Polymorph issue with open state handling due to hover and click events...

**Comment by DominikGuzei** [comment]
@DmitriiGaico please re-test - the issues with the "more" button should now be fixed 👍

**Comment by DmitriiGaico** [comment]
@DominikGuzei Great, i'll fire it up once build is ready! Thanks!

**Comment by nikolaglumac** [comment]
@DominikGuzei yes - @DmitriiGaico found it. He will post a report.

**Comment by DmitriiGaico** [comment]
@DominikGuzei Hi Dom!
Please see my findings.
When you select "Settings" or "UTXO" the selected Option Should be Bold. If you remain at selected screen and hover over More again The selected option should be Bold but without the background.
I'm attaching records for a reference.
This is how it works Currently in RC2 - All Green.
MoreOptions

And here How it works in PR build - Issue.
MoreOptions_Issue



@nikolaglumac Nikola, please comment if we keep the RC2 logic fully or DropDown should be closed once you select the Settings or UTXO.

**Comment by DmitriiGaico** [comment]
@DominikGuzei Hello Dominik! Do you have any updates for this PR?
Thank you in advance!

**Comment by DominikGuzei** [comment]
@nikolaglumac @DmitriiGaico @gnpf i fixed the remaining issue (selected dropdown option is bold now & dropdown hover covers select options within content area (e.g settings)) and this PR is ready for final review (it is also a pre-requesite to the numeric input number format feature, so it's important to get this merged soon :)

**Pull request merged**
