### PR TITLE
[DDW-42] Update UI copy

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces new UI copy.

## Screenshots

**_1. Update UI copy (English)_**

Screen Shot 2020-03-26 at 10 32 55

Screen Shot 2020-03-26 at 10 47 57

Screen Shot 2020-03-26 at 11 16 13

Screen Shot 2020-03-26 at 11 54 12

Screen Shot 2020-03-26 at 11 54 32

Screen Shot 2020-03-26 at 12 20 53

Screen Shot 2020-03-26 at 12 41 26

Screen Shot 2020-03-26 at 12 51 03

**_2. Update UI copy (Japanese)_**

Screen Shot 2020-03-26 at 10 33 02

Screen Shot 2020-03-26 at 10 49 41

Screen Shot 2020-03-26 at 11 17 08
Screen Shot 2020-03-26 at 12 23 47

Screen Shot 2020-03-26 at 12 24 36

Screen Shot 2020-03-26 at 12 25 17

Screen Shot 2020-03-26 at 12 41 58

Screen Shot 2020-03-26 at 12 52 46

**_3. Changed and kept UI copy (INCENTIVIZED TESTNET)_**

Screen Shot 2020-03-26 at 13 09 15

Screen Shot 2020-03-26 at 13 09 34

Screen Shot 2020-03-26 at 13 10 14

Screen Shot 2020-03-26 at 13 10 27

Screen Shot 2020-03-26 at 13 11 26

Screen Shot 2020-03-26 at 13 48 26

Screen Shot 2020-03-26 at 14 00 51

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1585229273024200)

_In-App testing_
- [ ] Walk through app inside `selfnode` and check if copy changes are correct
- [ ] Walk through app inside`itn_selfnode` and check if copy changes are correct

**NOTES:**
- New UI copy: https://docs.google.com/document/d/1KXt5PpDRD6sQpI7FOcqwSBbcY8V4oh-_pj2m3-lQsAU/edit
- Be careful with testing. Some copy updates are applied only outside Incentivized Testnet and kept under it, especially where phrases and words like `Incentivized Testnet`, `Reward`, `Rewards wallet` are presented.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by darko-mijic** [comment]
Reviewing this now...

**Comment by darko-mijic** [comment]
Great work!

**Comment by ManusMcCole** [comment]
In MacOS Selfnode I see 
image the text reads "Keep your wallet secure by setting a spending password" but in the document it reads "Keep your private keys safely encrypted by settings a spending password. Is this correct ?

**Comment by tomothespian** [comment]
> In MacOS Selfnode I see
> image the text reads "Keep your wallet secure by setting a spending password" but in the document it reads "Keep your private keys safely encrypted by settings a spending password. Is this correct ?

@ManusMcCole that is not correct. Please check document again!
Screen Shot 2020-03-26 at 16 35 51

**Pull request merged**
