### PR TITLE
[DDW-610] Implement new Block-consolidation status design

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements the new Block-consolidation status design.

## Todo:

- [x] Implement component layout colors and images

## Normal screen

image

## Loading state

image

--

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1554474253066000)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance  and unit tests are passing (`yarn run test` and `yarn run test:unit`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] There are no *prettier* errors or warnings (`yarn run prettier:check`)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
Reviewing this one now...

**Comment by daniloprates** [comment]
> @daniloprates great work! I have just a couple of remarks:
> 
> 1. Contents of the page should be vertically centered:
>    
> 2. The "Learn More" button looks strange in green and dark themes:
>    Screen Shot 2019-04-08 at 15 46 47
>    Screen Shot 2019-04-08 at 15 47 17
>    Perhaps we should have the same styling in all the themes? What do you think @a-rukin?

Went for the same colors on all themes. Otherwise, we need new BG and text colors as well. @a-rukin let me know if you prefer going for this second option.

**Comment by a-rukin** [comment]
@daniloprates have you seen this zpl.io/bzN3l07 ? 
The only change is the bg color and color of a text on the image

**Comment by daniloprates** [comment]
> @daniloprates have you seen this http://zpl.io/bzN3l07 ?
> The only change is the bg color and color of a text on the image

I hadn't seen this. Thanks. Do you have the same for UTXO?

**Comment by daniloprates** [comment]
> @daniloprates have you seen this http://zpl.io/bzN3l07 ?
> The only change is the bg color and color of a text on the image

@a-rukin what about the hover state. I have added the current ones for the themes. Let me know if they should be different.

Screen Shot 2019-04-08 at 15 17 26 (2)
Screen Shot 2019-04-08 at 15 17 37 (2)

**Comment by a-rukin** [comment]
> @a-rukin what about the hover state. I have added the current ones for the themes. Let me know if they should be different.

no borders for hover state

**Comment by daniloprates** [comment]
> > @a-rukin what about the hover state. I have added the current ones for the themes. Let me know if they should be different.
> 
> no borders for hover state

@a-rukin it looks a bit washed on light theme. what bg color can I use for the hover on this theme?

hover

**Pull request merged**
