### PR TITLE
[DDW-727] Implement process management for decoupled cardano-wallet and node

### PR DESCRIPTION
**Pull request by Sam-Jeston**
This PR, into a new base branch, allows the integration of the new cardano-wallet API (https://input-output-hk.github.io/cardano-wallet/api/edge/).

The new base branch will be used as V2 API endpoints are integrated. We will stay away from develop (but keep the HEADs aligned regularly), as this branch will be unstable until:
1) cardano-wallet is feature complete
2) We get access to the new Haskell node. We are using an intermediary edge node (http-bridge) to enable development, but this will never see production.

This feature embeds the `cardano-wallet launcher` as the process that is managed my CardanoNode. GET wallet and addresses has been implemented so that the main Daedalus homepage will render.

Fixing E2E tests are not within the scope of this initial work

### CODE REVIEW

**Comment by Sam-Jeston** [comment]
@tomothespian due to the number of mocks against the new API (which involved commenting out lots of things to get this started, and hardcoding a few values), I didn't see a lot of value in getting those checks passing at this point, particularly as this is moving into a different base branch for the time being.

I had a conversation about this with @nikolaglumac and @daniloprates on Monday. It is up to you guys though. @daniloprates have you had time to play / look at this?

I'm going hands off on development of this (as my role was just to get the new dependencies into the dev process to enable you guys to start developing against the new API). But if you collectively agree you want the checks passing, I'll do that

**Comment by Sam-Jeston** [comment]
@daniloprates @tomothespian I've updated this branch to the most recent version of cardano-wallet which has a few new endpoints.

While I was there I just fixed the lint and flow errors. More things commented out, but it might be easier for you guys that way

**Comment by daniloprates** [comment]
@Sam-Jeston after pulling the latest changes from `cardano-sl@develop` and `daedalus@feature/ddw-727-new-wallet-and-node-process-manager` I'm not able to connect to cardano anymore 👇

Screen Shot 2019-07-29 at 22 16 32
Screen Shot 2019-07-29 at 22 17 22

**Comment by Sam-Jeston** [comment]
@daniloprates I just tested it on both my mac and Ubuntu installs. No issues. Please provide more info. What is the output of `cardano-node.log`. Anything strange in the terminal etc etc.

But I imagine this will be easier to just pair on

**Pull request merged**
