### PR TITLE
[DDW-690] Fix minimum window height on Windows and Linux

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR adds different main window minimum height based on the OS. Minimum height is calculated by subtracting title bar height from main window wrapper and passed as a minimum value while window object is being created. 

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1563959360032300)
- [ ] Test if minimum heights are different on different OS and aligned for every size of main window of the app
- [ ] Test if minimum heights are not breaking the scrollability and size of the main window of the app

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by DeeJayElly** [comment]
> @DeeJayElly did you also included menu bar in your calculations, not just title bar (on windows, menu is in window not like on mac)?
> Capture

Added

**Comment by gnpf** [comment]
@DeeJayElly The actual height and width are different from what is shown in the console
image

**Comment by tomothespian** [comment]
> @DeeJayElly The actual height and width are different from what is shown in the console
> image

@gnpf on which element you inspected that height? Should be element with id "root"

**Comment by tomothespian** [comment]
@DeeJayElly please pay attention on commit messages.
`[DDW-725] Implement Storybook minimum sizes` is not proper msg on this PR

**Comment by gnpf** [comment]
> @gnpf on which element you inspected that height? Should be element with id "root"

@tomothespian Yes, it's that element

image

**Comment by DeeJayElly** [comment]
> Hello. Inner size for win is too small comparing to lin.
> image-3

Fixed

**Comment by IuliaDolishniak** [comment]
screen
@DeeJayElly I can still see the difference between the height of 2 environments.

**Comment by daniloprates** [comment]
We need to re-think this approach. In my windows version, the menubar has a different height, so we can't rely on it. Investigating another option for this fix.

**Comment by nikolaglumac** [comment]
@daniloprates please remove the `WIP` tag after you implement the final fixes and notify @DmitriiGaico. Thanks!

**Comment by DeeJayElly** [comment]
@nikolaglumac Ok seems ok to me. @daniloprates did a good job reshaping the approach.

**Comment by nikolaglumac** [comment]
@DeeJayElly I think there are some defect that @DmitriiGaico found. @DmitriiGaico can you please post those here?

**Comment by DmitriiGaico** [comment]
> @DeeJayElly I think there are some defect that @DmitriiGaico found. @DmitriiGaico can you please post those here?

Yes, after the Default Size fix we loose 20px for Windows Build. Fortunately @DeeJayElly already prepared a fix so i checking it right now.

**Pull request merged**
