### PR TITLE
[DDW-922] Change the "Delete Wallet" Button Layout

### PR DESCRIPTION
**Pull request by MarcusHurney**
This PR changes the layout of the delete wallet button so it's easy to spot it while understanding its consequences.
---
## Screenshots
Screen Shot 2019-10-23 at 2 09 31 AM

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571811104199800)
- [Zeplin](https://zpl.io/brLDwJW )
---

### Basics

- [x] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn flow:test`)
- [x] There are no *lint* errors or warnings (`yarn lint`)
- [x] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [x] Japanese text changes are proofread and approved (Junko Oda)
- [x] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [x] Important parts of the code are properly commented and documented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-renderings
- [x] Any code that only works in main process is neatly separated from components

### Testing
- [x] New feature/change is covered by acceptance tests
- [x] New feature/change is manually tested and approved by QA team
- [x] All existing acceptance tests are still up-to-date
- [x] New feature/change is covered by Daedalus Testing scenario
- [x] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@a-rukin can you please review this one today? 🙏

**Comment by nikolaglumac** [comment]
@IuliaDolishniak this is not related to this PR as the same issue is present in develop too.
We have a separate task for fixing that: https://iohk.myjetbrains.com/youtrack/issue/DDW-970

**Comment by nikolaglumac** [comment]
@DominikGuzei may I kindly ask you to review this one please?

**Comment by MarcusHurney** [comment]
@nikolaglumac 
I've removed everything related to the export wallet feature throughout the entire app. Good catch 😎

**Pull request merged**
