### PR TITLE
[DDW-339] Correct order of receiving addresses

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR reverses ordering of addresses on the 'Receive' screen so that the oldest ones are shown on the top and the newest one on the bottom of the list.

## Screenshots

Screenshot 2020-09-04 at 14 42 26
Screenshot 2020-09-04 at 14 42 53

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Create new wallet and send ada to the address from the top of the “Receive” screen. After the transaction is confirmed the top address should be shown as “used” and only one new address should be added to the bottom of the list.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by ManusMcCole** [comment]
Hi @nikolaglumac. Looks to be working 100% on Mac.On windows however even after using 6 addresses and filtering them out no new addresses are added to the or bottom (or top) of the list

**Comment by nikolaglumac** [comment]
> Hi @nikolaglumac. Looks to be working 100% on Mac.On windows however even after using 6 addresses and filtering them out no new addresses are added to the bottom (or top) of the list

@ManusMcCole did you test on a brand new and unused wallet?

**Comment by ManusMcCole** [comment]
Sorry my bad yeah its working now with a completely fresh wallet @nikolaglumac

**Review by ManusMcCole — APPROVED** [review]
Looks good 👍

**Review by gnpf — APPROVED** [review]

**Pull request merged**
