### PR TITLE
[DDW-567] Log system specification info to a dedicated log file

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements a "System-info.json" file that is updated on each Daedalus start time, containing the system specification of the machine user is running Daedalus.

System-info.json output:

```
{
  "at": "2019-01-31T030723.0000Z",
  "env": "development:darwin:17.7.0:0.12.1",
  "ns": [
    "daedalus",
    "*production*"
  ],
  "data": {
    "cardanoVersion": "2.0.0",
    "cpu": [
      {
        "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
        "speed": 2300,
        "times": {
          "user": 31516500,
          "nice": 0,
          "sys": 18948620,
          "idle": 149039610,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
        "speed": 2300,
        "times": {
          "user": 17880400,
          "nice": 0,
          "sys": 8585540,
          "idle": 173022040,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
        "speed": 2300,
        "times": {
          "user": 30465590,
          "nice": 0,
          "sys": 14779150,
          "idle": 154243270,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
        "speed": 2300,
        "times": {
          "user": 17901670,
          "nice": 0,
          "sys": 7882680,
          "idle": 173703600,
          "irq": 0
        }
      }
    ],
    "daedalusVersion": "0.12.1",
    "isInSafeMode": false,
    "network": "development",
    "platform": "darwin",
    "platformVersion": "17.7.0",
    "ram": "8589934592",
    "startTime": "2019-01-31T030723.0000Z"
  },
  "app": [
    "daedalus"
  ],
  "msg": "",
  "sev": "",
  "thread": ""
}
```

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates can you please add this new log file to the logs zip too?

**Comment by daniloprates** [comment]
> @daniloprates can you please add this new log file to the logs zip too?

@nikolaglumac ✅

**Comment by nikolaglumac** [comment]
@daniloprates please make sure the log file is properly formatted - perhaps @MarcusHurney can assist you here as he is working on structured logging task!

**Comment by daniloprates** [comment]
As I could read, there is no standard for structured logging, but the main idea is to have it machine readable, making it easy to perform queries. 

I am not sure what exactly to change, but here is a proposal. Please, let me know your thoughts, @nikolaglumac / @MarcusHurney:

Currently:
```
{
  "startTime": "Wed Jan 30 2019 11:02:56 GMT-0200 (-02)",
  "build": "Daedalus (0.12.1#dev) development",
  "platform": "darwin",
  "platformVersion": "17.7.0",
  "CPU": "[\n  {\n    \"model\": \"Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz\",\n    \"speed\": 2300,\n    \"times\": {\n      \"user\": 24240590,\n      \"nice\": 0,\n      \"sys\": 14608650,\n      \"idle\": 118213620,\n      \"irq\": 0\n    }\n  },\n  {\n    \"model\": \"Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz\",\n    \"speed\": 2300,\n    \"times\": {\n      \"user\": 13862830,\n      \"nice\": 0,\n      \"sys\": 6628220,\n      \"idle\": 136556660,\n      \"irq\": 0\n    }\n  },\n  {\n    \"model\": \"Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz\",\n    \"speed\": 2300,\n    \"times\": {\n      \"user\": 23338690,\n      \"nice\": 0,\n      \"sys\": 11297570,\n      \"idle\": 122411490,\n      \"irq\": 0\n    }\n  },\n  {\n    \"model\": \"Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz\",\n    \"speed\": 2300,\n    \"times\": {\n      \"user\": 13873410,\n      \"nice\": 0,\n      \"sys\": 6092750,\n      \"idle\": 137081530,\n      \"irq\": 0\n    }\n  }\n]",
  "RAM": "8589934592",
  "isInSafeMode": false
}
```

Proposal:
```
{
  "startTime": "2018-09-11T17:08:31.002287Z",
  "daedalusVersion": "0.12.1",
  "cardanoVersion": "2.0.0",
  "environment": "production",
  "platform": "darwin",
  "platformVersion": "17.7.0",
  "isInSafeMode": false,
  "ram": "8589934592",
  "cpu": [
    {
      "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
      "speed": 2300,
      "times": {
        "user": 24240590,
        "nice": 0,
        "sys": 14608650,
        "idle": 118213620,
        "irq": 0
      }
    },
    {
      "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
      "speed": 2300,
      "times": {
        "user": 13862830,
        "nice": 0,
        "sys": 6628220,
        "idle": 136556660,
        "irq": 0
      }
    },
    {
      "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
      "speed": 2300,
      "times": {
        "user": 23338690,
        "nice": 0,
        "sys": 11297570,
        "idle": 122411490,
        "irq": 0
      }
    },
    {
      "model": "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz",
      "speed": 2300,
      "times": {
        "user": 13873410,
        "nice": 0,
        "sys": 6092750,
        "idle": 137081530,
        "irq": 0
      }
    }
  ]
}
```

**Comment by nikolaglumac** [comment]
@darko-mijic we log only last Daedalus start-time system info in this file and then overwrite it on the next Daedalus start. Is this sufficient? I think it is.

**Comment by daniloprates** [comment]
Thanks, @MarcusHurney. I have changed the data format accordingly.

**Comment by darko-mijic** [comment]
> we log only last Daedalus start-time system info in this file and then overwrite it on the next Daedalus start. Is this sufficient? I think it is
Yes, in my opinion.

**Pull request merged**
