### PR TITLE
[DDW-686] Validate search for native tokens and conversion currency

### PR DESCRIPTION
**Pull request by daniloprates**
This PR fixes issues in the Dropdown search.

## Todos

- [x] "No results" is not translated to Japanese.
- [x] After pressing enter on the native tokens search, the token is removed.

## Screenshots

Screen Shot 2021-05-19 at 15 06 01
Screen Shot 2021-05-19 at 15 06 15
Entre-Solved

---

## Issues Summary

**N/A:**
- Can the scroll move according to the item that is selected on the dropdown? If I move up and down with the arrows, the list doesn't move. Check videos [1](https://drive.google.com/file/d/1PonR5SGIg6rb6BrIWf5p0kx2Lq--ui6_/view?usp=sharing) and [2](https://drive.google.com/file/d/1fUtr4-xUoX7esQGQiUQFQzgnQF6DsnNN/view?usp=sharing).
- The small list is still visible when there are multiple tokens or the window was resized, can this be improved? Check[ this screenshot.](https://drive.google.com/file/d/1k0tO_HfMh7n7PrlEZjpG2FfJjY4S4nPz/view?usp=sharing)
- I found an instances where the search for currencys sometimes is acting strange on Mac(other builds were not available). In the [Video1-VND](https://drive.google.com/file/d/1pa6NqhA1ZkHiQFj7nUmAP_bZx4fCnbf3/view?usp=sharing) VND - ViatnameseDong is currently selected and the user attempts to search for BTC in the input box, after the b is entered it closes the dialog. When it is reopened we can see the b was entered but when T is added it gets closed again. 
- Also when I click enter at the end when only 1 search result is in the box it doesnt select the only viable option as it does in Native Tokens search bar. The search issue I mentioned seems to only happen for VND possibly related to the fact it has no characters in common with BTC (In the ticker or fullname) as the same happens with Xlm - Stellar Lumens(Only has t in common in name) [Video2-XLM](https://drive.google.com/file/d/1Ztc_uN-wkpSV4yAgh6WWV6Z5AbMVaiDe/view?usp=sharing). Issue seems to be intermittent(happening 20% of the time)(perhaps caught in some state as it seems to not happen at all then happens each time for a while before disappearing again)

**Fixed:**
- "No results" is translated to Japanese.
- Token is no longer removed when pressing enter.
- The message "No results" is not visible in English. Instead, it reads "ADA". Check screenshots [1](https://drive.google.com/file/d/1P69MZcT6KARgp0UGvu_Gkuh0lmBYSCDa/view?usp=sharing) and [2](https://drive.google.com/file/d/1c8Y1bwJUdl5nxugg8i_5NWby4h0Lz5-Z/view?usp=sharing).

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---
## Test Scenarios 

**Scenario 1 - Validate search**
```gherkin
Given that I am on |Screen|
And the |Dropdown| is open
When I enter at least two characters that match the name of any of the items on the list
Then I can see the list is updated with the list matching the search
```
**Scenario 2 - Validate search with no results**
```gherkin
Given that I am on |Screen|
And the |Dropdown| is open
When I enter at least two characters that don't match the name of any of the items on the list
Then I can see the list is updated showing "No results"
```
Screen | Dropdown
-- | --
Settings - Wallets | Select currency
Wallet - Send | Native token

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gabriela-ponce** [comment]
@daniloprates Here's a summary for build 18017:

New:
- The message "No results" is not visible in English. Instead, it reads "ADA". Check screenshots [1](https://drive.google.com/file/d/1P69MZcT6KARgp0UGvu_Gkuh0lmBYSCDa/view?usp=sharing) and [2](https://drive.google.com/file/d/1c8Y1bwJUdl5nxugg8i_5NWby4h0Lz5-Z/view?usp=sharing).
- Can the scroll move according to the item that is selected on the dropdown? If I move up and down with the arrows, the list doesn't move. Check videos [1](https://drive.google.com/file/d/1PonR5SGIg6rb6BrIWf5p0kx2Lq--ui6_/view?usp=sharing) and [2](https://drive.google.com/file/d/1fUtr4-xUoX7esQGQiUQFQzgnQF6DsnNN/view?usp=sharing).

Pending:
- The small list is still visible when there are multiple tokens or the window was resized, can this be improved? Check[ this screenshot.](https://drive.google.com/file/d/1k0tO_HfMh7n7PrlEZjpG2FfJjY4S4nPz/view?usp=sharing)

Fixed:
- "No results" is translated to Japanese.
- Token is no longer removed when pressing enter.

**Comment by daniloprates** [comment]
Thanks @gabriela-ponce!


> * The message "No results" is not visible in English. Instead, it reads "ADA". 

Had this done, but forgot to push ✔️ 

> * Can the scroll move according to the item that is selected on the dropdown? If I move up and down with the arrows, the list doesn't move. 

This can't be changed, at the moment. It would require a refactoring inside react-polymorph


> * The small list is still visible when there are multiple tokens or the window was resized, can this be improved? Check[ this screenshot.](https://drive.google.com/file/d/1k0tO_HfMh7n7PrlEZjpG2FfJjY4S4nPz/view?usp=sharing)

Not something we can deal with. The user would need to [scroll](https://user-images.githubusercontent.com/1504716/118877940-6ce5ce00-b8c5-11eb-81a1-39597f312123.png) it down

**Comment by ManusMcCole** [comment]
Hi @daniloprates.Tested on build 18018

I found an instances where the search for currencys sometimes is acting strange on Mac(other builds were not available). In the [Video1-VND](https://drive.google.com/file/d/1pa6NqhA1ZkHiQFj7nUmAP_bZx4fCnbf3/view?usp=sharing) VND - ViatnameseDong is currently selected and the user attempts to search for BTC in the input box, after the b is entered it closes the dialog. When it is reopened we can see the b was entered but when T is added it gets closed again. Also when I click enter at the end when only 1 search result is in the box it doesnt select the only viable option as it down in Native Tokens search bar. The search issue I mentioned seems to only happen for VND because it has no characters in common with BTC (In the ticker or fullname) as the same happens with Xlm [Video2-XLM](https://drive.google.com/file/d/1pa6NqhA1ZkHiQFj7nUmAP_bZx4fCnbf3/view?usp=sharing). Issue seems to be intermittent(happening 30% of the time)

**Comment by ManusMcCole** [comment]
Having trouble reproducing the issue above and also @Mior could not reproduce it. Not sure what caused it but it seems to be a non issue so you can ignore @daniloprates . I will keep an eye out for it

**Comment by gabriela-ponce** [comment]
@daniloprates The issue for the "No results" in English is fixed.
I can't reproduce the issue @ManusMcCole mentioned before either.

I added a summary of the issues in this PR so far.

**Review by dmitrii-gaico — APPROVED** [review]

**Review by gabriela-ponce — APPROVED** [review]

**Review by DominikGuzei — APPROVED** [review]
Code looks good 👍

**Pull request merged**
