### PR TITLE
[DDW-760] Theme Management Optimization

### PR DESCRIPTION
**Pull request by MarcusHurney**
This PR refactors the theme automation code associated with the scripts `themes:check` and `themes:update` so that new themes can be added in the future without touching the logic of the underlying functions. This makes theme management scalable.

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- *There are no changes in the UI or functionality to test*

---

### Basics

- [x] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn flow:test`)
- [x] There are no *lint* errors or warnings (`yarn lint`)
- [x] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [x] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [x] Japanese text changes are proofread and approved (Junko Oda)
- [x] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [x] Important parts of the code are properly commented and documented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-renderings
- [x] Any code that only works in main process is neatly separated from components

### Testing
- [x] New feature/change is covered by acceptance tests
- [x] New feature/change is manually tested and approved by QA team
- [x] All existing acceptance tests are still up-to-date
- [x] New feature/change is covered by Daedalus Testing scenario
- [x] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by daniloprates** [comment]
By running `yarn run themes:update` I've got this missing variable on all themes. Could you check if we can just commit the default color?
Screen Shot 2019-08-01 at 17 53 41 (2)

**Comment by daniloprates** [comment]
Also, it's not very clear the difference of `themes:check` and `themes:update` by their names. I deleted some vars on some themes and expected `themes:check` to point the issue, but actually got only by running `themes:update`. Maybe rename the scripts for clarity?

**Comment by daniloprates** [comment]
Besides my comments above I think it would be great if we had either a guide on how to add/edit themes or a UI theme generator. But this can be added to a separated card. Great job! ✨

**Comment by MarcusHurney** [comment]
@daniloprates 
I'm going to use the result of `themes:update` in my tutorial video since it is a perfect example. Thanks for the kind words, and I hope that my video will clarify any remaining questions or concerns.

**Comment by nikolaglumac** [comment]
No QA needed...

**Pull request merged**
