### PR TITLE
[DDW-594] Enable sending of native tokens for hardware wallets

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR enables sending of native tokens for hardware wallets.
[JIRA ticket](https://jira.iohk.io/browse/DDW-594)

## Todos

- [x] Implement "unformatted amount" view on the send-form "Confirmation" dialog
- [x] Enable hardware wallet sending on the API level
- [x] Explicitly order the token bundle entries before passing them to Ledger, making sure to replicate the logic of the wallet backend which uses the canonical ordering @tomislavhoracek 

### Hardware wallets

Screenshot 2021-03-11 at 09 20 08
Screenshot 2021-03-11 at 09 20 39
Screenshot 2021-03-11 at 09 20 07
Screenshot 2021-03-11 at 09 20 37

### Software wallets

Screenshot 2021-03-11 at 09 19 54
Screenshot 2021-03-11 at 09 20 27
Screenshot 2021-03-11 at 09 19 50
Screenshot 2021-03-11 at 09 20 25

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test sending native tokens with both Ledger and Trezor wallets on all platforms
- [ ] Test regular transactions without native tokens with both Ledger and Trezor wallets on all platforms.
- [ ] Test delegation with both Ledger and Trezor wallets on all platforms.

---
## Test Scenarios

**Scenario 1 - Send ADA + 1 Native token with Hardware Wallet**
```gherkin
Given a |Hardware Wallet| is added to Daedalus
And a Shelley wallet is added to Daedalus
And both wallets are synced
And the |Hardware Wallet| balance is >=2
And the |Hardware Wallet| has native tokens
When I access the "Send" screen for the |Hardware Wallet|
And I paste an address from the Shelley wallet on the "Receiver" input
And I insert a valid amount on the "Amount" input
And I add a token to the transaction
And I click on "Next" and confirm the transaction
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the transaction is performed
And the transaction can be visible on both wallets
And transaction is labeled "Multiple tokens sent" in my transaction history
```

**Scenario 2 - Send ADA + multiple Native tokens with Hardware Wallet**
```gherkin
Given a |Hardware Wallet| is added to Daedalus
And a Shelley wallet is added to Daedalus
And both wallets are synced
And the |Hardware Wallet| balance is >=2
And the |Hardware Wallet| has native tokens
When I access the "Send" screen for the |Hardware Wallet|
And I paste an address from the Shelley wallet on the "Receiver" input
And I insert a valid amount on the "Amount" input
And I add multiple tokens to the transaction
And I click on "Next" and confirm the transaction
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the transaction is performed
And the transaction can be visible on both wallets
And transaction is labeled "Multiple tokens sent" in my transaction history
```

**Scenario 3 - Send ADA from Hardware Wallet**
```gherkin
Given a |Hardware Wallet| is added to Daedalus
And a Shelley wallet is added to Daedalus
And both wallets are synced
And the |Hardware Wallet| balance is >=2
When I access the "Send" screen for the |Hardware Wallet|
And I paste an address from the Shelley wallet on the "Receiver" input
And I insert a valid amount on the "Amount" input
And I click on "Next" and confirm the transaction
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the transaction is performed
And the transaction can be visible on both wallets
```

**Scenario 4 - Delegate Hardware Wallet**
```gherkin
Given a |Hardware Wallet| with at least 10 ADA is added
And both Daedalus and the wallet are synced
And the "Delegation Center" screen on "Staking Center" is displayed
When I click on "Delegate" button for the wallet
And I follow the instruction on the wizard to delegate the wallet
And I plug, unlock and export the public key on the device
And confirm the transaction on the dialog
Then the wallet is displayed as delegated to the new stake pool in the epoch number = current epoch + 2
```

|Hardware Wallet|
Trezor T
Ledger Nano S
Ledger Nano X

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by alexander-rukin — APPROVED** [review]
Perfect! As always

**Comment by tomislavhoracek** [comment]
@nikolaglumac Logic for signing and sending NT with hardware wallets is done.

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek. Tested on Testnet build 17053

When I attempt to send all of my balance of testcoin away from a hardware wallet Daedalus goes all white and I get this error on the console see <a href="https://drive.google.com/file/d/1CYDfiCavbzzN7S2C23Verc2Tdr9bD03S/view?usp=sharing">screenshot</a>

Also on the Trezor device when attempting to send Native Tokens the token comes up as Asset 1 name (Ascii): and on Ledger it shows up as "Asset name is empty"

**Comment by tomislavhoracek** [comment]
@ManusMcCole I will check now

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek

There is one scenario I am concerned with Ledger. If the user decides to press the back button on Daedalus for a transaction(doesnt matter if Native Assets are involved in the transaction) when the confirming the transaction process is underway on the device at any step the transaction confirming dialog stays alive on the Device. On Trezor it goes away immediately. The confirmation dialog stays on the device. Once the user attempted to sign another transaction they must continue confirming the past transaction even though its been cancelled in Daedalus. Once that is done the new transaction confirmation dialog is visible on the device. Once the user confirms the details for the new transaction a transaction confirmation error appears. See <a href="https://drive.google.com/file/d/1kgNjfv9kbDy7aGaL-wznNu58N9jVpDsf/view?usp=sharing">video</a>

Also with James coin it shows up the Asset name with the (Ascii): part also visible.Im not sure if this expected. I thought i would add just incase. See <a href="https://drive.google.com/file/d/1ZloNolAypSDhE_I4nCFHV3-VBmj5J3TM/view?usp=sharing
">screenshot</a>

**Comment by gabriela-ponce** [comment]
@tomislavhoracek 

Transactions without NT work as expected so far (I struggled with Daedalus not detecting the device, it happened on production too). I got these results after sending NT from Ledger S:

- 1st try: "An error occurred" after confirming with the device and clicking "Send". The transaction was performed anyway.
Check the screenshot of the [error](https://drive.google.com/file/d/18ddjKhWeBSGB_zRXdDGmOe6FJvLPZTVA/view?usp=sharing), of the [transaction](https://drive.google.com/file/d/1E8qgmJw62WALaXmbyIsgxyN7dJake-0K/view?usp=sharing) and the [logs](https://drive.google.com/file/d/1k3PLS2wJJsUuO2hIzPyuNHlChj-M3l8Q/view?usp=sharing).

- 2nd: Blank screen after confirming with the device and clicking "Send". The transaction was performed anyway.
Check the screenshot of the [error](https://drive.google.com/file/d/1WEN9NsIlxJCUiHacGBAxl_9-OYJdJNx3/view?usp=sharing), of the [transaction](https://drive.google.com/file/d/1vTo3AHdG4IuOCCpCgyHXoAYxBFQYUtsq/view?usp=sharing) and the [logs](https://drive.google.com/file/d/1jNTzR6sfjeomD8Zw6lGqPgC3cINZUk1x/view?usp=sharing).

- 3rd: Loading for over 5 mins and Daedalus froze. The transaction wasn't performed.
Check[ this video](https://drive.google.com/file/d/1aaYMrMVjmfFvWzfeh78LanjmCHi9uln1/view?usp=sharing).

- Also, the tooltip for "Unformatted amount" looks wrong in both languages. Check screenshot [1](https://drive.google.com/file/d/1XyMLOWVoP_W71EffZASwDTtwjLQ1_HAZ/view?usp=sharing) and [2](https://drive.google.com/file/d/1nNEddik_TnU14DWfxyHhEAtYLmPHFjzX/view?usp=sharing).

- I reproduced the same [issue](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1615377179229200?thread_ts=1615319944.224200&cid=GGKFXSKC6) @miorsufianiohk mentioned on the thread, regarding the asset name. Check [this screenshot.](https://drive.google.com/file/d/1DV3w4Fzbg9hC3XyDeJhBscV-kE5Qg_J8/view?usp=sharing)

I'll continue testing transactions with NT and let you know if I reproduce any of these again or if I find something else 👍

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek  and @nikolaglumac. The error we discussed on the call for Ledger when a transaction is cancelled is as predicted present in production. I will open up a ticket

**Comment by nikolaglumac** [comment]
@gabriela-ponce your test results are not valid anymore - please use the latest build. Thanks!

**Comment by nikolaglumac** [comment]
ASCII name is now implemented!
The “HEX” value gets copied and you can select and manually copy the ASCII value.

Screenshot 2021-03-10 at 14 37 53
Screenshot 2021-03-10 at 14 37 58

**Review by miorsufianiohk — APPROVED** [review]
LGTM on Nano X. Tested on 17061. Great job @nikolaglumac @tomislavhoracek 👍

**Comment by gabriela-ponce** [comment]
@nikolaglumac @tomislavhoracek [These issues](https://github.com/input-output-hk/daedalus/pull/2446#issuecomment-795362573) don't reproduce in 17061 👍 

The tooltip still is wrong in both languages. Check the [new screenshot.](https://drive.google.com/file/d/1iwudO8DXbNeCSIqwaq9Zu09O8gs5MLlp/view?usp=sharing)

**Review by ManusMcCole — APPROVED** [review]
Great work @tomislavhoracek 👍 Tested on build 17061 Trezor Model T Testnet

**Review by gabriela-ponce — APPROVED** [review]

**Review by miorsufianiohk — APPROVED** [review]
LGTM on 17068. Great work @nikolaglumac 👍

**Pull request merged**
