### PR TITLE
[DDW-411] Implement design review fixes and improvements

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements design review fixes and improvements.

## Todo:

- [x] Provide the fixes and improvements based on [this document](https://docs.google.com/document/d/1WUuPL9mi_pE4H5DUw4sm_QeRaCrM3E7IK2lkBXa5AGE/edit)
- [x] Implement the Copy Address button in the Paper Wallet dialog
- [x] Implement the middle ellipsis for the Copy Address in the Wallet Receive page
- [x] [[DDW-409](https://iohk.myjetbrains.com/youtrack/issue/DDW-409)] Fix input field line-height issues

### Copy address at the Paper Wallet dialog

image

### Middle ellipsis

notification

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@a-rukin please also review this one by testing the installer and checking if the fixes are fine 🙏

**Comment by daniloprates** [comment]
@nikolaglumac this method has a few issues:

* When pseudo-element only appears with `display: inline-block;`, which prevents the text to break the line in the link space:

screen shot 2018-09-17 at 11 30 28

* The multiline link will have the underline only on the last line

screen shot 2018-09-17 at 11 29 19

Should I proceed with this method in the other cases?

**Comment by a-rukin** [comment]
image
here it works 🤷‍♀️

**Comment by daniloprates** [comment]
@a-rukin is this the `border-bottom` or the `&:after` version? The `border-bottom` one works fine.

**Comment by a-rukin** [comment]
it's Daedalus (0.11.1#1.3.1.2698) build

**Comment by daniloprates** [comment]
this uses the other method, via `border-bottom` and should work fine :)

**Comment by nikolaglumac** [comment]
@daniloprates you are right. Bottom border is a better choice. However, I saw that while using this option the text within the link moves 1 px vertically and then the font baseline doesn't match the rest of the words around the link. We might need to fix that somehow OR find a 3rd solution. My proposal obviously fails when it comes to multiline links :(

**Comment by a-rukin** [comment]
not sure it’s medium font here…
also fades out too fast, may be we can expand fade out time?
image 1

**Comment by daniloprates** [comment]
@a-rukin ✅

**Comment by nikolaglumac** [comment]
@daniloprates great work! I have found some other smaller issues which I will fix now...

**Comment by nikolaglumac** [comment]
Thanks for the fixes @daniloprates!
I will now test this again. Also, I will send the installer URL to @a-rukin so that he can help me testing too!

**Pull request merged**
