### PR TITLE
[DDW-711] Update Storybook to the latest version

### PR DESCRIPTION
**Pull request by daniloprates**
This PR upgrades Storybook to its latest version. It also makes the current Theme and Language state persistent and shareable. 

## Todos

- [x] Upgrade Storybook and its Add-ons to the latest version
- [x] Add DaedalusMenu into the new Tools area
- [x] Make the Theme and Language persistent

---

## Screenshots

image

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1564070287046000)
- [_Slack QA old thread_](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1560861951068400)
* [Netifly](https://daniloprates.github.io/daedalus/)
* All stories should work
* When reloading the page, sharing the current link or clicking another story, the current Theme and Language should be preserved.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates I have moved this PR back to WIP state until the changes @tomothespian requested are implemented.

**Comment by gnpf** [comment]
@daniloprates There is some flickering in **WalletTransactionsList - rendering many transactions** when changing the size of the screen

TkE1WetA0F

**Comment by daniloprates** [comment]
> @daniloprates There is some flickering in **WalletTransactionsList - rendering many transactions** when changing the size of the screen
@gnpf this is not related to this PR and can't be avoided, due to the scrollbar toggle.

**Comment by IuliaDolishniak** [comment]
@daniloprates Dark Cardano theme, nothing is shown
screen

**Comment by IuliaDolishniak** [comment]
No borders for white theme is this expected?
screen

**Comment by IuliaDolishniak** [comment]
Step Names are not translated even after Refresh
screen

**Comment by IuliaDolishniak** [comment]
Ada Redemption screen looks very pale
screen

**Comment by IuliaDolishniak** [comment]
screen

**Comment by IuliaDolishniak** [comment]
screen
Nothing is visible here

**Comment by IuliaDolishniak** [comment]
screen

**Comment by IuliaDolishniak** [comment]
screen
not translated into Japanese

**Comment by IuliaDolishniak** [comment]
screen
no label is visible

**Comment by daniloprates** [comment]
@IuliaDolishniak thanks for the reports. Could you use this [old Storybook version](https://deploy-preview-1468--daedalus-storybook.netlify.com/) to compare? So, only issues that are not present in the old version should be reported on this PR. All the others could go into a single card for Storybook adjustments.

**Comment by daniloprates** [comment]
@IuliaDolishniak could you empty the browser's cache and try again? I couldn't reproduce the pale items...

image

**Comment by IuliaDolishniak** [comment]
> @IuliaDolishniak could you empty the browser's cache and try again? I couldn't reproduce the pale items...
> 
> image

Can you please check DarkBlue here?

**Comment by IuliaDolishniak** [comment]
> Step Names are not translated even after Refresh
> screen

This one doesn't exist on the old StoryBook. I can see steps translated after Refresh. This is for all Staking screens where steps are shown.

**Pull request merged**
