### PR TITLE
[DDW-828] Remove dropdown arrow

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR removed arrow image of select dropdown component
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-828)

## Todos
- [x] Remove select dropdown arrow

## Screenshots
image
image
image
image

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1567163816009600)
- [x] Go to any screen which has select dropdown control
- [x] Click on select input, and see if arrow was removed from dropdown panel

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@yakovkaravelov The space between the field and the dropdown in these scenarios is too big, compared to similar scenarios:

- Add Wallet -> Wallet Restore
- Paper Wallet -> Shielded recovery phrase and password verification

image

**Comment by a-rukin** [comment]
image
Input box here (Enter recovery phrase) has wrong border color, pls check zeplin

**Comment by a-rukin** [comment]
Make sure input styles were updated too

**Comment by DominikGuzei** [comment]
@nikolaglumac @yakovkaravelov this is a ok-ish quick hack in Daedalus but i guess it would be more solid to make the react polymorph component configurable to work without the arrow - should i setup a task for that?

**Comment by nikolaglumac** [comment]
Agreed @DominikGuzei! Please create a card for this. Thanks!

**Comment by yakovkaravelov** [comment]
@a-rukin @tomothespian This is done, please review. Thanks.

**Comment by tomothespian** [comment]
@yakovkaravelov can you please do this 🙏 
https://github.com/input-output-hk/daedalus/pull/1550#pullrequestreview-282058083

**Comment by gnpf** [comment]
@yakovkaravelov In most screens, the alignment of the list changes according to the size of the window and platform. 
Can you take a look at this, please? I'm going to test this on Daedalus as well to confirm, but because of the known issues with MacOS builds I won't be able to check there.

kbbOY7bEHa
aCjHZ6jt2I
r1tnhqrq0B
3MoeCqHYtD

**Comment by a-rukin** [comment]
image
As you may see there are two issues here:
1) text inside input has transparency (but it shouldn't) 
2) is a bit more global... the background of the box is #fafbfc, but it should be #ffffff for the green (Cardano) theme, so input is sticking out (border of this box is also wrong), so the container box is just a copy of a light blue theme

**Comment by nikolaglumac** [comment]
@yakovkaravelov please merge in latest develop and address the issues @a-rukin and @gnpf found. Thanks!

**Comment by a-rukin** [comment]
> is a bit more global... the background of the box is #fafbfc, but it should be #ffffff for the green (Cardano) theme, so input is sticking out (border of this box is also wrong), so the container box is just a copy of a light blue theme

Created another card for this https://iohk.myjetbrains.com/youtrack/issue/DDW-883

**Comment by nikolaglumac** [comment]
@a-rukin OK thanks! Please make sure to always post this info to the GH PR.

**Comment by yakovkaravelov** [comment]
> image
> 
> As you may see there are two issues here:
> 
> 1. text inside input has transparency (but it shouldn't)
> 2. is a bit more global... the background of the box is #fafbfc, but it should be #ffffff for the green (Cardano) theme, so input is sticking out (border of this box is also wrong), so the container box is just a copy of a light blue theme

@a-rukin 
Just fixed them.
Please review.
Thanks.

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov In most screens, the alignment of the list changes according to the size of the window and platform.
> Can you take a look at this, please? I'm going to test this on Daedalus as well to confirm, but because of the known issues with MacOS builds I won't be able to check there.
> 
> kbbOY7bEHa
> aCjHZ6jt2I
> r1tnhqrq0B
> 3MoeCqHYtD

@gnpf I noticed that resizing window manually makes selection dropdown resized automatically with closing pop up.
Your reproduction step above is just automatic resize by selecting various platforms (MAC, and Windows), and that might be the cause of this issue.
And furthermore, I can't even reproduce this one on my chrome, did you use Windows chrome?
I tested it using my MAC chrome.
Can we call if you are available?

**Comment by gnpf** [comment]
@yakovkaravelov I reproduced this in Win-Chrome, but I had to resize the window for that because it happens when the vertical scroll is displayed on Mac/Linux, but not in Win. Maybe it's not related at all, but that's the only pattern I found. 

I'm available to call whenever you can 👍

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov I reproduced this in Win-Chrome, but I had to resize the window for that because it happens when the vertical scroll is displayed on Mac/Linux, but not in Win. Maybe it's not related at all, but that's the only pattern I found.
> 
> I'm available to call whenever you can 👍

@DominikGuzei I think this should be handled in polymorph select component itself.
So issue is that select dropdown width is not recalculated on automatic window resizing while keeping it opened up.
If you close popup, and reclick, then it works fine.
So dropdown width calculation needs to be on window resize event handler as well.

**Pull request merged**
