### PR TITLE
Feature/daef 110 changing wallet transaction assurance level

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR introduces new dropdown field for changing wallet transaction assurance level on Wallet-settings page.

wallet settings

### CODE REVIEW

**Comment by DominikGuzei** [comment]
Reviewing this now

**Comment by nikolaglumac** [comment]
@DominikGuzei great! :)
BTW. this PR includes also updates from this one: https://github.com/input-output-hk/daedalus/pull/194
Not sure how to proceed with the merge...

**Comment by DominikGuzei** [comment]
@nikolaglumac yeah i also saw that, please let's avoid this in the future as requirements are quickly changing in this project 😉 in general a PR should only do one thing to keep it simple and avoid dependencies on "that has to be merged before this" … in rare cases it's hard to avoid that but usually we should not do it.

**Comment by nikolaglumac** [comment]
I am aware of that but since I've finished the PR with units setting in the morning and assurance-level task  was depending on it I did not want to pause my work until it was merged into master...

**Comment by DominikGuzei** [comment]
@nikolaglumac why was it depending on the other setting? We should do it like we did with the my settings PR (delete wallet dialog), prepare the overlapping work (like introducing a basic settings page) but then work on the features independently 😉 but no worries, I will take care of this PR and then merge it

**Comment by nikolaglumac** [comment]
@DominikGuzei I agree with you and I'm sorry to cause merge issues :(
The basic settings page was lacking store and other UI logic which I've implemented in the other PR...

**Comment by DominikGuzei** [comment]
@nikolaglumac no worries, that was my fault – that's what i meant back then in slack, that we should have setup the store etc. before starting to code on these features as it was clear they will share some logic. It's not a big issue, we just have to be careful in the future to avoid unnecessary work 😉

**Comment by DominikGuzei** [comment]
@nikolaglumac i cleaned up the PR and improved the assurance mode logic with proper Flow types and mobx logic so that transactions dynamically update their labels on changes.

**Comment by DominikGuzei** [comment]
@darko-mijic please review this 😉

**Pull request merged**
