### PR TITLE
[DDW-447] Fix yarn test in nix shell

### PR DESCRIPTION
**Pull request by deepfire**
This fixes `chromedriver` issues in `nix` environment by supplying it via `nix` instead of the `npm`.

**Note:**
These changes have no impact on the way `nix-shell` is used in the development cycle - so if you are using `yarn nix:dev` and then `yarn test` to run Daedalus tests it will still use your system dependencies.
However, if you start the tests through: `nix-shell --run "yarn test"` then `nix` will purge and install all the dependencies from scratch.

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@deepfire can you elaborate a little bit on how you fixed which problem in this PR?

**Comment by deepfire** [comment]
@DominikGuzei, https://iohk.myjetbrains.com/youtrack/issue/DDW-447 has the details, but briefly, `chromedriver` was being supplied by `npm`, instead of Nix.

**Comment by nikolaglumac** [comment]
Thanks @deepfire - I have added this info to the PR description.
cc @DominikGuzei

**Comment by nikolaglumac** [comment]
@deepfire one more question - I see this PR also includes fault-injection argument - is this intended?

**Comment by deepfire** [comment]
@nikolaglumac, right, it's unrelated, but it doesn't hurt either -- it facilitates passing the argument to the wallet node, when entering the shell.  I've decided to bundle all shell changes together -- but that's not required, and can be removed.

**Comment by nikolaglumac** [comment]
@deepfire so this doesn't change anything by default - we just have an option to pass this argument?

**Comment by deepfire** [comment]
@nikolaglumac, exactly, yes.

**Comment by nikolaglumac** [comment]
@deepfire all good! :)

**Comment by deepfire** [comment]
Thank you, Nikola! : -)

**Pull request merged**
