### PR TITLE
[DDW-416] Add backdrop blur to some overlays/dialogs

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR adds a backdrop blur effect to dialogs and overlays.

## Todos

- [x] Check if the blur amount is good in all cases
- [x] Check if we missed any dialogs/overlays in the app
- [x] Remove backdrop blur from stake pool filter dialog

### Overlays:
daedalus-wallet-import-overlay-backdrop
daedalus-diagnostic-overlay-backdrop
daedalus-about-overlay-backdrop
incident-overlay-backdrop
alert-overlay-backdrop
experimental-data-overlay-backdrop

### Dialogs:
delegate-wallet-dialog-backdrop
daedalus-hd-wallet-dialog-backdrop
daedalus-create-wallet-dialog-backdrop
daedalus-restore-wallet-dialog-backdrop
daedalus-set-pw-dialog-backdrop

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test if the backdrop is correctly shown for all dialogs/overlays in the app

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by alexander-rukin** [comment]
image
I've changed bg to non transparent color, but it still has some extra opacity (that's why it looks more transparent to me)

**Comment by alexander-rukin** [comment]
image
this shouldn't have this blur effect

**Comment by DominikGuzei** [comment]
> image
> I've changed bg to non transparent color, but it still has some extra opacity (that's why it looks more transparent to me)

should I make the overlay background colors opaque then?

**Comment by nikolaglumac** [comment]
@DominikGuzei @alexander-rukin please get on a call today and discuss our options 🙏

**Comment by DominikGuzei** [comment]
@alexander-rukin @nikolaglumac I had to refactor the transaction filter dialog to use `PopOver` instead of `Dialog` since it's not very easy to change the Modal styles for a single case and the code much cleaner this way anyway 😉 The only thing that changed is that it's now possible to scroll the transactions while the dialog is open – is that ok or should I hide it on scrolling?

https://user-images.githubusercontent.com/172414/110153507-6f1aaf00-7de3-11eb-986d-e6e3595475f2.mp4

**Comment by nikolaglumac** [comment]
@DominikGuzei nice job! I actually like that we can scroll the content and keep the filter popover open 👍

**Comment by nikolaglumac** [comment]
@DominikGuzei can you please check the lint errors?

**Review by alexander-rukin — APPROVED** [review]

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@DominikGuzei please check the transactions filter dialog UX - it seems it no longer closes upon submission. We need to keep that behavior. Everything else is 👌 

PS. please fix lint issues 🙏

**Comment by DominikGuzei** [comment]
@nikolaglumac the filter dialog issue should be resolved now 👍

**Review by nikolaglumac — APPROVED** [review]
Great work @DominikGuzei! Looks really nice! 💅

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Great job @DominikGuzei 👍

**Pull request merged**
