### PR TITLE
[DDW-1179] Update LedgerJS to 6.0.0 version 

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces `@cardano-foundation/ledgerjs-hw-app-cardano` library update to version 6.0.0

[Jira Ticket](https://input-output.atlassian.net/browse/DDW-1188)

**_Useful links:_**
https://input-output-rnd.slack.com/archives/G010N9UFDNH/p1669826305137549

## Todos

- [x] Update LedgerJs to v6.0.0-rc2
- [x] Update LedgerJs to official release v6.0.0
- [x] Revert changes related to `str_to_path` and use proper implementation suggested by @rhyslbw https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/issues/36

## Screenshots
**_No_**

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1663246796183579)

_**In the scope of this PR we should test voting breaking changes. Also, it would be nice to check regular transactions and delegation. LEDGER ONLY!**_
- [x] Test with current / official Ledger Cardano App
- [x] Update Ledger Cardano App to version v6.0.3. - This is an experimental app and you can install it using Ledger Live ( with an enabled Experimental flag under provider number 4)

---

### Basics

- [ ] PR assigned to the PR author(s)
- [ ] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [ ] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [ ] PR link is added to a Jira ticket, ticket moved to In Review
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR contains screenshots (in case of UI changes)
- [ ] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by rhyslbw — COMMENTED** [review]
Undocumented breaking change with `str_to_path` util export explained here:
https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/issues/36

**Comment by tomislavhoracek** [comment]
> Undocumented breaking change with `str_to_path` util export explained here: [cardano-foundation/ledgerjs-hw-app-cardano#36](https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/issues/36)

Thank you soo much @rhyslbw <3

**Review by przemyslaw-wlodek — APPROVED** [review]
🎉

**Review by gabriela-ponce — APPROVED** [review]
Nice job! Requires an additional QA review before merging 🙏

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Tested on Cardano app 5.0.0 and 6.0.3 with Nano S, Nano X and Nano S Plus. Great work @tomislavhoracek 👍 .

**Review by dmitrii-gaico — APPROVED** [review]

**Pull request merged**
