### PR TITLE
[DDW-921] Remove Discreet mode notification

### PR DESCRIPTION
**Pull request by lucas-barros**
This PR removes discreet mode tooltip and notification.

## Todos

- [ ] TODO

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

## Test Scenarios

```Gherkin
Scenario 1: No discreet mode notification displayed when launching Daedalus
Given I just (freshly installed | upgraded) Daedalus
When I launch Daedalus
And I observe the eye icon
Then the discreet mode notification is not displayed 

Scenario 2: Discreet mode notification displayed when hovered
Given I am on Daedalus
When I hover the cursor on the eye icon
Then the discreet mode notification is displayed

Scenario 3: Absence of red dot on Security option
Given I am on Daedalus
And I am on Settings
When I observe 'Security' option on the right side
Then there is no red dot next to it
```
---

### Basics

- [x] PR assigned to the PR author(s)
- [x] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] ~~If there are UI changes, Alexander Rukin assigned as an additional reviewer~~
- [ ] ~~All visual regression testing has been reviewed (Go to Github Actions tab -> Select Chromatic workflow -> Run on your working branch)~~
- [x] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [x] PR link is added to a Jira ticket, ticket moved to In Review
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes
- [ ] ~~PR contains screenshots (in case of UI changes)~~
- [x] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] ~~Text changes are proofread and approved (Jane Wild / Amy Reeve)~~
- [ ] ~~Japanese text changes are proofread and approved (Junko Oda)~~
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [ ] ~~In case of dependency changes `yarn.lock` file is updated~~

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by marcin-mazurek — APPROVED** [review]
LGTM 👍

**Comment by marcin-mazurek** [comment]
@lucas-barros do we need to remove this Storybook knob? 🤔 
https://github.com/input-output-hk/daedalus/blob/develop/storybook/stories/_support/DiscreetModeToggleKnob.ts#L8

**Comment by lucas-barros** [comment]
> @lucas-barros do we need to remove this Storybook knob? 🤔 https://github.com/input-output-hk/daedalus/blob/develop/storybook/stories/_support/DiscreetModeNotificationKnob.ts#L8

@marcin-mazurek Yes, I removed since the tooltip/notification was removed.

**Comment by marcin-mazurek** [comment]
@lucas-barros sorry, I missed it, all good.

**Review by ManusMcCole — APPROVED** [review]
Looks good @lucas-barros 👍

**Comment by daniloprates** [comment]
@lucas-barros we are keeping the code necessary to have this dot for new features, correct?

**Comment by lucas-barros** [comment]
> @lucas-barros we are keeping the code necessary to have this dot for new features, correct?

@daniloprates some parts, like storage, where removed because they where in feature specific code. Others can be reused  like:
https://github.com/input-output-hk/daedalus/blob/13f235d77f8ca5550ef5112e48ee4b43347e0978/source/renderer/app/components/settings/menu/hooks.ts#L8
https://github.com/input-output-hk/daedalus/blob/13f235d77f8ca5550ef5112e48ee4b43347e0978/source/renderer/app/components/widgets/notification-dot/NotificationDot.tsx

The next one we should make a notification feature to keep the storage and the other components/hooks in one place.

**Review by gabriela-ponce — APPROVED** [review]

**Pull request merged**
