### PR TITLE
[DDW-344] Integrate Rewards redemption API endpoint

### PR DESCRIPTION
**Pull request by daniloprates**
This PR integrates the Rewards redemption API endpoint and fixes the wrong colors in different themes.

## Todos

- [x] Calculate Fee
- [x] Request the rewards redemption
- [x] Handle errors
- [x] Fix the colors for all themes

## Screenshots

JP01
JP02
JP03
JP04

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@daniloprates There is a space missing between the period and "you":

Screenshot at Aug 05 17-46-47

**Comment by ManusMcCole** [comment]
Hi @daniloprates There seems to be some text missing in Japanese. Unless there has been a change since the screenshots 
image

**Comment by ManusMcCole** [comment]
Hi @daniloprates. When I attempt to redeem rewards in to a wallet that does not have enough to pay for fees I recieve this error message. Perhaps the second line should say something like please select a wallet with enough ada to pay fees to redeem rewards
image

**Comment by ManusMcCole** [comment]
We still need a fullstop in the text copy on the first screen 
image

**Comment by daniloprates** [comment]
> @daniloprates There is a space missing between the period and "you":

[24156070b731cb9eb74142fa843b8b9629a569c5](https://github.com/input-output-hk/daedalus/pull/2133/commits/24156070b731cb9eb74142fa843b8b9629a569c5)

**Comment by daniloprates** [comment]
> Hi @daniloprates. When I attempt to redeem rewards in to a wallet that does not have enough to pay for fees I recieve this error message. Perhaps the second line should say something like please select a wallet with enough ada to pay fees to redeem rewards
> image

@ManusMcCole [db847261853e0e8c6c478703d42f0816fd1b8c2c](https://github.com/input-output-hk/daedalus/pull/2133/commits/db847261853e0e8c6c478703d42f0816fd1b8c2c)

**Pull request merged**
