### PR TITLE
[DDW-406] V1 API Improve Network Store

### PR DESCRIPTION
**Pull request by MarcusHurney**
- This PR replaces the Ada API methods `getSyncProgress` and `getLocalTimeDifference` with a unified V1 method called `getNetworkStatus`. 

- Refactors `NetworkStatusStore` to use the gifts of the V1 API and renames variables to be more accurate and intuitive. 

- Uses the V1 API to more explicitly compute the various states a node undergoes while syncing. Uses the new `getNetworkStatus` to reduce code length.

- Removes depreciated environment checks intended for ETC.

## Todo
- [x] Restore logic with block-stalling

### Basics

- [x] PR is updated to the most recent version of target branch (and there are no conflicts)
- [x] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn run flow:test`)
- [x] There are no *lint* errors or warnings (`yarn run lint`)
- [x] Text changes are proofread and approved (Jane Wild)
- [x] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [x] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn run storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [x] Important parts of the code are properly documented and commented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-rendering
- [x] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by MarcusHurney** [comment]
@nikolaglumac 
I'm getting errors when importing a wallet with via key file. Even though the import is successful, an error is still thrown. This is also reflected in the failed tests. This error just started when I pulled in `feature/ddw-321` so it shouldn't have anything to do with the changes you'd be reviewing here.

**Comment by nikolaglumac** [comment]
@MarcusHurney only import of wallet `.key` file is working!

**Comment by nikolaglumac** [comment]
@MarcusHurney we will need to disable wallet-import/export acceptance tests which use JSON wallet file...

**Comment by MarcusHurney** [comment]
Yes, sorry, I meant JSON wallet files. It’s late and I am entering the zone of sloppiness! Glad you are aware of the error though!

**Comment by nikolaglumac** [comment]
No worries @MarcusHurney - we are on the same page :)
Have nice sleep! 💤

**Comment by nikolaglumac** [comment]
@MarcusHurney I was testing this PR today by using mainnet installer and running Daedalus while disconnected from the Internet. This situation did not result in expected behavior (Daedalus should show "Connection lost. Reconnecting..." screen. I believe this is due to a bug in your code as we got JS errors:
screen shot 2018-09-05 at 15 52 24
I believe the problem is you did not correctly type response of the `/api/v1/node-info` endpoint. If you look more closely in the docs it looks like `blockchainHeight` can be `null` which would explain the JS errors I saw:
screen shot 2018-09-05 at 15 57 07
Therefore, I added a fix: https://github.com/input-output-hk/daedalus/pull/1081/commits/427427caa66c9c2184875f9481a39293b909925e
Will re-run my tests after CI produces new installers...

**Comment by MarcusHurney** [comment]
@nikolaglumac 
I made improvements here based on your feedback this past Friday.

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei can you guys also review this PR? It's an important change and I would like us all to agree on the way it is implemented... Thanks!

**Pull request merged**
