### PR TITLE
[DDW-786] Discreet mode - Create the TopBar icon

### PR DESCRIPTION
**Pull request by lucas-barros**
This PR implements the discreet mode top bar toggle.

## Todos

- [ ] Integrate with discreet mode actions

## Screenshots
image
image
image
image
image

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by alexander-rukin** [comment]
> > https://zpl.io/V0OyG5l - @daniloprates what do you think of this suggestion?
> 
> @alexander-rukin Would TadaButton be placed after the sync icon and before the dash in this scenario?
> 
> image

i'd place it in this order: 
sync + | + eye + tada+ bell

**Comment by alexander-rukin** [comment]
image
@lucas-barros base opacity of icon (non-hoverred state) should be 0.4  – reference https://zpl.io/V0OyG5l

**Comment by lucas-barros** [comment]
> image
> 
> @lucas-barros base opacity of icon (non-hoverred state) should be 0.4 – reference https://zpl.io/V0OyG5l

@alexander-rukin fixed, thanks!

**Comment by dmitrii-gaico** [comment]
Could you please advise if it is implemented that Toggle can be switched in real build ? I am running Testnet build and toggle is static.

https://user-images.githubusercontent.com/83477982/139850233-c4f2a99c-2e2c-4b0b-9b13-30183c949656.mp4

**Comment by alexander-rukin** [comment]
@daniloprates btw isn't it the time to remove TADA, how long would it be here ?))

**Comment by daniloprates** [comment]
> @daniloprates btw isn't it the time to remove TADA, how long would it be here ?))

@alexander-rukin it's not visible, it's there just in case we have another celebration in the future

**Comment by miorsufianiohk** [comment]
Hi @lucas-barros ,

On build 19518, 

There's a pipe symbol between the discreet mode symbol and the sync status icon. Since the screenshots at the top of this PR don't show any, maybe screenshots need to be updated to reflect this? 🤔 
pipesymbol

**Comment by lucas-barros** [comment]
> Hi @lucas-barros ,
> 
> On build 19518,
> 
> There's a pipe symbol between the discreet mode symbol and the sync status icon. Since the screenshots at the top of this PR don't show any, maybe screenshots need to be updated to reflect this? 🤔 pipesymbol

@miorsufianiohk yes, I updated the screenshots. Thanks!

**Pull request merged**
