### PR TITLE
[DDW-854] Update node and yarn

### PR DESCRIPTION
**Pull request by yakovkaravelov**
Draft: This PR is dependent on https://github.com/input-output-hk/daedalus/pull/1873
It should be merged after pervious one is merged.

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by tomothespian** [comment]
@yakovkaravelov can you please create a branch from `v2-integration` branch. This PR contains an unmerged branch and that is not correct. Also do not update Electron, just Node and Yarn!
cc. @nikolaglumac

**Comment by yakovkaravelov** [comment]
> @yakovkaravelov can you please create a branch from `v2-integration` branch. This PR contains an unmerged branch and that is not correct. Also do not update Electron, just Node and Yarn!
> cc. @nikolaglumac

@tomothespian No, it was already created based off `v2-integration`
After basing off `v2-integration`, I merged https://github.com/input-output-hk/daedalus/pull/1873 to include lock file fix work.
So it's dependent on previous PR.

**Comment by yakovkaravelov** [comment]
@tomothespian As Nikola mentioned, please approve https://github.com/input-output-hk/daedalus/pull/1873 if everything is ok.
Also once that is approved and merged to v2-integration, there will be nothing to do with this PR regarding `unmerged branch and that is not correct` thing.

**Comment by nikolaglumac** [comment]
@yakovkaravelov https://github.com/input-output-hk/daedalus/pull/1873 is merged now. Please proceed with closing this one and opening a clean PR from latest v2-integration. Thanks!

**Comment by nikolaglumac** [comment]
This PR was closed unmerged as it's git commit history was unpure. A new PR will be opened for this task.
cc @yakovkaravelov

**Pull request closed without merging**
