### PR TITLE
[DDW-310] Add acceptance tests for about dialog

### PR DESCRIPTION
**Pull request by daniloprates**
This PR adds acceptance tests for about dialog.

## Todo:

- [x] Test opening about dialog
- [x] Test closing about dialog
- [x] Test if the Daedalus version matches the package.json version key value

---

### Basics

- [x] PR is updated to the most recent version of target branch (and there are no conflicts)
- [x] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance tests are passing (`npm run test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`npm run dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`npm run package` / CI builds)
- [x] There are no *flow* errors or warnings (`npm run flow:test`)
- [x] There are no *lint* errors or warnings (`npm run lint`)
- [x] Text changes are proofread and approved (Jane Wild)
- [x] There are no missing translations (running `npm run manage:translations` produces no changes)
- [x] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`npm run storybook`)
- [x] In case of npm dependency changes both `package-lock.json` and `yarn.lock` files are updated

### Code Quality
- [x] Important parts of the code are properly documented and commented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-rendering
- [x] Any code that only works in Electron is neatly separated from components

### Testing
- [x] New feature / change is covered by acceptance tests
- [x] All existing acceptance tests are still up-to-date
- [x] New feature / change is covered by Daedalus Testing scenario
- [x] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates this is the thread I've found: https://github.com/electron/spectron/issues/21

**Comment by DominikGuzei** [comment]
reviewing this now

**Comment by DominikGuzei** [comment]
@nikolaglumac i looked closer into that thread and it basically shows that this is not easily possible with spectron atm (we would have to introduce special code in the main process just to make this possible … which is not a good approach IMO)

**Comment by nikolaglumac** [comment]
Thanks for checking it out @DominikGuzei. If that is the case then I am fine with the current setup :)

**Comment by DominikGuzei** [comment]
@nikolaglumac this is ready to be merged from my side!

**Pull request merged**
