### PR TITLE
[DDW-355] Improve stake pools rendering performance

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR implement stake pools preloader which improves rendering peformance of the "Stake pools" screen and "Delegation setup" wizard. This solution includes deferred loading of the stake pools in case there is more than 100 stake pools to be rendered, which ensures smooth navigation. A loading spinner is shown in place of the stake pools in case preloading is in progress.

## Screenshots

Screenshot 2020-09-04 at 16 59 05
Screenshot 2020-09-04 at 17 02 17

Screenshot 2020-09-04 at 16 59 11
Screenshot 2020-09-04 at 17 02 21

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
image

can we fit it in one line 😓 ?

**Comment by a-rukin** [comment]
image

Is this normal that I can't see balance while syncing? 
Previously it showed balance, and even if it were changed while syncing, it was OK

**Comment by nikolaglumac** [comment]
> image
> 
> can we fit it in one line 😓 ?

That's out of the scope of this PR. Please ask @DeeJayElly to fix it in PR https://github.com/input-output-hk/daedalus/pull/2152

**Comment by nikolaglumac** [comment]
> image
> 
> Is this normal that I can't see balance while syncing?
> Previously it showed balance, and even if it were changed while syncing, it was OK

@a-rukin this is expected. This change was introduced in https://github.com/input-output-hk/daedalus/pull/2168

**Comment by a-rukin** [comment]
image
Was it always like this? I mean the 30px padding belongs to scrollable area, not button (it aclually could be a a split 20 + 10)  -> now it looks like cropped

**Comment by nikolaglumac** [comment]
> image
> 
> Was it always like this? I mean the 30px padding belongs to scrollable area, not button (it aclually could be a a split 20 + 10) -> now it looks like cropped

That's out of the scope of this PR. Please ask @DeeJayElly to fix it in PR #2152

**Review by a-rukin — APPROVED** [review]

**Review by ManusMcCole — APPROVED** [review]
Looks good 👍

**Pull request merged**
