### PR TITLE
[DDW-1083] Build Daedalus with Nix flakes

### PR DESCRIPTION
**Pull request by michalrus**
We need to update the builds for Nix flakes.

## Todos

- [x] new build versioning schema (instead of Buildkite build numbers)
- [x] pure Darwin builds
- [x] Darwin signing `nix run` script
- [x] links to installers via Cicero's `nar-serve` analog
- [x] Windows cleanup
- [x] Linux cleanup
- [x] Windows signing (`nix run` script)
- [ ] verify that release scripts / `proposal-ui` still work in a test release

## Screenshots

More detailed version reporting as a bonus:

image

## Testing Checklist

- TODO: Slack QA thread
- [ ] Test

---

### Basics

- [x] PR assigned to the PR author(s)
- [x] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [x] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [x] PR link is added to a Jira ticket, ticket moved to In Review
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes
- [x] PR contains screenshots (in case of UI changes)
- [x] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [x] Important parts of the code are properly commented and documented
- [x] Code is properly typed with typescript types
- [x] React components are split-up enough to avoid unnecessary re-renderings
- [x] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
Quick favor: merge `develop` branch into this branch so that I can build `5.1` with the flake?

**Comment by michalrus** [comment]
@quinn-dougherty okay, I’ll try to squeeze in resolving those conflicts today =)

**Comment by michalrus** [comment]
@quinn-dougherty there you go, just pushed the merge :octocat:

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Nice work @michalrus 👍

**Review by ManusMcCole — APPROVED** [review]
🚀

**Review by dmitrii-gaico — APPROVED** [review]

**Pull request merged**
