### PR TITLE
[DDW-431] Newsfeed shadow

### PR DESCRIPTION
**Pull request by DeeJayElly**
This PR fixes Newsfeed drop shadow when there is an update item.

## Screenshots

Screen Shot 2020-11-20 at 1 35 37 PM

Screen Shot 2020-11-20 at 1 33 01 PM

Screen Shot 2020-11-20 at 1 31 02 PM

Screen Shot 2020-11-20 at 1 14 18 PM

Screen Shot 2020-11-20 at 1 14 04 PM

Screen Shot 2020-11-13 at 10 29 24 AM

Screen Shot 2020-11-13 at 10 29 44 AM

Screen Shot 2020-11-13 at 10 30 55 AM

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1605260049428600)

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by a-rukin** [comment]
@DeeJayElly did you use https://zpl.io/2ZX1YJl as a reference?

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@DeeJayElly this doesn't seem right... Please see attached screenshot:

shadow

**Comment by DeeJayElly** [comment]
> @DeeJayElly this doesn't seem right... Please see attached screenshot:
> 
> shadow

Fixed

**Comment by gnpf** [comment]
@DeeJayElly When the update item is not displayed, there is an extra space between the shadow and the rest of the item, that is visible while scrolling. This looks different on the [layout](https://zpl.io/2ZX1YJl). Check this [screenshot](https://drive.google.com/file/d/1KU10cNrHSW_w5ktuZCETm9I4qhZyzFRQ/view?usp=sharing) and [recording](https://drive.google.com/file/d/19FnJebPUEQy4SPMnqxxhlm68xEooZGpx/view?usp=sharing).
The shadow looks good when the update item is displayed.

**Comment by DeeJayElly** [comment]
> recording

Fixed

**Review by gnpf — APPROVED** [review]

**Comment by nikolaglumac** [comment]
@daniloprates please review this one 🙏

**Comment by a-rukin** [comment]
shadow uses an incorrect value:
now it is - ` box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);`
but it should be -  `box-shadow: 0 10px 10px -5px rgba(0, 0, 0, 0.25);`
+
pay attention to the white theme, shadows there are lighter, they use 8% instead of 25% - `rgba(0, 0, 0, 0.08);`

**Comment by DeeJayElly** [comment]
> shadow uses an incorrect value:
> now it is - ` box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);`
> but it should be - `box-shadow: 0 10px 10px -5px rgba(0, 0, 0, 0.25);`
> +
> pay attention to the white theme, shadows there are lighter, they use 8% instead of 25% - `rgba(0, 0, 0, 0.08);`

New box-shadow colors are added pls recheck @a-rukin

**Review by a-rukin — APPROVED** [review]
Good job!

**Review by mioriohk — APPROVED** [review]
Looks good. 👍

**Comment by daniloprates** [comment]
Screen Shot 2020-11-17 at 22 43 39
Screen Shot 2020-11-17 at 22 44 15

@DeeJayElly 
I couldn't make it work in the actual app 🤔  did you have a chance to test it with dummy data or just in the storybook?

**Comment by DeeJayElly** [comment]
> Screen Shot 2020-11-17 at 22 43 39
> Screen Shot 2020-11-17 at 22 44 15
> 
> @DeeJayElly
> I couldn't make it work in the actual app 🤔 did you have a chance to test it with dummy data or just in the storybook?

Yes i did, you have to add dummy data + make sure some of the flags are set true.

For example your 'hasShadow' flag is not set on true, thats why you don't see the shadow on the element.

Screen Shot 2020-11-18 at 11 52 36 AM

**Comment by a-rukin** [comment]
Oh... noticed this:
1. [Strange line ](https://user-images.githubusercontent.com/2539345/99526703-b4d67780-29ac-11eb-8c2a-f4779b732c3b.png)on your screenshot
2. Pls check [color of the scroll bar](https://user-images.githubusercontent.com/2539345/99526782-d0da1900-29ac-11eb-8f51-42cfbdcd4d0a.png). It looks like it's grey

**Comment by DeeJayElly** [comment]
> Oh... noticed this:
> 
> 1. [Strange line ](https://user-images.githubusercontent.com/2539345/99526703-b4d67780-29ac-11eb-8c2a-f4779b732c3b.png)on your screenshot
> 2. Pls check [color of the scroll bar](https://user-images.githubusercontent.com/2539345/99526782-d0da1900-29ac-11eb-8f51-42cfbdcd4d0a.png). It looks like it's grey

1. This line is removed

2. Scrollbar color is the old color which we have already across the whole application, for this light blue theme its:
'--theme-scrollbar-thumb-background': 'rgba(94, 96, 102, 0.3)',

**Comment by a-rukin** [comment]
> 2. Scrollbar color is the old color which we have already across the whole application, for this light blue theme its:
>    '--theme-scrollbar-thumb-background': 'rgba(94, 96, 102, 0.3)',

We have scrollbar color in a color of a text, so this color (you sent) is relevant only for parts where text is dark-grey. For the inverted parts color would be rgba(250, 251, 252, 0.3)

**Review by a-rukin — APPROVED** [review]
Looks good

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@DeeJayElly this is still no good... The vertical paddings are now off. Please **test all cases** and post screenshots to the PR description. **Do not only test in storybook** 🙏 

Expected:
Screenshot 2020-11-19 at 19 29 27

Actual:
Screenshot 2020-11-19 at 19 27 42

**Comment by DeeJayElly** [comment]
> @DeeJayElly this is still no good... The vertical paddings are now off. Please **test all cases** and post screenshots to the PR description. **Do not only test in storybook** 🙏
> 
> Expected:
> Screenshot 2020-11-19 at 19 29 27
> 
> Actual:
> Screenshot 2020-11-19 at 19 27 42

Fixed

**Comment by a-rukin** [comment]
**Issues:**
1. Now it has [weird padding](https://user-images.githubusercontent.com/2539345/99790460-35c07b00-2b35-11eb-9bb7-470b18a29d6e.png) when content is scrolled
2. Where is a [separator line](https://user-images.githubusercontent.com/2539345/99790537-55f03a00-2b35-11eb-996e-616efdac0ef7.png) between update item and others. See [design before scroll](https://user-images.githubusercontent.com/2539345/99790653-7d470700-2b35-11eb-9345-b5b46290b6e4.png) and [after scroll](https://user-images.githubusercontent.com/2539345/99790738-951e8b00-2b35-11eb-8708-88fae35e2f18.png) - https://zpl.io/2ZX1YJl

**Comment by DeeJayElly** [comment]
> **Issues:**
> 
> 1. Now it has [weird padding](https://user-images.githubusercontent.com/2539345/99790460-35c07b00-2b35-11eb-9bb7-470b18a29d6e.png) when content is scrolled
> 2. Where is a [separator line](https://user-images.githubusercontent.com/2539345/99790537-55f03a00-2b35-11eb-996e-616efdac0ef7.png) between update item and others. See design [before scroll](https://user-images.githubusercontent.com/2539345/99790653-7d470700-2b35-11eb-9345-b5b46290b6e4.png) and [after scroll](https://user-images.githubusercontent.com/2539345/99790738-951e8b00-2b35-11eb-8708-88fae35e2f18.png) - https://zpl.io/2ZX1YJl

Updated

**Comment by nikolaglumac** [comment]
@a-rukin please test again 🙏

**Comment by daniloprates** [comment]
Screen Shot 2020-11-20 at 13 39 21

@DeeJayElly great adjustments. Just a minor thing: when there's no update item, the scrollbar looks odd ☝️

**Comment by DeeJayElly** [comment]
> Screen Shot 2020-11-20 at 13 39 21
> 
> @DeeJayElly great adjustments. Just a minor thing: when there's no update item, the scrollbar looks odd ☝️

Fixed @daniloprates

**Comment by a-rukin** [comment]
image
without update item list has some strange paddings (top and bottom)

**Comment by DeeJayElly** [comment]
> image
> 
> without update item list has some strange paddings (top and bottom)

Ok its fixed now. @a-rukin

**Comment by nikolaglumac** [comment]
@a-rukin please retest 🙏 
@DeeJayElly I really hope you have covered all the cases...

**Review by a-rukin — APPROVED** [review]
lgtm

**Review by nikolaglumac — APPROVED** [review]
🎉

**Pull request merged**
