### PR TITLE
[DDW-267]: Fix data displayed outside component on transaction list screen

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR fixed transaction list screen showing data outside the component when resizing window.
[Jira Ticket](https://jira.iohk.io/browse/DDW-267)

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1591950490037000)
- [ ] Resize app window on transaction list screen to see if data is displayed outside the component

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@yakovkaravelov When the window is maximized and you restore the size, a part of the transaction is not visible.

K1DbGgOPTS

It also happens when you resize "manually", it's adjusted after scrolling though.

qYKOjQTaFp

**Comment by nikolaglumac** [comment]
@yakovkaravelov I believe you will have to reach out to @DominikGuzei and discuss the virtual list implementation with him. We probably need to reconfigure it for these long addresses.

**Comment by DominikGuzei** [comment]
@gnpf i cannot reproduce these issues on osx with ITN selfnode - can you confirm that this is only happening on Windows? Also i saw that you are using the `friends & family` ITN version - is that the same?

**Comment by gnpf** [comment]
@DominikGuzei I still can reproduce this issue on Mac

image

I have used SN, FF and also MN to test this, happens on any network, I just used any wallet with ADA or transactions

**Comment by DominikGuzei** [comment]
@gnpf are you 100% sure that you are using the build from this PR? I will test this now with the build from CI (because my local build works flawlessly)

**Pull request merged**
