### PR TITLE
[DDW-974] Test onChange handler fix for RP checkboxes

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR just bumps the version of react-polymorph so that we can test that [[DDW-974] Fix double triggering of checkbox onChange](https://github.com/input-output-hk/react-polymorph/pull/206#) works correctly in Daedalus.

## Todos:
- [x] Review this PR and ensure that checkbox in Daedalus still work as before
- [x] Release new react-polymorph version
- [x] Update this PR to include the bumped version
- [x] Merge this PR to update Daedalus to use the new version

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test any checkbox in Daedalus if it still works correctly

---

### Basics

- [ ] PR assigned to the PR author(s)
- [ ] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [ ] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [ ] PR link is added to a Jira ticket, ticket moved to In Review
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR contains screenshots (in case of UI changes)
- [ ] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### Test Scenarios
Please contact @miorsufianiohk for comment on test scenarios
```Gherkin
Scenario 1: Select/Unselect any checkbox
Given I (select | unselect) a checkbox
Then the checkbox is (selected | unselected)
And it is working as expected
```

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by marcin-mazurek** [comment]
@DominikGuzei the related PR https://github.com/input-output-hk/daedalus/pull/2907 is merged now

**Comment by DominikGuzei** [comment]
@danielmain @dmitrii-gaico the merge conflicts are fixed now 👍

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Great work @DominikGuzei 👍  . Tested on 21512

**Review by dmitrii-gaico — APPROVED** [review]

**Comment by DominikGuzei** [comment]
@danielmain updated to react-polymorph@1.0.4 which includes the fix 👍

**Comment by DominikGuzei** [comment]
Just saw that this was already released as we upgrade to 1.0.4 earlier on :D closing this PR

**Pull request closed without merging**
