### PR TITLE
[DDW-548] Update recovery phrase input placeholder

### PR DESCRIPTION
**Pull request by yakovkaravelov**
This PR updated recovery phrase input placeholder
[Jira Ticket](https://jira.iohk.io/browse/DDW-548)

## Todos
- [x] Update recovery phrase input placeholder

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1612302578137900)

## Test Cases

```Gherkin
Scenario 1: Input placeholder in English
Given my default language is English
And I am (creating a new wallet|restoring a wallet|at wallet recovery phrase verification)
And I am at Recovery phrase step
And I haven’t entered any word in the textbox
When I enter <word_amount> word
Then input placeholder displays <placeholder_text>

|word_amount|placeholder_text
|0          |Enter word #1
|1          |Enter word #2
|2          |Enter word #3
```
```Gherkin
Scenario 2: Input placeholder in Japanese
Given my default language is Japanese
And I am (creating a new wallet|restoring a wallet|at wallet recovery phrase verification)
And I am at Recovery phrase step
And I haven’t entered any word in the textbox
When I enter <word_amount> word
Then input placeholder displays <placeholder_text>

|word_amount|placeholder_text
|0          |1 番目の単語を入力
|1          |2 番目の単語を入力
|2          |3 番目の単語を入力
```

```Gherkin
Scenario 3: Enter the last mnemonic word
Given I am (creating a new wallet|restoring a wallet|at wallet recovery phrase verification)
And I am at Recovery phrase step
And I am about to enter the last word
When I enter the last word
Then input placeholder will not be displayed
```

## Test Summary

Test results for build 16214
|Test cases | Results|Note|
|-----------|----|----|
|Scenario 1 | Failed|Looks good but implementation missing at wallet recovery phrase verification|
|Scenario 2| Failed|Looks good but implementation missing at wallet recovery phrase verification|
|Scenario 3| Failed|Looks good but implementation missing at wallet recovery phrase verification|

### App
- [x] Go to `Create a new wallet` dialog and continue steps to reach at `Recovery phrase` step and make sure input placeholder was updated with new text 
- [x] Go to `Restore wallet` dialog and continue steps to reach at `Recovery phrase` step and make sure input placeholder was updated with new text 
- [x] Go to `Wallet settings` => `Wallet recovery phrase verification` dialog and continue steps to reach at `Recovery phrase` step and make sure input placeholder was updated with new text

### English
image
image
image

### Japanese
image
image
image

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@yakovkaravelov please add screenshots to the PR description.

I can see you haven't implemented this change on the "Wallet recovery phrase verification" dialog?
Screenshot 2021-02-03 at 11 12 28

**Review by mioriohk — CHANGES_REQUESTED** [review]
Hi @yakovkaravelov . Here are the test results for build 16214

|Test cases | Results|Note|
|-----------|----|----|
|Scenario 1 | Failed|Looks good but implementation missing at wallet recovery phrase verification|
|Scenario 2| Failed|Looks good but implementation missing at wallet recovery phrase verification|
|Scenario 3| Failed|Looks good but implementation missing at wallet recovery phrase verification|

**Comment by yakovkaravelov** [comment]
@nikolaglumac @mioriohk This was fixed.
Please review/test again. Thanks.

**Review by nikolaglumac — APPROVED** [review]
Looks good 👍 
Thanks!

**Review by mioriohk — APPROVED** [review]
LGTM. Good work @yakovkaravelov 👍 . Tested on 16229.

**Pull request merged**
