### PR TITLE
[DEVOPS-299] Fix TLS certificate path

### PR DESCRIPTION
**Pull request by domenkozar**
Testing...

### CODE REVIEW

**Comment by domenkozar** [comment]
@fersel can you test win installer if certs work (and if not, paste the beginning of the daedalus log)?

**Comment by fersel** [comment]
@domenkozar certs are working correctly for the provided installer.

**Comment by fersel** [comment]
@domenkozar not so lucky with the mac one, certs are not created :
```
[91m[node:ERROR:ThreadId 4936] [0m[2017-08-30 19:26:03 MSK] Reporting misbehaviour “Worker/plugin with logger name LoggerName {loggerName = “node”} failed with exception: /Users/fersel/Library/Application Support/Daedalus/tls/server/server.crt: openBinaryFile: does not exist (No such file or directory)”
[94m[node.worker.slotting.ntp:INFO:ThreadId 4934] [0m[2017-08-30 19:26:03 MSK] Host “time.windows.com” is resolved: 51.140.127.197:123
[91m[node:ERROR:ThreadId 4936] [0m[2017-08-30 19:26:03 MSK] Reporting misbehaviour “Worker/plugin with logger name LoggerName {loggerName = “node”} failed with exception: /Users/fersel/Library/Application Support/Daedalus/tls/server/server.crt: openBinaryFile: does not exist (No such file or directory)”
Rawlogs size is: 18
[94m[node.worker.slotting.ntp:INFO:ThreadId 4934] [0m[2017-08-30 19:26:03 MSK] Host “clock.isc.org” is resolved: 149.20.64.28:123
[91m[node:ERROR:ThreadId 4936] [0m[2017-08-30 19:26:03 MSK] Didn’t manage to report misbehaveour Worker/plugin with logger name LoggerName {loggerName = “node”} failed with exception: /Users/fersel/Library/Application Support/Daedalus/tls/server/server.crt: openBinaryFile: does not exist (No such file or directory) because of exception /nix/store/v529vfry3dygak9kvpig1d7dvkp9fbqg-SecurityTool-55115/bin/security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
[94m[node.worker.slotting.ntp:INFO:ThreadId 4934] [0m[2017-08-30 19:26:03 MSK] Host “ntp5.stratum2.ru” is resolved: 88.147.254.234:123
[91m[node:ERROR:ThreadId 4936] [0m[2017-08-30 19:26:03 MSK] Didn’t manage to report misbehaveour Worker/plugin with logger name LoggerName {loggerName = “node”} failed with exception: /Users/fersel/Library/Application Support/Daedalus/tls/server/server.crt: openBinaryFile: does not exist (No such file or directory) because of exception /nix/store/v529vfry3dygak9kvpig1d7dvkp9fbqg-SecurityTool-55115/bin/security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

The beginning of the daedalus log:
```
[2017-08-30 19:25:58:0498] [info] /Applications/Daedalus.app/Contents/MacOS/tls/ca/ca.crt
```

Tell me if you need full log(s).

**Comment by deepfire** [comment]
I think I know what's the problem.

**Comment by fersel** [comment]
@domenkozar that fixes the topology issue, thanks! The node seems to work OK now.

But now the frontend part wouldn't start because of the `ReferenceError: appLogFolderPath is not defined` exception.

**Comment by fersel** [comment]
@domenkozar we're getting closer :) now I'm getting
```
[2017-08-31 14:36:56:0902] [error] CardanoClientApi::syncProgress error: {
  "stack": "Error: self signed certificate in certificate chain\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:584:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)",
  "message": "self signed certificate in certificate chain",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}
```

From Daedalus.log:
```
[2017-08-31 14:43:37:0914] [error] Error while loading ca.crt: Error: ENOENT: no such file or directory, open '/Applications/Daedalus.app/Contents/Resources/app/dist/Applications/Daedalus.app/Contents/MacOS/tls/ca/ca.crt'
```

(Note that certs are being "fetched by" the node though).

**Comment by domenkozar** [comment]
Rebase of master broke things :) Should be fixed now.

**Comment by fersel** [comment]
@domenkozar now this:
```
[2017-08-31 21:26:35:0117] [info] Using certificates from: /Applications/Daedalus.app/Contents/MacOS/tls/ca/ca.crt
[2017-08-31 21:26:35:0117] [error] Error while loading ca.crt: ReferenceError: pathToCertificate is not defined
```

(node is ok but frontend is not working)

**Comment by domenkozar** [comment]
@fersel confirmed that it works.

**Comment by darko-mijic** [comment]
The code looks good to me. I have also verified that installer is now working properly on Mac @domenkozar.

**Pull request merged**
