### PR TITLE
[DDW-277] Fix Download Manager directory creation error

### PR DESCRIPTION
**Pull request by daniloprates**
This PR fix the current issue with the Download Manager, where it will not create the proper `Downloads` directory, which will prevent Daedalus to load.

## Screenshots

Screen Shot 2020-06-15 at 09 48 44

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1592228040046300)
1. Delete the `stateDirectoryPath` (it can be found in the Diagnostics screen);
2. Run Daedalus;
3. The error message in the image above should not appear and Daedalus should run normally.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@daniloprates For Windows I'm getting this message after deleting the state directory. Works as expected in Mac and still pending to check in Lin;

image

Also, not sure if this is related, but the state directory path is not visible the first time the app is opened in Win;

image

**Comment by gnpf** [comment]
@daniloprates Failed on Linux too:

image

**Comment by daniloprates** [comment]
> @daniloprates For Windows I'm getting this message after deleting the state directory. Works as expected in Mac and still pending to check in Lin;
> 
> image
> 
> Also, not sure if this is related, but the state directory path is not visible the first time the app is open in Win;
> 
> image

That's odd 🤔 could you rename all Daedalus directories into *-BKP and try reinstalling it?

**Comment by gnpf** [comment]
@daniloprates I tried again on different networks and got the same error. Before installing, both machines on Lin and Win had the previous versions and state directories wiped out:

iDamKLYMCC

Also, the error on the Diagnostics screen (path not visible) is intermittent.

**Comment by daniloprates** [comment]
@gnpf please try deleting the directory before the installation

**Pull request merged**
