### PR TITLE
[DDW-376] Cleanup SimpleTheme Config in Daedalus

### PR DESCRIPTION
**Pull request by MarcusHurney**
- This PR refactors the theme configuration of Daedalus so that the css variables used in `react-polymorph` components are distinguishable from other css variables used in Daedalus internally.

- `react-polymorph` css vars are organized into individual objects per component.

- Prefixes the `react-polymorph` css vars with `--rp` and renames them to follow a uniform naming convention that describes their use from broad to specific. 

  - Example: `--rp-formfield-label-text-color` and `--rp-formfield-label-text-color-disabled`.
     This convention follows `--rp- prefix` + `component` + `element` + `property` + `state`.

- Removes the existing configuration of `SimpleTheme` in Daedalus which imports `SimpleTheme` from the `react-polymorph` module and overrides its scss variables manually.

- Creates new `react-polymorph` css vars in addition to the existing set. The new ones allow nearly all of the existing css properties within each component to be themed using a configuration object / template. This reduces existing single instance css variables in Daedalus which target properties on `react-polymorph` elements that are not currently exposed for customization. Such as `font-size`, `border`, `height`, and `width`.

- Creates `source/renderer/app/themes/overrides` directory for styles that target `react-polymorph` components but aren't configurable through `--rp` css vars. These overrides are passed to `ThemeProvider`'s `themeOverrides` prop for composition with the base theme.

### Basics

- [x] PR is updated to the most recent version of target branch (and there are no conflicts)
- [x] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [x] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [x] Automated tests: All acceptance tests are passing (`yarn run test`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [x] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [x] There are no *flow* errors or warnings (`yarn run flow:test`)
- [x] There are no *lint* errors or warnings (`yarn run lint`)
- [x] Text changes are proofread and approved (Jane Wild)
- [x] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [x] Storybook works and no stories are broken (`yarn run storybook`)
- [x] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [x] Important parts of the code are properly documented and commented
- [x] Code is properly typed with flow
- [x] React components are split-up enough to avoid unnecessary re-rendering
- [x] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@MarcusHurney can you please add more info in the PR description? Thanks 🙏

**Comment by MarcusHurney** [comment]
@nikolaglumac 
@DominikGuzei 
After reviewing this PR and after I make any necessary adjustments, @a-rukin will need to review the UI before it can be merged. Thanks!

**Comment by nikolaglumac** [comment]
@MarcusHurney can you please merge in latest `develop` and fix the conflicts? Thanks!

**Comment by nikolaglumac** [comment]
@MarcusHurney @DominikGuzei the changes look good but I have failing tests - it's actually the same problem as with https://github.com/input-output-hk/daedalus/pull/1156
I am puzzled how this now appeared in this branch 😱 

screen shot 2018-11-14 at 13 46 20
screen shot 2018-11-14 at 13 46 17

**Comment by nikolaglumac** [comment]
@MarcusHurney @DominikGuzei I just got the same issues on develop branch. It could be related to my local setup :-/

**Pull request merged**
