### PR TITLE
Fix/ddw 261 Prevent text wrap in wallet navigation tabs

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR prevents text wrapping within the wallet navigation tabs by increasing the width of the tabs and by adding `text-overflow: ellipsis` CSS rule.

## Screenshots:

- Screenshot

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`npm run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`npm run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`npm run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`npm run flow-test`)
- [ ] There are no *lint* errors or warnings (`npm run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `npm run manage-translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`npm run storybook`)
- [ ] In case of npm dependency changes both `package-lock.json` and `yarn.lock` files are updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by a-rukin** [comment]
@nikolaglumac on the second screenshot last "symbol" is missing (I can see only part of it).
From the description, I thought that tab size would be dynamicaly increased to fit the text. 🤔

**Comment by nikolaglumac** [comment]
@a-rukin that is not possible. All tabs must be equal in width. I have slightly increased the width and added overflow-ellipsis and this is why when it happens (on certain screen widths) that the text is cut off we show "..."

**Comment by nikolaglumac** [comment]
In other words - we can not make it 100% visible in all screen sizes.
The sidebar also plays the role - when it is hidden then there is enough room for the text...

**Comment by a-rukin** [comment]
p.s. Also, languages are full of synonyms... Still can't understand why Japanese is always so long. 
p.p.s. "Add wallet" translation is also too big... broke right padding

**Comment by nikolaglumac** [comment]
@a-rukin yeah well we have what we have :(
Add wallet is like that since always. There is no magic we could add to fix it...

**Comment by a-rukin** [comment]
I understand 😩

**Comment by nikolaglumac** [comment]
I did not say that my update made this 💯 perfect. It made it better and I that is it :)

**Comment by DominikGuzei** [comment]
Reviewing this now …

**Pull request merged**
