### PR TITLE
[CSL-807] Use NSIS liteFirewall plugin to add/remove rules

### PR DESCRIPTION
**Pull request by jmitchell**

### CODE REVIEW

**Comment by jmitchell** [comment]
Based on my test environment, Windows 10, the liteFirewall approach made the networking Windows Security Alert prompt go away.

The installer is now _strongly_ discouraged by SmartScreen, but this will probably go away in a signed build after this PR is merged. To override the warning I had to click a small "more info" link.

**Comment by jmitchell** [comment]
PRs are excluded from signing and I want to test a signed version of these changes. The new `test/csl807-windows-firewall` branch has the same changes, and should be signed in the Appveyor build.

**Comment by jmitchell** [comment]
In my test environment the signed version of these changes worked; no aggressive SmartScreen warning nor firewall prompts.

**Comment by domenkozar** [comment]
Looks good! :)

**Pull request merged**
