### PR TITLE
[DDW-573] Update Ledger and Trezor JS libraries

### PR DESCRIPTION
**Pull request by tomislavhoracek**
This PR introduces an update for Trezor and Ledger JS libraries / dependencies 
- `@cardano-foundation/ledgerjs-hw-app-cardano`to version `2.2.0`
- `trezor-connet` to version `8.1.22` .

---

## TODO
- [x] Update Ledger JS Lib and apply changes
- [x] Update Trezor JS Lib and apply changes
- [x] Fix Windows build issue @cleverca22 

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1613650139282100?thread_ts=1613650075.281800&cid=GGKFXSKC6)
- [ ] Hardware Wallets regression testing

---

## Test Cases 

**Trezor Test Cases**
```Gherkin
Scenario 1 : Add Wallet
Given that I have Daedalus running
When I try to add a Trezor Wallet
Then I will be prompted to export the public key
And the wallet will be successfully imported

Scenario 2 : Reconnecting device
Given that I have a Trezor wallet already paired and loaded
And my device is physically disconnected from my machine
When I physically reconnect my device
And click pair
Then I will be asked to export my public key 
And exporting public key will be a success
And I will be redirected to the corresponding wallet summary screen

Scenario 3 : Redelegation
Given that I have a Trezor wallet already paired and loaded
And I wish to redelegate my wallet
When I select redelegate from the Stake Pools Wallet Menu
And I follow the Delegate Wallet wizard instructions
Then I am prompted to export my public key
And I am asked to confirm the transaction

Scenario 4 : Sending a transaction
Given that I have a Trezor wallet already paired and loaded
When I select to send a transaction
Then I am prompted to export my public key
And I am asked to confirm the transaction

```
**Ledger Test Cases**

```Gherkin

Scenario 1 : Add Wallet
Given that I have Daedalus running
When I try to add a Ledger Wallet
Then I will be prompted to export the public key
And exporting public key will be succesfull
And the wallet will be succesfully imported

Scenario 2 Unlocking and launching Cardano App before opening Daedalus
Given that I have Daedalus installed and currently closed
And my Ledger device is not connected
When I unlock my device
And Launch Cardano App
And launch Daedalus
And click on "Pair"
Then I am asked to export the public key
And I am brought to the landing page for the correct wallet

Scenario 3: Unlock device before opening Daedalus.But dont launch Cardano App until after clicking Pair
Given that Ledger Device is plugged in and unlocked
And I Open Daedalus
And I Click on "Pair"
When I Launch Cardano App
Then I am asked to confirm export the key
And I am brought to the landing page for the correct wallet

Scenario 4: Open Daedalus first.Plug in device and unlock.Select Cardano app after clicking pair
Given that I have Daedalus installed and open
And I Click on "Pair"
And I Plug in the Ledger Device
And Unlock it
When I Launch the Cardano App
Then I am asked to export the public key
And I am brought to the landing page for the correct wallet

Scenario 5 : Reconnecting device
Given that I have a Ledger wallet already paired and loaded
And I disconnect my device
When I reconnect my device
And I click Pair
And I unlock my device
Then I will be asked to export my public key 
And exporting public key will be a success
And I will be redirected to the corresponding wallet summary screen

Scenario 6 : Redelegation
Given that I have a Ledger wallet already paired and loaded
And I wish to redelegate my wallet
When I select redelegate from the Stake Pools Wallet Menu
And I follow the Delegate Wallet wizard instructions
Then I am prompted to export my public key
And I am asked to confirm the transaction

Scenario 7 : Sending a transaction
Given that I have a Ledger wallet already paired and loaded
When I select to send a transaction
Then I am prompted to export my public key
And I am asked to confirm the transaction
```

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by tomislavhoracek** [comment]
@DominikGuzei Can you help us here with Netlify. It same issue like here (where @nikolaglumac mentioned you) https://github.com/input-output-hk/daedalus/pull/2284#issuecomment-756008387

Netlify Link: https://app.netlify.com/sites/daedalus-storybook/deploys/602e9391d4da9300082c5ecd

**Comment by ManusMcCole** [comment]
Hi @Tomislav. Tested on Mainnet 16656

There is an issue with public key export on Ledger Nano S. It is throwing a cannot export extended public key error. See <a href="https://drive.google.com/file/d/1CsPj08x1DhusutQb1S3rWCk--dg_jUiL/view?usp=sharing">Screenshot</a>

On Linux the button for Daedalus diagnostic screen is greyed out and disabled. I checked latest develop and the button is working fine so it leads me to believe this PR has somehow affected it

**Comment by nikolaglumac** [comment]
> On Linux the button for Daedalus diagnostic screen is greyed out and disabled. I checked latest develop and the button is working fine so it leads me to believe this PR has somehow affected it

Where do we have a "button" for the Diagnostics screen? 🤔  
A screenshot and more context would help here @ManusMcCole ...

**Comment by tomislavhoracek** [comment]
@ManusMcCole Can you please describe "Export key" steps with more details?
Do you have just one device connected to the machine? When you conencted that devic (before starting Daedalus, before Pair, when Pair started)? Please add more details

**Comment by ManusMcCole** [comment]
Hi @nikolaglumac. Here is a <a href="https://drive.google.com/file/d/1dOrqnknj8vVpWjFoROlYw3ID75yZqBla/view?usp=sharing">screenshot</a>.For more context I was trying to open the Diagnostics screen so I could transplant the chain folder cause on a Linux VM it takes a long long time otherwise

**Comment by tomislavhoracek** [comment]
P.S. @ManusMcCole Can you reproduce this on the latest stable build (from develop branch) too?

**Review by miorsufianiohk — APPROVED** [review]
LGTM. Good job @tomislavhoracek . Approving for Nano X. 👍

**Comment by nikolaglumac** [comment]
Ok we are just missing @ManusMcCole approval...

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek.I could not reproduce the most recent issue with Ledger S on the newest develop build

**Comment by ManusMcCole** [comment]
Tested again on newest build 16666

> @ManusMcCole Can you please describe "Export key" steps with more details?
> Do you have just one device connected to the machine? When you connected that device (before starting Daedalus, before Pair, when Pair started), Platform? Please add more details !!!

Hi Tomislav. Only one device connected to the machine at any one time. So ive found that if i do a transaction with the Ledger and then plug it out and plug in Trezor and then I get this error. Daedalus says launch Cardano app so its expecting a Ledger device. See <a href="https://drive.google.com/file/d/1ObkTtUULLgK8PMmQIt7Lq1IKuQEz3Y0a/view?usp=sharing">Screenshot</a>. Error is different this time. Ill keep investigating now

**Comment by nikolaglumac** [comment]
@ManusMcCole @tomislavhoracek please focus on this one today. We need to fix the issues and merge this PR ASAP. Thanks 🙏

**Comment by ManusMcCole** [comment]
Hi @tomislavhoracek. I reproduced the "Cannot export extended public key error" now on Ledger S and on Mac only. See <a href="https://drive.google.com/file/d/1sGamS7s1pTBjCqgJl7lW2UiBVpLtWEPW/view?usp=sharing">screenshot</a>. The steps to reproduce are.1. Daedalus is closed.2.Plugin and unlock ledger device (launch Cardano app is optional error appears in both cases).3 Open Daedalus 4. Attempt to create transaction. Daedalus gets stuck at the "Export Public key on your device message".Ledger device says "Waiting for commands...". Console error says "Cannot export extended public key error"

 

https://drive.google.com/file/d/1sGamS7s1pTBjCqgJl7lW2UiBVpLtWEPW/view?usp=sharing

**Review by ManusMcCole — APPROVED** [review]
Good work @tomislavhoracek

**Review by nikolaglumac — APPROVED** [review]

**Pull request merged**
