### PR TITLE
[CSL-1758] Pass Node DB path to launcher

### PR DESCRIPTION
**Pull request by int-index**
I did not test (don't know the entire procedure to build the installers), but the change is simple.

### CODE REVIEW

**Comment by gromakovsky** [comment]
@fersel please test.

**Comment by deepfire** [comment]
Restarting the build -- seems like an intermittent failure to download CardanoSL.zip.

**Comment by deepfire** [comment]
Ok, the https://s3.eu-central-1.amazonaws.com/cardano-sl-testing/ bucket is gone.  Investigating..

**Comment by deepfire** [comment]
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-524

**Comment by domenkozar** [comment]
@int-index why do we need to pass this parameter to cardano-launcher?

**Comment by int-index** [comment]
Because the launcher tracks what updates were installed. You can read the discussion in comments to CSL-1758

**Comment by domenkozar** [comment]
@int-index OK, you should rebase to get CI working and then you can use the installer to test.

**Comment by domenkozar** [comment]
It creates file `patak` with following contents: `Entered launcher's mainCaught an exception: ExitFailure 1`

**Comment by gromakovsky** [comment]
It was merged in #553

**Comment by domenkozar** [comment]
it wasn't merged.

**Comment by gromakovsky** [comment]
Oh, sorry, I confused it with #545.

**Pull request merged**
