### PR TITLE
Feature/daef 418 About page, available from the system menu

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces about page window from system menu.
about window

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei: @tomothespian and I have tried to find a way to speed it up and failed :(
The only possible way to speed it up would be to pre-generate about page in pure html. That way it would be display instantaneously BUT this approach has 2 pitfalls: we need theming and translations support.
In the end I don't think our About page is much slower (or at all slower) than the one from Slack ;)

**Comment by DominikGuzei** [comment]
Ok thanks for the report 👍 you're right, this seems to be a problem with electron / rendering speed of the web app. It's not critical since the about page is not viewed regularly 😉

**Comment by DominikGuzei** [comment]
Merging when CI is done

**Comment by darko-mijic** [comment]
Let's not merge it until we update the list of people.

**Pull request merged**
