### PR TITLE
[DDW-1000] Integrate legacy wallet transactions list V2 API endpoint

### PR DESCRIPTION
**Pull request by tomothespian**
This PR introduces the Legacy Wallet transactions list API V2 endpoint.

## Todos

- [x] Display UNRESOLVED transaction inputs
- [x] Japanese Translations for UNRESOLVED transaction inputs

## Screenshots

_No Addresses_

EN - No Addresses
JA - No Addresses

_Unresolved addresses_

EN - Unresolved addresses
JA - Unresolved addresses

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1573063083355100)

**NOTE: **
_It is not possible to test Legacy wallet transactions because we don't have wallet with transactions_

**1. Test Storybook stories**
- [ ] Test Storybook story under: `WalletTransactionsList -> transactions with unresolved income addresses`
- [ ] Test Storybook story under: `WalletTransactionsList -> transactions without income addresses`

**2. In-App testing**
- [ ]  Transactions without income addresses
- Run `yarn v2-api-importer` to get wallets with funds
- Check transaction details on one off wallets and `From` address should be: `No Addresses`

- [ ]  Transactions with unresolved income addresses 
- Run `yarn v2-api-importer` to get wallets with funds
- Create `Test Wallet`
- Send ADA from one of imported wallets to `Test Wallet`
- Check `Test Wallet` transaction details and `From` address should be: `Open this transaction in Cardano explorer` link.

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@daniloprates please review this one 🙏

**Comment by gnpf** [comment]
@tomothespian The font sizes/styles look different between 1, 2 & 3:

image

**Comment by gnpf** [comment]
@tomothespian In the minimum resolution, the word "Addresses" is split:

image

**Comment by tomothespian** [comment]
> @tomothespian The font sizes/styles look different between 1, 2 & 3:
> 
> image

@gnpf this is how is defined in designs:
https://zpl.io/adl6D1a

**Comment by a-rukin** [comment]
my bad... sorry
will fix it in a moment

**Comment by tomothespian** [comment]
> @tomothespian code changes look good and everything works good.
> Please check the comments from @gnpf AND make sure the fonts are correctly rendered.
> This is very important as the row heights have to be exactly the same since we have that virtual list rendering here. If you look more closely when toggling expanded/collapsed transaction state you can see that there is some hickups with the rendering of the expanded transaction size - as if it first renders with height X and then in the next second decreases in size to X-10px or so.
> We can have a call about this tomorrow...

@nikolaglumac I'm not sure that I can reproduce that, I mean, I tried. It would be great if you can show me on call

**Comment by a-rukin** [comment]
https://zpl.io/adl6D1a - updated this screen 
(you can view last 3 versions to see that the latest one is more balanced, even it has some strange font size)

**Comment by tomothespian** [comment]
> @tomothespian In the minimum resolution, the word "Addresses" is split:
> 
> image

@gnpf this one is done

**Comment by tomothespian** [comment]
@gnpf @a-rukin styles updated! Can you please check again.

**Pull request merged**
