### PR TITLE
[DDW-543] Integrate improved numeric input

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR integrates the [improved NumericInput component](https://github.com/input-output-hk/react-polymorph/pull/156) with arbitrary number precision based on bignumber.js.

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1611606878041800)
- [x] The Wallet send form (sending transactions) should work exactly like before
- [x] The `fromAmount` and `toAmount` filters on the wallet transactions page should work as before

---

## Test cases

**Scenario 1 - Enter a value > 0**
```Gherkin
Given that the focus is on <NumericInput>
When I insert a value > 0
Then the value is displayed on the field
```

**Scenario 2 - Enter a value < 0**
```Gherkin
Given that the focus is on <NumericInput>
When I insert a value below 0
Then the - sign is not displayed on the field
And only the numbers are displayed
```

**Scenario 3 - Enter a value > 900,719,925.474099**
```Gherkin
Given that the focus is on <NumericInput>
When I insert a value over 900,719,925.474099
Then the  value is displayed on the field
```

**Scenario 4 - Enter a value with 6 decimals digits**
```Gherkin
Given that the focus is on <NumericInput>
When I insert a value with 6 decimals digits
Then the value is persiste on the field
```

**Scenario 5 - Enter a value with more than 6 decimals**
```Gherkin
Given that the focus is on <NumericInput>
When I insert a value with more than 6 decimals digits
Then the value is displayed on the field up to the 6th digit
And all the numbers after the 6th decimal place are not displayed
```

**Scenario 6 - Enter a non numeric value**
```Gherkin
Given that the focus is on <NumericInput>
When I insert a non numeric value on the field
Then the value is not displayed on the field
```

**Scenario 7 - Try to delete decimal separator**
```Gherkin
Given that the focus is on <NumericInput>
And a value with decimal digits is inserted
When I try to delete the decimal separator by pressing "Backspace" or "Delete"
Then the cursor moves skips the separator
And moves to the corresponding side without deleting it
```

**Scenario 8 - Try to delete thousand separator**
```Gherkin
Given that the focus is on <NumericInput>
And a value >999 is inserted
When I try to delete the thousand separator by pressing "Backspace" or "Delete"
Then the cursor moves skips the separator
And moves to the corresponding side without deleting it
```

**Scenario 9 - Overwrite the value**
```Gherkin
Given that the focus is on <NumericInput>
And a value is inserted
When I select part of the number
And I insert a different number
Then the value is updated
```

**Scenario 10 - Insert a number in the middle of the whole number part**
```Gherkin
Given that the focus is on <NumericInput>
And a value is inserted
When I place the cursor in the middle of the whole number part
And I insert a new number
Then the number is displayed
```

**Scenario 11 - Insert a number in the middle of the decimal part**
```Gherkin
Given that the focus is on <NumericInput>
And a value with 6 decimal digits is inserted
When I place the cursor in the middle of the decimal part
And I insert a new number
Then the number is displayed
And all the numbers after the 6th decimal place are deleted
```

**Scenario 12 - Insert a decimal separator in the middle of the value**
```Gherkin
Given that the focus is on <NumericInput>
And a value with decimal digits is inserted
When I place the cursor in the middle of the value
And I insert a decimal separator
Then the decimal separator moves to the position of the cursor
And the value is updated
And it will display only 6 decimal digits deleting the exceeding numbers
```

**NumericInput:**
Wallet - Send - Amount
Wallet - Transaction - Filter - Amount of ada - From
Wallet - Transaction - Filter - Amount of ada - To

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by gnpf** [comment]
@DominikGuzei a few issues on build 16048:

1 - The fees and the "Calculating" messages [are not displayed over the input](https://drive.google.com/file/d/1_7Nowt8PeEVeXQK83JxhNLmC1gmn_l67/view?usp=sharing). Check [this screenshot](https://drive.google.com/file/d/1BE96SjWmnoJXhwa757BlozUUuyIhtaru/view?usp=sharing) of how it looks in production.

2 - The value "0.000000" [is displayed by default in the input](https://drive.google.com/file/d/16wiYVqxVM1Mx8E2Rqzw20qnjZ71qgjql/view?usp=sharing). In production, the value is displayed [as a placeholder](https://drive.google.com/file/d/1nObzIuvCGq456M04bxdzcXGg0kXnlpjm/view?usp=sharing).

**Comment by mioriohk** [comment]
Hi @DominikGuzei . Tested on build 16048. 

Not sure if this is related to your changes, I could press numeric buttons from 5 to 9 to increment ada amount. [See video](https://drive.google.com/file/d/1E25seHnuT0vDaz2ZH3fCftSJ8E08B9TZ/view?usp=sharing). Note: this doesn't exist on production.

**Comment by DominikGuzei** [comment]
Thanks, @mioriohk and @gnpf I will debug and tackle these issues tomorrow 👍

**Comment by DominikGuzei** [comment]
@mioriohk @gnpf the issues you mentioned should be fixed now 🎉 please re-test!

**Review by mioriohk — APPROVED** [review]
LGTM. Great job @DominikGuzei 👍 . Tested all scenarios + other reported issues on 16103

**Review by nikolaglumac — CHANGES_REQUESTED** [review]
@DominikGuzei can you please fix flow errors? 🙏

**Review by gnpf — APPROVED** [review]
Looks good! 🎉 

I updated the cases to cover all the numeric inputs affected (_From_ and _To_ on Transactions filter)

**Review by ManusMcCole — APPROVED** [review]
Looks good 👍

**Comment by DominikGuzei** [comment]
@nikolaglumac done, ready for merge 👍

**Review by nikolaglumac — APPROVED** [review]
Love this one 🥳  💯

**Pull request merged**
