### PR TITLE
[DDW-544] Fix 'Daedalus' state directory on 'Staging' and 'Testnet' 

### PR DESCRIPTION
**Pull request by daniloprates**
This PR fixes 'Daedalus' state directory on 'Staging' and 'Testnet' builds.

Since the Electron upgrade, the Staging and Testnet builds on Windows are creating a “Daedalus” state directory, within which they add an empty “logs” directory. It seems to be a known Electron [issue](https://github.com/electron/electron/issues/11858).

## Screenshots:

screen_shot_2019-01-04_at_17 39 44

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by daniloprates** [comment]
@DominikGuzei @nikolaglumac I made some [attempts](https://github.com/input-output-hk/daedalus/pull/1316/commits) of playing around with `package.js`, but it didn't work. Do you have any suggestion? Maybe something [here](https://github.com/input-output-hk/daedalus/blob/develop/source/main/config.js#L56)?

**Comment by nikolaglumac** [comment]
@daniloprates it is important to figure out whether this default `Daedalus` folder is created at the installation time or during the first Daedalus launch. This could also be an Electron bug. The application name is different for each of the 3 applications (Daedalus, Daedalus Staging and Daedalus Testnet).

**Comment by nikolaglumac** [comment]
@daniloprates perhaps this is the problem: https://github.com/input-output-hk/daedalus/blob/develop/source/main/utils/setupLogging.js#L20

**Comment by nikolaglumac** [comment]
@daniloprates I would suggest you try to disable logging and check if the `Daedalus` directory is created in that case. I think it should be enough to comment out this line: https://github.com/input-output-hk/daedalus/blob/develop/source/main/index.js#L54

**Comment by daniloprates** [comment]
> @daniloprates it is important to figure out whether this default `Daedalus` folder is created at the installation time or during the first Daedalus launch. This could also be an Electron bug. The application name is different for each of the 3 applications (Daedalus, Daedalus Staging and Daedalus Testnet).

@nikolaglumac `Daedalus` folder is only created during the first Daedalus launch. Cool, I'll test these suggestions.

**Comment by daniloprates** [comment]
@nikolaglumac removing the logs didn't work. Still creating the `Daedalus` folder.

**Comment by daniloprates** [comment]
@nikolaglumac @DominikGuzei failed attempts so far:

* [Adding](https://github.com/input-output-hk/daedalus/pull/1316/commits/10a4dfd49058cff7d42cc934e3418502489b5caa#diff-b0bbd6444a2b11817a80788388383bf8) `appname: 'Daedalus',` on [package.js](https://github.com/input-output-hk/daedalus/pull/1316/commits/10a4dfd49058cff7d42cc934e3418502489b5caa#diff-b0bbd6444a2b11817a80788388383bf8)
* [Hardcoding](https://github.com/input-output-hk/daedalus/pull/1316/commits/845cb36f85012f09c890861ef938c5ad2bb3e4e7) `name: 'Daedalus',` on [package.js](https://github.com/input-output-hk/daedalus/pull/1316/commits/845cb36f85012f09c890861ef938c5ad2bb3e4e7#diff-b0bbd6444a2b11817a80788388383bf8)
* [Removing](https://github.com/input-output-hk/daedalus/pull/1316/commits/ce16d4b51f7cce9b1e112a2522b3ecc5c2b9fcb5) the logs

**Comment by DominikGuzei** [comment]
@daniloprates how should hardcoding `name: 'Daedalus'` result in anything else but a `Daedalus` folder being created? 😄 I would rather try to hardcode `Daedalus Staging` etc. (the correct name) … my guess is that electron-builder just picks the `productName` in `package.json` so i would try to rewrite that property before building + change it back afterwards.

**Comment by nikolaglumac** [comment]
@cleverca22 any idea about this one? It's a Windows only issue :(

**Comment by daniloprates** [comment]
Tried to [rename](https://github.com/input-output-hk/daedalus/pull/1316/commits/49d7e6bed1cee1d88c7c32440845429fa3434971#diff-b0bbd6444a2b11817a80788388383bf8R46) `productName` when running `package.js`, but it didn't work.

**Comment by DmitriiGaico** [comment]
Please see my findings below.
Steps and results provided in Chronological order. All the steps and results are valid for Test and Staging nets.
1. Install Daedalus TestNet on a clean Windows VM. No Daedalus Folder was created.
2. After installation a Blank short cut was created pointing to "Daedalus.exe" file.
3. After running shortcut the error was displayed. (ScreenShot attached)
4. In the root folder the .exe file created with the name "Daedalus Testnet.exe"
5. Manually renamed Daedalus Testnet.exe > Daedalus.exe. VM Reboot.
6. After VM Reboot the shortcut displayed as expected.
7. Running Daedalus Shortcut caused the app to Run Just fine. After App started and Sync process started "Daedalus" folder was not created.
testnet

**Comment by nikolaglumac** [comment]
Looks like we are close to getting this fixed - can you help us fix the last part @cleverca22 🙏

**Comment by cleverca22** [comment]
the dhall files will likely need to be updated (perhaps on every platform) to account for the new name for electron

**Comment by DmitriiGaico** [comment]
@cleverca22 Hello! I'll do some tests on Linux but for the Windows results are below.
Green: 1. After Installing and Starting "TestNet / Staging" no Daedalus folder created. 2. App can be started via desktop shortcut with no errors. 
RED : 1. ShortCuts are still Blank.
shortcuts

**Comment by nikolaglumac** [comment]
So we just need to sort out the icons - thanks for looking in to it @cleverca22 🙏

**Comment by nikolaglumac** [comment]
@cleverca22 here's the root of the problem with the desktop icons:

image

**Comment by nikolaglumac** [comment]
@cleverca22 Mainnet installer has no icon issues on Windows 🎉

**Pull request merged**
