### PR TITLE
❤️ Add members of Cardano Wallet team to the "About Daedalus" screen.

### PR DESCRIPTION
**Pull request by jonathanknowles**
Hi there!

The "About Daedalus" screen includes _some_ members of the Cardano Wallet developer team, but some are missing. I wonder if it's possible to add the remaining members? 🙏🏻 (I've added them in this PR.)

The following members are already listed within the "Cardano Team" section:

- Johannes Lund (@anviking)
- Pawel Jakubas (@paweljakubas)
- Piotr Stachyra (@piotr-iohk)

This PR adds the remaining (current) members to the same section:

- Heinrich Apfelmus (@HeinrichApfelmus)
- Jonathan Knowles (@jonathanknowles)
- Paolo Veronelli (@paolino)
- Yura Lazarev (@Unisay)

Many thanks! 🎄 

Jonathan

### CODE REVIEW

**Comment by tomislavhoracek** [comment]
cc @danielmain @daniloprates

**Comment by jonathanknowles** [comment]
Hi @tomislavhoracek,

Just curious (just attempting to tie up a loose end). Is there anything that we need to add to get this merged?

Though no pressure if you're already snowed under.

All the best

Jonathan

**Comment by piotr-iohk** [comment]
Please approve and make our children, wives and girlfriends happy and proud... :pray:

**Comment by jonathanknowles** [comment]
> Yuriy Lazaryev

@Unisay Apologies for using the wrong spelling here. -- I've now updated it! Could you verify that the new spelling is correct? 🙏🏻

**Comment by jonathanknowles** [comment]
cc @marcin-mazurek

**Review by marcin-mazurek — APPROVED** [review]

**Review by tomislavhoracek — APPROVED** [review]

**Comment by tomislavhoracek** [comment]
Please add a CHANGELOG entry 🙏

**Review by DominikGuzei — APPROVED** [review]
LGTM 🚢

**Pull request merged**
