### PR TITLE
[DDW-497] Improve Mnemonic Phrase Input UX

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR improves the mnemonic input UX in the whole app:

Currently, we have "Please enter all 12 words" error message while still typing the mnemonics. The suggestion is to indicate progress with a counter on the top-right of this element and with tooltips show only errors, like "Invalid recovery phrase" 

Design: https://zpl.io/bArKNW8 

## Todos

- [x] Use translations
- [x] Get Japanese translation

### Create Wallet

Create Wallet - Wallet Recovery Phrase Entry Dialog

### Restore Wallet

Daedalus 12 Words
Restore Wallet - Daedalus 12 Words

Daedalus 15 Words
Restore Wallet - Daedalus 15 Words

Daedalus 24 Words
Restore Wallet - Daedalus 24 Words

Wallet Restore 24 words UX Recording:
Wallet Restore 24 Words

### Verify Wallet Recovery Phrase

Verify Wallet Recovery Phrase - 2 Words entered

Verify Wallet Recovery Phrase - 12 Words entered - error

Verify Wallet Recovery Phrase

### Japanese translations

grafik

grafik

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1608315971062200)
- [ ] Test all mnemonic inputs in the application: if the required word count is known there should be "x of x words entered" and if the required word count can be variable (e.g: when verifying the wallet mnemonics) then it should say "x words entered"

---

## Test Cases

**Scenario 1: Validate message on the Wallet Creation Wizard with no words inserted**

```Gherkin
  Given that I am on wallet creation wizard
  When I see the input to write the recovery phrase
  Then I see the following message is displayed over it:
  
  EN: 0 of 24 words entered
  JA: 0/24語入力済み
```

**- Scenario 2: Validate message on the Wallet Creation Wizard with 1 word inserted**

```Gherkin
Given that I am on the wallet creation wizard 
When I see the input to write the recovery phrase
And I enter the first word of the recovery phase
Then I see the following message is displayed over the input:

EN: 1 of 24 words entered
JA: 1/24語入力済み
```

**- Scenario 3: Validate message on the Wallet Creation Wizard with all words inserted**

```Gherkin
Given that I am on the wallet creation wizard 
When I see the input to write the recovery phrase
And I enter the whole recovery phase
Then I see the following message is displayed over the input:

EN 24 of 24 words entered
JA: 24/24語入力済み
```

**- Scenario 4: Validate message on the Wallet Restoration Wizard with no words inserted**

```Gherkin
Given that I am on wallet restoration wizard
And X is the number of words this type of wallet requires
When I see the input to write the recovery phrase
Then I see the following message is displayed over it:

EN: 0 of X words entered
JA: 0/X語入力済み
```

**- Scenario 5: Validate message on the Wallet Restoration Wizard with 1 word inserted**

```Gherkin
Given that I am on wallet restoration wizard
And X is the number of words this type of wallet requires
When I see the input to write the recovery phrase
And I enter the first word of the recovery phase
Then I see the following message is displayed over the input:

EN: 1 of X words entered
JA: 1/X語入力済み
```

**- Scenario 6: Validate message on the Wallet Restoration Wizard with all words inserted**

```Gherkin
Given that I am on wallet restoration wizard
And X is the number of words this type of wallet requires
When I see the input to write the recovery phrase
And I enter the whole recovery phase
Then I see the following message is displayed over the input:

EN: X of X words entered
JA: X/X語入力済み
```

**- Scenario 7: Validate message on the Wallet Recovery Phrase Verification with no words inserted**

```Gherkin
Given that I am on wallet recovery phrase verification wizard
When I see the input to write the recovery phrase
Then I see the following message is displayed over it:

EN: 0 words entered
JA: 0語入力済み
```

**- Scenario 8: Validate message on the Wallet Recovery Phrase Verification with 1 word inserted**

```Gherkin
Given that I am on wallet recovery phrase verification wizard
When I see the input to write the recovery phrase
And I enter the first word of the recovery phase
Then I see the following message is displayed over the input:

EN: 1 word entered
JA: 1語入力済み
```

**- Scenario 9: Validate message on the Wallet Recovery Phrase Verification with all words inserted**

```Gherkin
Given that I am on wallet recovery phrase verification wizard
When I see the input to write the recovery phrase
And I enter the whole recovery phase
And X is the number of words entered
Then I see the following message is displayed over the input:

EN: X words entered
JA: X語入力済み
```

---
## Test Summary

On Build 15764

Test case | Status | Comments
-- | -- | --
Scenario 1 | Passed |
Scenario 2 | Passed |
Scenario 3 | Passed |
Scenario 4 | Passed |
Scenario 5 | Passed |
Scenario 6 | Passed |
|Scenario 7 | Passed |
Scenario 8 | Passed |
Scenario 9 | Passed |

---

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@yakovkaravelov @gnpf please test/review this one today 🙏

**Comment by gnpf** [comment]
@DominikGuzei Here are some partial results for build 15726:

Test case | Status | Comments
-- | -- | --
Scenario 3 | Failed | A red outlining is visible for a second on the input when completing the whole phrase. Check [this video](https://drive.google.com/file/d/1Sr5NVck6spJkhh_IfI30QV2LoZ1YDK2L/view?usp=sharing).
Scenario 6 | Failed | A red outlining is visible for a second on the input when completing the whole phrase. Check [this video](https://drive.google.com/file/d/18G0NRxu-ayxAl37k5Gp1mBoL-aN5pWcu/view?usp=sharing).
Scenario 7 | Pending |  
Scenario 8 | Pending |  
Scenario 9 | Pending |  

The scenarios that are not included passed. I Will update this comment later the results for the rest.

**Comment by DominikGuzei** [comment]
@gnpf all scenarios except 8 should be fixed now!
Regarding Scenario 9 (On different instances, the message "Invalid recovery phrase" is displayed (12, 15 and 18 words) i think this is expected behavior - since we don't know which length the recovery phrase might have, we assume that any valid length could be correct. @nikolaglumac please confirm ☝️

**Comment by a-rukin** [comment]
@DominikGuzei seems like there is no variable for this text (or it is just wrong here) - [screenshot](https://user-images.githubusercontent.com/2539345/103280142-b00bd700-49e0-11eb-9850-ab1a1d2c7081.png)

**Comment by a-rukin** [comment]
[Here](https://user-images.githubusercontent.com/2539345/103281575-2f4eda00-49e4-11eb-983d-3e07f3efd7c5.png) i see that max length is 27 words, but when I try to verify my recovery phrase it allows to type only 24. Is this ok?

**Comment by mioriohk** [comment]
@DominikGuzei Findings for build 15764:

Test case | Status | Comments
-- | -- | --
Scenario 8 | Failed | The message reads "1 words inserted". "Word" should be singular for this case. Check [this screenshot](https://drive.google.com/file/d/1Asfi7TZhdaGlQufaDC8hoVccOQGwemhR/view?usp=sharing).
Scenario 9 | Failed | 1 - A red outlining is visible on the input when completing the whole phrase. Check [this video](https://drive.google.com/file/d/1g0bphn0N9x0aUg_fJvGO-r6Toj6bmY08/view?usp=sharing). Note: Waiting for confirmation from Nikola
Scenario 9 | Failed | 2 - On different instances, the message "Invalid recovery phrase" is displayed (12, 15 and 18 words), even if the phrase is not completed yet. Check [this video](https://drive.google.com/file/d/1zS_AhY01EKfFJiyqFpcR7poeZZl-qOb7/view?usp=sharing). Note: Waiting for confirmation from Nikola

**Comment by DominikGuzei** [comment]
> @DominikGuzei seems like there is no variable for this text (or it is just wrong here) - [screenshot](https://user-images.githubusercontent.com/2539345/103280142-b00bd700-49e0-11eb-9850-ab1a1d2c7081.png)

Which text do you mean exactly?

**Comment by DominikGuzei** [comment]
@mioriohk scenario 9-1 is definitely a bug 😉 only 9-2 is not a bug but expected (I think)

**Comment by DominikGuzei** [comment]
@mioriohk scenario 8 should be fixed now 👍

**Comment by DominikGuzei** [comment]
> [Here](https://user-images.githubusercontent.com/2539345/103281575-2f4eda00-49e4-11eb-983d-3e07f3efd7c5.png) i see that max length is 27 words, but when I try to verify my recovery phrase it allows to type only 24. Is this ok?

Yes that's fine (and I haven't changed anything regarding this logic) 👍 You can only enter 27 words when you **restore** a paper wallet mnemonic - that's the only one with 27 words.

**Comment by DominikGuzei** [comment]
@mioriohk I could not reproduce scenario 9-1 on the recovery phrase verification dialog:
CleanShot 2021-01-01 at 16 15 57

**Comment by a-rukin** [comment]
> > @DominikGuzei seems like there is no variable for this text (or it is just wrong here) - [screenshot](https://user-images.githubusercontent.com/2539345/103280142-b00bd700-49e0-11eb-9850-ab1a1d2c7081.png)
> 
> Which text do you mean exactly?

"2 of 12 words entered"

**Comment by mioriohk** [comment]
@DominikGuzei Findings for build 15770. Looks good to me except:

Test case | Status | Comments
-- | -- | --
Scenario 7 | Failed | I corrected the written scenario. Expected behaviour should be "0 word entered", not "0 words entered".

**Comment by gnpf** [comment]
@DominikGuzei On build 15570:

Test case | Status | Comments
-- | -- | --
Scenario 2 | Failed | [The message reads 1 of 24 _word_.](https://drive.google.com/file/d/1ku9NaSe7myjXGm5qB4wLJikN1avwL2RS/view?usp=sharing) "Word" refers to 1, instead of 24. I think it should be plural in this case (1 of 24 words).
Scenario 5 | Failed | [The message reads 1 of 12 _word_](https://drive.google.com/file/d/1W5GlmU7gYxVlg_SU7qMWhdnx2K7RiXDv/view?usp=sharing). "Word" refers to 1, instead of 24. I think it should be plural in this case (1 of 12 words).

Did we get a confirmation about the issues for scenario 9 on [this comment?](https://github.com/input-output-hk/daedalus/pull/2280#issuecomment-748971405)

**Comment by gnpf** [comment]
@DominikGuzei I tried to reproduce issue 1 for scenario 9 on [this comment](https://github.com/input-output-hk/daedalus/pull/2280#issuecomment-748971405) and it doesn't happen anymore 👍

**Comment by DominikGuzei** [comment]
@gnpf the pluralization issue (scenario 2 & 5) should be fixed 👍

**Comment by ManusMcCole** [comment]
Hi @DominikGuzei. Nice work. All the plurilization issues are fixed. Perhaps the text colour for "0 of 24 words entered" for themes Dark blue and Dark Cardano could be made a lighter shade ? See <a href="https://drive.google.com/file/d/1Lj93A_HIHdiLKKcaYbvwN5H15yZd2Nmm/view?usp=sharing">Dark blue</a> and <a href="https://drive.google.com/file/d/1G7FrFGy3Era0eyLImyv_cTfI3IYFbLEu/view?usp=sharing">Dark Cardano</a> .I find for these themes its a little hard to read and suggests that text is greyed out, as it is a darker shade even than the step "Configurations" which is not currently active. What do you think @a-rukin ?

**Review by ManusMcCole — APPROVED** [review]

**Comment by DominikGuzei** [comment]
@a-rukin @ManusMcCole I added theme variables for the new mnemonics label to control the color and position. Please check again 🙏  for me it looks good in all themes now 👍

**Comment by ManusMcCole** [comment]
Hi @DominikGuzei.Nice job on the styling changes looks really good now 👍 I could only test on Mac due to some failing builds though

**Comment by DominikGuzei** [comment]
thanks @ManusMcCole, I notified the devops team about the build failures 👍

**Review by mioriohk — APPROVED** [review]
LGTM. Great job @DominikGuzei  👍 . Tested on build 15808

**Review by nikolaglumac — APPROVED** [review]
Great UX improvement @DominikGuzei 💯

**Comment by darko-mijic** [comment]
I just realize we are missing one thing. We need to display the index of the word to be entered, not the number of entered words. Since words are enumerated to be entered easily. Instead of "2 of 24 words entered" "enter word 3 of 24".

**Pull request merged**
