### PR TITLE
Fix/daef 352 Modify acceptance tests to work with production environment setup

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR replaces default-wallet.key used in acceptance tests with one that works in production environment and increases acceptance tests before steps timeout.

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei I had to increase both `BeforeFeatures` and `Before` timeouts in order for the acceptance tests to work in production mode. Please review my updates.

**Comment by nikolaglumac** [comment]
All tests should pass except for `User Sends Money from wallet with spending password to Receiver` where following error is thrown:

screen shot 2017-07-05 at 16 24 09

Please note that when I run this test isolated it passes normally...

**Comment by nikolaglumac** [comment]
Also I have recorded few occasions where "Generating wallet address" acceptance test fails BUT I know for sure this is a false-positive due to race conditions between updating wallet's lastGeneratedAddress and all wallet addresses.

**Comment by DominikGuzei** [comment]
testing this now …

**Comment by DominikGuzei** [comment]
@nikolaglumac but will these changes solve the problem of `function timed out after 5000 milliseconds`? it seems to me that these settings are not affecting that. I will investigate and increase these limits too

**Comment by nikolaglumac** [comment]
@DominikGuzei I doubt that increasing individual step's timeout would help. For me only send-money scenarios fail and even though the failure is recorded as "function timed out after 5000 milliseconds" it times-out due to "Not enough money to send" message.

**Comment by DominikGuzei** [comment]
@nikolaglumac still, we should keep the cucumber timeout always higher than the webdriver timeouts … otherwise this make no sense 😉 the cucumber timeout should be the last resort and not a pre-emptive cut-off of the tests. Cucumber also produces non-informative errors "that step just timed out" and webdriver would tell you "this element was not visible after 5 seconds"

**Comment by DominikGuzei** [comment]
I can confirm that error messages are much better now:

`Error: element (".Transaction_title") still not visible after 10000ms`

instead of:

`function timed out after 10000 milliseconds`

**Comment by DominikGuzei** [comment]
@nikolaglumac will the production keys actually work in the dev environment?

**Comment by nikolaglumac** [comment]
@DominikGuzei I doubt they will work in dev mode - we have replaced them in order to be able to run the tests in production/staging mode.
If you want to run the tests in dev mode you will need to generate new key.

**Comment by DominikGuzei** [comment]
@nikolaglumac ok i guess at the moment it's not super important as we don't really need dev mode … it's much faster though, so at some point it could be that we need it again.

**Comment by nikolaglumac** [comment]
@DominikGuzei agreed! Perhaps we could have both keys and some custom flag to define which one we want to use for certain test-run ;)

**Pull request merged**
