### PR TITLE
Fix/ddw 72 Update copy for the sync error screen

### PR DESCRIPTION
**Pull request by nikolaglumac**
This PR introduces updated copy for the sync error screen text.

result

### TODO:
- [x] Update Japanese translations
- [x] Convert URL `daedaluswallet.io/faq` into a clickable link

### CODE REVIEW

**Comment by nikolaglumac** [comment]
@DominikGuzei I have found about one more setup step. Will update the PR shortly.

**Comment by darko-mijic** [comment]
We need new Japanese translations too. 
Can we have a link to the FAQ, different link for English and Japanese language?
https://daedaluswallet.io/faq/
https://daedaluswallet.io/ja/faq/

**Comment by nikolaglumac** [comment]
Currently those are not links - just text. I will add links and ask for Japanese translations.

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei TODOs added in PR's description.

**Comment by nikolaglumac** [comment]
@darko-mijic @DominikGuzei here's how the updated texts look like now after we added the button (which was a part of the original design of this screen):

english

japanese

**Comment by nikolaglumac** [comment]
PS. this PR is rebased to target `development` branch as per our agreement.

**Comment by nikolaglumac** [comment]
@tomothespian please update the Button text - replace the existing text with the url AND in the line above the button remove the link and the brackets and replace them with a `:`

**Comment by tomothespian** [comment]
@darko-mijic @DominikGuzei here's how the updated texts look like now.
sync error screen with updated text and button link

**Comment by nikolaglumac** [comment]
@DominikGuzei @darko-mijic I have reviewed this PR and it looks good to me.
Please check it out yourself too and let's get this merged today :)

**Pull request merged**
