### PR TITLE
[DDW-465] Multi-language installers

### PR DESCRIPTION
**Pull request by daniloprates**
This PR implements multi-language installers.

## Todo:

- [x] Japanese translation for Windows installer
- [x] Japanese translation for macOS installer
- [x] Create translation files to be used by the installers ([example](http://nsis.sourceforge.net/Examples/languages.nsi))
- [x] Implement translations for Windows Installer:
```
{Daedalus} Uninstaller {$Version}
Start Menu Shortcuts
{Daedalus} is running. It needs to be fully shut down before running the installer!
```
- [x] Implement translations for macOS Installer

---

### Basics

- [ ] PR is updated to the most recent version of target branch (and there are no conflicts)
- [ ] PR has good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance tests are passing (`yarn run test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn run dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn run package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn run flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn run lint`)
- [ ] Text changes are proofread and approved (Jane Wild)
- [ ] There are no missing translations (running `yarn run manage:translations` produces no changes)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn run storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly documented and commented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-rendering
- [ ] Any code that only works in Electron is neatly separated from components

### Testing
- [ ] New feature / change is covered by acceptance tests
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature / change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review:
- [ ] Merge PR
- [ ] Delete source branch
- [ ] Move ticket to `done` on the Youtrack board

### CODE REVIEW

**Comment by cleverca22** [comment]
screenshot_2019-01-31_09-45-37

currently, it doesnt ask for a language when installing
but if you set the entire OS to japanese, then the installer is also japanese

**Comment by daniloprates** [comment]
> screenshot_2019-01-31_09-45-37
> 
> currently, it doesnt ask for a language when installing
> but if you set the entire OS to japanese, then the installer is also japanese

@cleverca22 the same happens to the MacOS installer

**Comment by nikolaglumac** [comment]
@cleverca22 are there yet? :)

**Comment by DominikGuzei** [comment]
@daniloprates @cleverca22 what's the state of this PR? Should / did we hand it over to QA?

**Comment by nikolaglumac** [comment]
This PR is to be replaced by: https://github.com/input-output-hk/daedalus/pull/1298
@cleverca22 can you confirm this?

**Comment by nikolaglumac** [comment]
Closing this PR unmerged in favour of https://github.com/input-output-hk/daedalus/pull/1298

**Pull request closed without merging**
